# Generated by 2sc from function 'fixstore' (2026-08-05 15:58:14).
function fixstore {
    [CmdletBinding()]
    param([switch]$NoWsReset,[switch]$SkipLongRepair)

    $failures=@();$registered=0;$skipped=0;$progressId=711
    $report={param([string]$Status,[string]$Message,[ConsoleColor]$Color=[ConsoleColor]::Cyan) Write-Host ("FIXSTORE_{0} {1}" -f $Status,$Message) -ForegroundColor $Color}
    try{$identity=[Security.Principal.WindowsIdentity]::GetCurrent();$principal=New-Object Security.Principal.WindowsPrincipal($identity);$isAdmin=$principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)}catch{$isAdmin=$false;$failures+="admin-detection: $($_.Exception.Message)";&$report 'WARN' ("admin detection failed: {0}" -f $_.Exception.Message) Yellow}
    $registerPackage={param($package) if($null-eq$package){return};$location=[string]$package.InstallLocation;if([string]::IsNullOrWhiteSpace($location)-or-not[IO.Path]::IsPathRooted($location)){$script:skipped++;return};$manifest=Join-Path $location 'AppXManifest.xml';if(-not(Test-Path -LiteralPath $manifest)){$script:skipped++;return};try{Add-AppxPackage -DisableDevelopmentMode -Register $manifest -ErrorAction Stop;$script:registered++}catch{$script:skipped++;& $report 'WARN' ("register failed package={0}: {1}" -f $package.Name,$_.Exception.Message) Yellow}}
    try {
        Write-Progress -Id $progressId -Activity 'Microsoft Store repair' -Status 'Registering installed AppX packages' -PercentComplete 15
        $packages=@(Get-AppxPackage -AllUsers -ErrorAction Stop);$index=0
        foreach($package in $packages){$index++;if(($index%25)-eq0){Write-Progress -Id $progressId -Activity 'Microsoft Store repair' -Status ("Registering AppX package {0}/{1}" -f $index,$packages.Count) -PercentComplete ([Math]::Min(45,15+[int](30*$index/[Math]::Max(1,$packages.Count))))};&$registerPackage $package}
        & $report 'OK' ("AppX registration registered={0} skipped={1}" -f $registered,$skipped) Green
    } catch {$failures+="appx-enumeration: $($_.Exception.Message)";&$report 'FAIL' ("AppX enumeration failed: {0}" -f $_.Exception.Message) Red}
    Write-Progress -Id $progressId -Activity 'Microsoft Store repair' -Status 'Stopping Store process and starting services' -PercentComplete 50
    try{$store=@(Get-Process -Name 'WinStore.App' -ErrorAction SilentlyContinue);foreach($process in $store){Stop-Process -Id $process.Id -Force -ErrorAction Stop};&$report 'OK' ("Store processes stopped={0}" -f $store.Count) DarkCyan}catch{$failures+="store-process: $($_.Exception.Message)";&$report 'WARN' ("Store process stop failed: {0}" -f $_.Exception.Message) Yellow}
    if(-not$NoWsReset){try{$wsreset=Start-Process -FilePath 'wsreset.exe' -WindowStyle Hidden -PassThru -ErrorAction Stop;&$report 'OK' ("wsreset launched pid={0}" -f $wsreset.Id) DarkCyan}catch{$failures+="wsreset: $($_.Exception.Message)";&$report 'FAIL' ("wsreset launch failed: {0}" -f $_.Exception.Message) Red}}
    foreach($serviceName in @('wscsvc','wuauserv','bits','cryptsvc','AppXSvc','ClipSVC','TokenBroker','StorSvc')){try{Set-Service -Name $serviceName -StartupType Automatic -ErrorAction Stop;Start-Service -Name $serviceName -ErrorAction Stop;&$report 'OK' ("service started={0}" -f $serviceName) DarkCyan}catch{$failures+="service:$serviceName $($_.Exception.Message)";&$report 'WARN' ("service={0}: {1}" -f $serviceName,$_.Exception.Message) Yellow}}
    Write-Progress -Id $progressId -Activity 'Microsoft Store repair' -Status 'Applying registry and network repair' -PercentComplete 70
    try{& reg.exe delete 'HKCU\Software\Microsoft\Windows\CurrentVersion\Store' /f; if($LASTEXITCODE-notin@(0,1)){throw "reg delete exit=$LASTEXITCODE"};&$report 'OK' 'HKCU Store cache cleanup completed or was already absent' DarkCyan}catch{$failures+="registry-hkcu: $($_.Exception.Message)";&$report 'WARN' ("HKCU Store cleanup: {0}" -f $_.Exception.Message) Yellow}
    if($isAdmin){
        foreach($native in @(@('reg.exe',@('add','HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Deprovisioned','/f')),@('netsh.exe',@('winsock','reset')),@('netsh.exe',@('int','ip','reset')))){try{& $native[0] @($native[1]);if($LASTEXITCODE-ne0){throw "$($native[0]) exit=$LASTEXITCODE"};&$report 'OK' ("native repair completed: {0}" -f $native[0]) DarkCyan}catch{$failures+="native:$($native[0]) $($_.Exception.Message)";&$report 'WARN' ("native repair failed {0}: {1}" -f $native[0],$_.Exception.Message) Yellow}}
        if(-not$SkipLongRepair){foreach($native in @(@('sfc.exe',@('/scannow')),@('Dism.exe',@('/Online','/Cleanup-Image','/RestoreHealth')))){Write-Progress -Id $progressId -Activity 'Microsoft Store repair' -Status ("Running {0}" -f $native[0]) -PercentComplete 85;try{& $native[0] @($native[1]);if($LASTEXITCODE-ne0){throw "$($native[0]) exit=$LASTEXITCODE"};&$report 'OK' ("long repair completed: {0}" -f $native[0]) Green}catch{$failures+="long:$($native[0]) $($_.Exception.Message)";&$report 'FAIL' ("long repair failed {0}: {1}" -f $native[0],$_.Exception.Message) Red}}}
    } else {&$report 'INFO' 'non-elevated shell skipped admin-only registry, network, and long repairs' Yellow}
    $succeeded=$failures.Count-eq0;Write-Progress -Id $progressId -Activity 'Microsoft Store repair' -Completed;$global:LASTEXITCODE=if($succeeded){0}else{1};&$report $(if($succeeded){'OK'}else{'INCOMPLETE'}) ("registered={0} skipped={1} failures={2} admin={3}" -f $registered,$skipped,$failures.Count,$isAdmin) $(if($succeeded){'Green'}else{'Yellow'});return [pscustomobject]@{Succeeded=$succeeded;Registered=$registered;Skipped=$skipped;Failures=@($failures);IsAdmin=$isAdmin}
}

if ($MyInvocation.InvocationName -ne '.') {
    & 'fixstore' @args
}
