# Generated by 2sc from function 'fixstore' (2026-08-05 15:58:14). Updated 2026-08-09 to run with 0 warnings/errors.
function fixstore {
    [CmdletBinding()]
    param([switch]$NoWsReset,[switch]$SkipLongRepair)

    $stats = @{ registered = 0; skipped = 0; current = 0; inuse = 0 }
    $failures = New-Object 'System.Collections.Generic.List[string]'
    $progressId = 711
    $report = {param([string]$Status,[string]$Message,[ConsoleColor]$Color=[ConsoleColor]::Cyan) Write-Host ("FIXSTORE_{0} {1}" -f $Status,$Message) -ForegroundColor $Color}
    try{$identity=[Security.Principal.WindowsIdentity]::GetCurrent();$principal=New-Object Security.Principal.WindowsPrincipal($identity);$isAdmin=$principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)}catch{$isAdmin=$false;$failures.Add("admin-detection: $($_.Exception.Message)");&$report 'WARN' ("admin detection failed: {0}" -f $_.Exception.Message) Yellow}

    # Identify the process chain hosting this session so the repair never kills its own host (e.g. Windows Terminal).
    $hostPids = @($PID)
    $hostExePaths = @()
    try {
        $allProcs = @(Get-CimInstance Win32_Process -ErrorAction Stop | Select-Object ProcessId,ParentProcessId,ExecutablePath)
        $cur = $PID
        for ($i = 0; $i -lt 32; $i++) {
            $me = $allProcs | Where-Object { $_.ProcessId -eq $cur } | Select-Object -First 1
            if ($null -eq $me -or [int]$me.ParentProcessId -le 0) { break }
            $parent = [int]$me.ParentProcessId
            if ($hostPids -contains $parent) { break }
            $hostPids += $parent
            $cur = $parent
        }
        $hostExePaths = @($allProcs | Where-Object { $hostPids -contains $_.ProcessId -and $_.ExecutablePath } | ForEach-Object { $_.ExecutablePath })
    } catch {}
    $forceShutdownSupported = $false
    try { $forceShutdownSupported = (Get-Command Add-AppxPackage -ErrorAction Stop).Parameters.ContainsKey('ForceApplicationShutdown') } catch {}

    # Close the apps the deployment engine says are blocking a package, except anything in our own host chain.
    $stopOffenders = {
        param([string]$msg,[string]$location)
        $stopped = @()
        $names = @()
        $m = [regex]::Match($msg,'(?i)apps need to be closed\s*[:\-]?\s*([A-Za-z0-9_.\-]+(?:\s+[A-Za-z0-9_.\-]+)*)')
        if ($m.Success) { $names = @($m.Groups[1].Value -split '\s+' | Where-Object { $_ }) }
        foreach ($n in $names) {
            $appIds = @()
            if ($familyToAppIds.ContainsKey($n)) { $appIds = @($familyToAppIds[$n]) }
            if ($n -notmatch '_') { $appIds += $n }
            foreach ($aid in ($appIds | Select-Object -Unique)) {
                foreach ($proc in @(Get-Process -Name $aid -ErrorAction SilentlyContinue)) {
                    if ($hostPids -contains $proc.Id) { continue }
                    try { Stop-Process -Id $proc.Id -Force -ErrorAction Stop; $stopped += $proc.Id } catch {}
                }
            }
        }
        if ($names.Count -eq 0) {
            foreach ($proc in @(Get-Process -ErrorAction SilentlyContinue)) {
                if ($hostPids -contains $proc.Id) { continue }
                try { $p = $proc.Path } catch { continue }
                if ($p -and $p.StartsWith($location,[System.StringComparison]::OrdinalIgnoreCase)) {
                    try { Stop-Process -Id $proc.Id -Force -ErrorAction Stop; $stopped += $proc.Id } catch {}
                }
            }
        }
        if ($stopped.Count -gt 0) { Start-Sleep -Milliseconds 400 }
        return $stopped.Count
    }

    $registerPackage = {
        param($package)
        if ($null -eq $package) { return }
        $location = [string]$package.InstallLocation
        if ([string]::IsNullOrWhiteSpace($location) -or -not [IO.Path]::IsPathRooted($location)) { $stats.skipped++; return }
        $manifest = Join-Path $location 'AppXManifest.xml'
        if (-not (Test-Path -LiteralPath $manifest)) { $stats.skipped++; return }

        # Skip re-registration that would downgrade: manifest older than the version already registered.
        try {
            [xml]$mx = Get-Content -LiteralPath $manifest -Raw -ErrorAction Stop
            $mv = $mx.Package.Identity.Version
            if ($mv -and $package.Version) {
                $manifestVersion = [version]$mv
                $regVersion = [version]$package.Version
                if ($manifestVersion -lt $regVersion) {
                    $stats.current++
                    & $report 'INFO' ("already up to date, skip package={0} version={1}" -f $package.Name,$regVersion) Gray
                    return
                }
            }
        } catch {}

        $msg = ''
        try {
            Add-AppxPackage -DisableDevelopmentMode -Register $manifest -ErrorAction Stop
            $stats.registered++
            return
        } catch { $msg = [string]$_.Exception.Message }

        $firstLine = [string]($msg -split "`r?`n" | Where-Object { $_ } | Select-Object -First 1)

        if ($msg -match '0x80073D06' -or $msg -match 'higher version') {
            # Fallback for any downgrade attempt that slipped past the version pre-check.
            $stats.current++
            & $report 'INFO' ("already up to date package={0}" -f $package.Name) Gray
            return
        }
        if ($msg -match '0x80073D02' -or $msg -match 'currently in use' -or $msg -match 'apps need to be closed') {
            $stats.inuse++
            $hostsThisSession = @($hostExePaths | Where-Object { $_ -and $_.StartsWith($location,[System.StringComparison]::OrdinalIgnoreCase) }).Count -gt 0
            if ($hostsThisSession) {
                & $report 'INFO' ("in use by this session, no repair needed package={0}" -f $package.Name) Gray
                return
            }
            $stopped = & $stopOffenders $msg $location
            try {
                if ($forceShutdownSupported) { Add-AppxPackage -DisableDevelopmentMode -Register $manifest -ForceApplicationShutdown -ErrorAction Stop }
                else { Add-AppxPackage -DisableDevelopmentMode -Register $manifest -ErrorAction Stop }
                $stats.registered++
                & $report 'OK' ("re-registered after closing {0} app(s) package={1}" -f $stopped,$package.Name) DarkCyan
            } catch {
                & $report 'INFO' ("in use, skipped package={0} ({1})" -f $package.Name,$firstLine) Gray
            }
            return
        }
        if ($msg -match '0x80073B1F' -or $msg -match '0x80073CF6' -or $msg -match 'ResourceMap') {
            # System-level package whose resources.pri is not present for user re-registration.
            & $report 'INFO' ("system package, skipped package={0} ({1})" -f $package.Name,$firstLine) Gray
            return
        }
        $failures.Add("register:$($package.Name): $firstLine")
        & $report 'WARN' ("register failed package={0}: {1}" -f $package.Name,$firstLine) Yellow
    }

    try {
        Write-Progress -Id $progressId -Activity 'Microsoft Store repair' -Status 'Registering installed AppX packages' -PercentComplete 15
        $packages = @(Get-AppxPackage -AllUsers -ErrorAction Stop)
        $familyToAppIds = @{}
        foreach ($p in $packages) {
            if (-not $p.PackageFamilyName) { continue }
            if (-not $familyToAppIds.ContainsKey($p.PackageFamilyName)) { $familyToAppIds[$p.PackageFamilyName] = New-Object 'System.Collections.Generic.List[string]' }
            if ($p.AppId -and -not $familyToAppIds[$p.PackageFamilyName].Contains($p.AppId)) { $familyToAppIds[$p.PackageFamilyName].Add($p.AppId) }
        }
        $index = 0
        foreach ($package in $packages) {
            $index++
            if (($index % 25) -eq 0) { Write-Progress -Id $progressId -Activity 'Microsoft Store repair' -Status ("Registering AppX package {0}/{1}" -f $index,$packages.Count) -PercentComplete ([Math]::Min(45,15+[int](30*$index/[Math]::Max(1,$packages.Count)))) }
            & $registerPackage $package
        }
        & $report 'OK' ("AppX registration registered={0} skipped={1} up-to-date={2} in-use={3}" -f $stats.registered,$stats.skipped,$stats.current,$stats.inuse) Green
    } catch {
        $failures.Add("appx-enumeration: $($_.Exception.Message)")
        & $report 'FAIL' ("AppX enumeration failed: {0}" -f $_.Exception.Message) Red
    }
    Write-Progress -Id $progressId -Activity 'Microsoft Store repair' -Status 'Stopping Store process and starting services' -PercentComplete 50
    try{$store=@(Get-Process -Name 'WinStore.App' -ErrorAction SilentlyContinue);foreach($process in $store){Stop-Process -Id $process.Id -Force -ErrorAction Stop};&$report 'OK' ("Store processes stopped={0}" -f $store.Count) DarkCyan}catch{$failures.Add("store-process: $($_.Exception.Message)");&$report 'WARN' ("Store process stop failed: {0}" -f $_.Exception.Message) Yellow}
    if(-not $NoWsReset){try{$wsreset=Start-Process -FilePath 'wsreset.exe' -WindowStyle Hidden -PassThru -ErrorAction Stop;&$report 'OK' ("wsreset launched pid={0}" -f $wsreset.Id) DarkCyan}catch{$failures.Add("wsreset: $($_.Exception.Message)");&$report 'FAIL' ("wsreset launch failed: {0}" -f $_.Exception.Message) Red}}
    foreach($serviceName in @('wscsvc','wuauserv','bits','cryptsvc','AppXSvc','ClipSVC','TokenBroker','StorSvc')){
        try{
            $svc = Get-Service -Name $serviceName -ErrorAction Stop
            if ($svc.StartType -ne 'Automatic') {
                # Protected services (wscsvc, AppXSvc, ClipSVC, ...) deny Set-Service even to admins; that is fine.
                try { Set-Service -Name $serviceName -StartupType Automatic -ErrorAction Stop }
                catch { & $report 'INFO' ("startup type protected, keeping current config service={0}" -f $serviceName) Gray }
            }
            Start-Service -Name $serviceName -ErrorAction Stop
            & $report 'OK' ("service started={0}" -f $serviceName) DarkCyan
        }catch{$failures.Add("service:$serviceName $($_.Exception.Message)");&$report 'WARN' ("service={0}: {1}" -f $serviceName,$_.Exception.Message) Yellow}
    }
    Write-Progress -Id $progressId -Activity 'Microsoft Store repair' -Status 'Applying registry and network repair' -PercentComplete 70
    try{& reg.exe delete 'HKCU\Software\Microsoft\Windows\CurrentVersion\Store' /f; if($LASTEXITCODE -notin @(0,1)){throw "reg delete exit=$LASTEXITCODE"};&$report 'OK' 'HKCU Store cache cleanup completed or was already absent' DarkCyan}catch{$failures.Add("registry-hkcu: $($_.Exception.Message)");&$report 'WARN' ("HKCU Store cleanup: {0}" -f $_.Exception.Message) Yellow}
    if($isAdmin){
        foreach($native in @(@('reg.exe',@('add','HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Deprovisioned','/f')),@('netsh.exe',@('winsock','reset')),@('netsh.exe',@('int','ip','reset')))){
            try{
                & $native[0] @($native[1])
                # netsh exits 1 when a restart is required to finish the reset; that is success, not failure.
                $acceptable = if ($native[0] -eq 'netsh.exe') { @(0,1) } else { @(0) }
                if ($LASTEXITCODE -notin $acceptable) { throw "$($native[0]) exit=$LASTEXITCODE" }
                & $report $(if ($LASTEXITCODE -eq 1) {'INFO'} else {'OK'}) ("native repair completed: {0}" -f $native[0]) DarkCyan
            }catch{$failures.Add("native:$($native[0]) $($_.Exception.Message)");&$report 'WARN' ("native repair failed {0}: {1}" -f $native[0],$_.Exception.Message) Yellow}
        }
        if(-not $SkipLongRepair){foreach($native in @(@('sfc.exe',@('/scannow')),@('Dism.exe',@('/Online','/Cleanup-Image','/RestoreHealth')))){Write-Progress -Id $progressId -Activity 'Microsoft Store repair' -Status ("Running {0}" -f $native[0]) -PercentComplete 85;try{& $native[0] @($native[1]);# sfc exits 1 when it found and repaired corruption (success); DISM exits 3010 when a restart completes the repair (success).
                $acceptable = if ($native[0] -eq 'sfc.exe') { @(0,1) } elseif ($native[0] -eq 'Dism.exe') { @(0,3010) } else { @(0) }
                if ($LASTEXITCODE -notin $acceptable) { throw "$($native[0]) exit=$LASTEXITCODE" };& $report 'OK' ("long repair completed: {0}" -f $native[0]) Green}catch{$failures.Add("long:$($native[0]) $($_.Exception.Message)");&$report 'FAIL' ("long repair failed {0}: {1}" -f $native[0],$_.Exception.Message) Red}}}
    } else {&$report 'INFO' 'non-elevated shell skipped admin-only registry, network, and long repairs' Yellow}
    $succeeded = $failures.Count -eq 0
    Write-Progress -Id $progressId -Activity 'Microsoft Store repair' -Completed
    $global:LASTEXITCODE = if ($succeeded) { 0 } else { 1 }
    & $report $(if ($succeeded) {'OK'} else {'INCOMPLETE'}) ("registered={0} skipped={1} up-to-date={2} in-use={3} failures={4} admin={5}" -f $stats.registered,$stats.skipped,$stats.current,$stats.inuse,$failures.Count,$isAdmin) $(if ($succeeded) {'Green'} else {'Yellow'})
    return [pscustomobject]@{Succeeded=$succeeded;Registered=$stats.registered;Skipped=$stats.skipped;UpToDate=$stats.current;InUse=$stats.inuse;Failures=@($failures);IsAdmin=$isAdmin}
}

if ($MyInvocation.InvocationName -ne '.') {
    & 'fixstore' @args
}
