# Generated by 2sc from function '9gg' (2026-08-13 00:03:08).
# Self-bootstrap: load the profile environment when this script runs
# outside a profile session so it behaves exactly like the function it
# was copied from. The module is also force-re-imported when the copy
# loaded in this process is stale (psm1 changed on disk) so a long-
# running session never runs an outdated dispatcher.
$__2scProfileModule = 'C:\Users\micha\Documents\WindowsPowerShell\Modules\CodexProfileFunctions\CodexProfileFunctions.psd1'
$__2scNeedBootstrap = -not (Get-Command -Name 'Initialize-CodexProfileFunctions' -CommandType Function -ErrorAction SilentlyContinue)
if (-not $__2scNeedBootstrap) {
    $__2scLoadedModule = Get-Module -Name 'CodexProfileFunctions' -ErrorAction SilentlyContinue | Select-Object -First 1
    if ($__2scLoadedModule) {
        $__2scLoadedFingerprint = $__2scLoadedModule.SessionState.PSVariable.GetValue('ProfileModuleFingerprint')
        $__2scModuleFile = Join-Path $__2scLoadedModule.ModuleBase 'CodexProfileFunctions.psm1'
        if ([System.IO.File]::Exists($__2scModuleFile)) {
            $__2scDiskInfo = Get-Item -LiteralPath $__2scModuleFile -ErrorAction SilentlyContinue
            if ($__2scDiskInfo) {
                $__2scDiskFingerprint = '{0}|{1}' -f $__2scDiskInfo.Length, $__2scDiskInfo.LastWriteTimeUtc.Ticks
                if ([string]$__2scLoadedFingerprint -and $__2scDiskFingerprint -ne [string]$__2scLoadedFingerprint) { $__2scNeedBootstrap = $true }
            }
        }
    }
}
if ($__2scNeedBootstrap) {
    if (-not (Test-Path -LiteralPath $__2scProfileModule -PathType Leaf)) {
        throw "2sc-generated script requires the Codex profile module: $__2scProfileModule"
    }
    Import-Module -Name $__2scProfileModule -Force -DisableNameChecking -ErrorAction Stop
    Initialize-CodexProfileFunctions
}
function 9gg {
    param([string]$GamesPath = 'E:\games')
    $folders = Get-ChildItem -Path $GamesPath -Directory
    $sized = foreach ($f in $folders) {
        $size = (Get-ChildItem -Path $f.FullName -Recurse -File -ErrorAction SilentlyContinue | Measure-Object -Property Length -Sum).Sum
        [PSCustomObject]@{ Name = $f.Name; FullName = $f.FullName; SizeBytes = if ($size) { $size } else { 0 } }
    }
    $lightest = $sized | Sort-Object SizeBytes | Select-Object -First 9
    Write-Host '=== 9 Lightest Games ===' -ForegroundColor Cyan
    foreach ($g in $lightest) {
        $gb = [math]::Round($g.SizeBytes / 1GB, 2)
        Write-Host "  $($g.Name) - $gb GB" -ForegroundColor Green
    }
    Write-Host ''
    Write-Host 'Launching 3dd menu2 for each...' -ForegroundColor Yellow
    foreach ($g in $lightest) {
        & {
    if ($args.Count -eq 0) { Write-Host "Usage: 3dd <command> [args...]" -ForegroundColor Yellow; return }
    $parts = foreach ($a in $args) { if ($a -match '\s') { "'$a'" } else { $a } }
    $cmd = $parts -join ' '
    $profilePath = $PROFILE
    $tempScript = [System.IO.Path]::GetTempFileName() + ".ps1"
    Set-Content -Path $tempScript -Value ". '$profilePath'; $cmd"
    wt new-tab powershell.exe -NoExit -ExecutionPolicy Bypass -File $tempScript
} menu2 $g.FullName
    }
}

if ($MyInvocation.InvocationName -ne '.') {
    & '9gg' @args
}
