# Generated by 2sc from function 'arch2' (2026-08-13 00:39:35).
# Self-bootstrap: load the profile environment when this script runs
# outside a profile session so it behaves exactly like the function it
# was copied from. The module is also force-re-imported when the copy
# loaded in this process is stale (psm1 changed on disk) so a long-
# running session never runs an outdated dispatcher.
$__2scProfileModule = 'C:\Users\micha\Documents\WindowsPowerShell\Modules\CodexProfileFunctions\CodexProfileFunctions.psd1'
$__2scNeedBootstrap = -not (Get-Command -Name 'Initialize-CodexProfileFunctions' -CommandType Function -ErrorAction SilentlyContinue)
if (-not $__2scNeedBootstrap) {
    $__2scLoadedModule = Get-Module -Name 'CodexProfileFunctions' -ErrorAction SilentlyContinue | Select-Object -First 1
    if ($__2scLoadedModule) {
        $__2scLoadedFingerprint = $__2scLoadedModule.SessionState.PSVariable.GetValue('ProfileModuleFingerprint')
        $__2scModuleFile = Join-Path $__2scLoadedModule.ModuleBase 'CodexProfileFunctions.psm1'
        if ([System.IO.File]::Exists($__2scModuleFile)) {
            $__2scDiskInfo = Get-Item -LiteralPath $__2scModuleFile -ErrorAction SilentlyContinue
            if ($__2scDiskInfo) {
                $__2scDiskFingerprint = '{0}|{1}' -f $__2scDiskInfo.Length, $__2scDiskInfo.LastWriteTimeUtc.Ticks
                if ([string]$__2scLoadedFingerprint -and $__2scDiskFingerprint -ne [string]$__2scLoadedFingerprint) { $__2scNeedBootstrap = $true }
            }
        }
    }
}
if ($__2scNeedBootstrap) {
    if (-not (Test-Path -LiteralPath $__2scProfileModule -PathType Leaf)) {
        throw "2sc-generated script requires the Codex profile module: $__2scProfileModule"
    }
    Import-Module -Name $__2scProfileModule -Force -DisableNameChecking -ErrorAction Stop
    Initialize-CodexProfileFunctions
}
function arch2 {
    [CmdletBinding()]
    param(
        [switch] $AdbSelfTest,
        [int] $MaxArchives = 0,
        [Parameter(ValueFromRemainingArguments = $true)][string[]] $ArchArgs
    )

    $scriptPath = 'F:\study\AI_ML\AI_and_Machine_Learning\Artificial_Intelligence\cli\codex\codex-android-old-chat-archiver\Archive-CodexOldChats.ps1'
    if (-not (Test-Path -LiteralPath $scriptPath -PathType Leaf)) {
        Write-Host "arch2 unavailable: Android archiver script is not ready: $scriptPath" -ForegroundColor Yellow
        return
    }

    $adbPath = 'F:\study\Dev_Toolchain\Android\platform-tools\adb.exe'
    if (-not (Test-Path -LiteralPath $adbPath -PathType Leaf)) {
        $adbCommand = Get-Command adb.exe -ErrorAction SilentlyContinue
        if ($adbCommand) { $adbPath = $adbCommand.Source }
    }
    if (-not (Test-Path -LiteralPath $adbPath -PathType Leaf)) {
        Write-Host 'arch2 unavailable: adb.exe is not available.' -ForegroundColor Yellow
        return
    }
    $connectedDevices = @(& $adbPath devices 2>$null | Where-Object { $_ -match '\sdevice$' })
    if ($connectedDevices.Count -eq 0) {
        Write-Host 'arch2 unavailable: no connected Android device or emulator.' -ForegroundColor Yellow
        return
    }

    try {
        if ($AdbSelfTest) {
            if ($ArchArgs -and $ArchArgs.Count -gt 0) {
                & $scriptPath -AdbSelfTest -MaxArchives $MaxArchives -MinHours 24 @ArchArgs
            } else {
                & $scriptPath -AdbSelfTest -MaxArchives $MaxArchives -MinHours 24
            }
        } else {
            if ($ArchArgs -and $ArchArgs.Count -gt 0) {
                & $scriptPath -MaxArchives $MaxArchives -MinHours 24 @ArchArgs
            } else {
                & $scriptPath -MaxArchives $MaxArchives -MinHours 24
            }
        }
    } catch {
        Write-Host "arch2 unavailable: $($_.Exception.Message)" -ForegroundColor Yellow
        return
    }
}

if ($MyInvocation.InvocationName -ne '.') {
    & 'arch2' @args
}
