# Generated by 2sc from function 'Assert-ProfileFunctionMutationCommittedChanges' (2026-08-13 00:41:04).
# Self-bootstrap: load the profile environment when this script runs
# outside a profile session so it behaves exactly like the function it
# was copied from. The module is also force-re-imported when the copy
# loaded in this process is stale (psm1 changed on disk) so a long-
# running session never runs an outdated dispatcher.
$__2scProfileModule = 'C:\Users\micha\Documents\WindowsPowerShell\Modules\CodexProfileFunctions\CodexProfileFunctions.psd1'
$__2scNeedBootstrap = -not (Get-Command -Name 'Initialize-CodexProfileFunctions' -CommandType Function -ErrorAction SilentlyContinue)
if (-not $__2scNeedBootstrap) {
    $__2scLoadedModule = Get-Module -Name 'CodexProfileFunctions' -ErrorAction SilentlyContinue | Select-Object -First 1
    if ($__2scLoadedModule) {
        $__2scLoadedFingerprint = $__2scLoadedModule.SessionState.PSVariable.GetValue('ProfileModuleFingerprint')
        $__2scModuleFile = Join-Path $__2scLoadedModule.ModuleBase 'CodexProfileFunctions.psm1'
        if ([System.IO.File]::Exists($__2scModuleFile)) {
            $__2scDiskInfo = Get-Item -LiteralPath $__2scModuleFile -ErrorAction SilentlyContinue
            if ($__2scDiskInfo) {
                $__2scDiskFingerprint = '{0}|{1}' -f $__2scDiskInfo.Length, $__2scDiskInfo.LastWriteTimeUtc.Ticks
                if ([string]$__2scLoadedFingerprint -and $__2scDiskFingerprint -ne [string]$__2scLoadedFingerprint) { $__2scNeedBootstrap = $true }
            }
        }
    }
}
if ($__2scNeedBootstrap) {
    if (-not (Test-Path -LiteralPath $__2scProfileModule -PathType Leaf)) {
        throw "2sc-generated script requires the Codex profile module: $__2scProfileModule"
    }
    Import-Module -Name $__2scProfileModule -Force -DisableNameChecking -ErrorAction Stop
    Initialize-CodexProfileFunctions
}
function Assert-ProfileFunctionMutationCommittedChanges {
    param([Parameter(Mandatory)][object[]]$Changes)
    foreach ($change in $Changes) {
        if ($null -eq $change.Verification) { continue }
        Write-ProfileFunctionMutationProgress -Stage 'verifying-profile' -Detail $change.Path
        $document = Get-ProfileFunctionMutationDocument -Path $change.Path
        foreach ($name in @($change.Verification.AbsentNames)) {
            if (Get-ProfileFunctionMutationMatch -Document $document -Name $name) {
                throw "Saved profile '$($change.Path)' still contains removed function '$name'."
            }
        }
        if (-not [string]::IsNullOrWhiteSpace($change.Verification.PresentName)) {
            $savedFunctions = @(Get-ProfileFunctionMutationMatches -Document $document -Name $change.Verification.PresentName)
            if ($savedFunctions.Count -ne 1) {
                throw "Saved profile '$($change.Path)' has $($savedFunctions.Count) definitions for '$($change.Verification.PresentName)' after mutation."
            }
            $savedFunction = $savedFunctions[0]
            if (-not $savedFunction) {
                throw "Saved profile '$($change.Path)' does not contain function '$($change.Verification.PresentName)' after mutation."
            }
            $actualBody = ConvertTo-ProfileFunctionMutationNormalizedBody -BodyText $savedFunction.Body.Extent.Text
            $expectedBody = ConvertTo-ProfileFunctionMutationNormalizedBody -BodyText $change.Verification.ExpectedBody
            if ($actualBody -cne $expectedBody) {
                throw "Saved profile '$($change.Path)' did not retain the requested body for '$($change.Verification.PresentName)'."
            }
        }
    }
}

if ($MyInvocation.InvocationName -ne '.') {
    & 'Assert-ProfileFunctionMutationCommittedChanges' @args
}
