# Generated by 2sc from function 'Assert-ZapfTreeSafe' (2026-08-13 00:39:24).
# Self-bootstrap: load the profile environment when this script runs
# outside a profile session so it behaves exactly like the function it
# was copied from. The module is also force-re-imported when the copy
# loaded in this process is stale (psm1 changed on disk) so a long-
# running session never runs an outdated dispatcher.
$__2scProfileModule = 'C:\Users\micha\Documents\WindowsPowerShell\Modules\CodexProfileFunctions\CodexProfileFunctions.psd1'
$__2scNeedBootstrap = -not (Get-Command -Name 'Initialize-CodexProfileFunctions' -CommandType Function -ErrorAction SilentlyContinue)
if (-not $__2scNeedBootstrap) {
    $__2scLoadedModule = Get-Module -Name 'CodexProfileFunctions' -ErrorAction SilentlyContinue | Select-Object -First 1
    if ($__2scLoadedModule) {
        $__2scLoadedFingerprint = $__2scLoadedModule.SessionState.PSVariable.GetValue('ProfileModuleFingerprint')
        $__2scModuleFile = Join-Path $__2scLoadedModule.ModuleBase 'CodexProfileFunctions.psm1'
        if ([System.IO.File]::Exists($__2scModuleFile)) {
            $__2scDiskInfo = Get-Item -LiteralPath $__2scModuleFile -ErrorAction SilentlyContinue
            if ($__2scDiskInfo) {
                $__2scDiskFingerprint = '{0}|{1}' -f $__2scDiskInfo.Length, $__2scDiskInfo.LastWriteTimeUtc.Ticks
                if ([string]$__2scLoadedFingerprint -and $__2scDiskFingerprint -ne [string]$__2scLoadedFingerprint) { $__2scNeedBootstrap = $true }
            }
        }
    }
}
if ($__2scNeedBootstrap) {
    if (-not (Test-Path -LiteralPath $__2scProfileModule -PathType Leaf)) {
        throw "2sc-generated script requires the Codex profile module: $__2scProfileModule"
    }
    Import-Module -Name $__2scProfileModule -Force -DisableNameChecking -ErrorAction Stop
    Initialize-CodexProfileFunctions
}
function Assert-ZapfTreeSafe {
    param([Parameter(Mandatory = $true)][string]$ExtendedTarget)

    $pending = New-Object 'System.Collections.Generic.Stack[string]'
    $pending.Push($ExtendedTarget)
    while ($pending.Count -gt 0) {
        $directory = $pending.Pop()
        try {
            $directoryAttributes = Get-ZapfAttributes -Path $directory
            if (Test-ZapfReparsePoint -Attributes $directoryAttributes) {
                [void]$reparsePoints.Add((ConvertFrom-ZapfExtendedPath $directory))
                continue
            }

            foreach ($entry in [System.IO.Directory]::EnumerateFileSystemEntries($directory)) {
                try {
                    $attributes = Get-ZapfAttributes -Path $entry
                    if (Test-ZapfReparsePoint -Attributes $attributes) {
                        [void]$reparsePoints.Add((ConvertFrom-ZapfExtendedPath $entry))
                        continue
                    }
                    if (($attributes -band [System.IO.FileAttributes]::Directory) -ne 0) {
                        $pending.Push($entry)
                    }
                } catch {
                    Add-ZapfFailure -Path $entry -Operation 'PreflightAttributes' -Exception $_.Exception
                }
            }
        } catch {
            Add-ZapfFailure -Path $directory -Operation 'PreflightEnumeration' -Exception $_.Exception
        }
    }

    if ($reparsePoints.Count -gt 0) {
        $paths = @($reparsePoints | Select-Object -Unique) -join [Environment]::NewLine
        throw ("ZAPF_FAILURE: refusing to traverse reparse points under C:\fdrive. Preserved paths:{0}{1}" -f
            [Environment]::NewLine,
            $paths)
    }
    if ($failures.Count -gt 0) {
        $summary = @(
            $failures | ForEach-Object {
                "Preflight $($_.Operation) [$($_.NativeError)] $($_.Path): $($_.Message)"
            }
        ) -join [Environment]::NewLine
        throw ("ZAPF_FAILURE: preflight could not safely inspect C:\fdrive.{0}{1}" -f
            [Environment]::NewLine,
            $summary)
    }
}

if ($MyInvocation.InvocationName -ne '.') {
    & 'Assert-ZapfTreeSafe' @args
}
