# Generated by 2sc from function 'backupf' (2026-08-12 23:57:23).
# Self-bootstrap: load the profile environment when this script runs
# outside a profile session so it behaves exactly like the function it
# was copied from. The module is also force-re-imported when the copy
# loaded in this process is stale (psm1 changed on disk) so a long-
# running session never runs an outdated dispatcher.
$__2scProfileModule = 'C:\Users\micha\Documents\WindowsPowerShell\Modules\CodexProfileFunctions\CodexProfileFunctions.psd1'
$__2scNeedBootstrap = -not (Get-Command -Name 'Initialize-CodexProfileFunctions' -CommandType Function -ErrorAction SilentlyContinue)
if (-not $__2scNeedBootstrap) {
    $__2scLoadedModule = Get-Module -Name 'CodexProfileFunctions' -ErrorAction SilentlyContinue | Select-Object -First 1
    if ($__2scLoadedModule) {
        $__2scLoadedFingerprint = $__2scLoadedModule.SessionState.PSVariable.GetValue('ProfileModuleFingerprint')
        $__2scModuleFile = Join-Path $__2scLoadedModule.ModuleBase 'CodexProfileFunctions.psm1'
        if ([System.IO.File]::Exists($__2scModuleFile)) {
            $__2scDiskInfo = Get-Item -LiteralPath $__2scModuleFile -ErrorAction SilentlyContinue
            if ($__2scDiskInfo) {
                $__2scDiskFingerprint = '{0}|{1}' -f $__2scDiskInfo.Length, $__2scDiskInfo.LastWriteTimeUtc.Ticks
                if ([string]$__2scLoadedFingerprint -and $__2scDiskFingerprint -ne [string]$__2scLoadedFingerprint) { $__2scNeedBootstrap = $true }
            }
        }
    }
}
if ($__2scNeedBootstrap) {
    if (-not (Test-Path -LiteralPath $__2scProfileModule -PathType Leaf)) {
        throw "2sc-generated script requires the Codex profile module: $__2scProfileModule"
    }
    Import-Module -Name $__2scProfileModule -Force -DisableNameChecking -ErrorAction Stop
    Initialize-CodexProfileFunctions
}
function backupf {
[CmdletBinding()]
    param(
        [switch]$Fast,
        [switch]$Consistent,
        [ValidateRange(1, 10)]
        [int]$MaxConsistencyPasses = 5,
        [ValidateRange(1, 300)]
        [int]$QuietSeconds = 15
    )

    if ($Fast -and $Consistent) {
        throw 'backupf: -Fast and -Consistent cannot be used together. Verified logical consistency is the default.'
    }

    $sourceRoot = 'F:\'
    $destinationRoot = 'C:\fdrive'
    $metadataRoot = Join-Path $destinationRoot '.fdrive-backup'
    $manifestPath = Join-Path $metadataRoot 'manifest.json'
    $completePath = Join-Path $metadataRoot 'complete.json'
    $inProgressPath = Join-Path $metadataRoot 'in-progress.json'
    $copyOptions = @(
        '/E', '/MT:64', '/R:1', '/W:1', '/J',
        '/COPY:DAT', '/DCOPY:DA', '/XJ',
        '/NFL', '/NDL', '/NP'
    )
    $runId = Get-Date -Format 'yyyyMMdd-HHmmss-fff'
    $logDirectory = Join-Path $env:LOCALAPPDATA 'CodexProfileFunctions\Logs\backupf'
    $logFile = Join-Path $logDirectory "backupf-$runId.jsonl"
    $watchdogSeconds = 1800
    $watchdogRepeatSeconds = 300

    function Throw-BackupfFailure {
        param([Parameter(Mandatory)][string]$Message)
        throw ('BACKUPF_FAILURE: {0}' -f $Message)
    }

    function Get-BackupfIdentityToken {
        param([Parameter(Mandatory)][string]$Value)
        $sha = [System.Security.Cryptography.SHA256]::Create()
        try {
            return ([System.BitConverter]::ToString(
                $sha.ComputeHash([System.Text.Encoding]::UTF8.GetBytes($Value))
            ) -replace '-', '').Substring(0, 16)
        }
        finally {
            $sha.Dispose()
        }
    }

    function Write-BackupfAtomicJson {
        param(
            [Parameter(Mandatory)][string]$Path,
            [Parameter(Mandatory)]$Value
        )
        $directory = Split-Path -Parent $Path
        if (-not (Test-Path -LiteralPath $directory -PathType Container)) {
            New-Item -ItemType Directory -Path $directory -Force -ErrorAction Stop | Out-Null
        }
        $tempPath = '{0}.tmp-{1}' -f $Path, [Guid]::NewGuid().ToString('N')
        $encoding = New-Object System.Text.UTF8Encoding($false)
        try {
            $json = ConvertTo-Json -InputObject $Value -Depth 10
            [System.IO.File]::WriteAllText($tempPath, $json, $encoding)
            Move-Item -LiteralPath $tempPath -Destination $Path -Force -ErrorAction Stop
        }
        finally {
            if (Test-Path -LiteralPath $tempPath -PathType Leaf) {
                Remove-Item -LiteralPath $tempPath -Force -ErrorAction SilentlyContinue
            }
        }
    }

    function Assert-BackupfNotReparse {
        param(
            [Parameter(Mandatory)][string]$Path,
            [Parameter(Mandatory)][string]$Description
        )
        $item = Get-Item -LiteralPath $Path -Force -ErrorAction Stop
        if (($item.Attributes -band [System.IO.FileAttributes]::ReparsePoint) -ne 0) {
            Throw-BackupfFailure ("{0} is a reparse point: {1}" -f $Description, $Path)
        }
        return $item
    }

    function Get-BackupfCimState {
        $logical = @(Get-CimInstance `
            -ClassName Win32_LogicalDisk -Filter "DeviceID='F:'" -ErrorAction Stop)
        if ($logical.Count -ne 1) {
            Throw-BackupfFailure 'F: did not resolve to exactly one logical disk.'
        }
        $logical = $logical[0]
        if ([string]$logical.DeviceID -cne 'F:' -or
            [int]$logical.DriveType -ne 3 -or
            [string]$logical.FileSystem -cne 'exFAT' -or
            [string]$logical.VolumeName -cne 'Ventoy' -or
            -not [string]::IsNullOrWhiteSpace([string]$logical.ProviderName)) {
            Throw-BackupfFailure 'F: is not the expected fixed local exFAT Ventoy source.'
        }
        if ([string]$env:SystemDrive -ieq 'F:') {
            Throw-BackupfFailure 'F: is the current system drive; refusing to back it up under this contract.'
        }

        $associations = @(Get-CimInstance `
            -ClassName Win32_LogicalDiskToPartition -ErrorAction Stop | Where-Object {
                [string]$_.Dependent -match 'DeviceID\s*=\s*"F:"'
            })
        if ($associations.Count -ne 1) {
            Throw-BackupfFailure 'F: did not resolve to exactly one partition association.'
        }
        $partitionMatch = [regex]::Match(
            [string]$associations[0].Antecedent,
            'DeviceID\s*=\s*"([^"]+)"'
        )
        if (-not $partitionMatch.Success) {
            Throw-BackupfFailure 'F: partition association did not contain a stable identifier.'
        }
        $partitionId = $partitionMatch.Groups[1].Value
        $partition = @(Get-CimInstance `
            -ClassName Win32_DiskPartition -ErrorAction Stop | Where-Object {
                [string]$_.DeviceID -ceq $partitionId
            })
        if ($partition.Count -ne 1) {
            Throw-BackupfFailure 'F: did not resolve to exactly one partition.'
        }
        $partition = $partition[0]
        $disk = @(Get-CimInstance `
            -ClassName Win32_DiskDrive -ErrorAction Stop | Where-Object {
                [int]$_.Index -eq [int]$partition.DiskIndex
            })
        if ($disk.Count -ne 1) {
            Throw-BackupfFailure 'F: did not resolve to exactly one physical disk.'
        }
        $disk = $disk[0]

        $volumeSerial = ([string]$logical.VolumeSerialNumber).Trim()
        $diskPnp = ([string]$disk.PNPDeviceID).Trim()
        if ([string]::IsNullOrWhiteSpace($volumeSerial) -or
            [string]::IsNullOrWhiteSpace($diskPnp) -or
            [string]::IsNullOrWhiteSpace([string]$partition.DeviceID)) {
            Throw-BackupfFailure 'F: is missing a stable source identity.'
        }

        $partitionIdentity = '{0}|{1}|{2}|{3}' -f (
            [string]$partition.DeviceID
        ), (
            [int64]$partition.Size
        ), (
            [int64]$partition.StartingOffset
        ), (
            [string]$partition.Type
        )
        $diskIdentity = '{0}|{1}|{2}' -f $diskPnp, (
            [string]$disk.SerialNumber
        ).Trim(), (
            [string]$disk.Model
        ).Trim()
        $tokenInput = '{0}|{1}|{2}|F:' -f $diskIdentity, $partitionIdentity, $volumeSerial

        [pscustomobject]@{
            FileSystem = ([string]$logical.FileSystem).Trim()
            VolumeLabel = ([string]$logical.VolumeName).Trim()
            VolumeSerialNumber = $volumeSerial
            DiskIdentity = $diskIdentity
            DiskPnpDeviceId = $diskPnp
            DiskSerialNumber = ([string]$disk.SerialNumber).Trim()
            DiskModel = ([string]$disk.Model).Trim()
            PartitionDeviceId = ([string]$partition.DeviceID).Trim()
            PartitionSize = [int64]$partition.Size
            PartitionOffset = [int64]$partition.StartingOffset
            PartitionIdentity = $partitionIdentity
            IdentityToken = Get-BackupfIdentityToken -Value $tokenInput
        }
    }

    function Get-BackupfRootEntryCount {
        param([Parameter(Mandatory)][string]$Path)
        return @(
            Get-ChildItem -LiteralPath $Path -Force -ErrorAction Stop | Where-Object {
                [string]$_.Name -cne '.fdrive-backup'
            }
        ).Count
    }

    if (-not (Test-Path -LiteralPath $sourceRoot -PathType Container)) {
        throw "backupf: source drive is unavailable: $sourceRoot"
    }

    try {
        Get-Item -LiteralPath $sourceRoot -Force -ErrorAction Stop | Out-Null
        Get-ChildItem -LiteralPath $sourceRoot -Force -ErrorAction Stop |
            Select-Object -First 1 | Out-Null
        Assert-BackupfNotReparse -Path $sourceRoot -Description 'F:\ source root' | Out-Null
    }
    catch {
        throw "backupf: cannot read the source root $sourceRoot. $($_.Exception.Message)"
    }

    if (-not (Test-Path -LiteralPath $destinationRoot -PathType Container)) {
        New-Item -ItemType Directory -Path $destinationRoot -Force -ErrorAction Stop | Out-Null
    }
    Assert-BackupfNotReparse -Path $destinationRoot -Description 'C:\fdrive destination root' | Out-Null
    if (Test-Path -LiteralPath (Join-Path $sourceRoot '.fdrive-backup') -PathType Container) {
        Throw-BackupfFailure 'F:\.fdrive-backup is reserved for backup metadata and must not exist in the source tree.'
    }
    if (-not (Test-Path -LiteralPath $metadataRoot -PathType Container)) {
        New-Item -ItemType Directory -Path $metadataRoot -Force -ErrorAction Stop | Out-Null
    }
    Assert-BackupfNotReparse -Path $metadataRoot -Description 'backup metadata directory' | Out-Null

    try {
        $sourceState = Get-BackupfCimState
        $sourceVolume = Get-CimInstance `
            -ClassName Win32_LogicalDisk -Filter "DeviceID='F:'" -ErrorAction Stop
        $destinationVolume = Get-CimInstance `
            -ClassName Win32_LogicalDisk -Filter "DeviceID='C:'" -ErrorAction Stop
    }
    catch {
        throw "backupf: unable to inspect source/destination capacity. $($_.Exception.Message)"
    }

    if ($null -eq $sourceVolume -or $null -eq $destinationVolume) {
        throw 'backupf: source F: or destination C: is unavailable.'
    }

    # This is a conservative capacity gate. Existing matching destination files
    # reduce actual required space on reruns, so source size is an upper bound.
    if ([int64]$destinationVolume.FreeSpace -lt [int64]$sourceVolume.Size) {
        throw ("backupf: insufficient free space on C:. Source capacity is {0:N2} GiB; C: free space is {1:N2} GiB." -f (
            [double]$sourceVolume.Size / 1GB
        ), (
            [double]$destinationVolume.FreeSpace / 1GB
        ))
    }

    New-Item -ItemType Directory -Path $logDirectory -Force -ErrorAction Stop | Out-Null

    function Write-BackupfEvent {
        param(
            [string]$Event,
            [hashtable]$Data = @{}
        )

        $record = [ordered]@{
            timestamp = (Get-Date).ToString('o')
            runId = $runId
            event = $Event
        }
        foreach ($key in $Data.Keys) {
            $record[$key] = $Data[$key]
        }
        ($record | ConvertTo-Json -Compress -Depth 4) |
            Add-Content -LiteralPath $logFile -Encoding UTF8
    }

    function Invoke-BackupfRobocopyPass {
        param(
            [Parameter(Mandatory)]
            [string]$PassName,
            [Parameter(Mandatory)]
            [string[]]$Options
        )

        $safePassName = $PassName -replace '[^A-Za-z0-9._-]', '_'
        $rawOutput = Join-Path $logDirectory "backupf-$runId-$safePassName.stdout.log"
        $rawError = Join-Path $logDirectory "backupf-$runId-$safePassName.stderr.log"
        $arguments = @($sourceRoot, $destinationRoot) + $Options
        $process = $null
        $started = Get-Date
        $lastHeartbeat = $started
        $lastWarning = $started
        $lastCpuSeconds = 0.0
        $lastFreeBytes = [int64]$destinationVolume.FreeSpace
        $lastOutputWrite = $null

        try {
            Write-BackupfEvent -Event 'robocopy-pass-started' -Data @{
                pass = $PassName
                arguments = $arguments
                stdout = $rawOutput
                stderr = $rawError
            }
            Write-Host "backupf: $PassName started. Live status every 30 seconds; log: $logFile"

            $process = Start-Process -FilePath 'robocopy.exe' -ArgumentList $arguments -NoNewWindow -PassThru `
                -RedirectStandardOutput $rawOutput -RedirectStandardError $rawError -ErrorAction Stop

            while (-not $process.HasExited) {
                Start-Sleep -Seconds 2
                $now = Get-Date
                if (($now - $lastHeartbeat).TotalSeconds -lt 30) {
                    continue
                }

                try {
                    $process.Refresh()
                    $cpuSeconds = [math]::Round($process.TotalProcessorTime.TotalSeconds, 1)
                    $freeBytes = [int64](Get-CimInstance -ClassName Win32_LogicalDisk -Filter "DeviceID='C:'" -ErrorAction Stop).FreeSpace
                    $outputWrite = if (Test-Path -LiteralPath $rawOutput -PathType Leaf) {
                        (Get-Item -LiteralPath $rawOutput -ErrorAction Stop).LastWriteTime
                    }
                    else {
                        $null
                    }
                    $cpuDelta = [math]::Round($cpuSeconds - $lastCpuSeconds, 1)
                    $freeDeltaMiB = [math]::Round(($lastFreeBytes - $freeBytes) / 1MB, 1)
                    $outputChanged = $null -ne $outputWrite -and $outputWrite -ne $lastOutputWrite
                    $elapsedMinutes = [math]::Round(($now - $started).TotalMinutes, 1)
                    $status = "pass=$PassName elapsed=$elapsedMinutes min cpu+=$cpuDelta s C:written+=$freeDeltaMiB MiB logActivity=$outputChanged"

                    Write-Progress -Activity 'backupf Robocopy' -Status $status -PercentComplete -1
                    Write-Host "backupf: $status"
                    Write-BackupfEvent -Event 'heartbeat' -Data @{
                        pass = $PassName
                        elapsedMinutes = $elapsedMinutes
                        cpuDeltaSeconds = $cpuDelta
                        destinationWrittenMiB = $freeDeltaMiB
                        outputChanged = $outputChanged
                    }

                    $noActivity = $cpuDelta -le 0 -and $freeDeltaMiB -le 0 -and -not $outputChanged
                    if ($noActivity -and ($now - $started).TotalSeconds -ge $watchdogSeconds -and
                        ($now - $lastWarning).TotalSeconds -ge $watchdogRepeatSeconds) {
                        $message = "backupf: warning-only watchdog: no observed CPU, destination-space, or log activity for $watchdogSeconds seconds during $PassName. Robocopy is left running because metadata-heavy phases can be healthy."
                        Write-Warning $message
                        Write-BackupfEvent -Event 'watchdog-warning' -Data @{ pass = $PassName; message = $message }
                        $lastWarning = $now
                    }

                    $lastHeartbeat = $now
                    $lastCpuSeconds = $cpuSeconds
                    $lastFreeBytes = $freeBytes
                    $lastOutputWrite = $outputWrite
                }
                catch {
                    # Telemetry must not terminate a healthy Robocopy process.
                    $message = "backupf: telemetry warning during $PassName. $($_.Exception.Message)"
                    Write-Warning $message
                    Write-BackupfEvent -Event 'telemetry-warning' -Data @{ pass = $PassName; message = $message }
                    $lastHeartbeat = $now
                }
            }

            $process.WaitForExit()
            $process.Refresh()
            $exitCode = [int]$process.ExitCode
            $global:LASTEXITCODE = $exitCode
            Write-Progress -Activity 'backupf Robocopy' -Completed
            Write-BackupfEvent -Event 'robocopy-pass-completed' -Data @{
                pass = $PassName
                exitCode = $exitCode
                elapsedSeconds = [math]::Round(((Get-Date) - $started).TotalSeconds, 1)
            }
            Write-Host "backupf: $PassName completed with Robocopy exit code $exitCode."
            return [pscustomobject]@{
                Pass = $PassName
                ExitCode = $exitCode
                StdOut = $rawOutput
                StdErr = $rawError
            }
        }
        finally {
            if ($null -ne $process) {
                if (-not $process.HasExited) {
                    Write-BackupfEvent -Event 'robocopy-pass-interrupted' -Data @{ pass = $PassName; processId = $process.Id }
                    $process.Kill()
                    $process.WaitForExit()
                }
                $process.Dispose()
            }
            Write-Progress -Activity 'backupf Robocopy' -Completed
        }
    }

    function Test-BackupfSourceDifference {
        param([int]$ExitCode)
        return (($ExitCode -band 1) -ne 0) -or (($ExitCode -band 4) -ne 0)
    }

    try {
        $state = [ordered]@{
            SchemaVersion = 1
            Status = 'IN_PROGRESS'
            Function = 'backupf'
            RunId = $runId
            StartedUtc = [DateTime]::UtcNow.ToString('o')
            SourceDrive = 'F:'
            SourceRoot = 'F:\'
            DestinationRoot = 'C:\fdrive'
            SourceIdentityToken = $sourceState.IdentityToken
            VerificationContract = 'Robocopy logical D/A/T comparison with a quiet window; no VSS snapshot; no cryptographic verification'
            VssSnapshot = $false
            CryptographicVerification = $false
        }
        if (Test-Path -LiteralPath $completePath -PathType Leaf) {
            Remove-Item -LiteralPath $completePath -Force -ErrorAction Stop
        }
        Write-BackupfAtomicJson -Path $inProgressPath -Value $state

        Write-BackupfEvent -Event 'backup-started' -Data @{
            source = $sourceRoot
            destination = $destinationRoot
            mode = if ($Fast) { 'fast-unverified' } else { 'logical-consistency' }
            contract = $state.VerificationContract
            inaccessibleFiles = 'Robocopy traversal errors fail the run and never produce verified status'
        }
        Write-Host 'backupf: Robocopy logical comparison verifies D/A/T copy semantics. F: is exFAT, so this is not an atomic VSS snapshot and not a cryptographic checksum verification.'

        $initialCopy = Invoke-BackupfRobocopyPass -PassName 'initial-copy' -Options $copyOptions
        if ($initialCopy.ExitCode -ge 8) {
            Write-BackupfEvent -Event 'robocopy-error' -Data @{ pass = $initialCopy.Pass; exitCode = $initialCopy.ExitCode }
            throw "backupf: initial copy failed with Robocopy exit code $($initialCopy.ExitCode). See $($initialCopy.StdOut) and $($initialCopy.StdErr)."
        }

        if ($Fast) {
            $message = 'backupf: FAST COMPLETE. The copy pass completed, but this run was not logically consistency-verified.'
            Write-Warning $message
            Write-BackupfEvent -Event 'fast-complete-not-verified' -Data @{ exitCode = $initialCopy.ExitCode; message = $message }
            $state.Status = 'FAST_COMPLETE_NOT_VERIFIED'
            $state.CompletedUtc = [DateTime]::UtcNow.ToString('o')
            $state.RobocopyExitCode = $initialCopy.ExitCode
            Write-BackupfAtomicJson -Path $inProgressPath -Value $state
            return [pscustomobject]@{
                Result = 'FAST_COMPLETE_NOT_LOGICALLY_VERIFIED'
                RobocopyExitCode = $initialCopy.ExitCode
                Log = $logFile
                VerifiedMarkerCreated = $false
            }
        }

        $comparisonOptions = @($copyOptions + '/L')
        for ($passNumber = 1; $passNumber -le $MaxConsistencyPasses; $passNumber++) {
            $before = Invoke-BackupfRobocopyPass -PassName "compare-$passNumber-before-quiet" -Options $comparisonOptions
            if ($before.ExitCode -ge 8) {
                Write-BackupfEvent -Event 'comparison-error' -Data @{ pass = $passNumber; exitCode = $before.ExitCode }
                throw "backupf: comparison pass $passNumber failed with Robocopy exit code $($before.ExitCode). Verification cannot continue."
            }

            if (Test-BackupfSourceDifference -ExitCode $before.ExitCode) {
                Write-BackupfEvent -Event 'source-difference-detected' -Data @{ pass = $passNumber; stage = 'before-quiet'; exitCode = $before.ExitCode }
                $catchUp = Invoke-BackupfRobocopyPass -PassName "catchup-$passNumber-before-quiet" -Options $copyOptions
                if ($catchUp.ExitCode -ge 8) {
                    Write-BackupfEvent -Event 'robocopy-error' -Data @{ pass = $catchUp.Pass; exitCode = $catchUp.ExitCode }
                    throw "backupf: catch-up pass $passNumber failed with Robocopy exit code $($catchUp.ExitCode)."
                }
                continue
            }

            Write-BackupfEvent -Event 'quiet-window-started' -Data @{ pass = $passNumber; quietSeconds = $QuietSeconds }
            $quietUntil = (Get-Date).AddSeconds($QuietSeconds)
            while ((Get-Date) -lt $quietUntil) {
                $remaining = [math]::Max(0, [math]::Ceiling(($quietUntil - (Get-Date)).TotalSeconds))
                Write-Progress -Activity 'backupf verification' -Status "quiet window $passNumber of $MaxConsistencyPasses; $remaining seconds remaining" -PercentComplete -1
                Start-Sleep -Seconds 1
            }
            Write-Progress -Activity 'backupf verification' -Completed

            $after = Invoke-BackupfRobocopyPass -PassName "compare-$passNumber-after-quiet" -Options $comparisonOptions
            if ($after.ExitCode -ge 8) {
                Write-BackupfEvent -Event 'comparison-error' -Data @{ pass = $passNumber; exitCode = $after.ExitCode }
                throw "backupf: post-quiet comparison pass $passNumber failed with Robocopy exit code $($after.ExitCode). Verification cannot continue."
            }

            if (-not (Test-BackupfSourceDifference -ExitCode $after.ExitCode)) {
                $finalState = Get-BackupfCimState
                if ([string]$finalState.IdentityToken -cne [string]$sourceState.IdentityToken) {
                    throw 'backupf: F: identity changed during logical verification; no verified marker was created.'
                }
                $sourceRootEntryCount = Get-BackupfRootEntryCount -Path $sourceRoot
                $destinationRootEntryCount = Get-BackupfRootEntryCount -Path $destinationRoot
                if ($sourceRootEntryCount -lt 1 -or $destinationRootEntryCount -lt 1) {
                    throw 'backupf: verified marker requires at least one non-metadata source and destination root entry.'
                }
                $manifest = [ordered]@{
                    SchemaVersion = 1
                    Status = 'VERIFIED'
                    Function = 'backupf'
                    RunId = $runId
                    VerifiedAtUtc = [DateTime]::UtcNow.ToString('o')
                    SourceDrive = 'F:'
                    SourceRoot = 'F:\'
                    DestinationRoot = 'C:\fdrive'
                    SourceDriveType = 'Fixed'
                    SourceFileSystem = 'exFAT'
                    SourceVolumeLabel = $finalState.VolumeLabel
                    SourceVolumeSerialNumber = $finalState.VolumeSerialNumber
                    SourceIdentityToken = $finalState.IdentityToken
                    SourceDiskIdentity = $finalState.DiskIdentity
                    SourceDiskPnpDeviceId = $finalState.DiskPnpDeviceId
                    SourceDiskSerialNumber = $finalState.DiskSerialNumber
                    SourcePartitionDeviceId = $finalState.PartitionDeviceId
                    SourcePartitionSize = $finalState.PartitionSize
                    SourcePartitionOffset = $finalState.PartitionOffset
                    SourceRootEntryCount = $sourceRootEntryCount
                    DestinationRootEntryCount = $destinationRootEntryCount
                    VerificationPass = $passNumber
                    QuietSeconds = $QuietSeconds
                    InitialCopyRobocopyExitCode = $initialCopy.ExitCode
                    FinalComparisonRobocopyExitCode = $after.ExitCode
                    CopySemantics = 'Robocopy D/A/T; destination-only entries preserved; no mirror; no deletion'
                    VerificationContract = $state.VerificationContract
                    VssSnapshot = $false
                    CryptographicVerification = $false
                    InaccessibleFilesFailClosed = $true
                }
                Write-BackupfAtomicJson -Path $manifestPath -Value $manifest
                $manifestHash = (Get-FileHash -LiteralPath $manifestPath -Algorithm SHA256 -ErrorAction Stop).Hash.ToUpperInvariant()
                $complete = [ordered]@{
                    SchemaVersion = 1
                    Status = 'VERIFIED'
                    Function = 'backupf'
                    RunId = $runId
                    ManifestPath = $manifestPath
                    ManifestSha256 = $manifestHash
                    VerifiedAtUtc = $manifest.VerifiedAtUtc
                    VerificationContract = $state.VerificationContract
                    VssSnapshot = $false
                    CryptographicVerification = $false
                }
                Write-BackupfAtomicJson -Path $completePath -Value $complete
                $state.Status = 'VERIFIED'
                $state.CompletedUtc = [DateTime]::UtcNow.ToString('o')
                $state.ManifestSha256 = $manifestHash
                $state.RobocopyExitCode = $after.ExitCode
                Write-BackupfAtomicJson -Path $inProgressPath -Value $state
                Write-BackupfEvent -Event 'logical-verified' -Data @{
                    pass = $passNumber
                    quietSeconds = $QuietSeconds
                    beforeExitCode = $before.ExitCode
                    afterExitCode = $after.ExitCode
                }
                Write-Host "backupf: LOGICALLY VERIFIED after pass $passNumber and a $QuietSeconds-second quiet window. Destination-only files were preserved. This is not an atomic snapshot or cryptographic checksum verification."
                return [pscustomobject]@{
                    Result = 'LOGICALLY_VERIFIED'
                    VerificationPass = $passNumber
                    QuietSeconds = $QuietSeconds
                    Log = $logFile
                    Manifest = $manifestPath
                    CompletionMarker = $completePath
                    ManifestSha256 = $manifestHash
                    VerifiedMarkerCreated = $true
                    CryptographicVerification = $false
                }
            }

            Write-BackupfEvent -Event 'source-difference-detected' -Data @{ pass = $passNumber; stage = 'after-quiet'; exitCode = $after.ExitCode }
            $catchUp = Invoke-BackupfRobocopyPass -PassName "catchup-$passNumber-after-quiet" -Options $copyOptions
            if ($catchUp.ExitCode -ge 8) {
                Write-BackupfEvent -Event 'robocopy-error' -Data @{ pass = $catchUp.Pass; exitCode = $catchUp.ExitCode }
                throw "backupf: catch-up pass $passNumber failed with Robocopy exit code $($catchUp.ExitCode)."
            }
        }

        $message = "backupf: INDETERMINATE_SOURCE_CONTINUES_CHANGING after $MaxConsistencyPasses verification passes. No atomic snapshot was produced; the destination was not deleted or mirrored."
        Write-BackupfEvent -Event 'indeterminate-source-changing' -Data @{
            maxConsistencyPasses = $MaxConsistencyPasses
            quietSeconds = $QuietSeconds
            message = $message
        }
        throw $message
    }
    catch {
        if ($null -ne $state) {
            try {
                $state.Status = 'FAILED'
                $state.FailedUtc = [DateTime]::UtcNow.ToString('o')
                $state.Error = $_.Exception.Message
                Write-BackupfAtomicJson -Path $inProgressPath -Value $state
            }
            catch {
                Write-Warning ('backupf could not update its failure state marker: {0}' -f $_.Exception.Message)
            }
        }
        Write-BackupfEvent -Event 'backup-failed' -Data @{ message = $_.Exception.Message }
        throw
    }
}

if ($MyInvocation.InvocationName -ne '.') {
    & 'backupf' @args
}
