# Generated by 2sc from function 'be' (2026-08-13 00:38:41).
# Self-bootstrap: load the profile environment when this script runs
# outside a profile session so it behaves exactly like the function it
# was copied from. The module is also force-re-imported when the copy
# loaded in this process is stale (psm1 changed on disk) so a long-
# running session never runs an outdated dispatcher.
$__2scProfileModule = 'C:\Users\micha\Documents\WindowsPowerShell\Modules\CodexProfileFunctions\CodexProfileFunctions.psd1'
$__2scNeedBootstrap = -not (Get-Command -Name 'Initialize-CodexProfileFunctions' -CommandType Function -ErrorAction SilentlyContinue)
if (-not $__2scNeedBootstrap) {
    $__2scLoadedModule = Get-Module -Name 'CodexProfileFunctions' -ErrorAction SilentlyContinue | Select-Object -First 1
    if ($__2scLoadedModule) {
        $__2scLoadedFingerprint = $__2scLoadedModule.SessionState.PSVariable.GetValue('ProfileModuleFingerprint')
        $__2scModuleFile = Join-Path $__2scLoadedModule.ModuleBase 'CodexProfileFunctions.psm1'
        if ([System.IO.File]::Exists($__2scModuleFile)) {
            $__2scDiskInfo = Get-Item -LiteralPath $__2scModuleFile -ErrorAction SilentlyContinue
            if ($__2scDiskInfo) {
                $__2scDiskFingerprint = '{0}|{1}' -f $__2scDiskInfo.Length, $__2scDiskInfo.LastWriteTimeUtc.Ticks
                if ([string]$__2scLoadedFingerprint -and $__2scDiskFingerprint -ne [string]$__2scLoadedFingerprint) { $__2scNeedBootstrap = $true }
            }
        }
    }
}
if ($__2scNeedBootstrap) {
    if (-not (Test-Path -LiteralPath $__2scProfileModule -PathType Leaf)) {
        throw "2sc-generated script requires the Codex profile module: $__2scProfileModule"
    }
    Import-Module -Name $__2scProfileModule -Force -DisableNameChecking -ErrorAction Stop
    Initialize-CodexProfileFunctions
}
function be {
[CmdletBinding()]param()
function Get-BeFunctionDefinitionMap {
    param(
        [Parameter(Mandatory)][string]$Path
    )
    $definitions = @{}
    if (-not (Test-Path -LiteralPath $Path)) { return $definitions }
    $item = Get-Item -LiteralPath $Path -Force -ErrorAction Stop
    if ($item.PSIsContainer) {
        $rootPath = [IO.Path]::GetFullPath($item.FullName).TrimEnd('\')
        $files = @(Get-ChildItem -LiteralPath $rootPath -Filter '*.ps1' -File -Recurse -ErrorAction Stop | Sort-Object FullName)
    } else {
        $rootPath = [IO.Path]::GetDirectoryName($item.FullName)
        $files = @($item)
    }
    foreach ($file in $files) {
        $tokens = $null; $parseErrors = $null
        $ast = [System.Management.Automation.Language.Parser]::ParseFile($file.FullName, [ref]$tokens, [ref]$parseErrors)
        $syntaxErrors = @($parseErrors | Where-Object { $_.ErrorId -ne 'ModuleNotFoundDuringParse' })
        if ($syntaxErrors.Count -gt 0) { throw "BE: cannot count functions because '$($file.FullName)' does not parse: $($syntaxErrors[0].Message)" }
        $relativePath = if ($item.PSIsContainer) { $file.FullName.Substring($rootPath.Length).TrimStart('\') } else { $file.Name }
        $relativePath = $relativePath.ToLowerInvariant()
        foreach ($definition in @($ast.EndBlock.Statements | Where-Object { $_ -is [System.Management.Automation.Language.FunctionDefinitionAst] })) {
            $name = $definition.Name -replace '^(?i:(?:global|script|local|private):)+', ''
            $definitionText = (($definition.Extent.Text.Trim() -replace "`r`n", "`n") -replace "`r", "`n")
            $part = "$relativePath`n$definitionText"
            if ($definitions.ContainsKey($name)) { $definitions[$name] = @($definitions[$name]) + $part } else { $definitions[$name] = @($part) }
        }
    }
    foreach ($name in @($definitions.Keys)) { $definitions[$name] = @($definitions[$name] | Sort-Object) -join "`n`0`n" }
    return $definitions
}
$backupScript = 'F:\backup\windowsapps\profile\profile.ps1'
$backupRoot = 'F:\backup\windowsapps\profile\backup-data'
$snapshotPath = Join-Path $backupRoot 'be-function-snapshot.json'
[System.IO.Directory]::CreateDirectory($backupRoot) | Out-Null
if (-not (Test-Path -LiteralPath $backupScript -PathType Leaf)) { throw "BE: profile backup script is missing: $backupScript" }

# ---- count functions changed since the previous be run (before any step can alter state) ----
$countPaths = @(
    'C:\Users\micha\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1',
    'C:\Users\micha\Documents\PowerShell\Microsoft.PowerShell_profile.ps1',
    'C:\Users\micha\Documents\WindowsPowerShell\ProfileSources\ps5-profile-portable\Microsoft.PowerShell_profile.runtime.ps1',
    'C:\Users\micha\Documents\WindowsPowerShell\ProfileSources\ps5-profile-portable\Microsoft.PowerShell_profile.full.ps1',
    'C:\Users\micha\Documents\WindowsPowerShell\ProfileSources\ps5-profile-portable\Microsoft.PowerShell_profile.full.definitions.ps1',
    'C:\Users\micha\Documents\WindowsPowerShell\ProfileSources\ps5-profile-portable\Microsoft.PowerShell_profile.ps1',
    'C:\Users\micha\Documents\WindowsPowerShell\ProfileSources\ps5-profile-portable\legacy-safe-functions',
    'C:\Users\micha\Documents\WindowsPowerShell\Modules\CodexProfileFunctions\CodexProfileFunctions.psm1'
)
$currentMap = @{}
foreach ($p in $countPaths) {
    try {
        $m = Get-BeFunctionDefinitionMap -Path $p
        foreach ($name in $m.Keys) {
            if ($currentMap.ContainsKey($name)) { $currentMap[$name] += "`n`0`n" + $m[$name] } else { $currentMap[$name] = $m[$name] }
        }
    } catch {
        Write-Warning "BE: could not scan '$p': $($_.Exception.Message)"
    }
}
$sha = [System.Security.Cryptography.SHA256]::Create()
$curHash = @{}
foreach ($name in $currentMap.Keys) {
    $curHash[$name] = ([BitConverter]::ToString($sha.ComputeHash([System.Text.Encoding]::UTF8.GetBytes($currentMap[$name]))) -replace '-', '')
}
$prevHash = @{}
$snapshotExisted = $false
if (Test-Path -LiteralPath $snapshotPath -PathType Leaf) {
    try {
        $prevObj = Get-Content -LiteralPath $snapshotPath -Raw | ConvertFrom-Json
        foreach ($prop in $prevObj.functions.PSObject.Properties) { $prevHash[$prop.Name] = [string]$prop.Value }
        $snapshotExisted = $true
    } catch {
        Write-Warning "BE: could not read previous snapshot: $($_.Exception.Message)"
    }
}
$functionsChanged = 0
if ($snapshotExisted) {
    $allKeys = @($curHash.Keys + $prevHash.Keys | Sort-Object -Unique)
    foreach ($k in $allKeys) {
        if (-not $curHash.ContainsKey($k) -or -not $prevHash.ContainsKey($k) -or $curHash[$k] -cne $prevHash[$k]) { $functionsChanged++ }
    }
} else {
    Write-Host 'BE: no previous snapshot found - recording baseline (first run).' -ForegroundColor DarkYellow
}

# ---- the four steps, in the user's exact order ----
Write-Host 'BE: [1/4] Reloading current profile (. $profile)...' -ForegroundColor Cyan
. $profile
Write-Host 'BE: [2/4] Backing up profile files (latest functions)...' -ForegroundColor Cyan
try { & $backupScript } catch { throw "BE: profile backup failed: $($_.Exception.Message)" }
Write-Host 'BE: [3/4] Syncing PowerShell 7 profile (ps527)...' -ForegroundColor Cyan
$ps527Command = Get-Command ps527 -CommandType Function -ErrorAction SilentlyContinue | Select-Object -First 1
if (-not $ps527Command) { throw 'BE: ps527 function is unavailable after profile reload.' }
& $ps527Command
Write-Host 'BE: [4/4] Done.' -ForegroundColor Cyan

# ---- persist the snapshot (the new baseline) ----
try {
    $snapObj = [pscustomobject]@{ createdAt = (Get-Date).ToString('o'); functions = $curHash }
    [System.IO.File]::WriteAllText($snapshotPath, ($snapObj | ConvertTo-Json -Depth 3), (New-Object System.Text.UTF8Encoding($false)))
} catch {
    Write-Warning "BE: could not save the function snapshot: $($_.Exception.Message)"
}
Write-Output "BE_OK functions_changed=$functionsChanged"
}

if ($MyInvocation.InvocationName -ne '.') {
    & 'be' @args
}
