# Generated by 2sc from function 'before' (2026-08-12 20:05:06).
function before {
[CmdletBinding()]
    param(
        [switch]$Full,
        [switch]$Quick,
        [switch]$WrapperSelfTest
    )

    if ($Full -and $Quick) {
        throw 'before: use either -Full or -Quick, not both.'
    }

    $profileBackupScript = 'F:\backup\windowsapps\profile\profile.ps1'
    $getServicingState = {
        $pending = New-Object System.Collections.Generic.List[string]
        if (Test-Path 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Component Based Servicing\RebootPending') { $pending.Add('CBS RebootPending') }
        if (Test-Path 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\WindowsUpdate\Auto Update\RebootRequired') { $pending.Add('Windows Update RebootRequired') }
        $sessionManager = Get-ItemProperty 'HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager' -ErrorAction SilentlyContinue
        if ($sessionManager -and ($sessionManager.PSObject.Properties.Name -contains 'PendingFileRenameOperations') -and $sessionManager.PendingFileRenameOperations) {
            $pending.Add('PendingFileRenameOperations')
        }
        $active = @(Get-Process TiWorker,TrustedInstaller,MoUsoCoreWorker,msiexec,dism,sfc -ErrorAction SilentlyContinue | Select-Object -ExpandProperty ProcessName -Unique)
        [pscustomobject]@{
            Pending = @($pending)
            ActiveServicing = @($active)
        }
    }

    if ($WrapperSelfTest) {
        if (-not (Test-Path -LiteralPath $profileBackupScript -PathType Leaf)) {
            throw "before: profile backup script is missing: $profileBackupScript"
        }
        $tokens = $null
        $errors = $null
        [void][System.Management.Automation.Language.Parser]::ParseFile($profileBackupScript, [ref]$tokens, [ref]$errors)
        if (@($errors).Count -gt 0) {
            throw "before: profile backup parser error: $($errors[0].Message)"
        }
        backcod -SelfTest
        ass -SelfTest
        fff -SelfTest
        Write-Output 'BEFORE_SELFTEST_OK defaultMode=full explicitStatusMode=-Quick steps=4'
        return
    }

    $preflight = & $getServicingState
    if ($Quick) {
        Write-Output ("BEFORE_QUICK_OK pending=[{0}] activeServicing=[{1}] fullWorkflowSkipped=true reason=explicit-Quick" -f ($preflight.Pending -join '; '), ($preflight.ActiveServicing -join '; '))
        $global:LASTEXITCODE = 0
        return
    }

    $identity = [Security.Principal.WindowsIdentity]::GetCurrent()
    $principal = New-Object Security.Principal.WindowsPrincipal($identity)
    if (-not $principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) {
        throw 'before requires an elevated Windows PowerShell 5.1 session for its DISM and SFC repair stage.'
    }

    $steps = @(
        [pscustomobject]@{ Name = 'Profile backup'; Action = { if (Test-Path -LiteralPath $profileBackupScript -PathType Leaf) { & $profileBackupScript } else { Write-Warning "before: profile backup script not found, skipping: $profileBackupScript" } } },
        [pscustomobject]@{ Name = 'Codex backup'; Action = { backcod } },
        [pscustomobject]@{ Name = 'Latest game backup'; Action = { ass } },
        [pscustomobject]@{ Name = 'DISM and SFC repair'; Action = { fff } }
    )

    $overall = [System.Diagnostics.Stopwatch]::StartNew()
    $currentStepName = 'preflight'
    $currentStepNumber = 0
    try {
        Write-Host ("BEFORE_PROGRESS stage=preflight pending=[{0}] activeServicing=[{1}] mode=full" -f ($preflight.Pending -join '; '), ($preflight.ActiveServicing -join '; ')) -ForegroundColor Cyan
        for ($index = 0; $index -lt $steps.Count; $index++) {
            $step = $steps[$index]
            $currentStepName = $step.Name
            $currentStepNumber = $index + 1
            $stepWatch = [System.Diagnostics.Stopwatch]::StartNew()
            Write-Host ("BEFORE_PROGRESS stage=starting step={0}/{1} name=[{2}] elapsed_ms={3}" -f $currentStepNumber, $steps.Count, $step.Name, $overall.ElapsedMilliseconds) -ForegroundColor Cyan
            & $step.Action
            if (-not $?) { throw "before: $($step.Name) reported failure." }
            $stepWatch.Stop()
            Write-Host ("BEFORE_PROGRESS stage=completed step={0}/{1} name=[{2}] step_elapsed_ms={3} total_elapsed_ms={4}" -f $currentStepNumber, $steps.Count, $step.Name, $stepWatch.ElapsedMilliseconds, $overall.ElapsedMilliseconds) -ForegroundColor Green
        }

        $postflight = & $getServicingState
        $overall.Stop()
        $global:LASTEXITCODE = 0
        Write-Host ("BEFORE_OK steps={0} elapsed_ms={1} pending=[{2}] activeServicing=[{3}]" -f $steps.Count, $overall.ElapsedMilliseconds, ($postflight.Pending -join '; '), ($postflight.ActiveServicing -join '; ')) -ForegroundColor Green
    } catch {
        $overall.Stop()
        $global:LASTEXITCODE = 1
        Write-Host ("BEFORE_FAILED step={0}/{1} name=[{2}] elapsed_ms={3} message=[{4}]" -f $currentStepNumber, $steps.Count, $currentStepName, $overall.ElapsedMilliseconds, $_.Exception.Message) -ForegroundColor Red
        throw
    }
}

if ($MyInvocation.InvocationName -ne '.') {
    & 'before' @args
}
