# Generated by 2sc from function 'bios2' (2026-08-13 00:43:29).
# Self-bootstrap: load the profile environment when this script runs
# outside a profile session so it behaves exactly like the function it
# was copied from. The module is also force-re-imported when the copy
# loaded in this process is stale (psm1 changed on disk) so a long-
# running session never runs an outdated dispatcher.
$__2scProfileModule = 'C:\Users\micha\Documents\WindowsPowerShell\Modules\CodexProfileFunctions\CodexProfileFunctions.psd1'
$__2scNeedBootstrap = -not (Get-Command -Name 'Initialize-CodexProfileFunctions' -CommandType Function -ErrorAction SilentlyContinue)
if (-not $__2scNeedBootstrap) {
    $__2scLoadedModule = Get-Module -Name 'CodexProfileFunctions' -ErrorAction SilentlyContinue | Select-Object -First 1
    if ($__2scLoadedModule) {
        $__2scLoadedFingerprint = $__2scLoadedModule.SessionState.PSVariable.GetValue('ProfileModuleFingerprint')
        $__2scModuleFile = Join-Path $__2scLoadedModule.ModuleBase 'CodexProfileFunctions.psm1'
        if ([System.IO.File]::Exists($__2scModuleFile)) {
            $__2scDiskInfo = Get-Item -LiteralPath $__2scModuleFile -ErrorAction SilentlyContinue
            if ($__2scDiskInfo) {
                $__2scDiskFingerprint = '{0}|{1}' -f $__2scDiskInfo.Length, $__2scDiskInfo.LastWriteTimeUtc.Ticks
                if ([string]$__2scLoadedFingerprint -and $__2scDiskFingerprint -ne [string]$__2scLoadedFingerprint) { $__2scNeedBootstrap = $true }
            }
        }
    }
}
if ($__2scNeedBootstrap) {
    if (-not (Test-Path -LiteralPath $__2scProfileModule -PathType Leaf)) {
        throw "2sc-generated script requires the Codex profile module: $__2scProfileModule"
    }
    Import-Module -Name $__2scProfileModule -Force -DisableNameChecking -ErrorAction Stop
    Initialize-CodexProfileFunctions
}
function bios2 {
    $biosFile = "F:\Downloads\X870EAORUSPRO11.FB1a"
    $usb = Get-Volume | Where-Object { $_.DriveType -eq 'Removable' } | Select-Object -First 1
    if (-not $usb -or -not $usb.DriveLetter) { Write-Host "[bios2] No USB drive found. Insert a USB stick." -ForegroundColor Red; return }
    $usbRoot = "$($usb.DriveLetter):\"
    if ($usb.FileSystemType -ne 'FAT32') {
        Write-Host "[bios2] Formatting $($usb.DriveLetter): as FAT32..." -ForegroundColor Yellow
        Format-Volume -DriveLetter $usb.DriveLetter -FileSystem FAT32 -NewFileSystemLabel "BIOS" -Confirm:$false -Force
    }
    if (-not (Test-Path $biosFile)) { Write-Host "[bios2] BIOS file not found: $biosFile" -ForegroundColor Red; return }
    Write-Host "[bios2] Copying BIOS to $usbRoot ..." -ForegroundColor Cyan
    Copy-Item $biosFile $usbRoot -Force
    Write-Host "[bios2] BIOS file on USB. Rebooting into UEFI in 5 seconds..." -ForegroundColor Green
    Write-Host "[bios2] In BIOS: Q-Flash > Update BIOS > select X870EAORUSPRO11.FB1a > flash." -ForegroundColor Yellow
    shutdown /r /fw /t 5
}

if ($MyInvocation.InvocationName -ne '.') {
    & 'bios2' @args
}
