# Generated by 2sc from function 'cctools' (2026-08-13 00:10:26).
# Self-bootstrap: load the profile environment when this script runs
# outside a profile session so it behaves exactly like the function it
# was copied from. The module is also force-re-imported when the copy
# loaded in this process is stale (psm1 changed on disk) so a long-
# running session never runs an outdated dispatcher.
$__2scProfileModule = 'C:\Users\micha\Documents\WindowsPowerShell\Modules\CodexProfileFunctions\CodexProfileFunctions.psd1'
$__2scNeedBootstrap = -not (Get-Command -Name 'Initialize-CodexProfileFunctions' -CommandType Function -ErrorAction SilentlyContinue)
if (-not $__2scNeedBootstrap) {
    $__2scLoadedModule = Get-Module -Name 'CodexProfileFunctions' -ErrorAction SilentlyContinue | Select-Object -First 1
    if ($__2scLoadedModule) {
        $__2scLoadedFingerprint = $__2scLoadedModule.SessionState.PSVariable.GetValue('ProfileModuleFingerprint')
        $__2scModuleFile = Join-Path $__2scLoadedModule.ModuleBase 'CodexProfileFunctions.psm1'
        if ([System.IO.File]::Exists($__2scModuleFile)) {
            $__2scDiskInfo = Get-Item -LiteralPath $__2scModuleFile -ErrorAction SilentlyContinue
            if ($__2scDiskInfo) {
                $__2scDiskFingerprint = '{0}|{1}' -f $__2scDiskInfo.Length, $__2scDiskInfo.LastWriteTimeUtc.Ticks
                if ([string]$__2scLoadedFingerprint -and $__2scDiskFingerprint -ne [string]$__2scLoadedFingerprint) { $__2scNeedBootstrap = $true }
            }
        }
    }
}
if ($__2scNeedBootstrap) {
    if (-not (Test-Path -LiteralPath $__2scProfileModule -PathType Leaf)) {
        throw "2sc-generated script requires the Codex profile module: $__2scProfileModule"
    }
    Import-Module -Name $__2scProfileModule -Force -DisableNameChecking -ErrorAction Stop
    Initialize-CodexProfileFunctions
}
function cctools {
    $profilePath = Join-Path $env:USERPROFILE 'Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1'
    if (-not (Test-Path -LiteralPath $profilePath -PathType Leaf)) { throw "cctools profile not found: $profilePath" }
    $commands = @('kvrt','dism++','tweak','flyoobe','gdbooster','adw','cleanc','getascrm')
    $procs = @()
    try {
        for ($i=0; $i -lt $commands.Count; $i++) {
            $name=$commands[$i]; Write-Progress -Id 773 -Activity 'cctools' -Status "Starting $name" -PercentComplete ([int](($i/$commands.Count)*60))
            $script = ". '$profilePath'; & $name"
            $procs += Start-Process -FilePath "$env:SystemRoot\System32\WindowsPowerShell\v1.0\powershell.exe" -ArgumentList @('-NoProfile','-ExecutionPolicy','Bypass','-Command',$script) -PassThru -ErrorAction Stop
        }
        Write-Progress -Id 773 -Activity 'cctools' -Status 'Waiting for child commands' -PercentComplete 70
        $procs | Where-Object { $_ -and -not $_.HasExited } | ForEach-Object { $_.WaitForExit(); if ($_.ExitCode -ne 0) { throw "cctools child pid=$($_.Id) failed with exit code $($_.ExitCode)" } }
        Write-Progress -Id 773 -Activity 'cctools' -Status 'Launching follow-up commands' -PercentComplete 90
        sj gccleaner; sj classuni; sj chris
        Write-Host 'CCTOOLS_OK' -ForegroundColor Green
    } finally { Write-Progress -Id 773 -Activity 'cctools' -Completed }
}

if ($MyInvocation.InvocationName -ne '.') {
    & 'cctools' @args
}
