# Generated by 2sc from function 'claw' (2026-08-13 00:06:07).
# Self-bootstrap: load the profile environment when this script runs
# outside a profile session so it behaves exactly like the function it
# was copied from. The module is also force-re-imported when the copy
# loaded in this process is stale (psm1 changed on disk) so a long-
# running session never runs an outdated dispatcher.
$__2scProfileModule = 'C:\Users\micha\Documents\WindowsPowerShell\Modules\CodexProfileFunctions\CodexProfileFunctions.psd1'
$__2scNeedBootstrap = -not (Get-Command -Name 'Initialize-CodexProfileFunctions' -CommandType Function -ErrorAction SilentlyContinue)
if (-not $__2scNeedBootstrap) {
    $__2scLoadedModule = Get-Module -Name 'CodexProfileFunctions' -ErrorAction SilentlyContinue | Select-Object -First 1
    if ($__2scLoadedModule) {
        $__2scLoadedFingerprint = $__2scLoadedModule.SessionState.PSVariable.GetValue('ProfileModuleFingerprint')
        $__2scModuleFile = Join-Path $__2scLoadedModule.ModuleBase 'CodexProfileFunctions.psm1'
        if ([System.IO.File]::Exists($__2scModuleFile)) {
            $__2scDiskInfo = Get-Item -LiteralPath $__2scModuleFile -ErrorAction SilentlyContinue
            if ($__2scDiskInfo) {
                $__2scDiskFingerprint = '{0}|{1}' -f $__2scDiskInfo.Length, $__2scDiskInfo.LastWriteTimeUtc.Ticks
                if ([string]$__2scLoadedFingerprint -and $__2scDiskFingerprint -ne [string]$__2scLoadedFingerprint) { $__2scNeedBootstrap = $true }
            }
        }
    }
}
if ($__2scNeedBootstrap) {
    if (-not (Test-Path -LiteralPath $__2scProfileModule -PathType Leaf)) {
        throw "2sc-generated script requires the Codex profile module: $__2scProfileModule"
    }
    Import-Module -Name $__2scProfileModule -Force -DisableNameChecking -ErrorAction Stop
    Initialize-CodexProfileFunctions
}
function claw {
        $clawCommand = Get-Command claw -CommandType Application -ErrorAction SilentlyContinue
        if (-not $clawCommand) { $clawCommand = Get-Command claw.cmd -CommandType Application -ErrorAction SilentlyContinue }
        if (-not $clawCommand) { throw 'claw executable was not found on PATH.' }
        $clawBin = if ($clawCommand.Source) { $clawCommand.Source } else { $clawCommand.Path }
        $env:HOME = $env:USERPROFILE
        # Enable VT processing for proper ANSI rendering in PS v5 conhost
        $null = Add-Type -MemberDefinition @'
[DllImport("kernel32.dll", SetLastError = true)]
public static extern IntPtr GetStdHandle(int nStdHandle);
[DllImport("kernel32.dll", SetLastError = true)]
public static extern bool GetConsoleMode(IntPtr hConsoleHandle, out uint lpMode);
[DllImport("kernel32.dll", SetLastError = true)]
public static extern bool SetConsoleMode(IntPtr hConsoleHandle, uint dwMode);
'@ -Name 'VT' -Namespace 'Win32' -PassThru -ErrorAction SilentlyContinue
        try {
            $h = [Win32.VT]::GetStdHandle(-11)
            $m = 0; $null = [Win32.VT]::GetConsoleMode($h, [ref]$m)
            $null = [Win32.VT]::SetConsoleMode($h, ($m -bor 4))
        } catch {}
        [Console]::OutputEncoding = [System.Text.Encoding]::UTF8
        $env:TERM = 'xterm-256color'
        & $clawBin @args
    }

if ($MyInvocation.InvocationName -ne '.') {
    & 'claw' @args
}
