# Generated by 2sc from function 'Convert-MmmenuDockerSizeToBytes' (2026-08-13 00:09:57).
# Self-bootstrap: load the profile environment when this script runs
# outside a profile session so it behaves exactly like the function it
# was copied from. The module is also force-re-imported when the copy
# loaded in this process is stale (psm1 changed on disk) so a long-
# running session never runs an outdated dispatcher.
$__2scProfileModule = 'C:\Users\micha\Documents\WindowsPowerShell\Modules\CodexProfileFunctions\CodexProfileFunctions.psd1'
$__2scNeedBootstrap = -not (Get-Command -Name 'Initialize-CodexProfileFunctions' -CommandType Function -ErrorAction SilentlyContinue)
if (-not $__2scNeedBootstrap) {
    $__2scLoadedModule = Get-Module -Name 'CodexProfileFunctions' -ErrorAction SilentlyContinue | Select-Object -First 1
    if ($__2scLoadedModule) {
        $__2scLoadedFingerprint = $__2scLoadedModule.SessionState.PSVariable.GetValue('ProfileModuleFingerprint')
        $__2scModuleFile = Join-Path $__2scLoadedModule.ModuleBase 'CodexProfileFunctions.psm1'
        if ([System.IO.File]::Exists($__2scModuleFile)) {
            $__2scDiskInfo = Get-Item -LiteralPath $__2scModuleFile -ErrorAction SilentlyContinue
            if ($__2scDiskInfo) {
                $__2scDiskFingerprint = '{0}|{1}' -f $__2scDiskInfo.Length, $__2scDiskInfo.LastWriteTimeUtc.Ticks
                if ([string]$__2scLoadedFingerprint -and $__2scDiskFingerprint -ne [string]$__2scLoadedFingerprint) { $__2scNeedBootstrap = $true }
            }
        }
    }
}
if ($__2scNeedBootstrap) {
    if (-not (Test-Path -LiteralPath $__2scProfileModule -PathType Leaf)) {
        throw "2sc-generated script requires the Codex profile module: $__2scProfileModule"
    }
    Import-Module -Name $__2scProfileModule -Force -DisableNameChecking -ErrorAction Stop
    Initialize-CodexProfileFunctions
}
function Convert-MmmenuDockerSizeToBytes {
        param([string]$Text)
        if ([string]::IsNullOrWhiteSpace($Text)) { return $null }
        if ($Text -match '^\s*([0-9]+(?:\.[0-9]+)?)\s*([KMGT]?i?B|B)\s*$') {
            $n=[double]$matches[1]; $u=$matches[2].ToUpperInvariant()
            switch -Regex ($u) {
                '^B$' { return [int64]$n }
                '^KB$' { return [int64]($n*1000) }
                '^KIB$' { return [int64]($n*1KB) }
                '^MB$' { return [int64]($n*1000*1000) }
                '^MIB$' { return [int64]($n*1MB) }
                '^GB$' { return [int64]($n*1000*1000*1000) }
                '^GIB$' { return [int64]($n*1GB) }
                '^TB$' { return [int64]($n*1000*1000*1000*1000) }
                '^TIB$' { return [int64]($n*1TB) }
            }
        }
        return $null
    }

if ($MyInvocation.InvocationName -ne '.') {
    & 'Convert-MmmenuDockerSizeToBytes' @args
}
