# Generated by 2sc from function 'Copy-DKillFastSettingsFile' (2026-08-13 00:03:11).
# Self-bootstrap: load the profile environment when this script runs
# outside a profile session so it behaves exactly like the function it
# was copied from. The module is also force-re-imported when the copy
# loaded in this process is stale (psm1 changed on disk) so a long-
# running session never runs an outdated dispatcher.
$__2scProfileModule = 'C:\Users\micha\Documents\WindowsPowerShell\Modules\CodexProfileFunctions\CodexProfileFunctions.psd1'
$__2scNeedBootstrap = -not (Get-Command -Name 'Initialize-CodexProfileFunctions' -CommandType Function -ErrorAction SilentlyContinue)
if (-not $__2scNeedBootstrap) {
    $__2scLoadedModule = Get-Module -Name 'CodexProfileFunctions' -ErrorAction SilentlyContinue | Select-Object -First 1
    if ($__2scLoadedModule) {
        $__2scLoadedFingerprint = $__2scLoadedModule.SessionState.PSVariable.GetValue('ProfileModuleFingerprint')
        $__2scModuleFile = Join-Path $__2scLoadedModule.ModuleBase 'CodexProfileFunctions.psm1'
        if ([System.IO.File]::Exists($__2scModuleFile)) {
            $__2scDiskInfo = Get-Item -LiteralPath $__2scModuleFile -ErrorAction SilentlyContinue
            if ($__2scDiskInfo) {
                $__2scDiskFingerprint = '{0}|{1}' -f $__2scDiskInfo.Length, $__2scDiskInfo.LastWriteTimeUtc.Ticks
                if ([string]$__2scLoadedFingerprint -and $__2scDiskFingerprint -ne [string]$__2scLoadedFingerprint) { $__2scNeedBootstrap = $true }
            }
        }
    }
}
if ($__2scNeedBootstrap) {
    if (-not (Test-Path -LiteralPath $__2scProfileModule -PathType Leaf)) {
        throw "2sc-generated script requires the Codex profile module: $__2scProfileModule"
    }
    Import-Module -Name $__2scProfileModule -Force -DisableNameChecking -ErrorAction Stop
    Initialize-CodexProfileFunctions
}
function Copy-DKillFastSettingsFile {
    [CmdletBinding()]
    param([Parameter(Mandatory)][string]$Source,[Parameter(Mandatory)][string]$SnapshotRoot)

    if([string]::IsNullOrWhiteSpace($Source) -or -not (Test-Path -LiteralPath $Source -PathType Leaf)) {
        return $false
    }
    try {
        $resolved = (Resolve-Path -LiteralPath $Source -ErrorAction Stop).ProviderPath
        if($resolved -notmatch '^(?i)C:\\') {
            Write-DKillFastLine ("DKILL_SETTINGS_SNAPSHOT_REJECT outside C drive: {0}" -f $resolved) Yellow
            return $false
        }
        $relative = $resolved.Substring(3)
        $destination = Join-Path $SnapshotRoot $relative
        New-Item -ItemType Directory -Force -Path (Split-Path -Parent $destination) -ErrorAction Stop | Out-Null
        Copy-Item -LiteralPath $resolved -Destination $destination -Force -ErrorAction Stop
        $sourceHash = (Get-FileHash -LiteralPath $resolved -Algorithm SHA256 -ErrorAction Stop).Hash
        $destinationHash = (Get-FileHash -LiteralPath $destination -Algorithm SHA256 -ErrorAction Stop).Hash
        if($sourceHash -ne $destinationHash) { throw 'SHA256 mismatch after snapshot copy' }
        Write-DKillFastLine ("DKILL_SETTINGS_SNAPSHOT_OK {0}" -f $relative) DarkGray
        return $true
    } catch {
        Write-DKillFastLine ("DKILL_SETTINGS_SNAPSHOT_FAIL source={0}: {1}" -f $Source,$_.Exception.Message) Red
        return $false
    }
}

if ($MyInvocation.InvocationName -ne '.') {
    & 'Copy-DKillFastSettingsFile' @args
}
