# Generated by 2sc from function 'Copy-RedockerSafeDir' (2026-08-13 00:00:38).
# Self-bootstrap: load the profile environment when this script runs
# outside a profile session so it behaves exactly like the function it
# was copied from. The module is also force-re-imported when the copy
# loaded in this process is stale (psm1 changed on disk) so a long-
# running session never runs an outdated dispatcher.
$__2scProfileModule = 'C:\Users\micha\Documents\WindowsPowerShell\Modules\CodexProfileFunctions\CodexProfileFunctions.psd1'
$__2scNeedBootstrap = -not (Get-Command -Name 'Initialize-CodexProfileFunctions' -CommandType Function -ErrorAction SilentlyContinue)
if (-not $__2scNeedBootstrap) {
    $__2scLoadedModule = Get-Module -Name 'CodexProfileFunctions' -ErrorAction SilentlyContinue | Select-Object -First 1
    if ($__2scLoadedModule) {
        $__2scLoadedFingerprint = $__2scLoadedModule.SessionState.PSVariable.GetValue('ProfileModuleFingerprint')
        $__2scModuleFile = Join-Path $__2scLoadedModule.ModuleBase 'CodexProfileFunctions.psm1'
        if ([System.IO.File]::Exists($__2scModuleFile)) {
            $__2scDiskInfo = Get-Item -LiteralPath $__2scModuleFile -ErrorAction SilentlyContinue
            if ($__2scDiskInfo) {
                $__2scDiskFingerprint = '{0}|{1}' -f $__2scDiskInfo.Length, $__2scDiskInfo.LastWriteTimeUtc.Ticks
                if ([string]$__2scLoadedFingerprint -and $__2scDiskFingerprint -ne [string]$__2scLoadedFingerprint) { $__2scNeedBootstrap = $true }
            }
        }
    }
}
if ($__2scNeedBootstrap) {
    if (-not (Test-Path -LiteralPath $__2scProfileModule -PathType Leaf)) {
        throw "2sc-generated script requires the Codex profile module: $__2scProfileModule"
    }
    Import-Module -Name $__2scProfileModule -Force -DisableNameChecking -ErrorAction Stop
    Initialize-CodexProfileFunctions
}
function Copy-RedockerSafeDir {
        param([string]$Source,[string]$Dest)
        if([string]::IsNullOrWhiteSpace($Source) -or -not (Test-Path -LiteralPath $Source)){ return $false }
        try {
            New-Item -ItemType Directory -Force -Path $Dest | Out-Null
            $sourceItem = Get-Item -LiteralPath $Source -Force -ErrorAction Stop
            if(-not $sourceItem.PSIsContainer){
                Copy-Item -LiteralPath $Source -Destination $Dest -Force -ErrorAction Stop
                return $true
            }
            $copied = 0
            Get-ChildItem -LiteralPath $Source -Force -Recurse -ErrorAction SilentlyContinue | ForEach-Object {
                $rel = $_.FullName.Substring($Source.Length).TrimStart('\')
                if([string]::IsNullOrWhiteSpace($rel)){ return }
                $target = Join-Path $Dest $rel
                try {
                    if($_.PSIsContainer){
                        New-Item -ItemType Directory -Force -Path $target | Out-Null
                    } else {
                        $sourceFile = $_.FullName
                        New-Item -ItemType Directory -Force -Path (Split-Path -Parent $target) | Out-Null
                        Copy-Item -LiteralPath $sourceFile -Destination $target -Force -ErrorAction Stop
                        $script:RedockerSafeCopiedFiles++
                        $copied++
                    }
                } catch {
                    Write-RedockerSafeLine ("snapshot skipped locked file {0}" -f $sourceFile) DarkYellow
                }
            }
            return ($copied -gt 0 -or (Test-Path -LiteralPath $Dest))
        } catch { Write-RedockerSafeLine ("snapshot copy failed {0}: {1}" -f $Source,$_.Exception.Message) Yellow; return $false }
    }

if ($MyInvocation.InvocationName -ne '.') {
    & 'Copy-RedockerSafeDir' @args
}
