# Generated by 2sc from function 'Copy-ReassTree' (2026-08-13 00:39:07).
# Self-bootstrap: load the profile environment when this script runs
# outside a profile session so it behaves exactly like the function it
# was copied from. The module is also force-re-imported when the copy
# loaded in this process is stale (psm1 changed on disk) so a long-
# running session never runs an outdated dispatcher.
$__2scProfileModule = 'C:\Users\micha\Documents\WindowsPowerShell\Modules\CodexProfileFunctions\CodexProfileFunctions.psd1'
$__2scNeedBootstrap = -not (Get-Command -Name 'Initialize-CodexProfileFunctions' -CommandType Function -ErrorAction SilentlyContinue)
if (-not $__2scNeedBootstrap) {
    $__2scLoadedModule = Get-Module -Name 'CodexProfileFunctions' -ErrorAction SilentlyContinue | Select-Object -First 1
    if ($__2scLoadedModule) {
        $__2scLoadedFingerprint = $__2scLoadedModule.SessionState.PSVariable.GetValue('ProfileModuleFingerprint')
        $__2scModuleFile = Join-Path $__2scLoadedModule.ModuleBase 'CodexProfileFunctions.psm1'
        if ([System.IO.File]::Exists($__2scModuleFile)) {
            $__2scDiskInfo = Get-Item -LiteralPath $__2scModuleFile -ErrorAction SilentlyContinue
            if ($__2scDiskInfo) {
                $__2scDiskFingerprint = '{0}|{1}' -f $__2scDiskInfo.Length, $__2scDiskInfo.LastWriteTimeUtc.Ticks
                if ([string]$__2scLoadedFingerprint -and $__2scDiskFingerprint -ne [string]$__2scLoadedFingerprint) { $__2scNeedBootstrap = $true }
            }
        }
    }
}
if ($__2scNeedBootstrap) {
    if (-not (Test-Path -LiteralPath $__2scProfileModule -PathType Leaf)) {
        throw "2sc-generated script requires the Codex profile module: $__2scProfileModule"
    }
    Import-Module -Name $__2scProfileModule -Force -DisableNameChecking -ErrorAction Stop
    Initialize-CodexProfileFunctions
}
function Copy-ReassTree {
    param(
        [Parameter(Mandatory)]
        [string]$Source,

        [Parameter(Mandatory)]
        [string]$Destination,

        [Parameter(Mandatory)]
        [string]$Stage,

        [Parameter(Mandatory)]
        [int]$ProgressStart,

        [Parameter(Mandatory)]
        [int]$ProgressEnd
    )

    $sourceRoot = [IO.Path]::GetFullPath($Source).TrimEnd('\')
    $files = Get-ReassFiles -Path $sourceRoot
    $totalBytes = [int64]0
    foreach ($file in $files) {
        $totalBytes += $file.Length
    }

    New-Item -ItemType Directory -Path $Destination -Force -ErrorAction Stop | Out-Null
    $copiedBytes = [int64]0
    $buffer = New-Object byte[] (4MB)

    foreach ($file in $files) {
        $relative = $file.FullName.Substring($sourceRoot.Length).TrimStart('\')
        $target = Join-Path $Destination $relative
        $targetParent = Split-Path -Parent $target
        New-Item -ItemType Directory -Path $targetParent -Force -ErrorAction Stop | Out-Null

        $sourceStream = $null
        $targetStream = $null
        try {
            $sourceStream = [IO.File]::Open($file.FullName, [IO.FileMode]::Open, [IO.FileAccess]::Read, [IO.FileShare]::Read)
            $targetStream = [IO.File]::Open($target, [IO.FileMode]::Create, [IO.FileAccess]::Write, [IO.FileShare]::None)

            while (($read = $sourceStream.Read($buffer, 0, $buffer.Length)) -gt 0) {
                $targetStream.Write($buffer, 0, $read)
                $copiedBytes += $read
                $ratio = if ($totalBytes -gt 0) { $copiedBytes / [double]$totalBytes } else { 1 }
                $percent = $ProgressStart + [Math]::Floor(($ProgressEnd - $ProgressStart) * $ratio)
                Write-Progress -Id 776 -Activity 'Restoring High On Life 2 save data' -Status ("{0}: {1}" -f $Stage, $relative) -PercentComplete $percent
            }
        }
        finally {
            if ($targetStream) { $targetStream.Dispose() }
            if ($sourceStream) { $sourceStream.Dispose() }
        }

        [IO.File]::SetLastWriteTimeUtc($target, $file.LastWriteTimeUtc)
    }

    return [pscustomobject]@{
        FileCount = $files.Count
        Bytes     = $totalBytes
    }
}

if ($MyInvocation.InvocationName -ne '.') {
    & 'Copy-ReassTree' @args
}
