# Generated by 2sc from function 'Copy-DKillFastSettingsSnapshot' (2026-08-13 00:01:12).
# Self-bootstrap: load the profile environment when this script runs
# outside a profile session so it behaves exactly like the function it
# was copied from. The module is also force-re-imported when the copy
# loaded in this process is stale (psm1 changed on disk) so a long-
# running session never runs an outdated dispatcher.
$__2scProfileModule = 'C:\Users\micha\Documents\WindowsPowerShell\Modules\CodexProfileFunctions\CodexProfileFunctions.psd1'
$__2scNeedBootstrap = -not (Get-Command -Name 'Initialize-CodexProfileFunctions' -CommandType Function -ErrorAction SilentlyContinue)
if (-not $__2scNeedBootstrap) {
    $__2scLoadedModule = Get-Module -Name 'CodexProfileFunctions' -ErrorAction SilentlyContinue | Select-Object -First 1
    if ($__2scLoadedModule) {
        $__2scLoadedFingerprint = $__2scLoadedModule.SessionState.PSVariable.GetValue('ProfileModuleFingerprint')
        $__2scModuleFile = Join-Path $__2scLoadedModule.ModuleBase 'CodexProfileFunctions.psm1'
        if ([System.IO.File]::Exists($__2scModuleFile)) {
            $__2scDiskInfo = Get-Item -LiteralPath $__2scModuleFile -ErrorAction SilentlyContinue
            if ($__2scDiskInfo) {
                $__2scDiskFingerprint = '{0}|{1}' -f $__2scDiskInfo.Length, $__2scDiskInfo.LastWriteTimeUtc.Ticks
                if ([string]$__2scLoadedFingerprint -and $__2scDiskFingerprint -ne [string]$__2scLoadedFingerprint) { $__2scNeedBootstrap = $true }
            }
        }
    }
}
if ($__2scNeedBootstrap) {
    if (-not (Test-Path -LiteralPath $__2scProfileModule -PathType Leaf)) {
        throw "2sc-generated script requires the Codex profile module: $__2scProfileModule"
    }
    Import-Module -Name $__2scProfileModule -Force -DisableNameChecking -ErrorAction Stop
    Initialize-CodexProfileFunctions
}
function Copy-DKillFastSettingsSnapshot {
    [CmdletBinding()]
    param([Parameter(Mandatory)][string]$SnapshotRoot)

    $copied = 0
    $failures = 0
    try {
        New-Item -ItemType Directory -Force -Path $SnapshotRoot -ErrorAction Stop | Out-Null
    } catch {
        Write-DKillFastLine ("DKILL_SETTINGS_SNAPSHOT_FAIL root={0}: {1}" -f $SnapshotRoot,$_.Exception.Message) Red
        return $false
    }
    foreach($directory in @((Join-Path $env:USERPROFILE '.docker'),(Join-Path $env:APPDATA 'Docker'),(Join-Path $env:APPDATA 'Docker Desktop'))) {
        if([string]::IsNullOrWhiteSpace($directory) -or -not (Test-Path -LiteralPath $directory)) { continue }
        try {
            $files = @(Get-ChildItem -LiteralPath $directory -File -Force -ErrorAction Stop | Where-Object {
                $_.Extension -ieq '.json' -or $_.Name -match '^(config|daemon|windows-daemon|settings-store|settings|features|login-info)(\..*)?$'
            })
            foreach($file in $files) {
                if(Copy-DKillFastSettingsFile -Source $file.FullName -SnapshotRoot $SnapshotRoot) { $copied++ } else { $failures++ }
            }
        } catch {
            $failures++
            Write-DKillFastLine ("DKILL_SETTINGS_SNAPSHOT_WARN enumerate path={0}: {1}" -f $directory,$_.Exception.Message) Yellow
        }
    }
    $succeeded = $failures -eq 0
    Write-DKillFastLine ("DKILL_SETTINGS_SNAPSHOT_{0} files={1} failures={2} root={3}" -f $(if($succeeded){'OK'}else{'INCOMPLETE'}),$copied,$failures,$SnapshotRoot) $(if($succeeded){'Green'}else{'Yellow'})
    return $succeeded
}

if ($MyInvocation.InvocationName -ne '.') {
    & 'Copy-DKillFastSettingsSnapshot' @args
}
