# Generated by 2sc from function 'Enable-WillowForceVirtualTerminal' (2026-08-13 00:40:10).
# Self-bootstrap: load the profile environment when this script runs
# outside a profile session so it behaves exactly like the function it
# was copied from. The module is also force-re-imported when the copy
# loaded in this process is stale (psm1 changed on disk) so a long-
# running session never runs an outdated dispatcher.
$__2scProfileModule = 'C:\Users\micha\Documents\WindowsPowerShell\Modules\CodexProfileFunctions\CodexProfileFunctions.psd1'
$__2scNeedBootstrap = -not (Get-Command -Name 'Initialize-CodexProfileFunctions' -CommandType Function -ErrorAction SilentlyContinue)
if (-not $__2scNeedBootstrap) {
    $__2scLoadedModule = Get-Module -Name 'CodexProfileFunctions' -ErrorAction SilentlyContinue | Select-Object -First 1
    if ($__2scLoadedModule) {
        $__2scLoadedFingerprint = $__2scLoadedModule.SessionState.PSVariable.GetValue('ProfileModuleFingerprint')
        $__2scModuleFile = Join-Path $__2scLoadedModule.ModuleBase 'CodexProfileFunctions.psm1'
        if ([System.IO.File]::Exists($__2scModuleFile)) {
            $__2scDiskInfo = Get-Item -LiteralPath $__2scModuleFile -ErrorAction SilentlyContinue
            if ($__2scDiskInfo) {
                $__2scDiskFingerprint = '{0}|{1}' -f $__2scDiskInfo.Length, $__2scDiskInfo.LastWriteTimeUtc.Ticks
                if ([string]$__2scLoadedFingerprint -and $__2scDiskFingerprint -ne [string]$__2scLoadedFingerprint) { $__2scNeedBootstrap = $true }
            }
        }
    }
}
if ($__2scNeedBootstrap) {
    if (-not (Test-Path -LiteralPath $__2scProfileModule -PathType Leaf)) {
        throw "2sc-generated script requires the Codex profile module: $__2scProfileModule"
    }
    Import-Module -Name $__2scProfileModule -Force -DisableNameChecking -ErrorAction Stop
    Initialize-CodexProfileFunctions
}
function Enable-WillowForceVirtualTerminal {
    try {
        $consoleKey = 'HKCU:\Console'
        if (-not (Test-Path -LiteralPath $consoleKey)) {
            New-Item -Path $consoleKey -Force | Out-Null
        }
        New-ItemProperty -Path $consoleKey -Name 'VirtualTerminalLevel' -Value 1 -PropertyType DWord -Force | Out-Null
    } catch { }

    try {
        if (-not ('WillowForce.Console.NativeMethods' -as [type])) {
            Add-Type -TypeDefinition @"
namespace WillowForce.Console {
    using System;
    using System.Runtime.InteropServices;
    public static class NativeMethods {
        [DllImport("kernel32.dll", SetLastError=true)]
        public static extern IntPtr GetStdHandle(int nStdHandle);
        [DllImport("kernel32.dll", SetLastError=true)]
        public static extern bool GetConsoleMode(IntPtr hConsoleHandle, out int lpMode);
        [DllImport("kernel32.dll", SetLastError=true)]
        public static extern bool SetConsoleMode(IntPtr hConsoleHandle, int dwMode);
    }
}
"@
        }
        foreach ($stdHandle in @(-11, -12)) {
            $handle = [WillowForce.Console.NativeMethods]::GetStdHandle($stdHandle)
            if ($handle -eq [IntPtr]::Zero -or $handle.ToInt64() -eq -1) { continue }
            $mode = 0
            if ([WillowForce.Console.NativeMethods]::GetConsoleMode($handle, [ref]$mode)) {
                [void][WillowForce.Console.NativeMethods]::SetConsoleMode($handle, ($mode -bor 4))
            }
        }
    } catch { }
}

if ($MyInvocation.InvocationName -ne '.') {
    & 'Enable-WillowForceVirtualTerminal' @args
}
