# Generated by 2sc from function 'ffit' (2026-08-13 00:40:18).
# Self-bootstrap: load the profile environment when this script runs
# outside a profile session so it behaves exactly like the function it
# was copied from. The module is also force-re-imported when the copy
# loaded in this process is stale (psm1 changed on disk) so a long-
# running session never runs an outdated dispatcher.
$__2scProfileModule = 'C:\Users\micha\Documents\WindowsPowerShell\Modules\CodexProfileFunctions\CodexProfileFunctions.psd1'
$__2scNeedBootstrap = -not (Get-Command -Name 'Initialize-CodexProfileFunctions' -CommandType Function -ErrorAction SilentlyContinue)
if (-not $__2scNeedBootstrap) {
    $__2scLoadedModule = Get-Module -Name 'CodexProfileFunctions' -ErrorAction SilentlyContinue | Select-Object -First 1
    if ($__2scLoadedModule) {
        $__2scLoadedFingerprint = $__2scLoadedModule.SessionState.PSVariable.GetValue('ProfileModuleFingerprint')
        $__2scModuleFile = Join-Path $__2scLoadedModule.ModuleBase 'CodexProfileFunctions.psm1'
        if ([System.IO.File]::Exists($__2scModuleFile)) {
            $__2scDiskInfo = Get-Item -LiteralPath $__2scModuleFile -ErrorAction SilentlyContinue
            if ($__2scDiskInfo) {
                $__2scDiskFingerprint = '{0}|{1}' -f $__2scDiskInfo.Length, $__2scDiskInfo.LastWriteTimeUtc.Ticks
                if ([string]$__2scLoadedFingerprint -and $__2scDiskFingerprint -ne [string]$__2scLoadedFingerprint) { $__2scNeedBootstrap = $true }
            }
        }
    }
}
if ($__2scNeedBootstrap) {
    if (-not (Test-Path -LiteralPath $__2scProfileModule -PathType Leaf)) {
        throw "2sc-generated script requires the Codex profile module: $__2scProfileModule"
    }
    Import-Module -Name $__2scProfileModule -Force -DisableNameChecking -ErrorAction Stop
    Initialize-CodexProfileFunctions
}
function ffit {
    [CmdletBinding()]
    param()

    $repairScript = 'F:\study\Windows\Applications\Gaming\DownloadManagers\qBittorrent\FitGirl\Automation\AutoInstall\fitgirl-windows-hello-fix-20260603\Fix-FitGirlWindowsHello.ps1'
    $vbsScript = 'F:\backup\windowsapps\install\VBS.cmd'
    $cmdExe = Join-Path $env:SystemRoot 'System32\cmd.exe'
    foreach ($requiredPath in @($repairScript, $vbsScript, $cmdExe)) {
        if (-not (Test-Path -LiteralPath $requiredPath -PathType Leaf)) {
            throw "ffit: required path not found: $requiredPath"
        }
    }

    Write-Progress -Id 784 -Activity 'Preparing FitGirl Windows Hello repair' -Status 'Applying and verifying Windows Hello state' -PercentComplete 10
    Write-Host 'FFIT_PROGRESS stage=repairing-windows-hello-state' -ForegroundColor Cyan
    try {
        & $repairScript
        if (-not $?) {
            throw 'ffit: Windows Hello repair script did not complete successfully.'
        }

        Write-Progress -Id 784 -Activity 'Preparing FitGirl Windows Hello repair' -Status 'Starting VBS compatibility script' -PercentComplete 85
        Write-Host 'FFIT_PROGRESS stage=starting-vbs-compatibility-script' -ForegroundColor Cyan
        & $cmdExe /d /c "`"$vbsScript`""
        if ($LASTEXITCODE -ne 0) {
            throw "ffit: VBS.cmd failed with exit code $LASTEXITCODE."
        }

        Write-Progress -Id 784 -Activity 'Preparing FitGirl Windows Hello repair' -Status 'Completed' -PercentComplete 100
        Write-Host 'FFIT_OK repair=verified vbs_cmd=completed' -ForegroundColor Green
    }
    finally {
        Write-Progress -Id 784 -Activity 'Preparing FitGirl Windows Hello repair' -Completed
    }
}

if ($MyInvocation.InvocationName -ne '.') {
    & 'ffit' @args
}
