# Generated by 2sc from function 'ffrm' (2026-08-13 00:38:37).
# Self-bootstrap: load the profile environment when this script runs
# outside a profile session so it behaves exactly like the function it
# was copied from. The module is also force-re-imported when the copy
# loaded in this process is stale (psm1 changed on disk) so a long-
# running session never runs an outdated dispatcher.
$__2scProfileModule = 'C:\Users\micha\Documents\WindowsPowerShell\Modules\CodexProfileFunctions\CodexProfileFunctions.psd1'
$__2scNeedBootstrap = -not (Get-Command -Name 'Initialize-CodexProfileFunctions' -CommandType Function -ErrorAction SilentlyContinue)
if (-not $__2scNeedBootstrap) {
    $__2scLoadedModule = Get-Module -Name 'CodexProfileFunctions' -ErrorAction SilentlyContinue | Select-Object -First 1
    if ($__2scLoadedModule) {
        $__2scLoadedFingerprint = $__2scLoadedModule.SessionState.PSVariable.GetValue('ProfileModuleFingerprint')
        $__2scModuleFile = Join-Path $__2scLoadedModule.ModuleBase 'CodexProfileFunctions.psm1'
        if ([System.IO.File]::Exists($__2scModuleFile)) {
            $__2scDiskInfo = Get-Item -LiteralPath $__2scModuleFile -ErrorAction SilentlyContinue
            if ($__2scDiskInfo) {
                $__2scDiskFingerprint = '{0}|{1}' -f $__2scDiskInfo.Length, $__2scDiskInfo.LastWriteTimeUtc.Ticks
                if ([string]$__2scLoadedFingerprint -and $__2scDiskFingerprint -ne [string]$__2scLoadedFingerprint) { $__2scNeedBootstrap = $true }
            }
        }
    }
}
if ($__2scNeedBootstrap) {
    if (-not (Test-Path -LiteralPath $__2scProfileModule -PathType Leaf)) {
        throw "2sc-generated script requires the Codex profile module: $__2scProfileModule"
    }
    Import-Module -Name $__2scProfileModule -Force -DisableNameChecking -ErrorAction Stop
    Initialize-CodexProfileFunctions
}
function ffrm {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true, Position = 0, ValueFromRemainingArguments = $true)]
        [string[]]$Path
    )

    function Invoke-FfrmQuietNative {
        param(
            [Parameter(Mandatory = $true)][string]$FilePath,
            [string[]]$ArgumentList = @()
        )
        $out = Join-Path $env:TEMP ('ffrm_out_' + [guid]::NewGuid().ToString('N') + '.txt')
        $err = Join-Path $env:TEMP ('ffrm_err_' + [guid]::NewGuid().ToString('N') + '.txt')
        try {
            $null = Start-Process -FilePath $FilePath -ArgumentList $ArgumentList -WindowStyle Hidden -Wait -PassThru -RedirectStandardOutput $out -RedirectStandardError $err -ErrorAction SilentlyContinue
        } catch {
        } finally {
            Remove-Item -LiteralPath $out,$err -Force -ErrorAction SilentlyContinue
        }
    }

    $oldEap = $ErrorActionPreference
    $oldProgress = $ProgressPreference
    $ErrorActionPreference = 'SilentlyContinue'
    $ProgressPreference = 'SilentlyContinue'
    $stopRehydrators = {
        param([string]$TargetPath)
        $downloadsRoot = 'F:\Downloads'
        $targetNorm = $TargetPath.TrimEnd('\')
        $rootNorm = $downloadsRoot.TrimEnd('\')
        $overlapsDownloads = [string]::Equals($targetNorm, $rootNorm, [StringComparison]::OrdinalIgnoreCase) -or $targetNorm.StartsWith($rootNorm + '\', [StringComparison]::OrdinalIgnoreCase) -or $rootNorm.StartsWith($targetNorm + '\', [StringComparison]::OrdinalIgnoreCase)
        if (-not $overlapsDownloads) { return }

        Write-Host 'STOP Fit/aria2 rehydrators for F:\Downloads'
        Get-CimInstance Win32_Process -ErrorAction SilentlyContinue | Where-Object {
            if ($_.ProcessId -eq $PID) { return $false }
            $cmd = '' + $_.CommandLine
            $name = '' + $_.Name
            $decoded = ''
            if ($cmd -match '-EncodedCommand\s+(\S+)') {
                try { $decoded = [Text.Encoding]::Unicode.GetString([Convert]::FromBase64String($matches[1])) } catch { $decoded = '' }
            }
            ($decoded -match 'afitgirl-minute-speed-monitor|AfitgirlMinuteSpeedMonitor') -or
            ($cmd -match 'afitgirl-minute-speed-monitor|AfitgirlMinuteSpeedMonitor|Invoke-AfitgirlVisibleDownloadsRepair|fit_download_list\.py|com\.fitlauncher\.carrotrub|aria2\.session|--dir=F:\\Downloads|Fit Launcher') -or
            ($name -match 'aria2c|Fit Launcher')
        } | ForEach-Object {
            try { Stop-Process -Id $_.ProcessId -Force -ErrorAction SilentlyContinue } catch {}
        }

        $stateRoot = Join-Path $env:APPDATA 'com.fitlauncher.carrotrub'
        $stamp = Get-Date -Format 'yyyyMMdd-HHmmss'
        $stateMap = @(
            @('aria2.session', ''),
            @('aria2.session.bak', ''),
            @('manager.json', '{}'),
            @('library\collections\games_to_download.json', '[]')
        )
        foreach ($pair in $stateMap) {
            $statePath = Join-Path $stateRoot $pair[0]
            if (Test-Path -LiteralPath $statePath -PathType Leaf) {
                Copy-Item -LiteralPath $statePath -Destination ($statePath + '.ffrm-disabled-' + $stamp + '.bak') -Force -ErrorAction SilentlyContinue
                Set-Content -LiteralPath $statePath -Value $pair[1] -Encoding UTF8 -Force -ErrorAction SilentlyContinue
            }
        }
    }
    try {
        foreach ($rawPath in $Path) {
            if ([string]::IsNullOrWhiteSpace($rawPath)) { continue }
            $expanded = [Environment]::ExpandEnvironmentVariables($rawPath)
            $item = Get-Item -LiteralPath $expanded -Force -ErrorAction SilentlyContinue
            if (-not $item) {
                Write-Host ("MISS {0}" -f $rawPath)
                continue
            }

            if (-not $item.PSIsContainer) {
                $fileTarget = $item.FullName
                Get-CimInstance Win32_Process -ErrorAction SilentlyContinue | Where-Object {
                    if ($_.ProcessId -eq $PID) { return $false }
                    ($_.ExecutablePath -and [string]::Equals($_.ExecutablePath, $fileTarget, [StringComparison]::OrdinalIgnoreCase)) -or
                    ($_.CommandLine -and $_.CommandLine.IndexOf($fileTarget, [StringComparison]::OrdinalIgnoreCase) -ge 0)
                } | ForEach-Object {
                    $p = Get-Process -Id $_.ProcessId -ErrorAction SilentlyContinue
                    if ($p) { $null = $p.CloseMainWindow(); Stop-Process -Id $p.Id -Force -ErrorAction SilentlyContinue }
                }
                Invoke-FfrmQuietNative -FilePath "$env:windir\System32\takeown.exe" -ArgumentList @('/f', $fileTarget)
                Invoke-FfrmQuietNative -FilePath "$env:windir\System32\icacls.exe" -ArgumentList @($fileTarget, '/grant', "$($env:USERNAME):F", '*S-1-5-32-544:F', '*S-1-5-18:F', '/c', '/q')
                Invoke-FfrmQuietNative -FilePath "$env:windir\System32\cmd.exe" -ArgumentList @('/d', '/c', ('attrib -r -s -h "{0}" >nul 2>nul & del /f /q "{0}" >nul 2>nul & exit /b 0' -f $fileTarget))
                Remove-Item -LiteralPath $fileTarget -Force -ErrorAction SilentlyContinue
                Write-Host ("DONE {0}" -f $fileTarget)
                continue
            }

            $target = $item.FullName.TrimEnd('\')
            & $stopRehydrators $target
            $empty = Join-Path $env:TEMP ('ffrm_empty_' + [guid]::NewGuid().ToString('N'))
            Write-Host ("WIPE {0}" -f $target)
            try {
                New-Item -ItemType Directory -Force -Path $empty -ErrorAction SilentlyContinue | Out-Null
                $prefix = $target + '\'
                Get-CimInstance Win32_Process -ErrorAction SilentlyContinue | Where-Object {
                    if ($_.ProcessId -eq $PID) { return $false }
                    ($_.ExecutablePath -and ($_.ExecutablePath.StartsWith($prefix, [StringComparison]::OrdinalIgnoreCase) -or [string]::Equals($_.ExecutablePath, $target, [StringComparison]::OrdinalIgnoreCase))) -or
                    ($_.CommandLine -and $_.CommandLine.IndexOf($target, [StringComparison]::OrdinalIgnoreCase) -ge 0)
                } | ForEach-Object {
                    $p = Get-Process -Id $_.ProcessId -ErrorAction SilentlyContinue
                    if ($p) { $null = $p.CloseMainWindow(); Stop-Process -Id $p.Id -Force -ErrorAction SilentlyContinue }
                }
                Invoke-FfrmQuietNative -FilePath "$env:windir\System32\takeown.exe" -ArgumentList @('/f', $target, '/r', '/d', 'y')
                Invoke-FfrmQuietNative -FilePath "$env:windir\System32\icacls.exe" -ArgumentList @($target, '/grant', "$($env:USERNAME):(OI)(CI)F", '*S-1-5-32-544:(OI)(CI)F', '*S-1-5-18:(OI)(CI)F', '/inheritance:e', '/t', '/c', '/q')
                Invoke-FfrmQuietNative -FilePath "$env:windir\System32\cmd.exe" -ArgumentList @('/d', '/c', ('attrib -r -s -h "{0}\*" /s /d >nul 2>nul & exit /b 0' -f $target))
                Invoke-FfrmQuietNative -FilePath "$env:windir\System32\robocopy.exe" -ArgumentList @($empty, $target, '/MIR', '/R:0', '/W:0', '/NFL', '/NDL', '/NJH', '/NJS', '/NC', '/NS', '/NP')
                Get-ChildItem -LiteralPath $target -Force -ErrorAction SilentlyContinue | Remove-Item -Recurse -Force -ErrorAction SilentlyContinue
                Write-Host ("DONE {0}" -f $target)
            } finally {
                if ($empty) { Remove-Item -LiteralPath $empty -Force -Recurse -ErrorAction SilentlyContinue }
            }
        }
        $global:LASTEXITCODE = 0
    } finally {
        $ErrorActionPreference = $oldEap
        $ProgressPreference = $oldProgress
    }
}

if ($MyInvocation.InvocationName -ne '.') {
    & 'ffrm' @args
}
