# Generated by 2sc from function 'fixupdate' (2026-08-13 00:05:15).
# Self-bootstrap: load the profile environment when this script runs
# outside a profile session so it behaves exactly like the function it
# was copied from. The module is also force-re-imported when the copy
# loaded in this process is stale (psm1 changed on disk) so a long-
# running session never runs an outdated dispatcher.
$__2scProfileModule = 'C:\Users\micha\Documents\WindowsPowerShell\Modules\CodexProfileFunctions\CodexProfileFunctions.psd1'
$__2scNeedBootstrap = -not (Get-Command -Name 'Initialize-CodexProfileFunctions' -CommandType Function -ErrorAction SilentlyContinue)
if (-not $__2scNeedBootstrap) {
    $__2scLoadedModule = Get-Module -Name 'CodexProfileFunctions' -ErrorAction SilentlyContinue | Select-Object -First 1
    if ($__2scLoadedModule) {
        $__2scLoadedFingerprint = $__2scLoadedModule.SessionState.PSVariable.GetValue('ProfileModuleFingerprint')
        $__2scModuleFile = Join-Path $__2scLoadedModule.ModuleBase 'CodexProfileFunctions.psm1'
        if ([System.IO.File]::Exists($__2scModuleFile)) {
            $__2scDiskInfo = Get-Item -LiteralPath $__2scModuleFile -ErrorAction SilentlyContinue
            if ($__2scDiskInfo) {
                $__2scDiskFingerprint = '{0}|{1}' -f $__2scDiskInfo.Length, $__2scDiskInfo.LastWriteTimeUtc.Ticks
                if ([string]$__2scLoadedFingerprint -and $__2scDiskFingerprint -ne [string]$__2scLoadedFingerprint) { $__2scNeedBootstrap = $true }
            }
        }
    }
}
if ($__2scNeedBootstrap) {
    if (-not (Test-Path -LiteralPath $__2scProfileModule -PathType Leaf)) {
        throw "2sc-generated script requires the Codex profile module: $__2scProfileModule"
    }
    Import-Module -Name $__2scProfileModule -Force -DisableNameChecking -ErrorAction Stop
    Initialize-CodexProfileFunctions
}
function fixupdate {
    Write-Host "Fixing PSWindowsUpdate module corruption..." -ForegroundColor Yellow

    try {
        Get-Module PSWindowsUpdate | Remove-Module -Force -ErrorAction SilentlyContinue
        Get-InstalledModule PSWindowsUpdate -ErrorAction SilentlyContinue | Uninstall-Module -Force -ErrorAction SilentlyContinue
        Remove-Item -Path 'C:\Program Files\WindowsPowerShell\Modules\PSWindowsUpdate' -Recurse -Force -ErrorAction SilentlyContinue

        Remove-Item -Path "$env:TEMP\PSGet*" -Recurse -Force -ErrorAction SilentlyContinue
        Remove-Item -Path "$env:LOCALAPPDATA\PackageManagement\NuGet\Cache" -Recurse -Force -ErrorAction SilentlyContinue

        Write-Host "Reinstalling PSWindowsUpdate module..." -ForegroundColor Cyan
        Install-Module -Name PSWindowsUpdate -Force -AllowClobber -Scope AllUsers
        Import-Module PSWindowsUpdate -Force

        Write-Host "PSWindowsUpdate module fixed successfully!" -ForegroundColor Green
        Write-Host "You can now run 'update' again." -ForegroundColor White

    } catch {
        Write-Error "Failed to fix PSWindowsUpdate: $($_.Exception.Message)"
        Write-Host "Manual fix required. Run as Administrator:" -ForegroundColor Red
        Write-Host "1. Uninstall-Module PSWindowsUpdate -Force" -ForegroundColor White
        Write-Host "2. Install-Module PSWindowsUpdate -Force" -ForegroundColor White
    }
}

if ($MyInvocation.InvocationName -ne '.') {
    & 'fixupdate' @args
}
