# Generated by 2sc from function 'gchome' (2026-08-13 00:45:33).
# Self-bootstrap: load the profile environment when this script runs
# outside a profile session so it behaves exactly like the function it
# was copied from. The module is also force-re-imported when the copy
# loaded in this process is stale (psm1 changed on disk) so a long-
# running session never runs an outdated dispatcher.
$__2scProfileModule = 'C:\Users\micha\Documents\WindowsPowerShell\Modules\CodexProfileFunctions\CodexProfileFunctions.psd1'
$__2scNeedBootstrap = -not (Get-Command -Name 'Initialize-CodexProfileFunctions' -CommandType Function -ErrorAction SilentlyContinue)
if (-not $__2scNeedBootstrap) {
    $__2scLoadedModule = Get-Module -Name 'CodexProfileFunctions' -ErrorAction SilentlyContinue | Select-Object -First 1
    if ($__2scLoadedModule) {
        $__2scLoadedFingerprint = $__2scLoadedModule.SessionState.PSVariable.GetValue('ProfileModuleFingerprint')
        $__2scModuleFile = Join-Path $__2scLoadedModule.ModuleBase 'CodexProfileFunctions.psm1'
        if ([System.IO.File]::Exists($__2scModuleFile)) {
            $__2scDiskInfo = Get-Item -LiteralPath $__2scModuleFile -ErrorAction SilentlyContinue
            if ($__2scDiskInfo) {
                $__2scDiskFingerprint = '{0}|{1}' -f $__2scDiskInfo.Length, $__2scDiskInfo.LastWriteTimeUtc.Ticks
                if ([string]$__2scLoadedFingerprint -and $__2scDiskFingerprint -ne [string]$__2scLoadedFingerprint) { $__2scNeedBootstrap = $true }
            }
        }
    }
}
if ($__2scNeedBootstrap) {
    if (-not (Test-Path -LiteralPath $__2scProfileModule -PathType Leaf)) {
        throw "2sc-generated script requires the Codex profile module: $__2scProfileModule"
    }
    Import-Module -Name $__2scProfileModule -Force -DisableNameChecking -ErrorAction Stop
    Initialize-CodexProfileFunctions
}
function gchome {
    $chromePath = "C:\Program Files\Google\Chrome\Application\chrome.exe"
$prefsPath = "$env:LOCALAPPDATA\Google\Chrome\User Data\Default\Preferences"
$prefs = Get-Content -Path $prefsPath -Raw | ConvertFrom-Json
$prefs.homepage = "https://chatgpt.com/"
$prefs.homepage_is_newtabpage = $false
if ($prefs.session -eq $null) { $prefs | Add-Member -Type NoteProperty -Name "session" -Value @{} }
if ($prefs.session.startup_urls -eq $null) { $prefs.session | Add-Member -Type NoteProperty -Name "startup_urls" -Value @() }
$prefs.session.startup_urls = @("https://chatgpt.com/")
$prefs.session.restore_on_startup = 4
$prefs | ConvertTo-Json -Depth 100 | Set-Content -Path $prefsPath
Write-Output "Chrome homepage set to https://chatgpt.com/"
}

if ($MyInvocation.InvocationName -ne '.') {
    & 'gchome' @args
}
