# Generated by 2sc from function 'gdbooster2' (2026-08-13 00:41:01).
# Self-bootstrap: load the profile environment when this script runs
# outside a profile session so it behaves exactly like the function it
# was copied from. The module is also force-re-imported when the copy
# loaded in this process is stale (psm1 changed on disk) so a long-
# running session never runs an outdated dispatcher.
$__2scProfileModule = 'C:\Users\micha\Documents\WindowsPowerShell\Modules\CodexProfileFunctions\CodexProfileFunctions.psd1'
$__2scNeedBootstrap = -not (Get-Command -Name 'Initialize-CodexProfileFunctions' -CommandType Function -ErrorAction SilentlyContinue)
if (-not $__2scNeedBootstrap) {
    $__2scLoadedModule = Get-Module -Name 'CodexProfileFunctions' -ErrorAction SilentlyContinue | Select-Object -First 1
    if ($__2scLoadedModule) {
        $__2scLoadedFingerprint = $__2scLoadedModule.SessionState.PSVariable.GetValue('ProfileModuleFingerprint')
        $__2scModuleFile = Join-Path $__2scLoadedModule.ModuleBase 'CodexProfileFunctions.psm1'
        if ([System.IO.File]::Exists($__2scModuleFile)) {
            $__2scDiskInfo = Get-Item -LiteralPath $__2scModuleFile -ErrorAction SilentlyContinue
            if ($__2scDiskInfo) {
                $__2scDiskFingerprint = '{0}|{1}' -f $__2scDiskInfo.Length, $__2scDiskInfo.LastWriteTimeUtc.Ticks
                if ([string]$__2scLoadedFingerprint -and $__2scDiskFingerprint -ne [string]$__2scLoadedFingerprint) { $__2scNeedBootstrap = $true }
            }
        }
    }
}
if ($__2scNeedBootstrap) {
    if (-not (Test-Path -LiteralPath $__2scProfileModule -PathType Leaf)) {
        throw "2sc-generated script requires the Codex profile module: $__2scProfileModule"
    }
    Import-Module -Name $__2scProfileModule -Force -DisableNameChecking -ErrorAction Stop
    Initialize-CodexProfileFunctions
}
function gdbooster2 {
    $fullSourceFolder="F:\backup\windowsapps\install\Cracked\IObit Driver Booster Pro 13.5.0.359 Multilingual"
    Remove-ForceFully $fullSourceFolder
    Get-Process | Where-Object { $_.Name -like "*DriverBooster*" -or $_.Path -like "*IObit*" } | Stop-Process -Force -ErrorAction SilentlyContinue
    Get-Service | Where-Object { $_.Name -like "*DriverBooster*" -or $_.DisplayName -like "*IObit*" } | Stop-Service -Force -ErrorAction SilentlyContinue
    $targetRoot="F:\backup\windowsapps\installed\DriverBooster"
    $extractPath="F:\backup\windowsapps\install\Cracked\IObit_Extracted"
    Add-MpPreference -ExclusionPath $targetRoot -ErrorAction SilentlyContinue
    Add-MpPreference -ExclusionPath $extractPath -ErrorAction SilentlyContinue
    Remove-ForceFully $targetRoot
    Remove-ForceFully $extractPath
    & "C:\Program Files\7-Zip\7z.exe" x "F:\backup\windowsapps\install\Cracked\IObit Driver Booster Pro 13.5.0.359 Multilingual [FileCR].zip" -p123 -o"$extractPath" -y
    $installDir="${extractPath}\IObit Driver Booster Pro 13.5.0.359 Multilingual\crack"
$installerDir="${extractPath}\IObit Driver Booster Pro 13.5.0.359 Multilingual"
    while(!(Test-Path "$installerDir\\driver_booster_setup.exe")){ Start-Sleep 1 }
    Start-Process "$installerDir\\driver_booster_setup.exe" -ArgumentList "/VERYSILENT","/NORESTART","/NoAutoRun","/DIR=$targetRoot" -Wait
    & "C:\Program Files\7-Zip\7z.exe" x "$installerDir\\Activator_By_ActVer.zip" -p123 -o"$installDir" -y
    `$finalDllDest="$targetRoot\13.5.0"
    New-Item -ItemType Directory -Path $finalDllDest -Force > $null
    Move-Item "$extractPath\IObit Driver Booster Pro 13.5.0.359 Multilingual\crack\version.dll" -Destination $finalDllDest -Force
    Remove-ForceFully $extractPath
    Remove-ForceFully $fullSourceFolder
    $taskbarDir="$env:APPDATA\Microsoft\Internet Explorer\Quick Launch\User Pinned\TaskBar"
    Get-ChildItem -Path $taskbarDir -Filter "*Driver*Booster*.lnk" -ErrorAction SilentlyContinue | Remove-Item -Force
    Start-Process "$finalDllDest\DriverBooster.exe"
    Start-Sleep -Seconds 4
    & "F:\study\Platforms\windows\AutoHotkey\DriverBoosterscan.ahk"
}

if ($MyInvocation.InvocationName -ne '.') {
    & 'gdbooster2' @args
}
