# Generated by 2sc from function 'gdbooster' (2026-08-12 19:37:32).
function gdbooster {
    [CmdletBinding()]
    param([switch]$SelfTest)

    $startedAt = Get-Date
    $wingetPath = 'C:\Users\micha\AppData\Local\Microsoft\WindowsApps\winget.exe'
    $chocoPath = 'C:\ProgramData\chocolatey\bin\choco.exe'
    $driverBoosterPath = 'F:\backup\windowsapps\installed\driverbooster'
    $installedRoots = @(
        $driverBoosterPath,
        'C:\Program Files\IObit\Driver Booster',
        'C:\Program Files (x86)\IObit\Driver Booster'
    )

    Write-Host 'GDBOOSTER_PROGRESS stage=detecting-supported-install' -ForegroundColor Cyan
    $exePath = $null
    foreach ($root in $installedRoots) {
        if (-not (Test-Path -LiteralPath $root)) { continue }
        $candidate = Get-ChildItem -LiteralPath $root -Filter 'DriverBooster.exe' -File -Recurse -ErrorAction SilentlyContinue | Select-Object -First 1
        if ($candidate) {
            $exePath = $candidate.FullName
            break
        }
    }

    if ($SelfTest) {
        if ($exePath) {
            $version = (Get-Item -LiteralPath $exePath).VersionInfo.FileVersion
            Write-Host "GDBOOSTER_SELFTEST_OK source=installed version=$version path=$exePath" -ForegroundColor Green
            return
        }
        if (-not ((Test-Path -LiteralPath $wingetPath -PathType Leaf) -or (Test-Path -LiteralPath $chocoPath -PathType Leaf))) {
            throw 'gdbooster self-test failed: no supported package manager is available.'
        }
        Write-Host 'GDBOOSTER_SELFTEST_OK source=supported-installer' -ForegroundColor Green
        return
    }

    # Like gccleaner: always refresh the app from the docker backup image
    # (latest tag) instead of only installing a fresh copy.
    Get-Process -Name 'DriverBooster' -ErrorAction SilentlyContinue | Stop-Process -Force

    Write-Host 'GDBOOSTER_PROGRESS stage=restoring-from-docker-backup' -ForegroundColor Cyan
    try {
        Remove-Item -LiteralPath $driverBoosterPath -Recurse -Force -Confirm:$false -ErrorAction SilentlyContinue
        $imageRef = Get-BackupDockerLatestImageRef -Path $driverBoosterPath
        Write-Host "GDBOOSTER_PROGRESS stage=docker-restore image=$imageRef" -ForegroundColor Cyan
        Invoke-BackupDockerInstalledAppRestore 'driverbooster'
    } catch {
        Write-Host "GDBOOSTER_PROGRESS stage=backup-check-unavailable reason=$($_.Exception.Message)" -ForegroundColor Yellow
    }

    foreach ($root in $installedRoots) {
        if (-not (Test-Path -LiteralPath $root)) { continue }
        $candidate = Get-ChildItem -LiteralPath $root -Filter 'DriverBooster.exe' -File -Recurse -ErrorAction SilentlyContinue | Select-Object -First 1
        if ($candidate) {
            $exePath = $candidate.FullName
            break
        }
    }

    if (-not $exePath) {
        Write-Host 'GDBOOSTER_PROGRESS stage=installing-supported-driverbooster' -ForegroundColor Cyan
        $installed = $false
        if (Test-Path -LiteralPath $wingetPath -PathType Leaf) {
            & $wingetPath install --id IObit.DriverBooster --exact --silent --accept-package-agreements --accept-source-agreements --disable-interactivity
            $installed = ($LASTEXITCODE -eq 0)
        }
        if (-not $installed -and (Test-Path -LiteralPath $chocoPath -PathType Leaf)) {
            & $chocoPath install driverbooster -y --no-progress
            $installed = ($LASTEXITCODE -eq 0)
        }
        if (-not $installed) {
            throw 'gdbooster could not install the supported Driver Booster package.'
        }

        foreach ($root in $installedRoots) {
            if (-not (Test-Path -LiteralPath $root)) { continue }
            $candidate = Get-ChildItem -LiteralPath $root -Filter 'DriverBooster.exe' -File -Recurse -ErrorAction SilentlyContinue | Select-Object -First 1
            if ($candidate) {
                $exePath = $candidate.FullName
                break
            }
        }
    }

    if (-not $exePath) {
        throw 'gdbooster completed installation but DriverBooster.exe is missing.'
    }

    $running = Get-Process -Name 'DriverBooster' -ErrorAction SilentlyContinue | Select-Object -First 1
    if ($running) {
        Write-Host "GDBOOSTER_PROGRESS stage=already-running pid=$($running.Id)" -ForegroundColor Cyan
    } else {
        Write-Host "GDBOOSTER_PROGRESS stage=starting-driverbooster path=$exePath" -ForegroundColor Cyan
        Start-Process -FilePath $exePath -ErrorAction Stop | Out-Null
    }
    $elapsedMs = [int]((Get-Date) - $startedAt).TotalMilliseconds
    Write-Host "GDBOOSTER_OK elapsed_ms=$elapsedMs" -ForegroundColor Green
}

if ($MyInvocation.InvocationName -ne '.') {
    & 'gdbooster' @args
}