# Generated by 2sc from function 'Get-BackupDockerLatestRemoteTag' (2026-08-13 00:01:16).
# Self-bootstrap: load the profile environment when this script runs
# outside a profile session so it behaves exactly like the function it
# was copied from. The module is also force-re-imported when the copy
# loaded in this process is stale (psm1 changed on disk) so a long-
# running session never runs an outdated dispatcher.
$__2scProfileModule = 'C:\Users\micha\Documents\WindowsPowerShell\Modules\CodexProfileFunctions\CodexProfileFunctions.psd1'
$__2scNeedBootstrap = -not (Get-Command -Name 'Initialize-CodexProfileFunctions' -CommandType Function -ErrorAction SilentlyContinue)
if (-not $__2scNeedBootstrap) {
    $__2scLoadedModule = Get-Module -Name 'CodexProfileFunctions' -ErrorAction SilentlyContinue | Select-Object -First 1
    if ($__2scLoadedModule) {
        $__2scLoadedFingerprint = $__2scLoadedModule.SessionState.PSVariable.GetValue('ProfileModuleFingerprint')
        $__2scModuleFile = Join-Path $__2scLoadedModule.ModuleBase 'CodexProfileFunctions.psm1'
        if ([System.IO.File]::Exists($__2scModuleFile)) {
            $__2scDiskInfo = Get-Item -LiteralPath $__2scModuleFile -ErrorAction SilentlyContinue
            if ($__2scDiskInfo) {
                $__2scDiskFingerprint = '{0}|{1}' -f $__2scDiskInfo.Length, $__2scDiskInfo.LastWriteTimeUtc.Ticks
                if ([string]$__2scLoadedFingerprint -and $__2scDiskFingerprint -ne [string]$__2scLoadedFingerprint) { $__2scNeedBootstrap = $true }
            }
        }
    }
}
if ($__2scNeedBootstrap) {
    if (-not (Test-Path -LiteralPath $__2scProfileModule -PathType Leaf)) {
        throw "2sc-generated script requires the Codex profile module: $__2scProfileModule"
    }
    Import-Module -Name $__2scProfileModule -Force -DisableNameChecking -ErrorAction Stop
    Initialize-CodexProfileFunctions
}
function Get-BackupDockerLatestRemoteTag {
    [CmdletBinding(DefaultParameterSetName = 'Path')]
    param(
        [Parameter(Mandatory, ParameterSetName = 'Path')]
        [string]$Path,

        [Parameter(Mandatory, ParameterSetName = 'Name')]
        [string]$Name,

        [Parameter(Mandatory, ParameterSetName = 'RepoSlug')]
        [string]$RepoSlug
    )

    $resolvedRepoSlug = if ($PSCmdlet.ParameterSetName -eq 'Path') {
        Get-BackupDockerRepoSlug -Path $Path
    } elseif ($PSCmdlet.ParameterSetName -eq 'Name') {
        Get-BackupDockerRepoSlug -Name $Name
    } else {
        $RepoSlug
    }
    $repository = Get-BackupDockerRepositoryFromSlug -RepoSlug $resolvedRepoSlug

    $remoteTags = @(Get-BackupDockerHubTagNames -RepoSlug $resolvedRepoSlug)
    $latestRemoteTag = Get-BackupDockerLatestTagNameFromSet -TagNames $remoteTags
    if ($latestRemoteTag) {
        return $latestRemoteTag
    }

    throw "No Docker Hub tags were found for $repository. Run menu for that path first."
}

if ($MyInvocation.InvocationName -ne '.') {
    & 'Get-BackupDockerLatestRemoteTag' @args
}
