# Generated by 2sc from function 'Get-NvidProtocolCommand' (2026-08-12 23:59:49).
# Self-bootstrap: load the profile environment when this script runs
# outside a profile session so it behaves exactly like the function it
# was copied from. The module is also force-re-imported when the copy
# loaded in this process is stale (psm1 changed on disk) so a long-
# running session never runs an outdated dispatcher.
$__2scProfileModule = 'C:\Users\micha\Documents\WindowsPowerShell\Modules\CodexProfileFunctions\CodexProfileFunctions.psd1'
$__2scNeedBootstrap = -not (Get-Command -Name 'Initialize-CodexProfileFunctions' -CommandType Function -ErrorAction SilentlyContinue)
if (-not $__2scNeedBootstrap) {
    $__2scLoadedModule = Get-Module -Name 'CodexProfileFunctions' -ErrorAction SilentlyContinue | Select-Object -First 1
    if ($__2scLoadedModule) {
        $__2scLoadedFingerprint = $__2scLoadedModule.SessionState.PSVariable.GetValue('ProfileModuleFingerprint')
        $__2scModuleFile = Join-Path $__2scLoadedModule.ModuleBase 'CodexProfileFunctions.psm1'
        if ([System.IO.File]::Exists($__2scModuleFile)) {
            $__2scDiskInfo = Get-Item -LiteralPath $__2scModuleFile -ErrorAction SilentlyContinue
            if ($__2scDiskInfo) {
                $__2scDiskFingerprint = '{0}|{1}' -f $__2scDiskInfo.Length, $__2scDiskInfo.LastWriteTimeUtc.Ticks
                if ([string]$__2scLoadedFingerprint -and $__2scDiskFingerprint -ne [string]$__2scLoadedFingerprint) { $__2scNeedBootstrap = $true }
            }
        }
    }
}
if ($__2scNeedBootstrap) {
    if (-not (Test-Path -LiteralPath $__2scProfileModule -PathType Leaf)) {
        throw "2sc-generated script requires the Codex profile module: $__2scProfileModule"
    }
    Import-Module -Name $__2scProfileModule -Force -DisableNameChecking -ErrorAction Stop
    Initialize-CodexProfileFunctions
}
function Get-NvidProtocolCommand {
    param([string]$ProtocolName)

    foreach ($path in @(
        ('Registry::HKEY_CLASSES_ROOT\{0}\shell\open\command' -f $ProtocolName),
        ('HKCU:\Software\Classes\{0}\shell\open\command' -f $ProtocolName)
    )) {
        if (-not (Test-Path $path)) {
            continue
        }

        $commandText = (Get-ItemProperty -Path $path -ErrorAction SilentlyContinue).'(default)'
        if (-not $commandText) {
            continue
        }

        $pathMatch = [regex]::Match($commandText, '^\s*"(?<value>[^"]+)"')
        $commandPath = if ($pathMatch.Success) { $pathMatch.Groups['value'].Value } else { $null }
        return [pscustomobject]@{
            Registered = $true
            RegistryPath = $path
            Command = $commandText
            Path = $commandPath
            PathExists = ($commandPath -and (Test-Path $commandPath))
        }
    }

    return [pscustomobject]@{
        Registered = $false
        RegistryPath = $null
        Command = $null
        Path = $null
        PathExists = $false
    }
}

if ($MyInvocation.InvocationName -ne '.') {
    & 'Get-NvidProtocolCommand' @args
}
