# Generated by 2sc from function 'Get-NvidOfficialAppInfo' (2026-08-12 23:59:34).
# Self-bootstrap: load the profile environment when this script runs
# outside a profile session so it behaves exactly like the function it
# was copied from. The module is also force-re-imported when the copy
# loaded in this process is stale (psm1 changed on disk) so a long-
# running session never runs an outdated dispatcher.
$__2scProfileModule = 'C:\Users\micha\Documents\WindowsPowerShell\Modules\CodexProfileFunctions\CodexProfileFunctions.psd1'
$__2scNeedBootstrap = -not (Get-Command -Name 'Initialize-CodexProfileFunctions' -CommandType Function -ErrorAction SilentlyContinue)
if (-not $__2scNeedBootstrap) {
    $__2scLoadedModule = Get-Module -Name 'CodexProfileFunctions' -ErrorAction SilentlyContinue | Select-Object -First 1
    if ($__2scLoadedModule) {
        $__2scLoadedFingerprint = $__2scLoadedModule.SessionState.PSVariable.GetValue('ProfileModuleFingerprint')
        $__2scModuleFile = Join-Path $__2scLoadedModule.ModuleBase 'CodexProfileFunctions.psm1'
        if ([System.IO.File]::Exists($__2scModuleFile)) {
            $__2scDiskInfo = Get-Item -LiteralPath $__2scModuleFile -ErrorAction SilentlyContinue
            if ($__2scDiskInfo) {
                $__2scDiskFingerprint = '{0}|{1}' -f $__2scDiskInfo.Length, $__2scDiskInfo.LastWriteTimeUtc.Ticks
                if ([string]$__2scLoadedFingerprint -and $__2scDiskFingerprint -ne [string]$__2scLoadedFingerprint) { $__2scNeedBootstrap = $true }
            }
        }
    }
}
if ($__2scNeedBootstrap) {
    if (-not (Test-Path -LiteralPath $__2scProfileModule -PathType Leaf)) {
        throw "2sc-generated script requires the Codex profile module: $__2scProfileModule"
    }
    Import-Module -Name $__2scProfileModule -Force -DisableNameChecking -ErrorAction Stop
    Initialize-CodexProfileFunctions
}
function Get-NvidOfficialAppInfo {
$pageUrl = 'https://www.nvidia.com/en-us/software/nvidia-app/'
        $releaseUrl = 'https://www.nvidia.com/en-us/software/nvidia-app/release-highlights/'
        $known = [pscustomobject]@{ Version = '11.0.7.247'; DownloadURL = 'https://us.download.nvidia.com/nvapp/client/11.0.7.247/NVIDIA_app_v11.0.7.247.exe'; PageURL = $pageUrl; ReleaseURL = $releaseUrl; Source = 'pinned-official-fallback-after-nvidia-page-error' }
        $headers = @{ 'User-Agent' = 'Mozilla/5.0 WindowsPowerShell/5.1 nvid'; 'Cache-Control' = 'no-cache'; 'Pragma' = 'no-cache' }
        for ($attempt = 1; $attempt -le 4; $attempt++) {
            try {
                $response = Invoke-WebRequest -Uri $pageUrl -UseBasicParsing -TimeoutSec 45 -Headers $headers
                $matches = [regex]::Matches([string]$response.Content, 'https://(?:us\.)?download\.nvidia\.com/nvapp/client/(?<version>[\d\.]+)/NVIDIA_app_v(?<fileversion>[\d\.]+)\.exe')
                $candidates = @()
                foreach ($m in $matches) {
                    if ($m.Groups['fileversion'].Success -and $m.Value) {
                        $candidates += [pscustomobject]@{ Version = [string]$m.Groups['fileversion'].Value; DownloadURL = [string]$m.Value; PageURL = $pageUrl; ReleaseURL = $releaseUrl; Source = 'nvidia-software-page' }
                    }
                }
                $best = $candidates | Sort-Object @{ Expression = { try { [version]$_.Version } catch { [version]'0.0' } } } -Descending | Select-Object -First 1
                if ($best) { return $best }
            } catch {
                Write-Host ("  NVIDIA App official page lookup attempt {0}/4 failed: {1}" -f $attempt,$_.Exception.Message) -ForegroundColor DarkYellow
                Start-Sleep -Seconds ([Math]::Min(12, 2 * $attempt))
            }
        }
        try {
            $statusPath = 'C:\ProgramData\NVIDIA Corporation\NVIDIA App\UpdateFramework\status\nvapp\updatecheck.json'
            if (Test-Path -LiteralPath $statusPath) {
                $status = Get-Content -LiteralPath $statusPath -Raw | ConvertFrom-Json
                foreach ($item in @($status)) {
                    if ($item.updateInfoJSON) {
                        $info = $item.updateInfoJSON | ConvertFrom-Json
                        if ($info.version -and $info.url) { return [pscustomobject]@{ Version = [string]$info.version; DownloadURL = [string]$info.url; PageURL = $pageUrl; ReleaseURL = $releaseUrl; Source = 'local-nvidia-update-status' } }
                    }
                }
            }
        } catch {}
        return $known
}

if ($MyInvocation.InvocationName -ne '.') {
    & 'Get-NvidOfficialAppInfo' @args
}
