# Generated by 2sc from function 'Get-ProfileManagedWebAppProcess' (2026-08-13 00:39:51).
# Self-bootstrap: load the profile environment when this script runs
# outside a profile session so it behaves exactly like the function it
# was copied from. The module is also force-re-imported when the copy
# loaded in this process is stale (psm1 changed on disk) so a long-
# running session never runs an outdated dispatcher.
$__2scProfileModule = 'C:\Users\micha\Documents\WindowsPowerShell\Modules\CodexProfileFunctions\CodexProfileFunctions.psd1'
$__2scNeedBootstrap = -not (Get-Command -Name 'Initialize-CodexProfileFunctions' -CommandType Function -ErrorAction SilentlyContinue)
if (-not $__2scNeedBootstrap) {
    $__2scLoadedModule = Get-Module -Name 'CodexProfileFunctions' -ErrorAction SilentlyContinue | Select-Object -First 1
    if ($__2scLoadedModule) {
        $__2scLoadedFingerprint = $__2scLoadedModule.SessionState.PSVariable.GetValue('ProfileModuleFingerprint')
        $__2scModuleFile = Join-Path $__2scLoadedModule.ModuleBase 'CodexProfileFunctions.psm1'
        if ([System.IO.File]::Exists($__2scModuleFile)) {
            $__2scDiskInfo = Get-Item -LiteralPath $__2scModuleFile -ErrorAction SilentlyContinue
            if ($__2scDiskInfo) {
                $__2scDiskFingerprint = '{0}|{1}' -f $__2scDiskInfo.Length, $__2scDiskInfo.LastWriteTimeUtc.Ticks
                if ([string]$__2scLoadedFingerprint -and $__2scDiskFingerprint -ne [string]$__2scLoadedFingerprint) { $__2scNeedBootstrap = $true }
            }
        }
    }
}
if ($__2scNeedBootstrap) {
    if (-not (Test-Path -LiteralPath $__2scProfileModule -PathType Leaf)) {
        throw "2sc-generated script requires the Codex profile module: $__2scProfileModule"
    }
    Import-Module -Name $__2scProfileModule -Force -DisableNameChecking -ErrorAction Stop
    Initialize-CodexProfileFunctions
}
function Get-ProfileManagedWebAppProcess {
    [CmdletBinding()]
    param([object]$State)

    if (-not $State -or -not $State.ProcessId) {
        return $null
    }

    $processId = [int]$State.ProcessId
    $process = Get-CimInstance -ClassName Win32_Process -Filter ("ProcessId = {0}" -f $processId) -ErrorAction SilentlyContinue
    if (-not $process) {
        return $null
    }

    $commandLine = [string]$process.CommandLine
    if ($commandLine -notmatch '(?i)(^|\s)-m\s+http\.server(\s|$)') {
        return $null
    }
    if ($State.Port -and $commandLine -notmatch ('(?<!\d){0}(?!\d)' -f [regex]::Escape([string]$State.Port))) {
        return $null
    }
    if ($State.ProcessStartedUtc) {
        $liveProcess = Get-Process -Id $processId -ErrorAction SilentlyContinue
        if (-not $liveProcess) {
            return $null
        }
        try {
            $expectedStart = [DateTime]::Parse([string]$State.ProcessStartedUtc).ToUniversalTime()
            $actualStart = $liveProcess.StartTime.ToUniversalTime()
            if ([Math]::Abs(($actualStart - $expectedStart).TotalSeconds) -gt 2) {
                return $null
            }
        } catch {
            return $null
        }
    }

    return $process
}

if ($MyInvocation.InvocationName -ne '.') {
    & 'Get-ProfileManagedWebAppProcess' @args
}
