# Generated by 2sc from function 'gwinpe' (2026-08-13 00:04:32).
# Self-bootstrap: load the profile environment when this script runs
# outside a profile session so it behaves exactly like the function it
# was copied from. The module is also force-re-imported when the copy
# loaded in this process is stale (psm1 changed on disk) so a long-
# running session never runs an outdated dispatcher.
$__2scProfileModule = 'C:\Users\micha\Documents\WindowsPowerShell\Modules\CodexProfileFunctions\CodexProfileFunctions.psd1'
$__2scNeedBootstrap = -not (Get-Command -Name 'Initialize-CodexProfileFunctions' -CommandType Function -ErrorAction SilentlyContinue)
if (-not $__2scNeedBootstrap) {
    $__2scLoadedModule = Get-Module -Name 'CodexProfileFunctions' -ErrorAction SilentlyContinue | Select-Object -First 1
    if ($__2scLoadedModule) {
        $__2scLoadedFingerprint = $__2scLoadedModule.SessionState.PSVariable.GetValue('ProfileModuleFingerprint')
        $__2scModuleFile = Join-Path $__2scLoadedModule.ModuleBase 'CodexProfileFunctions.psm1'
        if ([System.IO.File]::Exists($__2scModuleFile)) {
            $__2scDiskInfo = Get-Item -LiteralPath $__2scModuleFile -ErrorAction SilentlyContinue
            if ($__2scDiskInfo) {
                $__2scDiskFingerprint = '{0}|{1}' -f $__2scDiskInfo.Length, $__2scDiskInfo.LastWriteTimeUtc.Ticks
                if ([string]$__2scLoadedFingerprint -and $__2scDiskFingerprint -ne [string]$__2scLoadedFingerprint) { $__2scNeedBootstrap = $true }
            }
        }
    }
}
if ($__2scNeedBootstrap) {
    if (-not (Test-Path -LiteralPath $__2scProfileModule -PathType Leaf)) {
        throw "2sc-generated script requires the Codex profile module: $__2scProfileModule"
    }
    Import-Module -Name $__2scProfileModule -Force -DisableNameChecking -ErrorAction Stop
    Initialize-CodexProfileFunctions
}
function gwinpe {
    $adkWim = "C:\Program Files (x86)\Windows Kits\10\Assessment and Deployment Kit\Windows Preinstallation Environment\amd64\en-us\winpe.wim"
    $targetWim = "C:\Windows\System32\Recovery\Winre.wim"

    if (!(Test-Path $adkWim)) {
        Write-Host "Installing ADK+WinPE..." -ForegroundColor Cyan
        [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
        Invoke-WebRequest "https://go.microsoft.com/fwlink/?linkid=2271337" -OutFile "$env:TEMP\adksetup.exe"
        Invoke-WebRequest "https://go.microsoft.com/fwlink/?linkid=2271338" -OutFile "$env:TEMP\adkwinpesetup.exe"
        Start-Process "$env:TEMP\adksetup.exe" -ArgumentList "/features OptionId.DeploymentTools /quiet /norestart /ceip off" -Wait
        Start-Process "$env:TEMP\adkwinpesetup.exe" -ArgumentList "/features OptionId.WindowsPreinstallationEnvironment /quiet /norestart /ceip off" -Wait
    }

    if (!(Test-Path $targetWim)) {
        Write-Host "Restoring WinRE..." -ForegroundColor Cyan
        Copy-Item $adkWim $targetWim -Force
    }

    $re = reagentc /info 2>&1 | Out-String
    if ($re -match "Disabled") {
        Write-Host "Enabling WinRE..." -ForegroundColor Cyan
        reagentc /enable
    }

    Write-Host "=== WinPE setup complete ===" -ForegroundColor Green
}

if ($MyInvocation.InvocationName -ne '.') {
    & 'gwinpe' @args
}
