# Generated by 2sc from function 'Initialize-ProfileCommandModeFunctions' (2026-08-13 00:00:17).
# Self-bootstrap: load the profile environment when this script runs
# outside a profile session so it behaves exactly like the function it
# was copied from. The module is also force-re-imported when the copy
# loaded in this process is stale (psm1 changed on disk) so a long-
# running session never runs an outdated dispatcher.
$__2scProfileModule = 'C:\Users\micha\Documents\WindowsPowerShell\Modules\CodexProfileFunctions\CodexProfileFunctions.psd1'
$__2scNeedBootstrap = -not (Get-Command -Name 'Initialize-CodexProfileFunctions' -CommandType Function -ErrorAction SilentlyContinue)
if (-not $__2scNeedBootstrap) {
    $__2scLoadedModule = Get-Module -Name 'CodexProfileFunctions' -ErrorAction SilentlyContinue | Select-Object -First 1
    if ($__2scLoadedModule) {
        $__2scLoadedFingerprint = $__2scLoadedModule.SessionState.PSVariable.GetValue('ProfileModuleFingerprint')
        $__2scModuleFile = Join-Path $__2scLoadedModule.ModuleBase 'CodexProfileFunctions.psm1'
        if ([System.IO.File]::Exists($__2scModuleFile)) {
            $__2scDiskInfo = Get-Item -LiteralPath $__2scModuleFile -ErrorAction SilentlyContinue
            if ($__2scDiskInfo) {
                $__2scDiskFingerprint = '{0}|{1}' -f $__2scDiskInfo.Length, $__2scDiskInfo.LastWriteTimeUtc.Ticks
                if ([string]$__2scLoadedFingerprint -and $__2scDiskFingerprint -ne [string]$__2scLoadedFingerprint) { $__2scNeedBootstrap = $true }
            }
        }
    }
}
if ($__2scNeedBootstrap) {
    if (-not (Test-Path -LiteralPath $__2scProfileModule -PathType Leaf)) {
        throw "2sc-generated script requires the Codex profile module: $__2scProfileModule"
    }
    Import-Module -Name $__2scProfileModule -Force -DisableNameChecking -ErrorAction Stop
    Initialize-CodexProfileFunctions
}
function Initialize-ProfileCommandModeFunctions {
    if (-not $script:ProfileIsCommandMode) { return }

    $proxy = {
        $calledName = $MyInvocation.MyCommand.Name
        if (-not $calledName -or $calledName -eq '&') { $calledName = $MyInvocation.InvocationName }
        if (-not $calledName -or $calledName -eq '&') { throw 'Full profile proxy could not determine the command name to reload.' }

        $lookupName = $calledName -replace '^(?i:global:)', ''
        foreach ($sourcePath in Get-ProfileFunctionSourcePaths) {
            $functionMap = Get-ProfileFunctionMap -ProfilePath $sourcePath
            if (-not $functionMap.ContainsKey($lookupName)) { continue }
            . ([scriptblock]::Create("function global:$lookupName $($functionMap[$lookupName].Body.Extent.Text)"))
            $targetCommand = Get-Command $lookupName -CommandType Function -ErrorAction Stop
            & $targetCommand @args
            return
        }

        Write-Host "Function '$calledName' unavailable: no source definition was found." -ForegroundColor Yellow
    }

    $skip = @('Load-FullPowerShellProfile', 'fullprofile', 'nomouse', 'ps527', 'pps527', 'Get-ProfileFunctionMap', 'Get-ProfileFunctionSourcePaths', 'cfun', 'Repair-StandardWindowsProcessEnvironment',  'Initialize-FastProfilePsReadLineHistory', 'Initialize-ProfileCommandModeFunctions')
    foreach ($sourcePath in @($PROFILE)) {
        if ([string]::IsNullOrWhiteSpace($sourcePath) -or -not (Test-Path -LiteralPath $sourcePath -PathType Leaf)) { continue }
        $functionMap = Get-ProfileFunctionMap -ProfilePath $sourcePath
        foreach ($functionName in $functionMap.Keys) {
            $lookupName = $functionName -replace '^(?i:global:)', ''
            if ($lookupName -in $skip) { continue }
            if (Get-Command $lookupName -CommandType Function -ErrorAction SilentlyContinue) { continue }
            Set-Item -Path "Function:\global:$lookupName" -Value $proxy -Force
        }
    }
}

if ($MyInvocation.InvocationName -ne '.') {
    & 'Initialize-ProfileCommandModeFunctions' @args
}
