# Generated by 2sc from function 'Install-SpeedtestCliExecutable' (2026-08-13 00:40:39).
# Self-bootstrap: load the profile environment when this script runs
# outside a profile session so it behaves exactly like the function it
# was copied from. The module is also force-re-imported when the copy
# loaded in this process is stale (psm1 changed on disk) so a long-
# running session never runs an outdated dispatcher.
$__2scProfileModule = 'C:\Users\micha\Documents\WindowsPowerShell\Modules\CodexProfileFunctions\CodexProfileFunctions.psd1'
$__2scNeedBootstrap = -not (Get-Command -Name 'Initialize-CodexProfileFunctions' -CommandType Function -ErrorAction SilentlyContinue)
if (-not $__2scNeedBootstrap) {
    $__2scLoadedModule = Get-Module -Name 'CodexProfileFunctions' -ErrorAction SilentlyContinue | Select-Object -First 1
    if ($__2scLoadedModule) {
        $__2scLoadedFingerprint = $__2scLoadedModule.SessionState.PSVariable.GetValue('ProfileModuleFingerprint')
        $__2scModuleFile = Join-Path $__2scLoadedModule.ModuleBase 'CodexProfileFunctions.psm1'
        if ([System.IO.File]::Exists($__2scModuleFile)) {
            $__2scDiskInfo = Get-Item -LiteralPath $__2scModuleFile -ErrorAction SilentlyContinue
            if ($__2scDiskInfo) {
                $__2scDiskFingerprint = '{0}|{1}' -f $__2scDiskInfo.Length, $__2scDiskInfo.LastWriteTimeUtc.Ticks
                if ([string]$__2scLoadedFingerprint -and $__2scDiskFingerprint -ne [string]$__2scLoadedFingerprint) { $__2scNeedBootstrap = $true }
            }
        }
    }
}
if ($__2scNeedBootstrap) {
    if (-not (Test-Path -LiteralPath $__2scProfileModule -PathType Leaf)) {
        throw "2sc-generated script requires the Codex profile module: $__2scProfileModule"
    }
    Import-Module -Name $__2scProfileModule -Force -DisableNameChecking -ErrorAction Stop
    Initialize-CodexProfileFunctions
}
function Install-SpeedtestCliExecutable {
        if (-not (Test-Path -LiteralPath $installRoot -PathType Container)) {
            New-Item -ItemType Directory -Force -Path $installRoot | Out-Null
        }
        $extractRoot = Join-Path $env:TEMP ('ookla-speedtest-extract-' + [Guid]::NewGuid().ToString('N'))
        if (Test-Path -LiteralPath $zipPath -PathType Leaf) { Remove-Item -LiteralPath $zipPath -Force -ErrorAction SilentlyContinue }
        [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
        Invoke-WebRequest -Uri $url -OutFile $zipPath -UseBasicParsing -ErrorAction Stop
        $actualSha256 = (Get-FileHash -LiteralPath $zipPath -Algorithm SHA256).Hash.ToUpperInvariant()
        if ($actualSha256 -ne $expectedSha256) { throw "Speedtest CLI download hash mismatch: $actualSha256" }
        Add-Type -AssemblyName System.IO.Compression.FileSystem
        New-Item -ItemType Directory -Force -Path $extractRoot | Out-Null
        try {
            [System.IO.Compression.ZipFile]::ExtractToDirectory($zipPath, $extractRoot)
            $extractedExe = Join-Path $extractRoot 'speedtest.exe'
            if (-not (Test-Path -LiteralPath $extractedExe -PathType Leaf)) { throw "Speedtest CLI zip did not contain speedtest.exe" }
            Copy-Item -LiteralPath $extractedExe -Destination $installExe -Force
            $license = Join-Path $extractRoot 'speedtest.md'
            if (Test-Path -LiteralPath $license -PathType Leaf) { Copy-Item -LiteralPath $license -Destination (Join-Path $installRoot 'speedtest.md') -Force }
        } finally {
            Remove-Item -LiteralPath $extractRoot -Recurse -Force -ErrorAction SilentlyContinue
        }
        if (-not (Test-SpeedtestCliExecutable -Path $installExe)) { throw "Installed Speedtest CLI is not executable: $installExe" }
        $userPath = [Environment]::GetEnvironmentVariable('Path','User')
        $pathParts = @($userPath -split ';' | Where-Object { $_ })
        if ($pathParts -notcontains $installRoot) {
            [Environment]::SetEnvironmentVariable('Path', (($pathParts + $installRoot) -join ';'), 'User')
        }
        $envParts = @($env:Path -split ';' | Where-Object { $_ })
        if ($envParts -notcontains $installRoot) { $env:Path = (($envParts + $installRoot) -join ';') }
        return $installExe
    }

if ($MyInvocation.InvocationName -ne '.') {
    & 'Install-SpeedtestCliExecutable' @args
}
