# Generated by 2sc from function 'Install-NvidLatestDisplayDriver' (2026-08-12 22:27:20).
# Self-bootstrap: load the profile environment when this script runs
# outside a profile session so it behaves exactly like the function it
# was copied from.
if (-not (Get-Command -Name 'Initialize-CodexProfileFunctions' -CommandType Function -ErrorAction SilentlyContinue)) {
    $__2scProfileModule = 'C:\Users\micha\Documents\WindowsPowerShell\Modules\CodexProfileFunctions\CodexProfileFunctions.psd1'
    if (-not (Test-Path -LiteralPath $__2scProfileModule -PathType Leaf)) {
        throw "2sc-generated script requires the Codex profile module: $__2scProfileModule"
    }
    Import-Module -Name $__2scProfileModule -DisableNameChecking -ErrorAction Stop
    Initialize-CodexProfileFunctions
}
function Install-NvidLatestDisplayDriver {
        $target = Get-NvidDisplayTarget
        Write-NvidStep ("detected NVIDIA adapter {0} ({1}) mapped to ProductID {2}/SeriesID {3}" -f $target.ProductName,$target.Device.InstanceId,$target.ProductId,$target.SeriesId)
        $latest = Resolve-NvidLatestDriverDownload -Target $target
        Write-NvidStep ("latest NVIDIA display driver target is {0} (driver id {1})" -f $latest.Version,$latest.DriverId)
        $driverWork = Join-Path 'F:\hermes\nvid' ("nvid-driver-{0}" -f ($latest.Version -replace '[^0-9]',''))
        New-Item -ItemType Directory -Force -Path $driverWork | Out-Null
        $driverInstaller = Join-Path $driverWork (Split-Path $latest.Url -Leaf)
        if (-not (Test-Path -LiteralPath $driverInstaller -PathType Leaf)) {
            Write-NvidStep ("downloading NVIDIA display driver {0}" -f $latest.Url)
            Invoke-WebRequest -Uri $latest.Url -OutFile $driverInstaller -UseBasicParsing -TimeoutSec 1800
        } else {
            Write-NvidStep ("using existing NVIDIA display driver installer {0}" -f $driverInstaller)
        }
        $sig = Get-AuthenticodeSignature -LiteralPath $driverInstaller
        if ($sig.Status -ne 'Valid' -or $sig.SignerCertificate.Subject -notmatch 'NVIDIA') { throw ("NVIDIA display driver signature check failed: {0}" -f $sig.StatusMessage) }
        try { Unblock-File -LiteralPath $driverInstaller -ErrorAction SilentlyContinue } catch {}
        Stop-NvidAppProcesses
        try {
            Invoke-NvidNativeInstaller -FilePath $driverInstaller -Arguments @('-s','-noreboot') -Name 'NVIDIA display driver installer' | Out-Null
        } catch {
            if ($_.Exception.Message -notmatch '-2146762751|0x800B0001') { throw }
            Write-NvidStep 'NVIDIA package launcher hit 0x800B0001; falling back to signed-package extraction plus pnputil driver install'
            $extractDir = Join-Path $driverWork 'extracted'
            $sevenZip = @('C:\Program Files\7-Zip\7z.exe','C:\Program Files (x86)\7-Zip\7z.exe') | Where-Object { Test-Path -LiteralPath $_ -PathType Leaf } | Select-Object -First 1
            if (-not $sevenZip) { throw '7-Zip is required for the 0x800B0001 extraction fallback but was not found.' }
            $displayDriverExtracted = Join-Path $extractDir 'Display.Driver'
            $extractedLooksComplete = $false
            if (Test-Path -LiteralPath $displayDriverExtracted -PathType Container) {
                $infCount = @(Get-ChildItem -LiteralPath $displayDriverExtracted -Filter '*.inf' -ErrorAction SilentlyContinue).Count
                $sysCount = @(Get-ChildItem -LiteralPath $displayDriverExtracted -Filter '*.sys' -ErrorAction SilentlyContinue).Count
                $catCount = @(Get-ChildItem -LiteralPath $displayDriverExtracted -Filter '*.cat' -ErrorAction SilentlyContinue).Count
                $extractedLooksComplete = ($infCount -gt 5 -and $sysCount -gt 0 -and $catCount -gt 0)
                if (-not $extractedLooksComplete) {
                    Write-Host ("[nvid] existing extracted NVIDIA driver package on F: is incomplete (inf={0}, sys={1}, cat={2}); deleting and re-extracting cleanly" -f $infCount,$sysCount,$catCount) -ForegroundColor Yellow
                    Remove-Item -LiteralPath $extractDir -Recurse -Force -ErrorAction SilentlyContinue
                }
            }
            if (-not $extractedLooksComplete) {
                New-Item -ItemType Directory -Force -Path $extractDir | Out-Null
                Invoke-NvidNativeInstaller -FilePath $sevenZip -Arguments @('x','-y',('-o{0}' -f $extractDir),$driverInstaller) -Name 'NVIDIA driver extraction via 7-Zip' -AllowedExitCodes @(0) | Out-Null
            } else {
                Write-NvidStep ("using existing complete extracted NVIDIA driver package {0}" -f $extractDir)
            }
            $infRoot = Join-Path $extractDir 'Display.Driver'
            $infs = @(Get-ChildItem -LiteralPath $infRoot -Filter '*.inf' -Recurse -ErrorAction SilentlyContinue)
            if ($infs.Count -eq 0) { throw ("No NVIDIA Display.Driver INF files found under {0}" -f $infRoot) }
            $hardwareIdCandidates = New-Object 'System.Collections.Generic.List[string]'
            foreach($rawId in @($target.Device.InstanceId)) {
                if ($rawId) { [void]$hardwareIdCandidates.Add(([string]$rawId).ToUpperInvariant()) }
            }
            foreach($propKey in @('DEVPKEY_Device_HardwareIds','DEVPKEY_Device_CompatibleIds')) {
                try {
                    $prop = Get-PnpDeviceProperty -InstanceId $target.Device.InstanceId -KeyName $propKey -ErrorAction SilentlyContinue
                    foreach($rawId in @($prop.Data)) {
                        if ($rawId) { [void]$hardwareIdCandidates.Add(([string]$rawId).ToUpperInvariant()) }
                    }
                } catch {}
            }
            $expandedHardwareIds = New-Object 'System.Collections.Generic.List[string]'
            foreach($rawId in @($hardwareIdCandidates | Select-Object -Unique)) {
                if (-not $rawId) { continue }
                [void]$expandedHardwareIds.Add($rawId)
                $withoutInstance = ($rawId -replace '\\[^\\]+$','')
                if ($withoutInstance -and $withoutInstance -ne $rawId) { [void]$expandedHardwareIds.Add($withoutInstance) }
                $withoutRev = ($rawId -replace '&REV_[0-9A-F]{2}','')
                if ($withoutRev -and $withoutRev -ne $rawId) { [void]$expandedHardwareIds.Add($withoutRev) }
                $withoutSubsys = ($withoutRev -replace '&SUBSYS_[0-9A-F]{8}','')
                if ($withoutSubsys -and $withoutSubsys -ne $withoutRev) { [void]$expandedHardwareIds.Add($withoutSubsys) }
            }
            $expandedHardwareIds = @($expandedHardwareIds | Where-Object { $_ -and ($_ -match 'VEN_10DE&DEV_') } | Select-Object -Unique)
            Write-NvidStep ("matching NVIDIA INF against hardware IDs: {0}" -f ($expandedHardwareIds -join '; '))
            $selectedInf = $null
            foreach($pattern in $expandedHardwareIds) {
                foreach($inf in $infs) {
                    $txt = (Get-Content -LiteralPath $inf.FullName -Raw -ErrorAction SilentlyContinue).ToUpperInvariant()
                    if ($txt.IndexOf($pattern, [System.StringComparison]::OrdinalIgnoreCase) -ge 0) { $selectedInf = $inf; break }
                }
                if ($selectedInf) { break }
            }
            if (-not $selectedInf) {
                $genericPattern = 'PCI\VEN_10DE&DEV_' + $target.DeviceId
                foreach($inf in @($infs | Sort-Object @{Expression={ if($_.Name -eq 'nv_dispi.inf'){0}elseif($_.Name -match '^nv.*\.inf$'){1}else{2} }},Name)){ 
                    $txt = (Get-Content -LiteralPath $inf.FullName -Raw -ErrorAction SilentlyContinue).ToUpperInvariant()
                    if ($txt.IndexOf($genericPattern, [System.StringComparison]::OrdinalIgnoreCase) -ge 0 -or ($txt -match 'CLASS\s*=\s*DISPLAY' -and $txt -match 'NVIDIA')) { $selectedInf = $inf; break }
                }
            }
            if ($selectedInf) {
                Write-NvidStep ("installing best NVIDIA Display.Driver INF through pnputil: {0}" -f $selectedInf.FullName)
                & pnputil.exe /add-driver $selectedInf.FullName /install 2>&1 | Tee-Object -Variable pnputilOutput | Out-Host
                if (($LASTEXITCODE -ne 0) -and ($LASTEXITCODE -ne 259)) {
                    Write-Host ("[nvid] selected INF install exited {0}; retrying whole Display.Driver INF tree so Windows can choose the correct OEM match" -f $LASTEXITCODE) -ForegroundColor Yellow
                    & pnputil.exe /add-driver (Join-Path $infRoot '*.inf') /subdirs /install 2>&1 | Tee-Object -Variable pnputilOutputAll | Out-Host
                }
            } else {
                Write-Host ("[nvid] no single INF text matched {0}; installing whole Display.Driver INF tree so Windows SetupAPI can select the correct NVIDIA package" -f $target.Device.InstanceId) -ForegroundColor Yellow
                & pnputil.exe /add-driver (Join-Path $infRoot '*.inf') /subdirs /install 2>&1 | Tee-Object -Variable pnputilOutputAll | Out-Host
            }
            if (($LASTEXITCODE -ne 0) -and ($LASTEXITCODE -ne 259)) { throw ("pnputil NVIDIA Display.Driver install failed with exit {0}; tried selected INF and full INF-tree fallback under {1}" -f $LASTEXITCODE,$infRoot) }
            if ($LASTEXITCODE -eq 259) { Write-NvidStep 'pnputil returned 259 after reporting the NVIDIA driver package is already installed/up-to-date on the device; treating as success' }
        }
        try { pnputil.exe /scan-devices 2>&1 | Out-Host } catch {}
        Start-Sleep -Seconds 5
        $after = Get-CimInstance Win32_PnPSignedDriver | Where-Object { $_.DeviceName -match 'NVIDIA|GeForce|RTX' -or $_.HardwareID -match 'VEN_10DE' } | Sort-Object DriverDate -Descending | Select-Object -First 1
        if (-not $after) { throw 'NVIDIA display driver installation finished but Windows still reports no NVIDIA signed display driver.' }
        Write-NvidStep ("Windows reports NVIDIA driver after install: {0} {1}" -f $after.DeviceName,$after.DriverVersion)
        return [pscustomobject]@{ Version = $latest.Version; Installer = $driverInstaller; DeviceName = $after.DeviceName; InstalledDriverVersion = $after.DriverVersion }
    }

if ($MyInvocation.InvocationName -ne '.') {
    & 'Install-NvidLatestDisplayDriver' @args
}
