# Generated by 2sc from function 'Install-NvidDriverWithPnpUtilFallback' (2026-08-13 00:41:30).
# Self-bootstrap: load the profile environment when this script runs
# outside a profile session so it behaves exactly like the function it
# was copied from. The module is also force-re-imported when the copy
# loaded in this process is stale (psm1 changed on disk) so a long-
# running session never runs an outdated dispatcher.
$__2scProfileModule = 'C:\Users\micha\Documents\WindowsPowerShell\Modules\CodexProfileFunctions\CodexProfileFunctions.psd1'
$__2scNeedBootstrap = -not (Get-Command -Name 'Initialize-CodexProfileFunctions' -CommandType Function -ErrorAction SilentlyContinue)
if (-not $__2scNeedBootstrap) {
    $__2scLoadedModule = Get-Module -Name 'CodexProfileFunctions' -ErrorAction SilentlyContinue | Select-Object -First 1
    if ($__2scLoadedModule) {
        $__2scLoadedFingerprint = $__2scLoadedModule.SessionState.PSVariable.GetValue('ProfileModuleFingerprint')
        $__2scModuleFile = Join-Path $__2scLoadedModule.ModuleBase 'CodexProfileFunctions.psm1'
        if ([System.IO.File]::Exists($__2scModuleFile)) {
            $__2scDiskInfo = Get-Item -LiteralPath $__2scModuleFile -ErrorAction SilentlyContinue
            if ($__2scDiskInfo) {
                $__2scDiskFingerprint = '{0}|{1}' -f $__2scDiskInfo.Length, $__2scDiskInfo.LastWriteTimeUtc.Ticks
                if ([string]$__2scLoadedFingerprint -and $__2scDiskFingerprint -ne [string]$__2scLoadedFingerprint) { $__2scNeedBootstrap = $true }
            }
        }
    }
}
if ($__2scNeedBootstrap) {
    if (-not (Test-Path -LiteralPath $__2scProfileModule -PathType Leaf)) {
        throw "2sc-generated script requires the Codex profile module: $__2scProfileModule"
    }
    Import-Module -Name $__2scProfileModule -Force -DisableNameChecking -ErrorAction Stop
    Initialize-CodexProfileFunctions
}
function Install-NvidDriverWithPnpUtilFallback {
        param([Parameter(Mandatory=$true)][string]$ExtractRoot,[Parameter(Mandatory=$true)][string]$GpuInstanceId)
        $displayRoot = Join-Path $ExtractRoot 'Display.Driver'
        $dev = [regex]::Match($GpuInstanceId, 'DEV_([0-9A-Fa-f]{4})').Groups[1].Value
        $subsys = [regex]::Match($GpuInstanceId, 'SUBSYS_([0-9A-Fa-f]{8})').Groups[1].Value
        if (-not $dev) { throw "Unable to resolve NVIDIA device id from $GpuInstanceId" }
        $infMatches = @()
        foreach ($inf in Get-ChildItem -Path $displayRoot -Filter '*.inf' -ErrorAction Stop) {
            $text = Get-Content -LiteralPath $inf.FullName -Raw
            $score = 0
            if ($subsys -and $text -match [regex]::Escape("DEV_$dev&SUBSYS_$subsys")) { $score += 100 }
            if ($text -match [regex]::Escape("DEV_$dev")) { $score += 10 }
            if ($inf.Name -ieq 'nv_dispi.inf') { $score += 5 }
            if ($score -gt 0) { $infMatches += [pscustomobject]@{ Path=$inf.FullName; Score=$score } }
        }
        $selected = $infMatches | Sort-Object -Property @{Expression='Score';Descending=$true}, @{Expression='Path';Descending=$false} | Select-Object -First 1
        if (-not $selected) { throw "No extracted NVIDIA display INF matched DEV_$dev under $displayRoot" }
        Write-Host ("  NVIDIA setup failed or did not activate the driver; falling back to pnputil with {0}" -f $selected.Path) -ForegroundColor DarkYellow
        $output = (& pnputil.exe /add-driver $selected.Path /install 2>&1 | Out-String).Trim()
        Write-Host ("  pnputil /add-driver exit: {0}" -f $LASTEXITCODE) -ForegroundColor Gray
        if ($output) { Write-Host ("  pnputil output: {0}" -f (($output -split "`r?`n") -join ' | ')) -ForegroundColor Gray }
        try { & pnputil.exe /restart-device $GpuInstanceId 2>&1 | Out-Null } catch {}
        Start-Sleep -Seconds 10
    }

if ($MyInvocation.InvocationName -ne '.') {
    & 'Install-NvidDriverWithPnpUtilFallback' @args
}
