# Generated by 2sc from function 'Invoke-NvidLastChanceRuntimeRepair' (2026-08-12 23:58:28).
# Self-bootstrap: load the profile environment when this script runs
# outside a profile session so it behaves exactly like the function it
# was copied from. The module is also force-re-imported when the copy
# loaded in this process is stale (psm1 changed on disk) so a long-
# running session never runs an outdated dispatcher.
$__2scProfileModule = 'C:\Users\micha\Documents\WindowsPowerShell\Modules\CodexProfileFunctions\CodexProfileFunctions.psd1'
$__2scNeedBootstrap = -not (Get-Command -Name 'Initialize-CodexProfileFunctions' -CommandType Function -ErrorAction SilentlyContinue)
if (-not $__2scNeedBootstrap) {
    $__2scLoadedModule = Get-Module -Name 'CodexProfileFunctions' -ErrorAction SilentlyContinue | Select-Object -First 1
    if ($__2scLoadedModule) {
        $__2scLoadedFingerprint = $__2scLoadedModule.SessionState.PSVariable.GetValue('ProfileModuleFingerprint')
        $__2scModuleFile = Join-Path $__2scLoadedModule.ModuleBase 'CodexProfileFunctions.psm1'
        if ([System.IO.File]::Exists($__2scModuleFile)) {
            $__2scDiskInfo = Get-Item -LiteralPath $__2scModuleFile -ErrorAction SilentlyContinue
            if ($__2scDiskInfo) {
                $__2scDiskFingerprint = '{0}|{1}' -f $__2scDiskInfo.Length, $__2scDiskInfo.LastWriteTimeUtc.Ticks
                if ([string]$__2scLoadedFingerprint -and $__2scDiskFingerprint -ne [string]$__2scLoadedFingerprint) { $__2scNeedBootstrap = $true }
            }
        }
    }
}
if ($__2scNeedBootstrap) {
    if (-not (Test-Path -LiteralPath $__2scProfileModule -PathType Leaf)) {
        throw "2sc-generated script requires the Codex profile module: $__2scProfileModule"
    }
    Import-Module -Name $__2scProfileModule -Force -DisableNameChecking -ErrorAction Stop
    Initialize-CodexProfileFunctions
}
function Invoke-NvidLastChanceRuntimeRepair {
        Write-NvidStep 'running last-chance no-reboot NVIDIA runtime repair: services, AppX, caches, protocol/runtime state'
        Stop-NvidAppProcesses
        foreach($svcName in @('NVDisplay.ContainerLocalSystem','NvContainerLocalSystem')) {
            try { Set-Service -Name $svcName -StartupType Automatic -ErrorAction SilentlyContinue } catch {}
            try { Restart-Service -Name $svcName -Force -ErrorAction SilentlyContinue; Start-Sleep -Seconds 3 } catch { try { Start-Service -Name $svcName -ErrorAction SilentlyContinue } catch {} }
            $svcObj = Get-Service -Name $svcName -ErrorAction SilentlyContinue
            if ($svcObj) { Write-NvidStep ("service {0} status {1}" -f $svcName,$svcObj.Status) }
        }
        foreach($cacheDir in @(
            'C:\Users\micha\AppData\Local\NVIDIA\DXCache',
            'C:\Users\micha\AppData\Local\NVIDIA\GLCache',
            'C:\Users\micha\AppData\Local\NVIDIA\ComputeCache',
            'C:\Users\micha\AppData\Local\NVIDIA Corporation\NVIDIA App\CefCache',
            'C:\Users\micha\AppData\Local\NVIDIA Corporation\NVIDIA App\GPUCache',
            'C:\Users\micha\AppData\Local\NVIDIA Corporation\NVIDIA App\DawnCache',
            'C:\Users\micha\AppData\Local\NVIDIA Corporation\NVIDIA App\UXD',
            'C:\Users\micha\AppData\Local\NVIDIA Corporation\NVIDIA App\NvBackend',
            'C:\ProgramData\NVIDIA Corporation\NVIDIA App\MessageBus'
        )) { Backup-And-ClearDirectory $cacheDir 'lastchance-cache' }
        try {
            $cpl = Get-AppxPackage -Name 'NVIDIACorp.NVIDIAControlPanel' -ErrorAction SilentlyContinue | Select-Object -First 1
            if ($cpl -and (Test-Path -LiteralPath (Join-Path $cpl.InstallLocation 'AppxManifest.xml'))) {
                Add-AppxPackage -DisableDevelopmentMode -Register (Join-Path $cpl.InstallLocation 'AppxManifest.xml') -ErrorAction SilentlyContinue
                Write-NvidStep ("re-registered NVIDIA Control Panel AppX {0}" -f $cpl.Version)
            }
        } catch { Write-Host ("[nvid] NVIDIA Control Panel AppX repair warning: {0}" -f $_.Exception.Message) -ForegroundColor Yellow }
        try {
            $nvProfile = 'C:\Program Files\NVIDIA Corporation\Control Panel Client\nvcplui.exe'
            $nvCplDll = 'C:\Windows\System32\nvcpl.dll'
            if (Test-Path -LiteralPath $nvCplDll) { & regsvr32.exe /s $nvCplDll 2>$null | Out-Null; Write-NvidStep 'refreshed NVIDIA Control Panel shell registration' }
            if (Test-Path -LiteralPath $nvProfile) { Start-Process -FilePath $nvProfile -ArgumentList '-forcepsem' -WindowStyle Minimized -ErrorAction SilentlyContinue | Out-Null }
        } catch { Write-Host ("[nvid] NVIDIA Control Panel registration warning: {0}" -f $_.Exception.Message) -ForegroundColor Yellow }
        try {
            $nvContainerExe = 'C:\Program Files\NVIDIA Corporation\NvContainer\x86_64\NvContainer.exe'
            if (Test-Path -LiteralPath $nvContainerExe -and -not (Get-Process NvContainer -ErrorAction SilentlyContinue)) { Start-Process -FilePath $nvContainerExe -WindowStyle Hidden -ErrorAction SilentlyContinue | Out-Null }
        } catch {}
        try {
            $baseKey = 'HKLM:\SOFTWARE\NVIDIA Corporation\Global\NVTweak'
            if (-not (Test-Path $baseKey)) { New-Item -Path $baseKey -Force | Out-Null }
            New-ItemProperty -Path $baseKey -Name 'NvCplEnableRotatePage' -PropertyType DWord -Value 1 -Force | Out-Null
            New-ItemProperty -Path $baseKey -Name 'NvCplThermalSettings' -PropertyType DWord -Value 1 -Force | Out-Null
        } catch {}
    }

if ($MyInvocation.InvocationName -ne '.') {
    & 'Invoke-NvidLastChanceRuntimeRepair' @args
}
