# Generated by 2sc from function 'Invoke-DKillFastForegroundPrune' (2026-08-13 00:00:01).
# Self-bootstrap: load the profile environment when this script runs
# outside a profile session so it behaves exactly like the function it
# was copied from. The module is also force-re-imported when the copy
# loaded in this process is stale (psm1 changed on disk) so a long-
# running session never runs an outdated dispatcher.
$__2scProfileModule = 'C:\Users\micha\Documents\WindowsPowerShell\Modules\CodexProfileFunctions\CodexProfileFunctions.psd1'
$__2scNeedBootstrap = -not (Get-Command -Name 'Initialize-CodexProfileFunctions' -CommandType Function -ErrorAction SilentlyContinue)
if (-not $__2scNeedBootstrap) {
    $__2scLoadedModule = Get-Module -Name 'CodexProfileFunctions' -ErrorAction SilentlyContinue | Select-Object -First 1
    if ($__2scLoadedModule) {
        $__2scLoadedFingerprint = $__2scLoadedModule.SessionState.PSVariable.GetValue('ProfileModuleFingerprint')
        $__2scModuleFile = Join-Path $__2scLoadedModule.ModuleBase 'CodexProfileFunctions.psm1'
        if ([System.IO.File]::Exists($__2scModuleFile)) {
            $__2scDiskInfo = Get-Item -LiteralPath $__2scModuleFile -ErrorAction SilentlyContinue
            if ($__2scDiskInfo) {
                $__2scDiskFingerprint = '{0}|{1}' -f $__2scDiskInfo.Length, $__2scDiskInfo.LastWriteTimeUtc.Ticks
                if ([string]$__2scLoadedFingerprint -and $__2scDiskFingerprint -ne [string]$__2scLoadedFingerprint) { $__2scNeedBootstrap = $true }
            }
        }
    }
}
if ($__2scNeedBootstrap) {
    if (-not (Test-Path -LiteralPath $__2scProfileModule -PathType Leaf)) {
        throw "2sc-generated script requires the Codex profile module: $__2scProfileModule"
    }
    Import-Module -Name $__2scProfileModule -Force -DisableNameChecking -ErrorAction Stop
    Initialize-CodexProfileFunctions
}
function Invoke-DKillFastForegroundPrune {
        param([string]$DockerExe)
        if([string]::IsNullOrWhiteSpace($DockerExe) -or -not (Test-Path -LiteralPath $DockerExe)){ return $false }
        if(-not (Test-DKillFastDockerReady -DockerExe $DockerExe -FinalProbe)){ return $false }
        $prunePlan = @(
            ,@('builder','prune','--all','--force')
            ,@('system','prune','--all','--volumes','--force')
        )
        $allOk = $true
        try {
            foreach($args in $prunePlan){
                $remaining = Get-DKillFastRemainingMilliseconds
                if($remaining -lt 2500){
                    Write-DKillFastLine 'foreground Docker prune budget reached; preserving readiness gate' Yellow
                    $allOk = $false
                    break
                }
                $budgetSeconds = [Math]::Max(1,[Math]::Min(4,[int][Math]::Floor(($remaining - 1200) / 1000)))
                Write-DKillFastLine ("foreground prune: docker {0} (budget={1}s)" -f ($args -join ' '),$budgetSeconds) DarkCyan
                $code = Invoke-DKillFastBoundedDocker -DockerExe $DockerExe -DockerArgs $args -Seconds $budgetSeconds
                if($null -eq $code -or [int]$code -ne 0){ $allOk = $false }
                if(-not (Test-DKillFastDockerReady -DockerExe $DockerExe -FinalProbe)){
                    Write-DKillFastLine 'Docker daemon not ready after prune command; readiness recovery will run before returning' Yellow
                    $allOk = $false
                    break
                }
            }
        } catch {
            Write-DKillFastLine ("foreground Docker prune failed: {0}" -f $_.Exception.Message) Yellow
            $allOk = $false
        }
        if($allOk){ Write-DKillFastLine 'foreground Docker prune completed before readiness return' Green }
        return [bool]$allOk
    }

if ($MyInvocation.InvocationName -ne '.') {
    & 'Invoke-DKillFastForegroundPrune' @args
}
