# Generated by 2sc from function 'Invoke-NvidNativeInstaller' (2026-08-13 00:09:40).
# Self-bootstrap: load the profile environment when this script runs
# outside a profile session so it behaves exactly like the function it
# was copied from. The module is also force-re-imported when the copy
# loaded in this process is stale (psm1 changed on disk) so a long-
# running session never runs an outdated dispatcher.
$__2scProfileModule = 'C:\Users\micha\Documents\WindowsPowerShell\Modules\CodexProfileFunctions\CodexProfileFunctions.psd1'
$__2scNeedBootstrap = -not (Get-Command -Name 'Initialize-CodexProfileFunctions' -CommandType Function -ErrorAction SilentlyContinue)
if (-not $__2scNeedBootstrap) {
    $__2scLoadedModule = Get-Module -Name 'CodexProfileFunctions' -ErrorAction SilentlyContinue | Select-Object -First 1
    if ($__2scLoadedModule) {
        $__2scLoadedFingerprint = $__2scLoadedModule.SessionState.PSVariable.GetValue('ProfileModuleFingerprint')
        $__2scModuleFile = Join-Path $__2scLoadedModule.ModuleBase 'CodexProfileFunctions.psm1'
        if ([System.IO.File]::Exists($__2scModuleFile)) {
            $__2scDiskInfo = Get-Item -LiteralPath $__2scModuleFile -ErrorAction SilentlyContinue
            if ($__2scDiskInfo) {
                $__2scDiskFingerprint = '{0}|{1}' -f $__2scDiskInfo.Length, $__2scDiskInfo.LastWriteTimeUtc.Ticks
                if ([string]$__2scLoadedFingerprint -and $__2scDiskFingerprint -ne [string]$__2scLoadedFingerprint) { $__2scNeedBootstrap = $true }
            }
        }
    }
}
if ($__2scNeedBootstrap) {
    if (-not (Test-Path -LiteralPath $__2scProfileModule -PathType Leaf)) {
        throw "2sc-generated script requires the Codex profile module: $__2scProfileModule"
    }
    Import-Module -Name $__2scProfileModule -Force -DisableNameChecking -ErrorAction Stop
    Initialize-CodexProfileFunctions
}
function Invoke-NvidNativeInstaller {
        param(
            [Parameter(Mandatory=$true)][string]$FilePath,
            [Parameter(Mandatory=$true)][string[]]$Arguments,
            [Parameter(Mandatory=$true)][string]$Name,
            [int[]]$AllowedExitCodes = @(0,3010)
        )
        Write-NvidStep ("starting {0}: {1} {2}" -f $Name,$FilePath,($Arguments -join ' '))
        $p = Start-Process -FilePath $FilePath -ArgumentList $Arguments -PassThru -WindowStyle Hidden
        $started = Get-Date
        while(-not $p.HasExited) {
            Start-Sleep -Seconds 15
            try { $p.Refresh() } catch {}
            $elapsed = [int]((Get-Date) - $started).TotalSeconds
            Write-NvidStep ("{0} still running after {1}s (pid {2})" -f $Name,$elapsed,$p.Id)
        }
        Write-NvidStep ("{0} exit {1}" -f $Name,$p.ExitCode)
        if ($AllowedExitCodes -notcontains [int]$p.ExitCode) { throw ("{0} failed with exit {1}" -f $Name,$p.ExitCode) }
        return [int]$p.ExitCode
    }

if ($MyInvocation.InvocationName -ne '.') {
    & 'Invoke-NvidNativeInstaller' @args
}
