# Generated by 2sc from function 'Invoke-GitlogGh' (2026-08-13 00:39:40).
# Self-bootstrap: load the profile environment when this script runs
# outside a profile session so it behaves exactly like the function it
# was copied from. The module is also force-re-imported when the copy
# loaded in this process is stale (psm1 changed on disk) so a long-
# running session never runs an outdated dispatcher.
$__2scProfileModule = 'C:\Users\micha\Documents\WindowsPowerShell\Modules\CodexProfileFunctions\CodexProfileFunctions.psd1'
$__2scNeedBootstrap = -not (Get-Command -Name 'Initialize-CodexProfileFunctions' -CommandType Function -ErrorAction SilentlyContinue)
if (-not $__2scNeedBootstrap) {
    $__2scLoadedModule = Get-Module -Name 'CodexProfileFunctions' -ErrorAction SilentlyContinue | Select-Object -First 1
    if ($__2scLoadedModule) {
        $__2scLoadedFingerprint = $__2scLoadedModule.SessionState.PSVariable.GetValue('ProfileModuleFingerprint')
        $__2scModuleFile = Join-Path $__2scLoadedModule.ModuleBase 'CodexProfileFunctions.psm1'
        if ([System.IO.File]::Exists($__2scModuleFile)) {
            $__2scDiskInfo = Get-Item -LiteralPath $__2scModuleFile -ErrorAction SilentlyContinue
            if ($__2scDiskInfo) {
                $__2scDiskFingerprint = '{0}|{1}' -f $__2scDiskInfo.Length, $__2scDiskInfo.LastWriteTimeUtc.Ticks
                if ([string]$__2scLoadedFingerprint -and $__2scDiskFingerprint -ne [string]$__2scLoadedFingerprint) { $__2scNeedBootstrap = $true }
            }
        }
    }
}
if ($__2scNeedBootstrap) {
    if (-not (Test-Path -LiteralPath $__2scProfileModule -PathType Leaf)) {
        throw "2sc-generated script requires the Codex profile module: $__2scProfileModule"
    }
    Import-Module -Name $__2scProfileModule -Force -DisableNameChecking -ErrorAction Stop
    Initialize-CodexProfileFunctions
}
function Invoke-GitlogGh {
    param(
        [string[]]$ArgumentList,
        [string]$TokenForProcess,
        [string]$StandardInputText
    )

    $ghCommand = Get-Command gh -ErrorAction SilentlyContinue
    if (-not $ghCommand) {
        return [pscustomobject]@{ ExitCode = 127; Output = 'gh executable not found' }
    }

    $quotedArguments = @()
    foreach ($argument in $ArgumentList) {
        if ($argument -match '^[A-Za-z0-9._=:/-]+$') {
            $quotedArguments += $argument
        } else {
            $quotedArguments += ('"{0}"' -f ($argument -replace '"', '\"'))
        }
    }

    $psi = New-Object System.Diagnostics.ProcessStartInfo
    $psi.FileName = $ghCommand.Source
    $psi.Arguments = ($quotedArguments -join ' ')
    $psi.UseShellExecute = $false
    $psi.RedirectStandardInput = [bool]$StandardInputText
    $psi.RedirectStandardOutput = $true
    $psi.RedirectStandardError = $true
    $psi.CreateNoWindow = $true
    if ($TokenForProcess) {
        $psi.EnvironmentVariables['GH_TOKEN'] = $TokenForProcess
        $psi.EnvironmentVariables['GITHUB_TOKEN'] = $TokenForProcess
    }

    $process = New-Object System.Diagnostics.Process
    $process.StartInfo = $psi
    [void]$process.Start()
    if ($StandardInputText) {
        $process.StandardInput.Write($StandardInputText)
        $process.StandardInput.Close()
    }
    $stdout = $process.StandardOutput.ReadToEnd()
    $stderr = $process.StandardError.ReadToEnd()
    $process.WaitForExit()
    $output = (($stdout + "`n" + $stderr).Trim())
    return [pscustomobject]@{ ExitCode = $process.ExitCode; Output = $output }
}

if ($MyInvocation.InvocationName -ne '.') {
    & 'Invoke-GitlogGh' @args
}
