# Generated by 2sc from function 'Invoke-UpgraderStep' (2026-08-13 00:02:29).
# Self-bootstrap: load the profile environment when this script runs
# outside a profile session so it behaves exactly like the function it
# was copied from. The module is also force-re-imported when the copy
# loaded in this process is stale (psm1 changed on disk) so a long-
# running session never runs an outdated dispatcher.
$__2scProfileModule = 'C:\Users\micha\Documents\WindowsPowerShell\Modules\CodexProfileFunctions\CodexProfileFunctions.psd1'
$__2scNeedBootstrap = -not (Get-Command -Name 'Initialize-CodexProfileFunctions' -CommandType Function -ErrorAction SilentlyContinue)
if (-not $__2scNeedBootstrap) {
    $__2scLoadedModule = Get-Module -Name 'CodexProfileFunctions' -ErrorAction SilentlyContinue | Select-Object -First 1
    if ($__2scLoadedModule) {
        $__2scLoadedFingerprint = $__2scLoadedModule.SessionState.PSVariable.GetValue('ProfileModuleFingerprint')
        $__2scModuleFile = Join-Path $__2scLoadedModule.ModuleBase 'CodexProfileFunctions.psm1'
        if ([System.IO.File]::Exists($__2scModuleFile)) {
            $__2scDiskInfo = Get-Item -LiteralPath $__2scModuleFile -ErrorAction SilentlyContinue
            if ($__2scDiskInfo) {
                $__2scDiskFingerprint = '{0}|{1}' -f $__2scDiskInfo.Length, $__2scDiskInfo.LastWriteTimeUtc.Ticks
                if ([string]$__2scLoadedFingerprint -and $__2scDiskFingerprint -ne [string]$__2scLoadedFingerprint) { $__2scNeedBootstrap = $true }
            }
        }
    }
}
if ($__2scNeedBootstrap) {
    if (-not (Test-Path -LiteralPath $__2scProfileModule -PathType Leaf)) {
        throw "2sc-generated script requires the Codex profile module: $__2scProfileModule"
    }
    Import-Module -Name $__2scProfileModule -Force -DisableNameChecking -ErrorAction Stop
    Initialize-CodexProfileFunctions
}
function Invoke-UpgraderStep {
        param(
            [string]$Name,
            [scriptblock]$Action,
            [int]$Retries = 3,
            [int]$SleepSeconds = 2
        )

        for ($i = 1; $i -le $Retries; $i++) {
            try {
                $global:LASTEXITCODE = $null
                & $Action
                if ($LASTEXITCODE -eq 0 -or $null -eq $LASTEXITCODE) {
                    return $true
                }
            } catch {
                if ($i -eq $Retries) {
                    Write-Warning ("upgrader step failed [{0}]: {1}" -f $Name, $_.Exception.Message)
                }
            }

            if ($i -lt $Retries) {
                Start-Sleep -Seconds $SleepSeconds
            }
        }

        return $false
    }

if ($MyInvocation.InvocationName -ne '.') {
    & 'Invoke-UpgraderStep' @args
}
