# Generated by 2sc from function 'Invoke-FastTransferRobocopy' (2026-08-13 00:38:48).
# Self-bootstrap: load the profile environment when this script runs
# outside a profile session so it behaves exactly like the function it
# was copied from. The module is also force-re-imported when the copy
# loaded in this process is stale (psm1 changed on disk) so a long-
# running session never runs an outdated dispatcher.
$__2scProfileModule = 'C:\Users\micha\Documents\WindowsPowerShell\Modules\CodexProfileFunctions\CodexProfileFunctions.psd1'
$__2scNeedBootstrap = -not (Get-Command -Name 'Initialize-CodexProfileFunctions' -CommandType Function -ErrorAction SilentlyContinue)
if (-not $__2scNeedBootstrap) {
    $__2scLoadedModule = Get-Module -Name 'CodexProfileFunctions' -ErrorAction SilentlyContinue | Select-Object -First 1
    if ($__2scLoadedModule) {
        $__2scLoadedFingerprint = $__2scLoadedModule.SessionState.PSVariable.GetValue('ProfileModuleFingerprint')
        $__2scModuleFile = Join-Path $__2scLoadedModule.ModuleBase 'CodexProfileFunctions.psm1'
        if ([System.IO.File]::Exists($__2scModuleFile)) {
            $__2scDiskInfo = Get-Item -LiteralPath $__2scModuleFile -ErrorAction SilentlyContinue
            if ($__2scDiskInfo) {
                $__2scDiskFingerprint = '{0}|{1}' -f $__2scDiskInfo.Length, $__2scDiskInfo.LastWriteTimeUtc.Ticks
                if ([string]$__2scLoadedFingerprint -and $__2scDiskFingerprint -ne [string]$__2scLoadedFingerprint) { $__2scNeedBootstrap = $true }
            }
        }
    }
}
if ($__2scNeedBootstrap) {
    if (-not (Test-Path -LiteralPath $__2scProfileModule -PathType Leaf)) {
        throw "2sc-generated script requires the Codex profile module: $__2scProfileModule"
    }
    Import-Module -Name $__2scProfileModule -Force -DisableNameChecking -ErrorAction Stop
    Initialize-CodexProfileFunctions
}
function Invoke-FastTransferRobocopy {
    param(
        [Parameter(Mandatory = $true)]
        [string]$SourcePath,

        [Parameter(Mandatory = $true)]
        [string]$DestinationRoot,

        [Parameter(Mandatory = $true)]
        [ValidateSet('Copy', 'Move')]
        [string]$Mode
    )

    $robocopyPath = Join-Path $env:SystemRoot 'System32\robocopy.exe'
    if (-not (Test-Path -LiteralPath $robocopyPath -PathType Leaf)) {
        throw "robocopy.exe not found at $robocopyPath"
    }

    $item = Get-Item -LiteralPath $SourcePath -Force
    $targetPath = Join-Path $DestinationRoot $item.Name
    $threadCount = [Math]::Min(128, [Math]::Max(32, [Environment]::ProcessorCount * 8))

    function New-RobocopyArgumentLine {
        param([string[]]$Values)

        $quotedValues = foreach ($value in $Values) {
            if ($null -eq $value) { continue }
            if ($value -match '[\s"]') {
                '"' + $value.Replace('"', '\"') + '"'
            } else {
                $value
            }
        }
        return [string]::Join(' ', $quotedValues)
    }

    if ($item.PSIsContainer) {
        New-Item -ItemType Directory -Path $targetPath -Force | Out-Null
        $arguments = @(
            $SourcePath,
            $targetPath,
            '/E',
            '/R:0',
            '/W:0',
            '/XJ',
            ('/MT:{0}' -f $threadCount),
            '/DCOPY:DAT',
            '/COPY:DAT'
        )
        if ($Mode -eq 'Move') {
            $arguments += '/MOVE'
        }

        $argumentLine = New-RobocopyArgumentLine -Values $arguments
        $process = Start-Process -FilePath $robocopyPath -ArgumentList $argumentLine -Wait -NoNewWindow -PassThru
        $exitCode = $process.ExitCode
        if ($exitCode -gt 7) {
            throw "robocopy directory $Mode failed with exit code $exitCode for '$SourcePath'"
        }
        return
    }

    $sourceParent = Split-Path -Parent $SourcePath
    $filter = $item.Name
    $arguments = @(
        $sourceParent,
        $DestinationRoot,
        $filter,
        '/R:0',
        '/W:0',
        ('/MT:{0}' -f $threadCount),
        '/COPY:DAT'
    )
    if ($Mode -eq 'Move') {
        $arguments += '/MOV'
    }

    $argumentLine = New-RobocopyArgumentLine -Values $arguments
    $process = Start-Process -FilePath $robocopyPath -ArgumentList $argumentLine -Wait -NoNewWindow -PassThru
    $exitCode = $process.ExitCode
    if ($exitCode -gt 7) {
        throw "robocopy file $Mode failed with exit code $exitCode for '$SourcePath'"
    }
}

if ($MyInvocation.InvocationName -ne '.') {
    & 'Invoke-FastTransferRobocopy' @args
}
