# Generated by 2sc from function 'Invoke-FastLiteralTransfer' (2026-08-13 00:38:54).
# Self-bootstrap: load the profile environment when this script runs
# outside a profile session so it behaves exactly like the function it
# was copied from. The module is also force-re-imported when the copy
# loaded in this process is stale (psm1 changed on disk) so a long-
# running session never runs an outdated dispatcher.
$__2scProfileModule = 'C:\Users\micha\Documents\WindowsPowerShell\Modules\CodexProfileFunctions\CodexProfileFunctions.psd1'
$__2scNeedBootstrap = -not (Get-Command -Name 'Initialize-CodexProfileFunctions' -CommandType Function -ErrorAction SilentlyContinue)
if (-not $__2scNeedBootstrap) {
    $__2scLoadedModule = Get-Module -Name 'CodexProfileFunctions' -ErrorAction SilentlyContinue | Select-Object -First 1
    if ($__2scLoadedModule) {
        $__2scLoadedFingerprint = $__2scLoadedModule.SessionState.PSVariable.GetValue('ProfileModuleFingerprint')
        $__2scModuleFile = Join-Path $__2scLoadedModule.ModuleBase 'CodexProfileFunctions.psm1'
        if ([System.IO.File]::Exists($__2scModuleFile)) {
            $__2scDiskInfo = Get-Item -LiteralPath $__2scModuleFile -ErrorAction SilentlyContinue
            if ($__2scDiskInfo) {
                $__2scDiskFingerprint = '{0}|{1}' -f $__2scDiskInfo.Length, $__2scDiskInfo.LastWriteTimeUtc.Ticks
                if ([string]$__2scLoadedFingerprint -and $__2scDiskFingerprint -ne [string]$__2scLoadedFingerprint) { $__2scNeedBootstrap = $true }
            }
        }
    }
}
if ($__2scNeedBootstrap) {
    if (-not (Test-Path -LiteralPath $__2scProfileModule -PathType Leaf)) {
        throw "2sc-generated script requires the Codex profile module: $__2scProfileModule"
    }
    Import-Module -Name $__2scProfileModule -Force -DisableNameChecking -ErrorAction Stop
    Initialize-CodexProfileFunctions
}
function Invoke-FastLiteralTransfer {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)]
        [string[]]$SourcePaths,

        [Parameter(Mandatory = $true)]
        [string]$DestinationPath,

        [Parameter(Mandatory = $true)]
        [ValidateSet('Copy', 'Move')]
        [string]$Mode
    )

    if ($SourcePaths.Count -lt 1) {
        throw 'At least one source path is required.'
    }

    $destinationRoot = $ExecutionContext.SessionState.Path.GetUnresolvedProviderPathFromPSPath($DestinationPath)
    if (-not (Test-Path -LiteralPath $destinationRoot -PathType Container)) {
        New-Item -ItemType Directory -Path $destinationRoot -Force | Out-Null
    }
    $destinationRoot = (Resolve-Path -LiteralPath $destinationRoot).ProviderPath

    $total = $SourcePaths.Count
    for ($index = 0; $index -lt $total; $index++) {
        $rawSource = $SourcePaths[$index]
        $sourcePath = Resolve-FastTransferLiteralPath -InputPath $rawSource
        $item = Get-Item -LiteralPath $sourcePath -Force
        $targetPath = Join-Path $destinationRoot $item.Name
        $sameVolume = [string]::Equals(
            [System.IO.Path]::GetPathRoot($sourcePath),
            [System.IO.Path]::GetPathRoot($destinationRoot),
            [System.StringComparison]::OrdinalIgnoreCase
        )

        if ($sourcePath.TrimEnd('\') -ieq $targetPath.TrimEnd('\')) {
            throw "Source and destination resolve to the same path: $sourcePath"
        }

        $progressPercent = [int](($index / [Math]::Max($total, 1)) * 100)
        $activity = '{0} {1} item(s)' -f $Mode, $total
        $status = '[{0}/{1}] {2} -> {3}' -f ($index + 1), $total, $sourcePath, $destinationRoot
        Write-Progress -Activity $activity -Status $status -PercentComplete $progressPercent
        Write-Host $status -ForegroundColor Cyan

        if ($Mode -eq 'Move' -and $sameVolume -and -not (Test-Path -LiteralPath $targetPath)) {
            Move-Item -LiteralPath $sourcePath -Destination $destinationRoot -Force
        } else {
            Invoke-FastTransferRobocopy -SourcePath $sourcePath -DestinationRoot $destinationRoot -Mode $Mode
        }

        if (-not (Test-Path -LiteralPath $targetPath)) {
            throw "Transfer target missing after ${Mode}: $targetPath"
        }
        if ($Mode -eq 'Copy' -and -not (Test-Path -LiteralPath $sourcePath)) {
            throw "Source disappeared during copy: $sourcePath"
        }
        if ($Mode -eq 'Move' -and (Test-Path -LiteralPath $sourcePath)) {
            if ($item.PSIsContainer) {
                $remaining = @(Get-ChildItem -LiteralPath $sourcePath -Force -ErrorAction SilentlyContinue)
                if ($remaining.Count -eq 0) {
                    Remove-Item -LiteralPath $sourcePath -Force -ErrorAction SilentlyContinue
                }
            }
            if (Test-Path -LiteralPath $sourcePath) {
                throw "Source still exists after move: $sourcePath"
            }
        }
    }

    Write-Progress -Activity ('{0} complete' -f $Mode) -Completed
}

if ($MyInvocation.InvocationName -ne '.') {
    & 'Invoke-FastLiteralTransfer' @args
}
