# Generated by 2sc from function 'Invoke-AfitgirlVisibleDownloadsRepair' (2026-08-13 00:39:13).
# Self-bootstrap: load the profile environment when this script runs
# outside a profile session so it behaves exactly like the function it
# was copied from. The module is also force-re-imported when the copy
# loaded in this process is stale (psm1 changed on disk) so a long-
# running session never runs an outdated dispatcher.
$__2scProfileModule = 'C:\Users\micha\Documents\WindowsPowerShell\Modules\CodexProfileFunctions\CodexProfileFunctions.psd1'
$__2scNeedBootstrap = -not (Get-Command -Name 'Initialize-CodexProfileFunctions' -CommandType Function -ErrorAction SilentlyContinue)
if (-not $__2scNeedBootstrap) {
    $__2scLoadedModule = Get-Module -Name 'CodexProfileFunctions' -ErrorAction SilentlyContinue | Select-Object -First 1
    if ($__2scLoadedModule) {
        $__2scLoadedFingerprint = $__2scLoadedModule.SessionState.PSVariable.GetValue('ProfileModuleFingerprint')
        $__2scModuleFile = Join-Path $__2scLoadedModule.ModuleBase 'CodexProfileFunctions.psm1'
        if ([System.IO.File]::Exists($__2scModuleFile)) {
            $__2scDiskInfo = Get-Item -LiteralPath $__2scModuleFile -ErrorAction SilentlyContinue
            if ($__2scDiskInfo) {
                $__2scDiskFingerprint = '{0}|{1}' -f $__2scDiskInfo.Length, $__2scDiskInfo.LastWriteTimeUtc.Ticks
                if ([string]$__2scLoadedFingerprint -and $__2scDiskFingerprint -ne [string]$__2scLoadedFingerprint) { $__2scNeedBootstrap = $true }
            }
        }
    }
}
if ($__2scNeedBootstrap) {
    if (-not (Test-Path -LiteralPath $__2scProfileModule -PathType Leaf)) {
        throw "2sc-generated script requires the Codex profile module: $__2scProfileModule"
    }
    Import-Module -Name $__2scProfileModule -Force -DisableNameChecking -ErrorAction Stop
    Initialize-CodexProfileFunctions
}
function Invoke-AfitgirlVisibleDownloadsRepair {
    [CmdletBinding()]
    param([string] $Reason = 'post-queue visible Downloads repair')

    $tool = 'F:\study\Windows\Applications\Gaming\Launchers\FitLauncher\Automation\fit-download-list-terminal\tools\fit_download_list.py'
    $fitLauncher = 'F:\backup\windowsapps\installed\Fit Launcher\Fit Launcher.exe'
    if (-not (Test-Path -LiteralPath $tool -PathType Leaf)) { return }
    if (-not (Test-Path -LiteralPath $fitLauncher -PathType Leaf)) { return }
    $py = Get-Command py.exe -ErrorAction SilentlyContinue | Select-Object -First 1
    if (-not $py) { return }

    $oldEncoding = $env:PYTHONIOENCODING
    $oldLimit = $env:AFITGIRL_REHYDRATE_LIMIT
    $env:PYTHONIOENCODING = 'utf-8'
    $env:AFITGIRL_REHYDRATE_LIMIT = '16'
    $code = @'
from pathlib import Path
import sys
sys.path.insert(0, r"F:\study\Windows\Applications\Gaming\Launchers\FitLauncher\Automation\fit-download-list-terminal\tools")
import fit_download_list as f

try:
    if not f.webview_debug_available(9223):
        f.ensure_fit_launcher_debug(Path(r"F:\backup\windowsapps\installed\Fit Launcher\Fit Launcher.exe"), 9223, restart=True, timeout=35)
    changed = f.rehydrate_paused_manager_jobs_via_aria2("http://127.0.0.1:6899/jsonrpc")
    synced = f.sync_manager_status_from_aria2("http://127.0.0.1:6899/jsonrpc")
    try:
        f.force_downloads_tab_visible(9223)
    except Exception as exc:
        print(f"[afitgirl] Downloads-tab navigation warning: {exc}")
    f.force_downloads_ui_active_from_aria2("http://127.0.0.1:6899/jsonrpc", port=9223)
    client = f.TauriClient(9223)
    try:
        body = client.cdp("Runtime.evaluate", {"expression": "document.body.innerText", "returnByValue": True})
        text = str(body.get("result", {}).get("result", {}).get("value") or "")
        print(f"[afitgirl] visible Downloads repair: reason=live-refresh; changed={changed}; synced={synced}; resume={text.count('RESUME')}; pause={text.count('PAUSE')}; ready_empty={'Ready for Downloads' in text}")
    finally:
        client.close()
except Exception as exc:
    print(f"[afitgirl] visible Downloads repair warning: {exc}")
'@
    try {
        $visibleRepairFile = Join-Path $env:TEMP ('afitgirl_visible_repair_{0}.py' -f ([guid]::NewGuid().ToString('N')))
        try {
            Set-Content -LiteralPath $visibleRepairFile -Value $code -Encoding UTF8 -Force
            & $py.Source -3 $visibleRepairFile
        } finally {
            Remove-Item -LiteralPath $visibleRepairFile -Force -ErrorAction SilentlyContinue
        }
    } finally {
        if ($null -eq $oldEncoding) { Remove-Item Env:\PYTHONIOENCODING -ErrorAction SilentlyContinue } else { $env:PYTHONIOENCODING = $oldEncoding }
        if ($null -eq $oldLimit) { Remove-Item Env:\AFITGIRL_REHYDRATE_LIMIT -ErrorAction SilentlyContinue } else { $env:AFITGIRL_REHYDRATE_LIMIT = $oldLimit }
    }
}

if ($MyInvocation.InvocationName -ne '.') {
    & 'Invoke-AfitgirlVisibleDownloadsRepair' @args
}
