# Generated by 2sc from function 'Invoke-CleancNativeLocal' (2026-08-13 00:07:44).
# Self-bootstrap: load the profile environment when this script runs
# outside a profile session so it behaves exactly like the function it
# was copied from. The module is also force-re-imported when the copy
# loaded in this process is stale (psm1 changed on disk) so a long-
# running session never runs an outdated dispatcher.
$__2scProfileModule = 'C:\Users\micha\Documents\WindowsPowerShell\Modules\CodexProfileFunctions\CodexProfileFunctions.psd1'
$__2scNeedBootstrap = -not (Get-Command -Name 'Initialize-CodexProfileFunctions' -CommandType Function -ErrorAction SilentlyContinue)
if (-not $__2scNeedBootstrap) {
    $__2scLoadedModule = Get-Module -Name 'CodexProfileFunctions' -ErrorAction SilentlyContinue | Select-Object -First 1
    if ($__2scLoadedModule) {
        $__2scLoadedFingerprint = $__2scLoadedModule.SessionState.PSVariable.GetValue('ProfileModuleFingerprint')
        $__2scModuleFile = Join-Path $__2scLoadedModule.ModuleBase 'CodexProfileFunctions.psm1'
        if ([System.IO.File]::Exists($__2scModuleFile)) {
            $__2scDiskInfo = Get-Item -LiteralPath $__2scModuleFile -ErrorAction SilentlyContinue
            if ($__2scDiskInfo) {
                $__2scDiskFingerprint = '{0}|{1}' -f $__2scDiskInfo.Length, $__2scDiskInfo.LastWriteTimeUtc.Ticks
                if ([string]$__2scLoadedFingerprint -and $__2scDiskFingerprint -ne [string]$__2scLoadedFingerprint) { $__2scNeedBootstrap = $true }
            }
        }
    }
}
if ($__2scNeedBootstrap) {
    if (-not (Test-Path -LiteralPath $__2scProfileModule -PathType Leaf)) {
        throw "2sc-generated script requires the Codex profile module: $__2scProfileModule"
    }
    Import-Module -Name $__2scProfileModule -Force -DisableNameChecking -ErrorAction Stop
    Initialize-CodexProfileFunctions
}
function Invoke-CleancNativeLocal {
    [CmdletBinding()]
    param([Parameter(Mandatory = $true)][string]$CommandLine)

    if ([string]::IsNullOrWhiteSpace($CommandLine)) {
        throw 'cleanc native command line is empty.'
    }

    Write-Host ("CLEANC_PROGRESS stage=native-command command={0}" -f $CommandLine) -ForegroundColor DarkCyan
    $output = & $env:ComSpec /d /c $CommandLine 2>&1
    $exitCode = $LASTEXITCODE
    if ($output) {
        $output | ForEach-Object { Write-Host ("CLEANC_NATIVE_OUTPUT {0}" -f $_) }
    }
    if ($exitCode -ne 0) {
        $message = "CLEANC_NATIVE_FAIL exit_code=$exitCode command=$CommandLine"
        Write-Host $message -ForegroundColor Yellow
        throw $message
    }

    Write-Host ("CLEANC_NATIVE_OK command={0}" -f $CommandLine) -ForegroundColor Green
    return $true
}

if ($MyInvocation.InvocationName -ne '.') {
    & 'Invoke-CleancNativeLocal' @args
}
