# Generated by 2sc from function 'Invoke-MmmenuCmdProgress' (2026-08-13 00:05:43).
# Self-bootstrap: load the profile environment when this script runs
# outside a profile session so it behaves exactly like the function it
# was copied from. The module is also force-re-imported when the copy
# loaded in this process is stale (psm1 changed on disk) so a long-
# running session never runs an outdated dispatcher.
$__2scProfileModule = 'C:\Users\micha\Documents\WindowsPowerShell\Modules\CodexProfileFunctions\CodexProfileFunctions.psd1'
$__2scNeedBootstrap = -not (Get-Command -Name 'Initialize-CodexProfileFunctions' -CommandType Function -ErrorAction SilentlyContinue)
if (-not $__2scNeedBootstrap) {
    $__2scLoadedModule = Get-Module -Name 'CodexProfileFunctions' -ErrorAction SilentlyContinue | Select-Object -First 1
    if ($__2scLoadedModule) {
        $__2scLoadedFingerprint = $__2scLoadedModule.SessionState.PSVariable.GetValue('ProfileModuleFingerprint')
        $__2scModuleFile = Join-Path $__2scLoadedModule.ModuleBase 'CodexProfileFunctions.psm1'
        if ([System.IO.File]::Exists($__2scModuleFile)) {
            $__2scDiskInfo = Get-Item -LiteralPath $__2scModuleFile -ErrorAction SilentlyContinue
            if ($__2scDiskInfo) {
                $__2scDiskFingerprint = '{0}|{1}' -f $__2scDiskInfo.Length, $__2scDiskInfo.LastWriteTimeUtc.Ticks
                if ([string]$__2scLoadedFingerprint -and $__2scDiskFingerprint -ne [string]$__2scLoadedFingerprint) { $__2scNeedBootstrap = $true }
            }
        }
    }
}
if ($__2scNeedBootstrap) {
    if (-not (Test-Path -LiteralPath $__2scProfileModule -PathType Leaf)) {
        throw "2sc-generated script requires the Codex profile module: $__2scProfileModule"
    }
    Import-Module -Name $__2scProfileModule -Force -DisableNameChecking -ErrorAction Stop
    Initialize-CodexProfileFunctions
}
function Invoke-MmmenuCmdProgress {
        param([Parameter(Mandatory=$true)][string]$Label,[Parameter(Mandatory=$true)][string]$CommandLine,[int]$HeartbeatSeconds=1,[switch]$QuietOutput)
        $runId=[Guid]::NewGuid().ToString('N'); $outFile=Join-Path $progressRoot "$runId.out.log"; $errFile=Join-Path $progressRoot "$runId.err.log"; $exitFile=Join-Path $progressRoot "$runId.exit"
        $started=Get-Date; Write-Host "[mmmenu][docker:$Label] START $(Get-Date -Format 'HH:mm:ss')" -ForegroundColor Cyan
        Push-Location $env:TEMP
        try {
            $wrappedCommand='('+$CommandLine+') & echo !ERRORLEVEL!>'+(Quote-MmmenuCmdArg $exitFile)+' & exit /b !ERRORLEVEL!'
            $p=Start-Process -FilePath $cmdExe -ArgumentList @('/v:on','/d','/s','/c',$wrappedCommand) -RedirectStandardOutput $outFile -RedirectStandardError $errFile -WindowStyle Hidden -PassThru
            $outOffset=[int64]0; $errOffset=[int64]0; $tick=0
            while(-not $p.HasExited){
                Start-Sleep -Seconds $HeartbeatSeconds; $tick++
                if(-not $QuietOutput){ Write-MmmenuNewLogBytes -File $outFile -Offset ([ref]$outOffset); Write-MmmenuNewLogBytes -File $errFile -Offset ([ref]$errOffset) }
                $elapsed=[int][Math]::Floor(((Get-Date)-$started).TotalSeconds)
                Write-MmmenuRealProgressLine -Label $Label -Elapsed $elapsed -ProcessId $p.Id -Tick $tick
            }
            $p.WaitForExit(); $p.Refresh()
            if(-not $QuietOutput){ Write-MmmenuNewLogBytes -File $outFile -Offset ([ref]$outOffset); Write-MmmenuNewLogBytes -File $errFile -Offset ([ref]$errOffset) }
            $code=$null
            if(Test-Path -LiteralPath $exitFile -PathType Leaf){ $exitRaw=Get-Content -LiteralPath $exitFile -Raw -ErrorAction SilentlyContinue; if(-not [string]::IsNullOrWhiteSpace($exitRaw)){ $parsedExit=0; if([int]::TryParse($exitRaw.Trim(),[ref]$parsedExit)){ $code=$parsedExit } } }
            if($null -eq $code){ $code=[int]$p.ExitCode }
            $elapsedFinal=[int][Math]::Ceiling(((Get-Date)-$started).TotalSeconds)
            Write-Host ("[mmmenu][docker:{0}] EXIT code={1} elapsed={2}s" -f $Label,$code,$elapsedFinal) -ForegroundColor Cyan
            return [int]$code
        } finally { Pop-Location; Remove-Item -LiteralPath $outFile,$errFile,$exitFile -Force -ErrorAction SilentlyContinue }
    }

if ($MyInvocation.InvocationName -ne '.') {
    & 'Invoke-MmmenuCmdProgress' @args
}
