# Generated by 2sc from function 'Invoke-AfitgirlPythonProcess' (2026-08-13 00:40:14).
# Self-bootstrap: load the profile environment when this script runs
# outside a profile session so it behaves exactly like the function it
# was copied from. The module is also force-re-imported when the copy
# loaded in this process is stale (psm1 changed on disk) so a long-
# running session never runs an outdated dispatcher.
$__2scProfileModule = 'C:\Users\micha\Documents\WindowsPowerShell\Modules\CodexProfileFunctions\CodexProfileFunctions.psd1'
$__2scNeedBootstrap = -not (Get-Command -Name 'Initialize-CodexProfileFunctions' -CommandType Function -ErrorAction SilentlyContinue)
if (-not $__2scNeedBootstrap) {
    $__2scLoadedModule = Get-Module -Name 'CodexProfileFunctions' -ErrorAction SilentlyContinue | Select-Object -First 1
    if ($__2scLoadedModule) {
        $__2scLoadedFingerprint = $__2scLoadedModule.SessionState.PSVariable.GetValue('ProfileModuleFingerprint')
        $__2scModuleFile = Join-Path $__2scLoadedModule.ModuleBase 'CodexProfileFunctions.psm1'
        if ([System.IO.File]::Exists($__2scModuleFile)) {
            $__2scDiskInfo = Get-Item -LiteralPath $__2scModuleFile -ErrorAction SilentlyContinue
            if ($__2scDiskInfo) {
                $__2scDiskFingerprint = '{0}|{1}' -f $__2scDiskInfo.Length, $__2scDiskInfo.LastWriteTimeUtc.Ticks
                if ([string]$__2scLoadedFingerprint -and $__2scDiskFingerprint -ne [string]$__2scLoadedFingerprint) { $__2scNeedBootstrap = $true }
            }
        }
    }
}
if ($__2scNeedBootstrap) {
    if (-not (Test-Path -LiteralPath $__2scProfileModule -PathType Leaf)) {
        throw "2sc-generated script requires the Codex profile module: $__2scProfileModule"
    }
    Import-Module -Name $__2scProfileModule -Force -DisableNameChecking -ErrorAction Stop
    Initialize-CodexProfileFunctions
}
function Invoke-AfitgirlPythonProcess {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory=$true)][string] $FilePath,
        [Parameter(Mandatory=$true)][string[]] $Arguments,
        [Parameter(Mandatory=$true)][string] $WorkingDirectory,
        [int] $TimeoutSeconds = 900
    )

    $outFile = Join-Path $env:TEMP ("afitgirl_stdout_{0}.log" -f ([guid]::NewGuid().ToString('N')))
    $errFile = Join-Path $env:TEMP ("afitgirl_stderr_{0}.log" -f ([guid]::NewGuid().ToString('N')))
    $argText = (($Arguments | ForEach-Object { ConvertTo-AfitgirlCommandLineArgument $_ }) -join ' ')
    $proc = Start-Process -FilePath $FilePath -ArgumentList $argText -WorkingDirectory $WorkingDirectory -NoNewWindow -RedirectStandardOutput $outFile -RedirectStandardError $errFile -PassThru
    try {
        if (-not $proc.WaitForExit($TimeoutSeconds * 1000)) {
            try { Stop-Process -Id $proc.Id -Force -ErrorAction SilentlyContinue } catch {}
            if (Test-Path -LiteralPath $outFile) { Get-Content -LiteralPath $outFile -ErrorAction SilentlyContinue | ForEach-Object { Write-Host $_ } }
            if (Test-Path -LiteralPath $errFile) { Get-Content -LiteralPath $errFile -ErrorAction SilentlyContinue | ForEach-Object { Write-Host $_ } }
            throw "afitgirl queue command timed out after $TimeoutSeconds seconds; returned control to PowerShell and reran speed/auto-install repair."
        }
        $stdout = if (Test-Path -LiteralPath $outFile) { Get-Content -LiteralPath $outFile -ErrorAction SilentlyContinue } else { @() }
        $stderr = if (Test-Path -LiteralPath $errFile) { Get-Content -LiteralPath $errFile -ErrorAction SilentlyContinue } else { @() }
        $stdout | ForEach-Object { Write-Host $_ }
        $stderr | ForEach-Object { Write-Host $_ }
        $code = [int]$proc.ExitCode
        $combined = (($stdout + $stderr) -join "`n")
        if ($code -eq 0 -and ($combined -match 'fit_download_list\.py: error:|Traceback|SyntaxError|RuntimeError|failed with exit code|Fit Launcher manager queue failed|falling back to aria2 direct queue|manager verification failed|(?m)^- .+: MISSING\b|SKIPPED_METADATA_TIMEOUT|SKIPPED_LEGACY_MAGNET|NO_MAGNET|RPC_PENDING|Connection timed out|timed out after|aria2 RPC is not reachable')) {
            $code = 4
        }
        $global:LASTEXITCODE = $code
        return $code
    }
    finally {
        Remove-Item -LiteralPath $outFile,$errFile -Force -ErrorAction SilentlyContinue
    }
}

if ($MyInvocation.InvocationName -ne '.') {
    & 'Invoke-AfitgirlPythonProcess' @args
}
