# Generated by 2sc from function 'Invoke-ProfileWebApp' (2026-08-13 00:38:43).
# Self-bootstrap: load the profile environment when this script runs
# outside a profile session so it behaves exactly like the function it
# was copied from. The module is also force-re-imported when the copy
# loaded in this process is stale (psm1 changed on disk) so a long-
# running session never runs an outdated dispatcher.
$__2scProfileModule = 'C:\Users\micha\Documents\WindowsPowerShell\Modules\CodexProfileFunctions\CodexProfileFunctions.psd1'
$__2scNeedBootstrap = -not (Get-Command -Name 'Initialize-CodexProfileFunctions' -CommandType Function -ErrorAction SilentlyContinue)
if (-not $__2scNeedBootstrap) {
    $__2scLoadedModule = Get-Module -Name 'CodexProfileFunctions' -ErrorAction SilentlyContinue | Select-Object -First 1
    if ($__2scLoadedModule) {
        $__2scLoadedFingerprint = $__2scLoadedModule.SessionState.PSVariable.GetValue('ProfileModuleFingerprint')
        $__2scModuleFile = Join-Path $__2scLoadedModule.ModuleBase 'CodexProfileFunctions.psm1'
        if ([System.IO.File]::Exists($__2scModuleFile)) {
            $__2scDiskInfo = Get-Item -LiteralPath $__2scModuleFile -ErrorAction SilentlyContinue
            if ($__2scDiskInfo) {
                $__2scDiskFingerprint = '{0}|{1}' -f $__2scDiskInfo.Length, $__2scDiskInfo.LastWriteTimeUtc.Ticks
                if ([string]$__2scLoadedFingerprint -and $__2scDiskFingerprint -ne [string]$__2scLoadedFingerprint) { $__2scNeedBootstrap = $true }
            }
        }
    }
}
if ($__2scNeedBootstrap) {
    if (-not (Test-Path -LiteralPath $__2scProfileModule -PathType Leaf)) {
        throw "2sc-generated script requires the Codex profile module: $__2scProfileModule"
    }
    Import-Module -Name $__2scProfileModule -Force -DisableNameChecking -ErrorAction Stop
    Initialize-CodexProfileFunctions
}
function Invoke-ProfileWebApp {
    [CmdletBinding()]
    param(
        [switch]$Stop,
        [switch]$List,
        [string]$Root = (Get-Location).Path,
        [ValidateRange(1, 65535)][int]$Port = 8080,
        [string]$BindAddress = '127.0.0.1'
    )

    $statePath = Get-ProfileManagedWebAppStatePath
    if ($List -or $Stop) {
        $state = $null
        if (Test-Path -LiteralPath $statePath -PathType Leaf) {
            try { $state = Get-Content -LiteralPath $statePath -Raw | ConvertFrom-Json } catch { $state = $null }
        }
        $process = Get-ProfileManagedWebAppProcess -State $state
        if ($List) {
            [pscustomobject]@{
                Status = if ($process) { 'running' } else { 'stopped' }
                ProcessId = if ($process) { $process.ProcessId } else { $null }
                Root = if ($state) { $state.Root } else { $null }
                Port = if ($state) { $state.Port } else { $null }
                Url = if ($state) { $state.Url } else { $null }
            }
            return
        }
        if ($process) {
            Write-Output ("WEBAPP_PROGRESS stage=stopping pid={0}" -f $process.ProcessId)
            Stop-Process -Id $process.ProcessId -Force -ErrorAction Stop
        }
        Remove-Item -LiteralPath $statePath -Force -ErrorAction SilentlyContinue
        Write-Output ("WEBAPP_OK action=stopped count={0}" -f $(if ($process) { 1 } else { 0 }))
        return
    }

    if (-not (Test-Path -LiteralPath $Root -PathType Container)) {
        throw "WEBAPP: web root does not exist: $Root"
    }
    $existingState = $null
    if (Test-Path -LiteralPath $statePath -PathType Leaf) {
        try { $existingState = Get-Content -LiteralPath $statePath -Raw | ConvertFrom-Json } catch { $existingState = $null }
    }
    $existingProcess = Get-ProfileManagedWebAppProcess -State $existingState
    if ($existingProcess) {
        Write-Output ("WEBAPP_OK action=already-running pid={0} url=""{1}""" -f $existingProcess.ProcessId, $existingState.Url)
        return
    }
    if ($existingState) {
        Remove-Item -LiteralPath $statePath -Force -ErrorAction SilentlyContinue
    }
    $python = Get-Command -Name 'py.exe' -CommandType Application -ErrorAction SilentlyContinue |
        Select-Object -First 1
    if (-not $python -or -not $python.Source) {
        throw 'WEBAPP: Python Launcher (py.exe) is not available.'
    }
    $stateDirectory = Split-Path -Parent $statePath
    New-Item -ItemType Directory -Path $stateDirectory -Force | Out-Null
    $resolvedRoot = (Resolve-Path -LiteralPath $Root -ErrorAction Stop).Path
    $logDirectory = Join-Path $stateDirectory 'logs'
    New-Item -ItemType Directory -Path $logDirectory -Force | Out-Null
    $stdout = Join-Path $logDirectory ('webapp-{0}.out.log' -f $Port)
    $stderr = Join-Path $logDirectory ('webapp-{0}.err.log' -f $Port)
    Write-Output ("WEBAPP_PROGRESS stage=starting root=""{0}"" port={1}" -f $resolvedRoot, $Port)
    $launcher = Start-Process -FilePath $python.Source -ArgumentList @('-3', '-m', 'http.server', $Port, '--bind', $BindAddress, '--directory', $resolvedRoot) -RedirectStandardOutput $stdout -RedirectStandardError $stderr -WindowStyle Hidden -PassThru
    Write-Output ("WEBAPP_PROGRESS stage=confirming-server launcher_pid={0}" -f $launcher.Id)
    $process = $null
    $deadline = (Get-Date).AddSeconds(5)
    do {
        $children = Get-CimInstance -ClassName Win32_Process -Filter ("ParentProcessId = {0}" -f $launcher.Id) -ErrorAction SilentlyContinue
        $process = @($children | Where-Object {
            ([string]$_.CommandLine) -match '(?i)(^|\s)-m\s+http\.server(\s|$)'
        } | Select-Object -First 1)[0]
        if (-not $process) {
            Start-Sleep -Milliseconds 100
        }
    } while (-not $process -and (Get-Date) -lt $deadline)
    if (-not $process) {
        $launcherProcess = Get-Process -Id $launcher.Id -ErrorAction SilentlyContinue
        if ($launcherProcess) {
            Stop-Process -Id $launcher.Id -Force -ErrorAction SilentlyContinue
        }
        throw 'WEBAPP: Python Launcher did not produce a managed HTTP server process within five seconds.'
    }
    $liveProcess = Get-Process -Id $process.ProcessId -ErrorAction Stop
    $url = 'http://{0}:{1}/' -f $BindAddress, $Port
    $state = [pscustomobject]@{
        ProcessId = $process.ProcessId
        ProcessStartedUtc = $liveProcess.StartTime.ToUniversalTime().ToString('o')
        Root = $resolvedRoot
        Port = $Port
        Url = $url
        StartedUtc = [DateTime]::UtcNow.ToString('o')
        StandardOutput = $stdout
        StandardError = $stderr
    }
    $temporaryStatePath = $statePath + '.' + [Guid]::NewGuid().ToString('N') + '.tmp'
    [System.IO.File]::WriteAllText($temporaryStatePath, ($state | ConvertTo-Json -Depth 3), (New-Object System.Text.UTF8Encoding($false)))
    Move-Item -LiteralPath $temporaryStatePath -Destination $statePath -Force
    Write-Output ("WEBAPP_OK pid={0} url=""{1}"" stdout=""{2}"" stderr=""{3}""" -f $process.ProcessId, $url, $stdout, $stderr)
}

if ($MyInvocation.InvocationName -ne '.') {
    & 'Invoke-ProfileWebApp' @args
}
