# Generated by 2sc from function 'Invoke-RedockerDownload' (2026-08-12 23:58:31).
# Self-bootstrap: load the profile environment when this script runs
# outside a profile session so it behaves exactly like the function it
# was copied from. The module is also force-re-imported when the copy
# loaded in this process is stale (psm1 changed on disk) so a long-
# running session never runs an outdated dispatcher.
$__2scProfileModule = 'C:\Users\micha\Documents\WindowsPowerShell\Modules\CodexProfileFunctions\CodexProfileFunctions.psd1'
$__2scNeedBootstrap = -not (Get-Command -Name 'Initialize-CodexProfileFunctions' -CommandType Function -ErrorAction SilentlyContinue)
if (-not $__2scNeedBootstrap) {
    $__2scLoadedModule = Get-Module -Name 'CodexProfileFunctions' -ErrorAction SilentlyContinue | Select-Object -First 1
    if ($__2scLoadedModule) {
        $__2scLoadedFingerprint = $__2scLoadedModule.SessionState.PSVariable.GetValue('ProfileModuleFingerprint')
        $__2scModuleFile = Join-Path $__2scLoadedModule.ModuleBase 'CodexProfileFunctions.psm1'
        if ([System.IO.File]::Exists($__2scModuleFile)) {
            $__2scDiskInfo = Get-Item -LiteralPath $__2scModuleFile -ErrorAction SilentlyContinue
            if ($__2scDiskInfo) {
                $__2scDiskFingerprint = '{0}|{1}' -f $__2scDiskInfo.Length, $__2scDiskInfo.LastWriteTimeUtc.Ticks
                if ([string]$__2scLoadedFingerprint -and $__2scDiskFingerprint -ne [string]$__2scLoadedFingerprint) { $__2scNeedBootstrap = $true }
            }
        }
    }
}
if ($__2scNeedBootstrap) {
    if (-not (Test-Path -LiteralPath $__2scProfileModule -PathType Leaf)) {
        throw "2sc-generated script requires the Codex profile module: $__2scProfileModule"
    }
    Import-Module -Name $__2scProfileModule -Force -DisableNameChecking -ErrorAction Stop
    Initialize-CodexProfileFunctions
}
function Invoke-RedockerDownload {
        $dir=Split-Path -Parent $Destination
        if (-not (Test-Path -LiteralPath $dir -PathType Container)) { New-Item -ItemType Directory -Path $dir -Force | Out-Null }
        Remove-Item -LiteralPath $Destination -Force -ErrorAction SilentlyContinue
        try { Get-BitsTransfer -AllUsers -ErrorAction SilentlyContinue | Where-Object { $_.DisplayName -eq 'Docker Desktop' } | Remove-BitsTransfer -Confirm:$false -ErrorAction SilentlyContinue } catch {}
        Write-RedockerStep 'downloading Docker Desktop with direct WebClient progress (BITS disabled to avoid 0%/unknown-size stall)'
        $wc=New-Object Net.WebClient
        $lastPct=-1
        $lastBytes=0L
        $lastProgress=Get-Date
        Register-ObjectEvent -InputObject $wc -EventName DownloadProgressChanged -SourceIdentifier RedockerDownloadProgress -Action {
            $pct=[int]$EventArgs.ProgressPercentage
            $bytes=[int64]$EventArgs.BytesReceived
            $total=[int64]$EventArgs.TotalBytesToReceive
            $script:RedockerDownloadLastBytes=$bytes
            $script:RedockerDownloadLastProgress=Get-Date
            if($pct -gt $script:RedockerDownloadLastPct){
                $script:RedockerDownloadLastPct=$pct
                $totalLabel=if($total -gt 0){ [math]::Round($total/1MB,0) } else { '?' }
                Write-Host ("`r[redocker] download {0}% ({1}/{2} MB)    " -f $pct,[math]::Round($bytes/1MB,0),$totalLabel) -NoNewline -ForegroundColor Cyan
            }
        } | Out-Null
        $script:RedockerDownloadLastPct=-1
        $script:RedockerDownloadLastBytes=0L
        $script:RedockerDownloadLastProgress=Get-Date
        try {
            $wc.DownloadFileAsync([Uri]$Url,$Destination)
            while($wc.IsBusy){
                Start-Sleep -Milliseconds 500
                if(((Get-Date)-$script:RedockerDownloadLastProgress).TotalSeconds -gt 60 -and $script:RedockerDownloadLastBytes -le 0){
                    $wc.CancelAsync(); throw 'direct download made no byte progress for 60s'
                }
            }
            Write-Host ''
        } finally {
            try { Unregister-Event -SourceIdentifier RedockerDownloadProgress -ErrorAction SilentlyContinue } catch {}
            try { Remove-Job -Name RedockerDownloadProgress -Force -ErrorAction SilentlyContinue } catch {}
            $wc.Dispose()
        }
        $item=Get-Item -LiteralPath $Destination -ErrorAction Stop
        if ($item.Length -lt 100MB) { throw "downloaded installer too small: $($item.Length) bytes" }
        Write-RedockerStep ("downloaded installer {0} MB" -f [math]::Round($item.Length/1MB,0))
    }

if ($MyInvocation.InvocationName -ne '.') {
    & 'Invoke-RedockerDownload' @args
}
