# Generated by 2sc from function 'Invoke-ProfileFixFRunner' (2026-08-13 00:39:54).
# Self-bootstrap: load the profile environment when this script runs
# outside a profile session so it behaves exactly like the function it
# was copied from. The module is also force-re-imported when the copy
# loaded in this process is stale (psm1 changed on disk) so a long-
# running session never runs an outdated dispatcher.
$__2scProfileModule = 'C:\Users\micha\Documents\WindowsPowerShell\Modules\CodexProfileFunctions\CodexProfileFunctions.psd1'
$__2scNeedBootstrap = -not (Get-Command -Name 'Initialize-CodexProfileFunctions' -CommandType Function -ErrorAction SilentlyContinue)
if (-not $__2scNeedBootstrap) {
    $__2scLoadedModule = Get-Module -Name 'CodexProfileFunctions' -ErrorAction SilentlyContinue | Select-Object -First 1
    if ($__2scLoadedModule) {
        $__2scLoadedFingerprint = $__2scLoadedModule.SessionState.PSVariable.GetValue('ProfileModuleFingerprint')
        $__2scModuleFile = Join-Path $__2scLoadedModule.ModuleBase 'CodexProfileFunctions.psm1'
        if ([System.IO.File]::Exists($__2scModuleFile)) {
            $__2scDiskInfo = Get-Item -LiteralPath $__2scModuleFile -ErrorAction SilentlyContinue
            if ($__2scDiskInfo) {
                $__2scDiskFingerprint = '{0}|{1}' -f $__2scDiskInfo.Length, $__2scDiskInfo.LastWriteTimeUtc.Ticks
                if ([string]$__2scLoadedFingerprint -and $__2scDiskFingerprint -ne [string]$__2scLoadedFingerprint) { $__2scNeedBootstrap = $true }
            }
        }
    }
}
if ($__2scNeedBootstrap) {
    if (-not (Test-Path -LiteralPath $__2scProfileModule -PathType Leaf)) {
        throw "2sc-generated script requires the Codex profile module: $__2scProfileModule"
    }
    Import-Module -Name $__2scProfileModule -Force -DisableNameChecking -ErrorAction Stop
    Initialize-CodexProfileFunctions
}
function Invoke-ProfileFixFRunner {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)][ValidateSet('ffixe', 'ffixf')][string]$Name,
        [Parameter(Mandatory = $true)][string]$ArtifactPath
    )

    $portableRoot = 'C:\Users\micha\Documents\WindowsPowerShell\ProfileSources\ps5-profile-portable'
    $workingDirectory = 'F:\study'
    if (-not (Test-Path -LiteralPath $ArtifactPath -PathType Leaf)) {
        throw "${Name}: repair artifact is missing: $ArtifactPath"
    }
    if (-not (Test-Path -LiteralPath $workingDirectory -PathType Container)) {
        throw "${Name}: working directory is missing: $workingDirectory"
    }

    $runnerDirectory = Join-Path $portableRoot 'temp'
    $runner = Join-Path $runnerDirectory ($Name + '-profile-launch.ps1')
    New-Item -ItemType Directory -Path $runnerDirectory -Force | Out-Null
    $payload = Get-Content -LiteralPath $ArtifactPath -Raw -ErrorAction Stop
    if ([string]::IsNullOrWhiteSpace($payload)) {
        throw "${Name}: repair artifact is empty: $ArtifactPath"
    }
    Set-Content -LiteralPath $runner -Value $payload -Encoding UTF8 -Force

    $systemRoot = [Environment]::GetEnvironmentVariable('SystemRoot', 'Process')
    if ([string]::IsNullOrWhiteSpace($systemRoot)) { $systemRoot = 'C:\Windows' }
    $powershell = Join-Path $systemRoot 'System32\WindowsPowerShell\v1.0\powershell.exe'
    if (-not (Test-Path -LiteralPath $powershell -PathType Leaf)) {
        throw "${Name}: Windows PowerShell 5 executable is missing: $powershell"
    }

    Write-Output ("{0}_PROGRESS stage=starting-runner path=""{1}""" -f $Name.ToUpperInvariant(), $runner)
    Set-Location -LiteralPath $workingDirectory
    [Environment]::CurrentDirectory = $workingDirectory
    $process = Start-Process -FilePath $powershell -ArgumentList @('-NoProfile', '-ExecutionPolicy', 'Bypass', '-File', $runner) -WorkingDirectory $workingDirectory -WindowStyle Minimized -PassThru
    Write-Output ("{0}_OK pid={1} working_directory=""{2}""" -f $Name.ToUpperInvariant(), $process.Id, $workingDirectory)
}

if ($MyInvocation.InvocationName -ne '.') {
    & 'Invoke-ProfileFixFRunner' @args
}
