# Generated by 2sc from function 'Jarvis-Speak' (2026-08-13 00:39:15).
# Self-bootstrap: load the profile environment when this script runs
# outside a profile session so it behaves exactly like the function it
# was copied from. The module is also force-re-imported when the copy
# loaded in this process is stale (psm1 changed on disk) so a long-
# running session never runs an outdated dispatcher.
$__2scProfileModule = 'C:\Users\micha\Documents\WindowsPowerShell\Modules\CodexProfileFunctions\CodexProfileFunctions.psd1'
$__2scNeedBootstrap = -not (Get-Command -Name 'Initialize-CodexProfileFunctions' -CommandType Function -ErrorAction SilentlyContinue)
if (-not $__2scNeedBootstrap) {
    $__2scLoadedModule = Get-Module -Name 'CodexProfileFunctions' -ErrorAction SilentlyContinue | Select-Object -First 1
    if ($__2scLoadedModule) {
        $__2scLoadedFingerprint = $__2scLoadedModule.SessionState.PSVariable.GetValue('ProfileModuleFingerprint')
        $__2scModuleFile = Join-Path $__2scLoadedModule.ModuleBase 'CodexProfileFunctions.psm1'
        if ([System.IO.File]::Exists($__2scModuleFile)) {
            $__2scDiskInfo = Get-Item -LiteralPath $__2scModuleFile -ErrorAction SilentlyContinue
            if ($__2scDiskInfo) {
                $__2scDiskFingerprint = '{0}|{1}' -f $__2scDiskInfo.Length, $__2scDiskInfo.LastWriteTimeUtc.Ticks
                if ([string]$__2scLoadedFingerprint -and $__2scDiskFingerprint -ne [string]$__2scLoadedFingerprint) { $__2scNeedBootstrap = $true }
            }
        }
    }
}
if ($__2scNeedBootstrap) {
    if (-not (Test-Path -LiteralPath $__2scProfileModule -PathType Leaf)) {
        throw "2sc-generated script requires the Codex profile module: $__2scProfileModule"
    }
    Import-Module -Name $__2scProfileModule -Force -DisableNameChecking -ErrorAction Stop
    Initialize-CodexProfileFunctions
}
function Jarvis-Speak {
    param([string]$Text, [switch]$Force)
    if ($script:JarvisMuted -and -not $Force) { Write-Host '[muted]' -ForegroundColor DarkGray; return }
    if ([string]::IsNullOrWhiteSpace($Text)) { return }
    if ($Text.Length -gt 4000) { $Text = $Text.Substring(0, 4000) + ' (response truncated; full text in the transcript)' }

    try {
        $py = Jarvis-FindPython
        $mp3 = Join-Path $env:TEMP 'jarvis-speech.mp3'
        $txt = Join-Path $env:TEMP 'jarvis-speech.txt'
        [System.IO.File]::WriteAllText($txt, $Text, (New-Object System.Text.UTF8Encoding($false)))
        & $py -m edge_tts --voice $script:JarvisVoice --file $txt --write-media $mp3 2>$null | Out-Null
        if (-not (Test-Path -LiteralPath $mp3) -or (Get-Item -LiteralPath $mp3).Length -lt 2048) {
            Write-Warning 'edge-tts returned no audio; falling back to the Windows system voice.'
            Add-Type -AssemblyName System.Speech -ErrorAction SilentlyContinue
            $synth = New-Object System.Speech.Synthesis.SpeechSynthesizer
            $synth.Rate = 0
            $script:JarvisSpeakStartTick = [System.Diagnostics.Stopwatch]::GetTimestamp()
            $synth.Speak($Text)
            $script:JarvisSpeakEndTick = [System.Diagnostics.Stopwatch]::GetTimestamp()
            return
        }

        # Playback, never blocking forever: MediaPlayer (bounded sleep) -> WMP (capped) -> OS default.
        # The speak-window ticks let the continuous listener discard our own echo.
        $script:JarvisSpeakStartTick = [System.Diagnostics.Stopwatch]::GetTimestamp()
        $script:JarvisSpeakEndTick = $script:JarvisSpeakStartTick
        try {
            Add-Type -AssemblyName PresentationCore -ErrorAction Stop
            $player = New-Object System.Windows.Media.MediaPlayer
            $player.Open([Uri](New-Object System.Uri($mp3)))
            $player.Play()
            $secs = [Math]::Min(180, [Math]::Max(2, [Math]::Ceiling($Text.Length / 14)))
            Start-Sleep -Seconds $secs
            try { $player.Stop(); $player.Close() } catch { }
            $script:JarvisSpeakEndTick = [System.Diagnostics.Stopwatch]::GetTimestamp()
        } catch {
            try {
                $wmp = New-Object -ComObject WMPlayer.OCX
                $wmp.settings.volume = 100
                $wmp.URL = $mp3
                $deadline = (Get-Date).AddSeconds(25)
                while ($wmp.playState -ne 1 -and (Get-Date) -lt $deadline) { Start-Sleep -Milliseconds 150 }
                $script:JarvisSpeakEndTick = [System.Diagnostics.Stopwatch]::GetTimestamp()
            } catch {
                try { Start-Process $mp3 } catch { }
                $script:JarvisSpeakEndTick = [System.Diagnostics.Stopwatch]::GetTimestamp()
                Write-Warning ("Speech playback failed: {0}" -f $_.Exception.Message)
            }
        }
    } catch {
        Write-Warning ("TTS failed: {0}" -f $_.Exception.Message)
    }
}

if ($MyInvocation.InvocationName -ne '.') {
    & 'Jarvis-Speak' @args
}
