# Generated by 2sc from function 'Jarvis-CdpCommand' (2026-08-13 00:40:33).
# Self-bootstrap: load the profile environment when this script runs
# outside a profile session so it behaves exactly like the function it
# was copied from. The module is also force-re-imported when the copy
# loaded in this process is stale (psm1 changed on disk) so a long-
# running session never runs an outdated dispatcher.
$__2scProfileModule = 'C:\Users\micha\Documents\WindowsPowerShell\Modules\CodexProfileFunctions\CodexProfileFunctions.psd1'
$__2scNeedBootstrap = -not (Get-Command -Name 'Initialize-CodexProfileFunctions' -CommandType Function -ErrorAction SilentlyContinue)
if (-not $__2scNeedBootstrap) {
    $__2scLoadedModule = Get-Module -Name 'CodexProfileFunctions' -ErrorAction SilentlyContinue | Select-Object -First 1
    if ($__2scLoadedModule) {
        $__2scLoadedFingerprint = $__2scLoadedModule.SessionState.PSVariable.GetValue('ProfileModuleFingerprint')
        $__2scModuleFile = Join-Path $__2scLoadedModule.ModuleBase 'CodexProfileFunctions.psm1'
        if ([System.IO.File]::Exists($__2scModuleFile)) {
            $__2scDiskInfo = Get-Item -LiteralPath $__2scModuleFile -ErrorAction SilentlyContinue
            if ($__2scDiskInfo) {
                $__2scDiskFingerprint = '{0}|{1}' -f $__2scDiskInfo.Length, $__2scDiskInfo.LastWriteTimeUtc.Ticks
                if ([string]$__2scLoadedFingerprint -and $__2scDiskFingerprint -ne [string]$__2scLoadedFingerprint) { $__2scNeedBootstrap = $true }
            }
        }
    }
}
if ($__2scNeedBootstrap) {
    if (-not (Test-Path -LiteralPath $__2scProfileModule -PathType Leaf)) {
        throw "2sc-generated script requires the Codex profile module: $__2scProfileModule"
    }
    Import-Module -Name $__2scProfileModule -Force -DisableNameChecking -ErrorAction Stop
    Initialize-CodexProfileFunctions
}
function Jarvis-CdpCommand {
    param([string]$WsUrl, [string]$Method, [hashtable]$Params = @{})
    try {
        $ws = New-Object System.Net.WebSockets.ClientWebSocket
        $uri = New-Object System.Uri($WsUrl)
        $cts = New-Object System.Threading.CancellationTokenSource(8000)
        $ws.ConnectAsync($uri, $cts.Token).Wait() | Out-Null
        $id = [System.Guid]::NewGuid().ToString('N')
        $msg = @{ id = $id; method = $Method; params = $Params } | ConvertTo-Json -Compress -Depth 10
        $bytes = [System.Text.Encoding]::UTF8.GetBytes($msg)
        $seg = New-Object System.ArraySegment[byte] -ArgumentList @(,$bytes)
        $ws.SendAsync($seg, [System.Net.WebSockets.WebSocketMessageType]::Text, $true, $cts.Token).Wait() | Out-Null
        $buffer = New-Object byte[] 2097152
        $deadline = (Get-Date).AddSeconds(8)
        # Chromium pushes unsolicited protocol events on connect; keep reading
        # frames until the reply to OUR command (matching id) arrives.
        while ((Get-Date) -lt $deadline) {
            $ms = New-Object System.IO.MemoryStream
            $res = $null
            do {
                $rseg = New-Object System.ArraySegment[byte] -ArgumentList @(,$buffer)
                $res = $ws.ReceiveAsync($rseg, $cts.Token).Result
                if ($res.MessageType -eq [System.Net.WebSockets.WebSocketMessageType]::Close) { break }
                $ms.Write($buffer, 0, $res.Count)
            } while (-not $res.EndOfMessage)
            $text = [System.Text.Encoding]::UTF8.GetString($ms.ToArray())
            try { $obj = $text | ConvertFrom-Json } catch { continue }
            if ($obj.id -eq $id) { return $obj }
        }
    } catch { }
    finally { try { $ws.Dispose() } catch { } }
    return $null
}

if ($MyInvocation.InvocationName -ne '.') {
    & 'Jarvis-CdpCommand' @args
}
