# Generated by 2sc from function 'Jarvis-ListenContinuous' (2026-08-13 00:40:43).
# Self-bootstrap: load the profile environment when this script runs
# outside a profile session so it behaves exactly like the function it
# was copied from. The module is also force-re-imported when the copy
# loaded in this process is stale (psm1 changed on disk) so a long-
# running session never runs an outdated dispatcher.
$__2scProfileModule = 'C:\Users\micha\Documents\WindowsPowerShell\Modules\CodexProfileFunctions\CodexProfileFunctions.psd1'
$__2scNeedBootstrap = -not (Get-Command -Name 'Initialize-CodexProfileFunctions' -CommandType Function -ErrorAction SilentlyContinue)
if (-not $__2scNeedBootstrap) {
    $__2scLoadedModule = Get-Module -Name 'CodexProfileFunctions' -ErrorAction SilentlyContinue | Select-Object -First 1
    if ($__2scLoadedModule) {
        $__2scLoadedFingerprint = $__2scLoadedModule.SessionState.PSVariable.GetValue('ProfileModuleFingerprint')
        $__2scModuleFile = Join-Path $__2scLoadedModule.ModuleBase 'CodexProfileFunctions.psm1'
        if ([System.IO.File]::Exists($__2scModuleFile)) {
            $__2scDiskInfo = Get-Item -LiteralPath $__2scModuleFile -ErrorAction SilentlyContinue
            if ($__2scDiskInfo) {
                $__2scDiskFingerprint = '{0}|{1}' -f $__2scDiskInfo.Length, $__2scDiskInfo.LastWriteTimeUtc.Ticks
                if ([string]$__2scLoadedFingerprint -and $__2scDiskFingerprint -ne [string]$__2scLoadedFingerprint) { $__2scNeedBootstrap = $true }
            }
        }
    }
}
if ($__2scNeedBootstrap) {
    if (-not (Test-Path -LiteralPath $__2scProfileModule -PathType Leaf)) {
        throw "2sc-generated script requires the Codex profile module: $__2scProfileModule"
    }
    Import-Module -Name $__2scProfileModule -Force -DisableNameChecking -ErrorAction Stop
    Initialize-CodexProfileFunctions
}
function Jarvis-ListenContinuous {
    # Blocks until a finished speech segment is queued, transcribes it and
    # returns the text. Returns $null when the session should end (ESC).
    # While this blocks, the mic keeps capturing: words spoken during
    # transcription, Freebuff work and reply playback are queued, not lost.
    while ($true) {
        if ($script:JarvisContinuumStop) { return $null }
        $path = [JarvisContinuum]::PopSegment()
        if ($path) {
            $startTick = [JarvisContinuum]::LastSegmentTick()
            if ($script:JarvisSpeakEndTick -gt $script:JarvisSpeakStartTick -and
                $startTick -ge $script:JarvisSpeakStartTick -and
                $startTick -le ($script:JarvisSpeakEndTick + $script:JarvisEchoMarginTicks)) {
                # This segment is our own reply echoing back into the mic.
                Jarvis-Log 'skipped self-echo segment'
                Remove-Item -LiteralPath $path -Force -ErrorAction SilentlyContinue
                continue
            }
            $text = Jarvis-Transcribe -Wav $path
            Remove-Item -LiteralPath $path -Force -ErrorAction SilentlyContinue
            if ($text) { return $text }
            continue
        }
        try {
            if ([Console]::KeyAvailable) {
                $key = [Console]::ReadKey($true)
                if ($key.Key -eq [ConsoleKey]::Escape) { $script:JarvisContinuumStop = $true; return $null }
            }
        } catch { }
        Start-Sleep -Milliseconds 120
    }
}

if ($MyInvocation.InvocationName -ne '.') {
    & 'Jarvis-ListenContinuous' @args
}
