# Generated by 2sc from function 'Jarvis-CdpSendPrompt' (2026-08-13 00:41:08).
# Self-bootstrap: load the profile environment when this script runs
# outside a profile session so it behaves exactly like the function it
# was copied from. The module is also force-re-imported when the copy
# loaded in this process is stale (psm1 changed on disk) so a long-
# running session never runs an outdated dispatcher.
$__2scProfileModule = 'C:\Users\micha\Documents\WindowsPowerShell\Modules\CodexProfileFunctions\CodexProfileFunctions.psd1'
$__2scNeedBootstrap = -not (Get-Command -Name 'Initialize-CodexProfileFunctions' -CommandType Function -ErrorAction SilentlyContinue)
if (-not $__2scNeedBootstrap) {
    $__2scLoadedModule = Get-Module -Name 'CodexProfileFunctions' -ErrorAction SilentlyContinue | Select-Object -First 1
    if ($__2scLoadedModule) {
        $__2scLoadedFingerprint = $__2scLoadedModule.SessionState.PSVariable.GetValue('ProfileModuleFingerprint')
        $__2scModuleFile = Join-Path $__2scLoadedModule.ModuleBase 'CodexProfileFunctions.psm1'
        if ([System.IO.File]::Exists($__2scModuleFile)) {
            $__2scDiskInfo = Get-Item -LiteralPath $__2scModuleFile -ErrorAction SilentlyContinue
            if ($__2scDiskInfo) {
                $__2scDiskFingerprint = '{0}|{1}' -f $__2scDiskInfo.Length, $__2scDiskInfo.LastWriteTimeUtc.Ticks
                if ([string]$__2scLoadedFingerprint -and $__2scDiskFingerprint -ne [string]$__2scLoadedFingerprint) { $__2scNeedBootstrap = $true }
            }
        }
    }
}
if ($__2scNeedBootstrap) {
    if (-not (Test-Path -LiteralPath $__2scProfileModule -PathType Leaf)) {
        throw "2sc-generated script requires the Codex profile module: $__2scProfileModule"
    }
    Import-Module -Name $__2scProfileModule -Force -DisableNameChecking -ErrorAction Stop
    Initialize-CodexProfileFunctions
}
function Jarvis-CdpSendPrompt {
    param([string]$Text)
    $js = '(() => {
        var el = document.querySelector("textarea, input[type=text], [contenteditable=true]");
        if (!el) return "no-input";
        var proto = el.tagName === "TEXTAREA" ? window.HTMLTextAreaElement.prototype : (el.tagName === "INPUT" ? window.HTMLInputElement.prototype : null);
        var text = ' + ($Text | ConvertTo-Json -Compress) + ';
        if (proto) {
            var setter = Object.getOwnPropertyDescriptor(proto, "value");
            if (setter && setter.set) setter.set.call(el, text);
        } else if (el.isContentEditable) {
            el.textContent = text;
        }
        el.dispatchEvent(new Event("input", { bubbles: true }));
        el.dispatchEvent(new Event("change", { bubbles: true }));
        el.dispatchEvent(new KeyboardEvent("keydown", { key: "Enter", code: "Enter", keyCode: 13, which: 13, bubbles: true }));
        el.dispatchEvent(new KeyboardEvent("keyup", { key: "Enter", code: "Enter", keyCode: 13, which: 13, bubbles: true }));
        return "sent";
    })()'
    $res = Jarvis-CdpEval -WsUrl $script:JarvisCdp -Expression $js
    if ($res -ne 'sent') {
        $script:JarvisCdp = Jarvis-GetCdpTarget
        if ($script:JarvisCdp) { $res = Jarvis-CdpEval -WsUrl $script:JarvisCdp -Expression $js }
    }
    if ($res -eq 'sent') { Start-Sleep -Seconds 1; return $true }
    Write-Host ('CDP send returned: {0} - falling back to clipboard.' -f $res) -ForegroundColor DarkGray
    return $false
}

if ($MyInvocation.InvocationName -ne '.') {
    & 'Jarvis-CdpSendPrompt' @args
}
