# Generated by 2sc from function 'Jarvis-Listen' (2026-08-13 00:39:38).
# Self-bootstrap: load the profile environment when this script runs
# outside a profile session so it behaves exactly like the function it
# was copied from. The module is also force-re-imported when the copy
# loaded in this process is stale (psm1 changed on disk) so a long-
# running session never runs an outdated dispatcher.
$__2scProfileModule = 'C:\Users\micha\Documents\WindowsPowerShell\Modules\CodexProfileFunctions\CodexProfileFunctions.psd1'
$__2scNeedBootstrap = -not (Get-Command -Name 'Initialize-CodexProfileFunctions' -CommandType Function -ErrorAction SilentlyContinue)
if (-not $__2scNeedBootstrap) {
    $__2scLoadedModule = Get-Module -Name 'CodexProfileFunctions' -ErrorAction SilentlyContinue | Select-Object -First 1
    if ($__2scLoadedModule) {
        $__2scLoadedFingerprint = $__2scLoadedModule.SessionState.PSVariable.GetValue('ProfileModuleFingerprint')
        $__2scModuleFile = Join-Path $__2scLoadedModule.ModuleBase 'CodexProfileFunctions.psm1'
        if ([System.IO.File]::Exists($__2scModuleFile)) {
            $__2scDiskInfo = Get-Item -LiteralPath $__2scModuleFile -ErrorAction SilentlyContinue
            if ($__2scDiskInfo) {
                $__2scDiskFingerprint = '{0}|{1}' -f $__2scDiskInfo.Length, $__2scDiskInfo.LastWriteTimeUtc.Ticks
                if ([string]$__2scLoadedFingerprint -and $__2scDiskFingerprint -ne [string]$__2scLoadedFingerprint) { $__2scNeedBootstrap = $true }
            }
        }
    }
}
if ($__2scNeedBootstrap) {
    if (-not (Test-Path -LiteralPath $__2scProfileModule -PathType Leaf)) {
        throw "2sc-generated script requires the Codex profile module: $__2scProfileModule"
    }
    Import-Module -Name $__2scProfileModule -Force -DisableNameChecking -ErrorAction Stop
    Initialize-CodexProfileFunctions
}
function Jarvis-Listen {
    param([ValidateSet('Whisper', 'WinRT')][string]$Engine, [switch]$NoKeys)
    if ($Engine -eq 'WinRT') { return Jarvis-ListenWinRT }

    if (-not ('JarvisWinMM' -as [type])) {
        Add-Type -TypeDefinition $JarvisRecorderCSharp -ErrorAction Stop
    }
    $wav = Join-Path $env:TEMP 'jarvis-capture.wav'
    if (Test-Path -LiteralPath $wav) { Remove-Item -LiteralPath $wav -Force }

    Write-Host ('Listening... (pause to finish | ENTER = stop now | ESC = quit)  max {0}s' -f $script:JarvisMaxSeconds) -ForegroundColor DarkYellow

    $stopEvt = $null
    try { $stopEvt = New-Object System.Threading.EventWaitHandle($false, [System.Threading.EventResetMode]::AutoReset, $script:JarvisStopEventName) } catch { }

    $max = $script:JarvisMaxSeconds
    $sil = $script:JarvisSilenceSeconds
    $idle = $script:JarvisIdleTimeout
    $task = [System.Threading.Tasks.Task]::Run([Func[int]]{ [JarvisWinMM]::Record($wav, $max, $sil, 0.012, $script:JarvisStopEventName, $idle) })

    $esc = $false
    if (-not $NoKeys) {
        while (-not $task.IsCompleted) {
            if ([Console]::KeyAvailable) {
                $key = [Console]::ReadKey($true)
                if ($key.Key -eq [ConsoleKey]::Enter) { if ($stopEvt) { $stopEvt.Set() } }
                elseif ($key.Key -eq [ConsoleKey]::Escape) { if ($stopEvt) { $stopEvt.Set() }; $esc = $true }
            }
            Start-Sleep -Milliseconds 100
        }
    } else {
        # Background (tray) mode: no keyboard input; silence/idle auto-stop only.
        try { $task.Wait() | Out-Null } catch { }   # fault handled by the Result check below
    }
    if ($esc) { return $null }

    $bytes = 0
    try { $bytes = [int]$task.Result }
    catch {
        Write-Warning ("Mic error: {0}" -f $_.Exception.InnerException.Message)
        return ''
    }
    if ($bytes -lt 3200) { Write-Host 'Nothing heard.' -ForegroundColor DarkGray; return '' }

    Write-Host 'Transcribing... (first run downloads the model)' -ForegroundColor DarkYellow
    return Jarvis-Transcribe -Wav $wav
}

if ($MyInvocation.InvocationName -ne '.') {
    & 'Jarvis-Listen' @args
}
