# Generated by 2sc from function 'killgame' (2026-08-13 00:03:55).
# Self-bootstrap: load the profile environment when this script runs
# outside a profile session so it behaves exactly like the function it
# was copied from. The module is also force-re-imported when the copy
# loaded in this process is stale (psm1 changed on disk) so a long-
# running session never runs an outdated dispatcher.
$__2scProfileModule = 'C:\Users\micha\Documents\WindowsPowerShell\Modules\CodexProfileFunctions\CodexProfileFunctions.psd1'
$__2scNeedBootstrap = -not (Get-Command -Name 'Initialize-CodexProfileFunctions' -CommandType Function -ErrorAction SilentlyContinue)
if (-not $__2scNeedBootstrap) {
    $__2scLoadedModule = Get-Module -Name 'CodexProfileFunctions' -ErrorAction SilentlyContinue | Select-Object -First 1
    if ($__2scLoadedModule) {
        $__2scLoadedFingerprint = $__2scLoadedModule.SessionState.PSVariable.GetValue('ProfileModuleFingerprint')
        $__2scModuleFile = Join-Path $__2scLoadedModule.ModuleBase 'CodexProfileFunctions.psm1'
        if ([System.IO.File]::Exists($__2scModuleFile)) {
            $__2scDiskInfo = Get-Item -LiteralPath $__2scModuleFile -ErrorAction SilentlyContinue
            if ($__2scDiskInfo) {
                $__2scDiskFingerprint = '{0}|{1}' -f $__2scDiskInfo.Length, $__2scDiskInfo.LastWriteTimeUtc.Ticks
                if ([string]$__2scLoadedFingerprint -and $__2scDiskFingerprint -ne [string]$__2scLoadedFingerprint) { $__2scNeedBootstrap = $true }
            }
        }
    }
}
if ($__2scNeedBootstrap) {
    if (-not (Test-Path -LiteralPath $__2scProfileModule -PathType Leaf)) {
        throw "2sc-generated script requires the Codex profile module: $__2scProfileModule"
    }
    Import-Module -Name $__2scProfileModule -Force -DisableNameChecking -ErrorAction Stop
    Initialize-CodexProfileFunctions
}
function killgame {
    param([string]$name)

    if ($name) {
        Write-Host "Killing $name..." -ForegroundColor Yellow
        cmd /c "taskkill /F /IM `"$name.exe`" /T" 2>$null
        Stop-Process -Name $name -Force -ErrorAction SilentlyContinue
    } else {
        Write-Host "Killing all unresponsive games..." -ForegroundColor Yellow
        Get-Process | Where-Object { 
            $_.MainWindowHandle -ne [IntPtr]::Zero -and 
            $_.WorkingSet64 -gt 500MB -and 
            -not $_.Responding 
        } | ForEach-Object {
            Write-Host "  Killing $($_.ProcessName)..." -ForegroundColor Red
            cmd /c "taskkill /F /IM `"$($_.ProcessName).exe`" /T" 2>$null
            Stop-Process -Name $_.ProcessName -Force -ErrorAction SilentlyContinue
        }
    }

    Stop-Process -Name "bridge32" -Force -ErrorAction SilentlyContinue
    Stop-Process -Name "bridge64" -Force -ErrorAction SilentlyContinue
    Stop-Process -Name "crs-handler" -Force -ErrorAction SilentlyContinue
    Stop-Process -Name "crs-uploader" -Force -ErrorAction SilentlyContinue

    Write-Host "Done!" -ForegroundColor Green
}

if ($MyInvocation.InvocationName -ne '.') {
    & 'killgame' @args
}
