# Generated by 2sc from function 'listcod' (2026-08-13 00:04:03).
# Self-bootstrap: load the profile environment when this script runs
# outside a profile session so it behaves exactly like the function it
# was copied from. The module is also force-re-imported when the copy
# loaded in this process is stale (psm1 changed on disk) so a long-
# running session never runs an outdated dispatcher.
$__2scProfileModule = 'C:\Users\micha\Documents\WindowsPowerShell\Modules\CodexProfileFunctions\CodexProfileFunctions.psd1'
$__2scNeedBootstrap = -not (Get-Command -Name 'Initialize-CodexProfileFunctions' -CommandType Function -ErrorAction SilentlyContinue)
if (-not $__2scNeedBootstrap) {
    $__2scLoadedModule = Get-Module -Name 'CodexProfileFunctions' -ErrorAction SilentlyContinue | Select-Object -First 1
    if ($__2scLoadedModule) {
        $__2scLoadedFingerprint = $__2scLoadedModule.SessionState.PSVariable.GetValue('ProfileModuleFingerprint')
        $__2scModuleFile = Join-Path $__2scLoadedModule.ModuleBase 'CodexProfileFunctions.psm1'
        if ([System.IO.File]::Exists($__2scModuleFile)) {
            $__2scDiskInfo = Get-Item -LiteralPath $__2scModuleFile -ErrorAction SilentlyContinue
            if ($__2scDiskInfo) {
                $__2scDiskFingerprint = '{0}|{1}' -f $__2scDiskInfo.Length, $__2scDiskInfo.LastWriteTimeUtc.Ticks
                if ([string]$__2scLoadedFingerprint -and $__2scDiskFingerprint -ne [string]$__2scLoadedFingerprint) { $__2scNeedBootstrap = $true }
            }
        }
    }
}
if ($__2scNeedBootstrap) {
    if (-not (Test-Path -LiteralPath $__2scProfileModule -PathType Leaf)) {
        throw "2sc-generated script requires the Codex profile module: $__2scProfileModule"
    }
    Import-Module -Name $__2scProfileModule -Force -DisableNameChecking -ErrorAction Stop
    Initialize-CodexProfileFunctions
}
function listcod {
    $p = 'F:\backup\codex'
    if (-not (Test-Path $p)) { Write-Warning "listcod: backup root not found: $p"; return }
    Write-Host "=== F:\backup\codex (newest first) ===" -ForegroundColor Cyan
    Write-Host ""
    $dirs = Get-ChildItem $p -Directory -Force | Sort-Object LastWriteTime -Descending
    foreach ($d in $dirs) {
        $metaPath = Join-Path $d.FullName 'BACKUP-METADATA.json'
        $sizeBytes = 0L
        $note = ''
        if (Test-Path $metaPath) {
            try {
                $meta = Get-Content $metaPath -Raw | ConvertFrom-Json
                if ($meta.PayloadBytes) { $sizeBytes = [int64]$meta.PayloadBytes }
            } catch {}
        }
        if (-not $sizeBytes) {
            try {
                $sizeBytes = (Get-ChildItem $d.FullName -Recurse -File -EA SilentlyContinue | Measure-Object Length -Sum).Sum
            } catch { $sizeBytes = 0L }
        }
        if (Test-Path (Join-Path $d.FullName 'BACKUP-POINTER.json')) { $note = '  [pointer -> latest payload]' }
        $sizeMB = [math]::Round($sizeBytes / 1MB, 2)
        $sizeGB = [math]::Round($sizeBytes / 1GB, 3)
        Write-Host ("[DIR]  {0,-45} {1,10} MB  ({2,8} GB)  Created: {3}{4}" -f $d.Name, $sizeMB, $sizeGB, $d.CreationTime.ToString('yyyy-MM-dd HH:mm:ss'), $note) -ForegroundColor Yellow
    }
}

if ($MyInvocation.InvocationName -ne '.') {
    & 'listcod' @args
}
