# Generated by 2sc from function 'Load-FullPowerShellProfile' (2026-08-12 23:59:19).
# Self-bootstrap: load the profile environment when this script runs
# outside a profile session so it behaves exactly like the function it
# was copied from. The module is also force-re-imported when the copy
# loaded in this process is stale (psm1 changed on disk) so a long-
# running session never runs an outdated dispatcher.
$__2scProfileModule = 'C:\Users\micha\Documents\WindowsPowerShell\Modules\CodexProfileFunctions\CodexProfileFunctions.psd1'
$__2scNeedBootstrap = -not (Get-Command -Name 'Initialize-CodexProfileFunctions' -CommandType Function -ErrorAction SilentlyContinue)
if (-not $__2scNeedBootstrap) {
    $__2scLoadedModule = Get-Module -Name 'CodexProfileFunctions' -ErrorAction SilentlyContinue | Select-Object -First 1
    if ($__2scLoadedModule) {
        $__2scLoadedFingerprint = $__2scLoadedModule.SessionState.PSVariable.GetValue('ProfileModuleFingerprint')
        $__2scModuleFile = Join-Path $__2scLoadedModule.ModuleBase 'CodexProfileFunctions.psm1'
        if ([System.IO.File]::Exists($__2scModuleFile)) {
            $__2scDiskInfo = Get-Item -LiteralPath $__2scModuleFile -ErrorAction SilentlyContinue
            if ($__2scDiskInfo) {
                $__2scDiskFingerprint = '{0}|{1}' -f $__2scDiskInfo.Length, $__2scDiskInfo.LastWriteTimeUtc.Ticks
                if ([string]$__2scLoadedFingerprint -and $__2scDiskFingerprint -ne [string]$__2scLoadedFingerprint) { $__2scNeedBootstrap = $true }
            }
        }
    }
}
if ($__2scNeedBootstrap) {
    if (-not (Test-Path -LiteralPath $__2scProfileModule -PathType Leaf)) {
        throw "2sc-generated script requires the Codex profile module: $__2scProfileModule"
    }
    Import-Module -Name $__2scProfileModule -Force -DisableNameChecking -ErrorAction Stop
    Initialize-CodexProfileFunctions
}
function Load-FullPowerShellProfile {
    if ($script:FullProfileLoaded) { return }
    $fullProfileLibraryPath = $script:FullProfileLibraryPath
    if ([string]::IsNullOrWhiteSpace($fullProfileLibraryPath)) {
        $fullProfileLibraryPath = 'C:\Users\micha\Documents\WindowsPowerShell\ProfileSources\ps5-profile-portable\Microsoft.PowerShell_profile.full.ps1'
    }
    $fullProfileDefinitionCachePath = $script:FullProfileDefinitionCachePath
    if ([string]::IsNullOrWhiteSpace($fullProfileDefinitionCachePath)) {
        $fullProfileDefinitionCachePath = 'C:\Users\micha\Documents\WindowsPowerShell\ProfileSources\ps5-profile-portable\Microsoft.PowerShell_profile.full.definitions.ps1'
    }
    if (-not (Test-Path -LiteralPath $fullProfileLibraryPath -PathType Leaf)) {
        throw "Full PowerShell profile library not found: $fullProfileLibraryPath"
    }

    Update-FullProfileDefinitionCache -SourcePath $fullProfileLibraryPath -CachePath $fullProfileDefinitionCachePath
    if (-not (Test-Path -LiteralPath $fullProfileDefinitionCachePath -PathType Leaf)) {
        throw "Full PowerShell profile definition cache not found: $fullProfileDefinitionCachePath"
    }

    $script:FullProfileLoaded = $true
    $env:PROFILE_FAST_PROXY_LOAD = '1'
    try {
        . $fullProfileDefinitionCachePath
        if ($script:ProfileMyFixOverride) { Set-Item -Path 'Function:\global:myfix' -Value $script:ProfileMyFixOverride -Force }
        if ($script:ProfileQAccessOverride) { Set-Item -Path 'Function:\global:qaccess' -Value $script:ProfileQAccessOverride -Force }
        if ($script:ProfileFixFixFixFixOverride) { Set-Item -Path 'Function:\global:fixfixfixfix' -Value $script:ProfileFixFixFixFixOverride -Force }
        if ($script:ProfileCluOverride) { Set-Item -Path 'Function:\global:clu' -Value $script:ProfileCluOverride -Force }
        if ($script:ProfileNvidRuntimeBridgeOverride) {
            Set-Item -Path 'Function:\global:nvid' -Value $script:ProfileNvidRuntimeBridgeOverride -Force
            Set-Item -Path 'Function:\global:nvid2' -Value $script:ProfileNvidRuntimeBridgeOverride -Force
            Set-Item -Path 'Function:\global:nvidia2' -Value $script:ProfileNvidRuntimeBridgeOverride -Force
        }
        if ($script:ProfileGetAmd2RuntimeBridgeOverride) { Set-Item -Path 'Function:\global:getamd2' -Value $script:ProfileGetAmd2RuntimeBridgeOverride -Force }
        if ($script:ProfileGititOverride) { Set-Item -Path 'Function:\global:gitit' -Value $script:ProfileGititOverride -Force }
        
    } finally {
        Remove-Item Env:\PROFILE_FAST_PROXY_LOAD -ErrorAction SilentlyContinue
    }
}

if ($MyInvocation.InvocationName -ne '.') {
    & 'Load-FullPowerShellProfile' @args
}
