# Generated by 2sc from function 'macres' (2026-08-13 00:54:06).
# Hardened: finds the latest COMPLETE backup set across both recovery folder
# names and restores it from the correct first span (-00-00).
# Self-bootstrap: load the profile environment when this script runs
# outside a profile session so it behaves exactly like the function it
# was copied from. The module is also force-re-imported when the copy
# loaded in this process is stale (psm1 changed on disk) so a long-
# running session never runs an outdated dispatcher.
$__2scProfileModule = 'C:\Users\micha\Documents\WindowsPowerShell\Modules\CodexProfileFunctions\CodexProfileFunctions.psd1'
$__2scNeedBootstrap = -not (Get-Command -Name 'Initialize-CodexProfileFunctions' -CommandType Function -ErrorAction SilentlyContinue)
if (-not $__2scNeedBootstrap) {
    $__2scLoadedModule = Get-Module -Name 'CodexProfileFunctions' -ErrorAction SilentlyContinue | Select-Object -First 1
    if ($__2scLoadedModule) {
        $__2scLoadedFingerprint = $__2scLoadedModule.SessionState.PSVariable.GetValue('ProfileModuleFingerprint')
        $__2scModuleFile = Join-Path $__2scLoadedModule.ModuleBase 'CodexProfileFunctions.psm1'
        if ([System.IO.File]::Exists($__2scModuleFile)) {
            $__2scDiskInfo = Get-Item -LiteralPath $__2scModuleFile -ErrorAction SilentlyContinue
            if ($__2scDiskInfo) {
                $__2scDiskFingerprint = '{0}|{1}' -f $__2scDiskInfo.Length, $__2scDiskInfo.LastWriteTimeUtc.Ticks
                if ([string]$__2scLoadedFingerprint -and $__2scDiskFingerprint -ne [string]$__2scLoadedFingerprint) { $__2scNeedBootstrap = $true }
            }
        }
    }
}
if ($__2scNeedBootstrap) {
    if (-not (Test-Path -LiteralPath $__2scProfileModule -PathType Leaf)) {
        throw "2sc-generated script requires the Codex profile module: $__2scProfileModule"
    }
    Import-Module -Name $__2scProfileModule -Force -DisableNameChecking -ErrorAction Stop
    Initialize-CodexProfileFunctions
}
function macres {
    $mrauto = 'F:\backup\windowsapps\installed\reflect\mrauto.exe'
    if (-not (Test-Path -LiteralPath $mrauto -PathType Leaf)) {
        Write-Host "macres: mrauto.exe not found: $mrauto" -ForegroundColor Red
        return
    }

    # Both folder spellings are supported so a renamed recovery folder is
    # still found. Only the first span (-00-00) of a spanned set or a single
    # .mrimg file is a valid restore entry point.
    $candidateFolders = @('F:\win11recovery', 'F:\windows11recovery')
    $entryPoints = @()
    foreach ($folder in $candidateFolders) {
        if (-not (Test-Path -LiteralPath $folder -PathType Container)) { continue }
        $entryPoints += @(Get-ChildItem -LiteralPath $folder -File -ErrorAction SilentlyContinue | Where-Object {
            $_.Extension -eq '.mrimg' -or $_.Name -match '-00-00\.mrimgx$'
        })
    }

    if ($entryPoints.Count -eq 0) {
        # Fallback: if the -00-00 span is missing, take the lexically first
        # spanned file so the user is never left with nothing to restore.
        $fallback = @()
        foreach ($folder in $candidateFolders) {
            if (-not (Test-Path -LiteralPath $folder -PathType Container)) { continue }
            $fallback += @(Get-ChildItem -LiteralPath $folder -File -ErrorAction SilentlyContinue | Where-Object {
                $_.Extension -in @('.mrimg', '.mrimgx')
            })
        }
        $fallback = @($fallback | Sort-Object LastWriteTime -Descending | Select-Object -First 1)
        if ($fallback.Count -eq 0) {
            Write-Host "No Macrium backup found in F:\win11recovery or F:\windows11recovery" -ForegroundColor Red
            return
        }
        Write-Warning ("macres: no first-span (-00-00) file found; restoring the newest available image: {0}" -f $fallback[0].FullName)
        $latest = $fallback[0]
    }
    else {
        $latest = $entryPoints | Sort-Object LastWriteTime -Descending | Select-Object -First 1
    }

    Write-Host ("macres: Restoring latest backup: {0}" -f $latest.FullName) -ForegroundColor Cyan
    'YES' | & $mrauto -r $latest.FullName --nowarning --quiet --wait
    Write-Host "macres: Restore complete. Rebooting..." -ForegroundColor Green
    reboot
}

if ($MyInvocation.InvocationName -ne '.') {
    & 'macres' @args
}
