# Generated by 2sc from function 'mmsr' (2026-08-13 00:01:32).
# Self-bootstrap: load the profile environment when this script runs
# outside a profile session so it behaves exactly like the function it
# was copied from. The module is also force-re-imported when the copy
# loaded in this process is stale (psm1 changed on disk) so a long-
# running session never runs an outdated dispatcher.
$__2scProfileModule = 'C:\Users\micha\Documents\WindowsPowerShell\Modules\CodexProfileFunctions\CodexProfileFunctions.psd1'
$__2scNeedBootstrap = -not (Get-Command -Name 'Initialize-CodexProfileFunctions' -CommandType Function -ErrorAction SilentlyContinue)
if (-not $__2scNeedBootstrap) {
    $__2scLoadedModule = Get-Module -Name 'CodexProfileFunctions' -ErrorAction SilentlyContinue | Select-Object -First 1
    if ($__2scLoadedModule) {
        $__2scLoadedFingerprint = $__2scLoadedModule.SessionState.PSVariable.GetValue('ProfileModuleFingerprint')
        $__2scModuleFile = Join-Path $__2scLoadedModule.ModuleBase 'CodexProfileFunctions.psm1'
        if ([System.IO.File]::Exists($__2scModuleFile)) {
            $__2scDiskInfo = Get-Item -LiteralPath $__2scModuleFile -ErrorAction SilentlyContinue
            if ($__2scDiskInfo) {
                $__2scDiskFingerprint = '{0}|{1}' -f $__2scDiskInfo.Length, $__2scDiskInfo.LastWriteTimeUtc.Ticks
                if ([string]$__2scLoadedFingerprint -and $__2scDiskFingerprint -ne [string]$__2scLoadedFingerprint) { $__2scNeedBootstrap = $true }
            }
        }
    }
}
if ($__2scNeedBootstrap) {
    if (-not (Test-Path -LiteralPath $__2scProfileModule -PathType Leaf)) {
        throw "2sc-generated script requires the Codex profile module: $__2scProfileModule"
    }
    Import-Module -Name $__2scProfileModule -Force -DisableNameChecking -ErrorAction Stop
    Initialize-CodexProfileFunctions
}
function mmsr {
    $f = "$env:TEMP\MSERT.exe"
    $removalLog = "F:\study\security\msert-automation\removal-log.txt"
    Write-Host "Downloading MSERT..." -ForegroundColor Cyan
    iwr 'https://go.microsoft.com/fwlink/?LinkId=212732' -OutFile $f
    Write-Host "Running scan (auto-removal enabled)..." -ForegroundColor Yellow
    $proc = Start-Process $f -ArgumentList "/Q" -PassThru -Wait
    $logPath = "C:\Windows\debug\msert.log"
    if (Test-Path $logPath) {
        $content = Get-Content $logPath -Raw
        $found = [regex]::Matches($content, '([A-Za-z]:\\[^\r\n"]+\.(exe|dll|bat|vbs|ps1|sys|tmp))')
        $removed = 0
        foreach ($m in $found) {
            $fp = $m.Groups[1].Value.Trim()
            if (Test-Path $fp -ErrorAction SilentlyContinue) {
                try {
                    takeown /f "$fp" /a 2>$null | Out-Null
                    icacls "$fp" /grant "Administrators:F" /c /q 2>$null | Out-Null
                    Remove-Item $fp -Force -ErrorAction Stop
                    Write-Host "[REMOVED] $fp" -ForegroundColor Green
                    Add-Content $removalLog "[mmsr][$(Get-Date -f 'yyyy-MM-dd HH:mm:ss')][REMOVED] $fp"
                    $removed++
                } catch { Write-Host "[FAILED] $fp" -ForegroundColor Red }
            }
        }
        try { Remove-MpThreat -ErrorAction SilentlyContinue } catch {}
        Write-Host "mmsr complete. $removed file(s) force-removed." -ForegroundColor Cyan
    }
    Remove-Item $f -Force -ErrorAction SilentlyContinue
}

if ($MyInvocation.InvocationName -ne '.') {
    & 'mmsr' @args
}
