# Generated by 2sc from function 'nodecontext1mb' (2026-08-13 00:46:13).
# Self-bootstrap: load the profile environment when this script runs
# outside a profile session so it behaves exactly like the function it
# was copied from. The module is also force-re-imported when the copy
# loaded in this process is stale (psm1 changed on disk) so a long-
# running session never runs an outdated dispatcher.
$__2scProfileModule = 'C:\Users\micha\Documents\WindowsPowerShell\Modules\CodexProfileFunctions\CodexProfileFunctions.psd1'
$__2scNeedBootstrap = -not (Get-Command -Name 'Initialize-CodexProfileFunctions' -CommandType Function -ErrorAction SilentlyContinue)
if (-not $__2scNeedBootstrap) {
    $__2scLoadedModule = Get-Module -Name 'CodexProfileFunctions' -ErrorAction SilentlyContinue | Select-Object -First 1
    if ($__2scLoadedModule) {
        $__2scLoadedFingerprint = $__2scLoadedModule.SessionState.PSVariable.GetValue('ProfileModuleFingerprint')
        $__2scModuleFile = Join-Path $__2scLoadedModule.ModuleBase 'CodexProfileFunctions.psm1'
        if ([System.IO.File]::Exists($__2scModuleFile)) {
            $__2scDiskInfo = Get-Item -LiteralPath $__2scModuleFile -ErrorAction SilentlyContinue
            if ($__2scDiskInfo) {
                $__2scDiskFingerprint = '{0}|{1}' -f $__2scDiskInfo.Length, $__2scDiskInfo.LastWriteTimeUtc.Ticks
                if ([string]$__2scLoadedFingerprint -and $__2scDiskFingerprint -ne [string]$__2scLoadedFingerprint) { $__2scNeedBootstrap = $true }
            }
        }
    }
}
if ($__2scNeedBootstrap) {
    if (-not (Test-Path -LiteralPath $__2scProfileModule -PathType Leaf)) {
        throw "2sc-generated script requires the Codex profile module: $__2scProfileModule"
    }
    Import-Module -Name $__2scProfileModule -Force -DisableNameChecking -ErrorAction Stop
    Initialize-CodexProfileFunctions
}
function nodecontext1mb {
    [System.Environment]::SetEnvironmentVariable('NODE_OPTIONS', '--max-old-space-size=8192 --max-http-header-size=1048576 --expose-gc --no-warnings', 'User')
    [System.Environment]::SetEnvironmentVariable('CLAUDE_CODE_MAX_MEMORY', '8192', 'User')
    [System.Environment]::SetEnvironmentVariable('CLAUDE_CODE_TIMEOUT', '0', 'User')
    [System.Environment]::SetEnvironmentVariable('CLAUDE_CODE_RETRY', 'true', 'User')
    [System.Environment]::SetEnvironmentVariable('UV_THREADPOOL_SIZE', '128', 'User')
    [System.Environment]::SetEnvironmentVariable('UV_USE_IO_URING', '0', 'User')
    refreshenv
    Write-Host "Permanent 1MB context size applied for ALL future sessions!" -ForegroundColor Green
    Write-Host "NODE_OPTIONS: $env:NODE_OPTIONS" -ForegroundColor Cyan
    Write-Host "Restart ALL terminals to see changes everywhere" -ForegroundColor Yellow
}

if ($MyInvocation.InvocationName -ne '.') {
    & 'nodecontext1mb' @args
}
