# Generated by 2sc from function 'ps5000' (2026-08-13 00:01:40).
# Self-bootstrap: load the profile environment when this script runs
# outside a profile session so it behaves exactly like the function it
# was copied from. The module is also force-re-imported when the copy
# loaded in this process is stale (psm1 changed on disk) so a long-
# running session never runs an outdated dispatcher.
$__2scProfileModule = 'C:\Users\micha\Documents\WindowsPowerShell\Modules\CodexProfileFunctions\CodexProfileFunctions.psd1'
$__2scNeedBootstrap = -not (Get-Command -Name 'Initialize-CodexProfileFunctions' -CommandType Function -ErrorAction SilentlyContinue)
if (-not $__2scNeedBootstrap) {
    $__2scLoadedModule = Get-Module -Name 'CodexProfileFunctions' -ErrorAction SilentlyContinue | Select-Object -First 1
    if ($__2scLoadedModule) {
        $__2scLoadedFingerprint = $__2scLoadedModule.SessionState.PSVariable.GetValue('ProfileModuleFingerprint')
        $__2scModuleFile = Join-Path $__2scLoadedModule.ModuleBase 'CodexProfileFunctions.psm1'
        if ([System.IO.File]::Exists($__2scModuleFile)) {
            $__2scDiskInfo = Get-Item -LiteralPath $__2scModuleFile -ErrorAction SilentlyContinue
            if ($__2scDiskInfo) {
                $__2scDiskFingerprint = '{0}|{1}' -f $__2scDiskInfo.Length, $__2scDiskInfo.LastWriteTimeUtc.Ticks
                if ([string]$__2scLoadedFingerprint -and $__2scDiskFingerprint -ne [string]$__2scLoadedFingerprint) { $__2scNeedBootstrap = $true }
            }
        }
    }
}
if ($__2scNeedBootstrap) {
    if (-not (Test-Path -LiteralPath $__2scProfileModule -PathType Leaf)) {
        throw "2sc-generated script requires the Codex profile module: $__2scProfileModule"
    }
    Import-Module -Name $__2scProfileModule -Force -DisableNameChecking -ErrorAction Stop
    Initialize-CodexProfileFunctions
}
function ps5000 {
$runtimePath = 'C:\Users\micha\Documents\WindowsPowerShell\ProfileSources\ps5-profile-portable\Microsoft.PowerShell_profile.runtime.ps1'
$roots = @('C:\Users\micha\Documents\WindowsPowerShell\ProfileSources\ps5-profile-portable','C:\Users\micha\Documents\WindowsPowerShell\legacy-safe-functions')
$filesToScan = @(foreach ($root in $roots) {
    if (-not (Test-Path -LiteralPath $root)) { continue }
    Get-ChildItem -LiteralPath $root -Filter *.ps1 -Recurse -File -ErrorAction SilentlyContinue | Where-Object {
        $_.FullName -notmatch '\\backups(?:\\|$)' -and $_.FullName -notmatch '\.bak-(?:funcmutation|rmfunc|saved)-'
    }
})
$runtimeFuncs = @()
if (Test-Path -LiteralPath $runtimePath) {
    $runtimeFuncs = @(. {
        $tokens = $null; $errors = $null
        $ast = [System.Management.Automation.Language.Parser]::ParseFile($runtimePath, [ref]$tokens, [ref]$errors)
        if (@($errors).Count -gt 0) { return }
        $ast.FindAll({
            param($node)
            if ($node -isnot [System.Management.Automation.Language.FunctionDefinitionAst]) { return $false }
            $parent = $node.Parent
            while ($parent) {
                if ($parent -is [System.Management.Automation.Language.FunctionDefinitionAst]) { return $false }
                $parent = $parent.Parent
            }
            $true
        }, $true) | ForEach-Object {
            [pscustomobject]@{
                Name = $_.Name -replace '^(?i:global:)', ''
                Lines = $_.Extent.EndLineNumber - $_.Extent.StartLineNumber + 1
                File = $runtimePath
            }
        }
    })
}
$runtimeNames = @{}
foreach ($f in $runtimeFuncs) { $runtimeNames[$f.Name] = $true }
$otherFuncs = @(foreach ($f in $filesToScan) {
    if ($f.FullName -eq $runtimePath) { continue }
    $tokens = $null; $errors = $null
    $ast = [System.Management.Automation.Language.Parser]::ParseFile($f.FullName, [ref]$tokens, [ref]$errors)
    if (@($errors).Count -gt 0) { continue }
    $ast.FindAll({
        param($node)
        if ($node -isnot [System.Management.Automation.Language.FunctionDefinitionAst]) { return $false }
        $parent = $node.Parent
        while ($parent) {
            if ($parent -is [System.Management.Automation.Language.FunctionDefinitionAst]) { return $false }
            $parent = $parent.Parent
        }
        $true
    }, $true) | ForEach-Object {
        [pscustomobject]@{
            Name = $_.Name -replace '^(?i:global:)', ''
            Lines = $_.Extent.EndLineNumber - $_.Extent.StartLineNumber + 1
            File = $f.FullName
        }
    }
})
$allFuncs = @($runtimeFuncs) + @($otherFuncs | Where-Object { -not $runtimeNames.ContainsKey($_.Name) })
$allFuncs | Group-Object { $_.Name -replace '(.)\1+', '$1' } | ForEach-Object { $_.Group | Sort-Object Lines -Descending | Select-Object -First 1 } | Sort-Object Lines -Descending | Select-Object -First 500 | Format-Table -AutoSize
}

if ($MyInvocation.InvocationName -ne '.') {
    & 'ps5000' @args
}
