# Generated by 2sc from function 'Read-CleancAllowlistLocal' (2026-08-13 00:05:46).
# Self-bootstrap: load the profile environment when this script runs
# outside a profile session so it behaves exactly like the function it
# was copied from. The module is also force-re-imported when the copy
# loaded in this process is stale (psm1 changed on disk) so a long-
# running session never runs an outdated dispatcher.
$__2scProfileModule = 'C:\Users\micha\Documents\WindowsPowerShell\Modules\CodexProfileFunctions\CodexProfileFunctions.psd1'
$__2scNeedBootstrap = -not (Get-Command -Name 'Initialize-CodexProfileFunctions' -CommandType Function -ErrorAction SilentlyContinue)
if (-not $__2scNeedBootstrap) {
    $__2scLoadedModule = Get-Module -Name 'CodexProfileFunctions' -ErrorAction SilentlyContinue | Select-Object -First 1
    if ($__2scLoadedModule) {
        $__2scLoadedFingerprint = $__2scLoadedModule.SessionState.PSVariable.GetValue('ProfileModuleFingerprint')
        $__2scModuleFile = Join-Path $__2scLoadedModule.ModuleBase 'CodexProfileFunctions.psm1'
        if ([System.IO.File]::Exists($__2scModuleFile)) {
            $__2scDiskInfo = Get-Item -LiteralPath $__2scModuleFile -ErrorAction SilentlyContinue
            if ($__2scDiskInfo) {
                $__2scDiskFingerprint = '{0}|{1}' -f $__2scDiskInfo.Length, $__2scDiskInfo.LastWriteTimeUtc.Ticks
                if ([string]$__2scLoadedFingerprint -and $__2scDiskFingerprint -ne [string]$__2scLoadedFingerprint) { $__2scNeedBootstrap = $true }
            }
        }
    }
}
if ($__2scNeedBootstrap) {
    if (-not (Test-Path -LiteralPath $__2scProfileModule -PathType Leaf)) {
        throw "2sc-generated script requires the Codex profile module: $__2scProfileModule"
    }
    Import-Module -Name $__2scProfileModule -Force -DisableNameChecking -ErrorAction Stop
    Initialize-CodexProfileFunctions
}
function Read-CleancAllowlistLocal {
        param([string]$Path,[string]$ResolvedRootPath)
        if (-not (Test-Path -LiteralPath $Path -PathType Leaf)) { throw "cleanc allowlist not found: $Path" }
        $set = New-Object 'System.Collections.Generic.HashSet[string]' ([System.StringComparer]::OrdinalIgnoreCase)
        $entries = New-Object 'System.Collections.Generic.List[string]'
        $rootPrefix = $ResolvedRootPath.TrimEnd('\') + '\'
        $lineNumber = 0
        foreach ($raw in [System.IO.File]::ReadAllLines($Path)) {
            $lineNumber++
            $line = $raw.Trim()
            if ([string]::IsNullOrWhiteSpace($line) -or $line.StartsWith('#') -or $line.StartsWith(';')) { continue }
            if ([System.IO.Path]::IsPathRooted($line)) {
                $resolved = [System.IO.Path]::GetFullPath($line)
                if (-not $resolved.StartsWith($rootPrefix, [System.StringComparison]::OrdinalIgnoreCase)) { throw "cleanc allowlist line $lineNumber is outside root ${ResolvedRootPath}: $line" }
                $name = $resolved.Substring($rootPrefix.Length).TrimStart('\')
                if ([string]::IsNullOrWhiteSpace($name) -or $name.Contains('\')) { throw "cleanc allowlist line $lineNumber must target a direct child of ${ResolvedRootPath}: $line" }
            } else {
                if ($line.Contains('\') -or $line.Contains('/')) { throw "cleanc allowlist line $lineNumber must be a root item name or rooted path: $line" }
                $name = $line
            }
            if ($set.Add($name)) { $entries.Add($name) | Out-Null }
        }
        if ($entries.Count -eq 0) { throw "cleanc allowlist is empty: $Path" }
        [pscustomobject]@{ Path=$Path; Entries=@($entries); EntrySet=$set }
    }

if ($MyInvocation.InvocationName -ne '.') {
    & 'Read-CleancAllowlistLocal' @args
}
