# Generated by 2sc from function 'Register-NvidAppProtocol' (2026-08-13 00:00:26).
# Self-bootstrap: load the profile environment when this script runs
# outside a profile session so it behaves exactly like the function it
# was copied from. The module is also force-re-imported when the copy
# loaded in this process is stale (psm1 changed on disk) so a long-
# running session never runs an outdated dispatcher.
$__2scProfileModule = 'C:\Users\micha\Documents\WindowsPowerShell\Modules\CodexProfileFunctions\CodexProfileFunctions.psd1'
$__2scNeedBootstrap = -not (Get-Command -Name 'Initialize-CodexProfileFunctions' -CommandType Function -ErrorAction SilentlyContinue)
if (-not $__2scNeedBootstrap) {
    $__2scLoadedModule = Get-Module -Name 'CodexProfileFunctions' -ErrorAction SilentlyContinue | Select-Object -First 1
    if ($__2scLoadedModule) {
        $__2scLoadedFingerprint = $__2scLoadedModule.SessionState.PSVariable.GetValue('ProfileModuleFingerprint')
        $__2scModuleFile = Join-Path $__2scLoadedModule.ModuleBase 'CodexProfileFunctions.psm1'
        if ([System.IO.File]::Exists($__2scModuleFile)) {
            $__2scDiskInfo = Get-Item -LiteralPath $__2scModuleFile -ErrorAction SilentlyContinue
            if ($__2scDiskInfo) {
                $__2scDiskFingerprint = '{0}|{1}' -f $__2scDiskInfo.Length, $__2scDiskInfo.LastWriteTimeUtc.Ticks
                if ([string]$__2scLoadedFingerprint -and $__2scDiskFingerprint -ne [string]$__2scLoadedFingerprint) { $__2scNeedBootstrap = $true }
            }
        }
    }
}
if ($__2scNeedBootstrap) {
    if (-not (Test-Path -LiteralPath $__2scProfileModule -PathType Leaf)) {
        throw "2sc-generated script requires the Codex profile module: $__2scProfileModule"
    }
    Import-Module -Name $__2scProfileModule -Force -DisableNameChecking -ErrorAction Stop
    Initialize-CodexProfileFunctions
}
function Register-NvidAppProtocol {
        param([Parameter(Mandatory=$true)][string]$NvidiaAppExe)
        if (-not (Test-Path -LiteralPath $NvidiaAppExe -PathType Leaf)) { throw ("NVIDIA App protocol repair cannot find executable: {0}" -f $NvidiaAppExe) }
        $commandValue = '"' + $NvidiaAppExe + '" "%1"'
        $principal = New-Object Security.Principal.WindowsPrincipal([Security.Principal.WindowsIdentity]::GetCurrent())
        foreach($root in @('HKCU:\Software\Classes\nvidiaapp','HKLM:\Software\Classes\nvidiaapp')) {
            try {
                if ($root -like 'HKLM:*' -and -not $principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) { continue }
                New-Item -Path $root -Force | Out-Null
                Set-Item -Path $root -Value 'URL:NVIDIA App Protocol' -ErrorAction SilentlyContinue
                New-ItemProperty -Path $root -Name 'URL Protocol' -PropertyType String -Value '' -Force | Out-Null
                New-Item -Path (Join-Path $root 'DefaultIcon') -Force | Out-Null
                Set-Item -Path (Join-Path $root 'DefaultIcon') -Value ('"{0}",0' -f $NvidiaAppExe) -ErrorAction SilentlyContinue
                New-Item -Path (Join-Path $root 'shell\open\command') -Force | Out-Null
                Set-Item -Path (Join-Path $root 'shell\open\command') -Value $commandValue -ErrorAction SilentlyContinue
            } catch { Write-Host ("[nvid] warning: failed to write NVIDIA App protocol key {0}: {1}" -f $root,$_.Exception.Message) -ForegroundColor Yellow }
        }
        foreach($appPathsRoot in @('HKCU:\Software\Microsoft\Windows\CurrentVersion\App Paths\NVIDIA App.exe','HKLM:\Software\Microsoft\Windows\CurrentVersion\App Paths\NVIDIA App.exe')) {
            try {
                if ($appPathsRoot -like 'HKLM:*' -and -not $principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) { continue }
                New-Item -Path $appPathsRoot -Force | Out-Null
                Set-Item -Path $appPathsRoot -Value $NvidiaAppExe -ErrorAction SilentlyContinue
                New-ItemProperty -Path $appPathsRoot -Name 'Path' -PropertyType String -Value (Split-Path -Parent $NvidiaAppExe) -Force | Out-Null
            } catch { Write-Host ("[nvid] warning: failed to write NVIDIA App App Paths key {0}: {1}" -f $appPathsRoot,$_.Exception.Message) -ForegroundColor Yellow }
        }
        $verifyCommand = $null
        foreach($verifyPath in @('HKCU:\Software\Classes\nvidiaapp\shell\open\command','HKLM:\Software\Classes\nvidiaapp\shell\open\command')) {
            try { $verifyCommand = (Get-Item -LiteralPath $verifyPath -ErrorAction Stop).GetValue(''); if ($verifyCommand) { break } } catch {}
        }
        if (-not $verifyCommand -or $verifyCommand -notmatch [regex]::Escape($NvidiaAppExe)) { throw 'NVIDIA App protocol registration verification failed; nvidiaapp:// would still open Store/search.' }
        Write-NvidStep ("registered nvidiaapp:// protocol to {0}" -f $NvidiaAppExe)
        return $verifyCommand
    }

if ($MyInvocation.InvocationName -ne '.') {
    & 'Register-NvidAppProtocol' @args
}
