# Generated by 2sc from function 'Remove-RedockerPath' (2026-08-12 23:57:49).
# Self-bootstrap: load the profile environment when this script runs
# outside a profile session so it behaves exactly like the function it
# was copied from. The module is also force-re-imported when the copy
# loaded in this process is stale (psm1 changed on disk) so a long-
# running session never runs an outdated dispatcher.
$__2scProfileModule = 'C:\Users\micha\Documents\WindowsPowerShell\Modules\CodexProfileFunctions\CodexProfileFunctions.psd1'
$__2scNeedBootstrap = -not (Get-Command -Name 'Initialize-CodexProfileFunctions' -CommandType Function -ErrorAction SilentlyContinue)
if (-not $__2scNeedBootstrap) {
    $__2scLoadedModule = Get-Module -Name 'CodexProfileFunctions' -ErrorAction SilentlyContinue | Select-Object -First 1
    if ($__2scLoadedModule) {
        $__2scLoadedFingerprint = $__2scLoadedModule.SessionState.PSVariable.GetValue('ProfileModuleFingerprint')
        $__2scModuleFile = Join-Path $__2scLoadedModule.ModuleBase 'CodexProfileFunctions.psm1'
        if ([System.IO.File]::Exists($__2scModuleFile)) {
            $__2scDiskInfo = Get-Item -LiteralPath $__2scModuleFile -ErrorAction SilentlyContinue
            if ($__2scDiskInfo) {
                $__2scDiskFingerprint = '{0}|{1}' -f $__2scDiskInfo.Length, $__2scDiskInfo.LastWriteTimeUtc.Ticks
                if ([string]$__2scLoadedFingerprint -and $__2scDiskFingerprint -ne [string]$__2scLoadedFingerprint) { $__2scNeedBootstrap = $true }
            }
        }
    }
}
if ($__2scNeedBootstrap) {
    if (-not (Test-Path -LiteralPath $__2scProfileModule -PathType Leaf)) {
        throw "2sc-generated script requires the Codex profile module: $__2scProfileModule"
    }
    Import-Module -Name $__2scProfileModule -Force -DisableNameChecking -ErrorAction Stop
    Initialize-CodexProfileFunctions
}
function Remove-RedockerPath {
    [CmdletBinding()]
    param([Parameter(Mandatory)][string]$Path)

    if([string]::IsNullOrWhiteSpace($Path) -or -not [IO.Path]::IsPathRooted($Path)) {
        Write-RedockerStep 'purge rejected: path must be rooted'
        return $false
    }
    if(-not (Test-Path -LiteralPath $Path)) {
        Write-RedockerStep ("purge already absent: {0}" -f $Path)
        return $true
    }
    try {
        $resolved = (Resolve-Path -LiteralPath $Path -ErrorAction Stop).ProviderPath
    } catch {
        Write-RedockerStep ("purge resolve failed for {0}: {1}" -f $Path,$_.Exception.Message)
        return $false
    }
    if($resolved.TrimEnd('\') -eq [IO.Path]::GetPathRoot($resolved).TrimEnd('\')) {
        Write-RedockerStep ("purge rejected: drive root {0}" -f $resolved)
        return $false
    }

    Write-RedockerStep ("purging {0}" -f $resolved)
    try {
        $item = Get-Item -LiteralPath $resolved -Force -ErrorAction Stop
        $takeown = Join-Path $env:SystemRoot 'System32\takeown.exe'
        $icacls = Join-Path $env:SystemRoot 'System32\icacls.exe'
        if(Test-Path -LiteralPath $takeown) {
            if($item.PSIsContainer) { & $takeown /F $resolved /R /D Y /A 2>&1 | Out-Null } else { & $takeown /F $resolved /A 2>&1 | Out-Null }
            if($LASTEXITCODE -gt 1) { throw "takeown exit=$LASTEXITCODE" }
        }
        if(Test-Path -LiteralPath $icacls) {
            if($item.PSIsContainer) { & $icacls $resolved /grant 'Administrators:(OI)(CI)F' /T /C 2>&1 | Out-Null } else { & $icacls $resolved /grant 'Administrators:F' /C 2>&1 | Out-Null }
            if($LASTEXITCODE -ne 0) { throw "icacls exit=$LASTEXITCODE" }
        }
    } catch {
        Write-RedockerStep ("purge ownership warning for {0}: {1}" -f $resolved,$_.Exception.Message)
    }
    try {
        Remove-Item -LiteralPath $resolved -Recurse -Force -ErrorAction Stop
    } catch {
        Write-RedockerStep ("purge primary delete failed for {0}: {1}" -f $resolved,$_.Exception.Message)
        try {
            $item = Get-Item -LiteralPath $resolved -Force -ErrorAction Stop
            if($item.PSIsContainer) { [IO.Directory]::Delete($resolved,$true) } else { [IO.File]::Delete($resolved) }
        } catch {
            Write-RedockerStep ("purge fallback delete failed for {0}: {1}" -f $resolved,$_.Exception.Message)
            return $false
        }
    }
    $verified = -not (Test-Path -LiteralPath $resolved)
    Write-RedockerStep ("purge {0}: {1}" -f $(if($verified){'verified'}else{'not verified'}),$resolved)
    return $verified
}

if ($MyInvocation.InvocationName -ne '.') {
    & 'Remove-RedockerPath' @args
}
