# Generated by 2sc from function 'Resolve-NvidLatestDriverDownload' (2026-08-13 00:00:29).
# Self-bootstrap: load the profile environment when this script runs
# outside a profile session so it behaves exactly like the function it
# was copied from. The module is also force-re-imported when the copy
# loaded in this process is stale (psm1 changed on disk) so a long-
# running session never runs an outdated dispatcher.
$__2scProfileModule = 'C:\Users\micha\Documents\WindowsPowerShell\Modules\CodexProfileFunctions\CodexProfileFunctions.psd1'
$__2scNeedBootstrap = -not (Get-Command -Name 'Initialize-CodexProfileFunctions' -CommandType Function -ErrorAction SilentlyContinue)
if (-not $__2scNeedBootstrap) {
    $__2scLoadedModule = Get-Module -Name 'CodexProfileFunctions' -ErrorAction SilentlyContinue | Select-Object -First 1
    if ($__2scLoadedModule) {
        $__2scLoadedFingerprint = $__2scLoadedModule.SessionState.PSVariable.GetValue('ProfileModuleFingerprint')
        $__2scModuleFile = Join-Path $__2scLoadedModule.ModuleBase 'CodexProfileFunctions.psm1'
        if ([System.IO.File]::Exists($__2scModuleFile)) {
            $__2scDiskInfo = Get-Item -LiteralPath $__2scModuleFile -ErrorAction SilentlyContinue
            if ($__2scDiskInfo) {
                $__2scDiskFingerprint = '{0}|{1}' -f $__2scDiskInfo.Length, $__2scDiskInfo.LastWriteTimeUtc.Ticks
                if ([string]$__2scLoadedFingerprint -and $__2scDiskFingerprint -ne [string]$__2scLoadedFingerprint) { $__2scNeedBootstrap = $true }
            }
        }
    }
}
if ($__2scNeedBootstrap) {
    if (-not (Test-Path -LiteralPath $__2scProfileModule -PathType Leaf)) {
        throw "2sc-generated script requires the Codex profile module: $__2scProfileModule"
    }
    Import-Module -Name $__2scProfileModule -Force -DisableNameChecking -ErrorAction Stop
    Initialize-CodexProfileFunctions
}
function Resolve-NvidLatestDriverDownload {
        param([Parameter(Mandatory=$true)]$Target)
        $osId = 135
        $uri = ('https://www.nvidia.com/Download/processFind.aspx?psid={0}&pfid={1}&osID={2}&languageCode=1033&beta=0&isWHQL=1&dltype=-1&sort1=0&numberOfResults=10&dtcid=1' -f $Target.SeriesId,$Target.ProductId,$osId)
        Write-NvidStep ("querying latest NVIDIA display driver for {0} via NVIDIA processFind" -f $Target.ProductName)
        $page = Invoke-WebRequest -Uri $uri -UseBasicParsing -TimeoutSec 60
        $html = [string]$page.Content
        $rows = [regex]::Matches($html, '<tr id="driverList">(?<row>[\s\S]*?)</tr>')
        foreach($m in $rows) {
            $row = $m.Groups['row'].Value
            $idMatch = [regex]::Match($row, 'driverResults\.aspx/(?<id>\d+)/en-us')
            $verMatch = [regex]::Match($row, '<td class="gridItem">(?<ver>\d+\.\d+)</td>')
            if ($idMatch.Success -and $verMatch.Success -and $row -match 'GeForce Game Ready Driver') {
                $ver = $verMatch.Groups['ver'].Value
                $driverId = $idMatch.Groups['id'].Value
                $candidates = @(
                    ('https://us.download.nvidia.com/Windows/{0}/{0}-desktop-win10-win11-64bit-international-dch-whql.exe' -f $ver),
                    ('https://international.download.nvidia.com/Windows/{0}/{0}-desktop-win10-win11-64bit-international-dch-whql.exe' -f $ver)
                )
                foreach($candidate in $candidates) {
                    try {
                        $req = [System.Net.HttpWebRequest]::Create($candidate)
                        $req.Method = 'HEAD'
                        $req.Timeout = 30000
                        $resp = $req.GetResponse()
                        try { if ([int]$resp.StatusCode -eq 200) { return [pscustomobject]@{ Version = $ver; DriverId = $driverId; Url = $candidate } } } finally { $resp.Close() }
                    } catch {}
                }
                throw ("Latest NVIDIA driver {0} was found but download URL pattern did not resolve." -f $ver)
            }
        }
        throw 'NVIDIA processFind returned no English GeForce Game Ready Driver rows.'
    }

if ($MyInvocation.InvocationName -ne '.') {
    & 'Resolve-NvidLatestDriverDownload' @args
}
