# Generated by 2sc from function 'Resolve-ProfilePythonExecutable' (2026-08-13 00:40:26).
# Self-bootstrap: load the profile environment when this script runs
# outside a profile session so it behaves exactly like the function it
# was copied from. The module is also force-re-imported when the copy
# loaded in this process is stale (psm1 changed on disk) so a long-
# running session never runs an outdated dispatcher.
$__2scProfileModule = 'C:\Users\micha\Documents\WindowsPowerShell\Modules\CodexProfileFunctions\CodexProfileFunctions.psd1'
$__2scNeedBootstrap = -not (Get-Command -Name 'Initialize-CodexProfileFunctions' -CommandType Function -ErrorAction SilentlyContinue)
if (-not $__2scNeedBootstrap) {
    $__2scLoadedModule = Get-Module -Name 'CodexProfileFunctions' -ErrorAction SilentlyContinue | Select-Object -First 1
    if ($__2scLoadedModule) {
        $__2scLoadedFingerprint = $__2scLoadedModule.SessionState.PSVariable.GetValue('ProfileModuleFingerprint')
        $__2scModuleFile = Join-Path $__2scLoadedModule.ModuleBase 'CodexProfileFunctions.psm1'
        if ([System.IO.File]::Exists($__2scModuleFile)) {
            $__2scDiskInfo = Get-Item -LiteralPath $__2scModuleFile -ErrorAction SilentlyContinue
            if ($__2scDiskInfo) {
                $__2scDiskFingerprint = '{0}|{1}' -f $__2scDiskInfo.Length, $__2scDiskInfo.LastWriteTimeUtc.Ticks
                if ([string]$__2scLoadedFingerprint -and $__2scDiskFingerprint -ne [string]$__2scLoadedFingerprint) { $__2scNeedBootstrap = $true }
            }
        }
    }
}
if ($__2scNeedBootstrap) {
    if (-not (Test-Path -LiteralPath $__2scProfileModule -PathType Leaf)) {
        throw "2sc-generated script requires the Codex profile module: $__2scProfileModule"
    }
    Import-Module -Name $__2scProfileModule -Force -DisableNameChecking -ErrorAction Stop
    Initialize-CodexProfileFunctions
}
function Resolve-ProfilePythonExecutable {
    if ($script:CachedProfilePythonExecutable -and (Test-Path -LiteralPath $script:CachedProfilePythonExecutable -PathType Leaf)) {
        return $script:CachedProfilePythonExecutable
    }

    $candidatePaths = @(
        $env:CODEX_PROFILE_PYTHON,
        (Join-Path $env:LOCALAPPDATA 'Programs\Python\Python312\python.exe'),
        (Join-Path $env:LOCALAPPDATA 'Programs\Python\Python311\python.exe'),
        'C:\Python312\python.exe',
        'C:\Python311\python.exe'
    )

    foreach ($candidate in $candidatePaths) {
        if ([string]::IsNullOrWhiteSpace($candidate)) { continue }
        if (Test-Path -LiteralPath $candidate -PathType Leaf) {
            $script:CachedProfilePythonExecutable = (Resolve-Path -LiteralPath $candidate).ProviderPath
            return $script:CachedProfilePythonExecutable
        }
    }

    $command = Get-Command python -All -CommandType Application -ErrorAction SilentlyContinue |
        Where-Object { $_.Path -and $_.Path -notlike '*\Microsoft\WindowsApps\python*.exe' } |
        Select-Object -First 1
    if ($command) {
        $script:CachedProfilePythonExecutable = $command.Path
        return $script:CachedProfilePythonExecutable
    }

    $launcher = Get-Command py.exe -CommandType Application -ErrorAction SilentlyContinue
    if ($launcher) { return $launcher.Path }

    throw 'No usable Python interpreter found. Install Python or set CODEX_PROFILE_PYTHON to a real python.exe path.'
}

if ($MyInvocation.InvocationName -ne '.') {
    & 'Resolve-ProfilePythonExecutable' @args
}
