# Generated by 2sc from function 'Resolve-PostAction' (2026-08-12 23:59:01).
# Self-bootstrap: load the profile environment when this script runs
# outside a profile session so it behaves exactly like the function it
# was copied from. The module is also force-re-imported when the copy
# loaded in this process is stale (psm1 changed on disk) so a long-
# running session never runs an outdated dispatcher.
$__2scProfileModule = 'C:\Users\micha\Documents\WindowsPowerShell\Modules\CodexProfileFunctions\CodexProfileFunctions.psd1'
$__2scNeedBootstrap = -not (Get-Command -Name 'Initialize-CodexProfileFunctions' -CommandType Function -ErrorAction SilentlyContinue)
if (-not $__2scNeedBootstrap) {
    $__2scLoadedModule = Get-Module -Name 'CodexProfileFunctions' -ErrorAction SilentlyContinue | Select-Object -First 1
    if ($__2scLoadedModule) {
        $__2scLoadedFingerprint = $__2scLoadedModule.SessionState.PSVariable.GetValue('ProfileModuleFingerprint')
        $__2scModuleFile = Join-Path $__2scLoadedModule.ModuleBase 'CodexProfileFunctions.psm1'
        if ([System.IO.File]::Exists($__2scModuleFile)) {
            $__2scDiskInfo = Get-Item -LiteralPath $__2scModuleFile -ErrorAction SilentlyContinue
            if ($__2scDiskInfo) {
                $__2scDiskFingerprint = '{0}|{1}' -f $__2scDiskInfo.Length, $__2scDiskInfo.LastWriteTimeUtc.Ticks
                if ([string]$__2scLoadedFingerprint -and $__2scDiskFingerprint -ne [string]$__2scLoadedFingerprint) { $__2scNeedBootstrap = $true }
            }
        }
    }
}
if ($__2scNeedBootstrap) {
    if (-not (Test-Path -LiteralPath $__2scProfileModule -PathType Leaf)) {
        throw "2sc-generated script requires the Codex profile module: $__2scProfileModule"
    }
    Import-Module -Name $__2scProfileModule -Force -DisableNameChecking -ErrorAction Stop
    Initialize-CodexProfileFunctions
}
function Resolve-PostAction {
        if (-not $afterPackage) {
            [void](Remove-WingupStateEntry $state $package.Id)
            return [pscustomobject]@{
                Status = 'success'
                Message = "$($package.Name) is no longer listed by winget."
            }
        }

        if ($result.RestartRequired) {
            $note = 'Upgrade succeeded, but winget still lists the old version until the app is restarted.'
            Set-WingupStateEntry $state $package 'restart-required' $note
            return [pscustomobject]@{
                Status = 'suppressed'
                Message = "$($package.Name) was updated and is now suppressed until restart state clears."
            }
        }

        if ($result.Succeeded -and $afterPackage.Current -eq 'Unknown' -and $afterPackage.Available -eq $package.Available) {
            $note = 'Upgrade succeeded, but winget still reports the package because the installed version stays Unknown.'
            Set-WingupStateEntry $state $package 'metadata-stuck' $note
            return [pscustomobject]@{
                Status = 'suppressed'
                Message = "$($package.Name) was upgraded; winget metadata is stuck, so it is suppressed until the available version changes."
            }
        }

        if ($package.Id -eq 'OpenAI.Codex' -and $result.AccessDenied -and (Test-CodexCliRunning)) {
            return [pscustomobject]@{
                Status = 'deferred'
                Message = 'Codex CLI is running from the winget-managed path. Close Codex CLI sessions and rerun wingup to finish that upgrade.'
            }
        }

        return [pscustomobject]@{
            Status = 'pending'
            Message = "$($package.Name) is still listed after the attempt."
        }
    }

if ($MyInvocation.InvocationName -ne '.') {
    & 'Resolve-PostAction' @args
}
