# Generated by 2sc from function 'Restart-AfitgirlAria2MaxSpeed' (2026-08-13 00:39:29).
# Self-bootstrap: load the profile environment when this script runs
# outside a profile session so it behaves exactly like the function it
# was copied from. The module is also force-re-imported when the copy
# loaded in this process is stale (psm1 changed on disk) so a long-
# running session never runs an outdated dispatcher.
$__2scProfileModule = 'C:\Users\micha\Documents\WindowsPowerShell\Modules\CodexProfileFunctions\CodexProfileFunctions.psd1'
$__2scNeedBootstrap = -not (Get-Command -Name 'Initialize-CodexProfileFunctions' -CommandType Function -ErrorAction SilentlyContinue)
if (-not $__2scNeedBootstrap) {
    $__2scLoadedModule = Get-Module -Name 'CodexProfileFunctions' -ErrorAction SilentlyContinue | Select-Object -First 1
    if ($__2scLoadedModule) {
        $__2scLoadedFingerprint = $__2scLoadedModule.SessionState.PSVariable.GetValue('ProfileModuleFingerprint')
        $__2scModuleFile = Join-Path $__2scLoadedModule.ModuleBase 'CodexProfileFunctions.psm1'
        if ([System.IO.File]::Exists($__2scModuleFile)) {
            $__2scDiskInfo = Get-Item -LiteralPath $__2scModuleFile -ErrorAction SilentlyContinue
            if ($__2scDiskInfo) {
                $__2scDiskFingerprint = '{0}|{1}' -f $__2scDiskInfo.Length, $__2scDiskInfo.LastWriteTimeUtc.Ticks
                if ([string]$__2scLoadedFingerprint -and $__2scDiskFingerprint -ne [string]$__2scLoadedFingerprint) { $__2scNeedBootstrap = $true }
            }
        }
    }
}
if ($__2scNeedBootstrap) {
    if (-not (Test-Path -LiteralPath $__2scProfileModule -PathType Leaf)) {
        throw "2sc-generated script requires the Codex profile module: $__2scProfileModule"
    }
    Import-Module -Name $__2scProfileModule -Force -DisableNameChecking -ErrorAction Stop
    Initialize-CodexProfileFunctions
}
function Restart-AfitgirlAria2MaxSpeed {
    [CmdletBinding()]
    param([string] $Reason = 'afitgirl max-speed restart')

    $root = Join-Path $env:APPDATA 'com.fitlauncher.carrotrub'
    $sessionPath = Join-Path $root 'aria2.session'
    $logPath = Join-Path $root 'logs\aria2.log'
    $aria2Exe = 'F:\backup\windowsapps\installed\Fit Launcher\aria2c.real.exe'
    $bridgeScript = 'F:\study\projects\games\DownloadNAutoInstall\windows\fit-launcher\automation\auto-install\path-bridge\scripts\FitLauncherPathBridge.ps1'
    $ps5 = Join-Path $env:SystemRoot 'System32\WindowsPowerShell\v1.0\powershell.exe'
    $completeHook = Join-Path $root 'fitgirl-complete-hook.cmd'
    $trackerList = 'udp://tracker.opentrackr.org:1337/announce,udp://open.tracker.cl:1337/announce,udp://open.demonii.com:1337/announce,udp://tracker.torrent.eu.org:451/announce,udp://tracker-udp.gbitt.info:80/announce,udp://explodie.org:6969/announce,udp://tracker.skyts.net:6969/announce,udp://tracker.ololosh.space:6969/announce,udp://exodus.desync.com:6969/announce,udp://ipv4.tracker.harry.lu:80/announce,udp://open.stealth.si:80/announce,udp://tracker.moeking.me:6969/announce,udp://tracker.dler.org:6969/announce,udp://tracker.bitsearch.to:1337/announce,https://tracker.gbitt.info:443/announce,https://tracker.bt4g.com:443/announce,http://tracker.bt4g.com:2095/announce,http://tracker.files.fm:6969/announce'
    if (-not (Test-Path -LiteralPath $root -PathType Container)) { New-Item -ItemType Directory -Force -Path $root | Out-Null }
    if (-not (Test-Path -LiteralPath (Split-Path -Parent $logPath) -PathType Container)) { New-Item -ItemType Directory -Force -Path (Split-Path -Parent $logPath) | Out-Null }
    if (-not (Test-Path -LiteralPath $aria2Exe -PathType Leaf)) { throw "aria2c missing: $aria2Exe" }
    if (Test-Path -LiteralPath $bridgeScript -PathType Leaf) {
        try { $autoWatchdog = Join-Path $scripts 'FitLauncherAutoInstallCompletionWatchdog.ps1'; Set-Content -LiteralPath $completeHook -Encoding ASCII -Force -Value ('@echo off' + "`r`n" + '"' + $ps5 + '" -NoProfile -ExecutionPolicy Bypass -File "' + $autoWatchdog + '" -Once >NUL 2>NUL' + "`r`n" + '"' + $ps5 + '" -NoProfile -ExecutionPolicy Bypass -File "' + $bridgeScript + '" -Once >NUL 2>NUL') } catch {}
    }
    try { [void](Invoke-AfitgirlAria2Rpc -Method 'aria2.saveSession' -Params @() -TimeoutSec 2) } catch {}
    Get-Process -Name aria2c,aria2c.real -ErrorAction SilentlyContinue | Stop-Process -Force -ErrorAction SilentlyContinue
    Start-Sleep -Milliseconds 700
    $stamp = Get-Date -Format 'yyyyMMddHHmmss'
    $safeDir = Join-Path 'F:\Downloads\.fitgirl_tmp' ("aria2-stale-state-$stamp")
    New-Item -ItemType Directory -Force -Path $safeDir | Out-Null
    if (Test-Path -LiteralPath $sessionPath -PathType Leaf) {
        Copy-Item -LiteralPath $sessionPath -Destination (Join-Path $safeDir 'aria2.session.backup') -Force -ErrorAction SilentlyContinue
    }
    foreach ($dht in @((Join-Path $env:USERPROFILE '.cache\aria2\dht.dat'),(Join-Path $env:USERPROFILE '.cache\aria2\dht6.dat'))) {
        if (Test-Path -LiteralPath $dht -PathType Leaf) { Move-Item -LiteralPath $dht -Destination (Join-Path $safeDir (Split-Path -Leaf $dht)) -Force -ErrorAction SilentlyContinue }
    }
    Get-ChildItem -LiteralPath 'F:\Downloads' -Filter '*.aria2' -File -ErrorAction SilentlyContinue | ForEach-Object {
        Move-Item -LiteralPath $_.FullName -Destination (Join-Path $safeDir $_.Name) -Force -ErrorAction SilentlyContinue
    }
    $args = @(
        '--enable-rpc','--rpc-listen-all=false','--rpc-listen-port=6899','--dir=F:\Downloads',
        '--input-file',$sessionPath,'--save-session',$sessionPath,'--save-session-interval=10','--auto-save-interval=10',
        '--continue=true','--allow-overwrite=true','--auto-file-renaming=false','--file-allocation=none','--disk-cache=128M',
        '--max-concurrent-downloads=16','--max-connection-per-server=16','--split=16','--min-split-size=1M',
        '--connect-timeout=8','--timeout=20','--max-tries=0','--retry-wait=2','--listen-port=6881',
        '--bt-max-peers=1000','--bt-request-peer-speed-limit=1K','--enable-dht=true','--enable-peer-exchange=true','--bt-enable-lpd=true',
        '--bt-save-metadata=true','--bt-load-saved-metadata=true','--bt-remove-unselected-file=true','--seed-ratio=0','--seed-time=0',
        '--max-overall-download-limit=0','--max-download-limit=0','--max-overall-upload-limit=0','--max-upload-limit=0',
        '--bt-tracker',$trackerList,'--log',$logPath,'--log-level=warn'
    )
    if (Test-Path -LiteralPath $completeHook -PathType Leaf) { $args += @('--on-download-complete',$completeHook) }
    Start-Process -FilePath $aria2Exe -ArgumentList $args -WindowStyle Hidden | Out-Null
    Start-Sleep -Seconds 5
    Write-Host ("[afitgirl] restarted aria2 max-speed worker: {0}" -f $Reason)
}

if ($MyInvocation.InvocationName -ne '.') {
    & 'Restart-AfitgirlAria2MaxSpeed' @args
}
