# Generated by 2sc from function 'rmackback' (2026-08-13 00:47:32).
# Self-bootstrap: load the profile environment when this script runs
# outside a profile session so it behaves exactly like the function it
# was copied from. The module is also force-re-imported when the copy
# loaded in this process is stale (psm1 changed on disk) so a long-
# running session never runs an outdated dispatcher.
$__2scProfileModule = 'C:\Users\micha\Documents\WindowsPowerShell\Modules\CodexProfileFunctions\CodexProfileFunctions.psd1'
$__2scNeedBootstrap = -not (Get-Command -Name 'Initialize-CodexProfileFunctions' -CommandType Function -ErrorAction SilentlyContinue)
if (-not $__2scNeedBootstrap) {
    $__2scLoadedModule = Get-Module -Name 'CodexProfileFunctions' -ErrorAction SilentlyContinue | Select-Object -First 1
    if ($__2scLoadedModule) {
        $__2scLoadedFingerprint = $__2scLoadedModule.SessionState.PSVariable.GetValue('ProfileModuleFingerprint')
        $__2scModuleFile = Join-Path $__2scLoadedModule.ModuleBase 'CodexProfileFunctions.psm1'
        if ([System.IO.File]::Exists($__2scModuleFile)) {
            $__2scDiskInfo = Get-Item -LiteralPath $__2scModuleFile -ErrorAction SilentlyContinue
            if ($__2scDiskInfo) {
                $__2scDiskFingerprint = '{0}|{1}' -f $__2scDiskInfo.Length, $__2scDiskInfo.LastWriteTimeUtc.Ticks
                if ([string]$__2scLoadedFingerprint -and $__2scDiskFingerprint -ne [string]$__2scLoadedFingerprint) { $__2scNeedBootstrap = $true }
            }
        }
    }
}
if ($__2scNeedBootstrap) {
    if (-not (Test-Path -LiteralPath $__2scProfileModule -PathType Leaf)) {
        throw "2sc-generated script requires the Codex profile module: $__2scProfileModule"
    }
    Import-Module -Name $__2scProfileModule -Force -DisableNameChecking -ErrorAction Stop
    Initialize-CodexProfileFunctions
}
function rmackback {
    $script = 'F:\study\Devops\backup\MacriumReflect\DisableGuardPurgeBackups\CleanupBackups.ps1'
    if (-not (Test-Path $script)) { Write-Host "ERROR: CleanupBackups.ps1 not found at $script" -ForegroundColor Red; return }
    & $script
    Write-Host "`nPurge done. Starting Macrium Reflect backup immediately..." -ForegroundColor Cyan
    macback
    Start-Sleep -Seconds 3
    $newBackup = Get-ChildItem 'F:\win11recovery' -Recurse -Force -ErrorAction SilentlyContinue | Select-Object -First 1
    if ($newBackup) { Write-Host "SUCCESS: New backup found -> $($newBackup.Name)" -ForegroundColor Green }
    else { Write-Host "WARNING: No backup file detected yet in F:\win11recovery (backup may still be running)" -ForegroundColor Yellow }
}

if ($MyInvocation.InvocationName -ne '.') {
    & 'rmackback' @args
}
