# Generated by 2sc from function 'rmrmcc' (2026-08-13 00:40:37).
# Self-bootstrap: load the profile environment when this script runs
# outside a profile session so it behaves exactly like the function it
# was copied from. The module is also force-re-imported when the copy
# loaded in this process is stale (psm1 changed on disk) so a long-
# running session never runs an outdated dispatcher.
$__2scProfileModule = 'C:\Users\micha\Documents\WindowsPowerShell\Modules\CodexProfileFunctions\CodexProfileFunctions.psd1'
$__2scNeedBootstrap = -not (Get-Command -Name 'Initialize-CodexProfileFunctions' -CommandType Function -ErrorAction SilentlyContinue)
if (-not $__2scNeedBootstrap) {
    $__2scLoadedModule = Get-Module -Name 'CodexProfileFunctions' -ErrorAction SilentlyContinue | Select-Object -First 1
    if ($__2scLoadedModule) {
        $__2scLoadedFingerprint = $__2scLoadedModule.SessionState.PSVariable.GetValue('ProfileModuleFingerprint')
        $__2scModuleFile = Join-Path $__2scLoadedModule.ModuleBase 'CodexProfileFunctions.psm1'
        if ([System.IO.File]::Exists($__2scModuleFile)) {
            $__2scDiskInfo = Get-Item -LiteralPath $__2scModuleFile -ErrorAction SilentlyContinue
            if ($__2scDiskInfo) {
                $__2scDiskFingerprint = '{0}|{1}' -f $__2scDiskInfo.Length, $__2scDiskInfo.LastWriteTimeUtc.Ticks
                if ([string]$__2scLoadedFingerprint -and $__2scDiskFingerprint -ne [string]$__2scLoadedFingerprint) { $__2scNeedBootstrap = $true }
            }
        }
    }
}
if ($__2scNeedBootstrap) {
    if (-not (Test-Path -LiteralPath $__2scProfileModule -PathType Leaf)) {
        throw "2sc-generated script requires the Codex profile module: $__2scProfileModule"
    }
    Import-Module -Name $__2scProfileModule -Force -DisableNameChecking -ErrorAction Stop
    Initialize-CodexProfileFunctions
}
function rmrmcc {
    [CmdletBinding()]
    param()
    global:Invoke-CcRequireAdmin
    if (-not ('Hermes.CcSrClient' -as [type])) {
        Add-Type -TypeDefinition @'
using System;
using System.Runtime.InteropServices;
namespace Hermes {
  public static class CcSrClient {
    [DllImport("SrClient.dll", SetLastError=true)]
    public static extern int SRRemoveRestorePoint(int dwRPNum);
  }
}
'@
    }
    $points = @(Get-ComputerRestorePoint | Sort-Object SequenceNumber -Descending)
    if ($points.Count -eq 0) {
        Write-Host 'No restore points to delete.'
        return
    }
    foreach ($point in $points) {
        $seq = [int]$point.SequenceNumber
        $rc = [Hermes.CcSrClient]::SRRemoveRestorePoint($seq)
        if ($rc -eq 0) {
            Write-Host ("Deleted restore point #{0}: {1}" -f $seq, $point.Description)
        } else {
            Write-Warning ("Failed to delete restore point #{0}; SRRemoveRestorePoint returned {1}" -f $seq, $rc)
        }
    }
    Write-Host 'rmrmcc finished deleting available restore points.'
}

if ($MyInvocation.InvocationName -ne '.') {
    & 'rmrmcc' @args
}
