# Generated by 2sc from function 'speed' (2026-08-13 00:38:47).
# Self-bootstrap: load the profile environment when this script runs
# outside a profile session so it behaves exactly like the function it
# was copied from. The module is also force-re-imported when the copy
# loaded in this process is stale (psm1 changed on disk) so a long-
# running session never runs an outdated dispatcher.
$__2scProfileModule = 'C:\Users\micha\Documents\WindowsPowerShell\Modules\CodexProfileFunctions\CodexProfileFunctions.psd1'
$__2scNeedBootstrap = -not (Get-Command -Name 'Initialize-CodexProfileFunctions' -CommandType Function -ErrorAction SilentlyContinue)
if (-not $__2scNeedBootstrap) {
    $__2scLoadedModule = Get-Module -Name 'CodexProfileFunctions' -ErrorAction SilentlyContinue | Select-Object -First 1
    if ($__2scLoadedModule) {
        $__2scLoadedFingerprint = $__2scLoadedModule.SessionState.PSVariable.GetValue('ProfileModuleFingerprint')
        $__2scModuleFile = Join-Path $__2scLoadedModule.ModuleBase 'CodexProfileFunctions.psm1'
        if ([System.IO.File]::Exists($__2scModuleFile)) {
            $__2scDiskInfo = Get-Item -LiteralPath $__2scModuleFile -ErrorAction SilentlyContinue
            if ($__2scDiskInfo) {
                $__2scDiskFingerprint = '{0}|{1}' -f $__2scDiskInfo.Length, $__2scDiskInfo.LastWriteTimeUtc.Ticks
                if ([string]$__2scLoadedFingerprint -and $__2scDiskFingerprint -ne [string]$__2scLoadedFingerprint) { $__2scNeedBootstrap = $true }
            }
        }
    }
}
if ($__2scNeedBootstrap) {
    if (-not (Test-Path -LiteralPath $__2scProfileModule -PathType Leaf)) {
        throw "2sc-generated script requires the Codex profile module: $__2scProfileModule"
    }
    Import-Module -Name $__2scProfileModule -Force -DisableNameChecking -ErrorAction Stop
    Initialize-CodexProfileFunctions
}
function speed {
    # 2026-06-01: hardened resolver; ignore broken WinGet zero-byte/app-execution-alias stubs and self-repair Ookla CLI.
    param(
        [Parameter(ValueFromRemainingArguments = $true)]
        [string[]] $ArgumentList
    )

    $installRoot = Join-Path $env:LOCALAPPDATA 'Programs\OoklaSpeedtestCLI'
    $installExe = Join-Path $installRoot 'speedtest.exe'
    $zipPath = Join-Path $env:TEMP 'ookla-speedtest-1.2.0-win64.zip'
    $url = 'https://install.speedtest.net/app/cli/ookla-speedtest-1.2.0-win64.zip'
    $expectedSha256 = '13E3D888B845D301A556419E31F14AB9BFF57E3F06089EF2FD3BDC9BA6841EFA'

    function Write-SpeedtestProgress {
        param([int] $PercentComplete, [string] $Status)
        Write-Progress -Id 768 -Activity 'Speedtest CLI' -Status $Status -PercentComplete $PercentComplete
    }

    Write-SpeedtestProgress 10 'Checking managed Speedtest CLI installation'
    try {
    function Test-SpeedtestCliExecutable {
& 'F:\study\Platforms\windows\functions\Test-SpeedtestCliExecutable.ps1' @args
}

    function Install-SpeedtestCliExecutable {
        if (-not (Test-Path -LiteralPath $installRoot -PathType Container)) {
            New-Item -ItemType Directory -Force -Path $installRoot | Out-Null
        }
        $extractRoot = Join-Path $env:TEMP ('ookla-speedtest-extract-' + [Guid]::NewGuid().ToString('N'))
        if (Test-Path -LiteralPath $zipPath -PathType Leaf) { Remove-Item -LiteralPath $zipPath -Force -ErrorAction SilentlyContinue }
        [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
        Write-SpeedtestProgress 50 'Downloading verified Ookla CLI package'
        Invoke-WebRequest -Uri $url -OutFile $zipPath -UseBasicParsing -ErrorAction Stop
        Write-SpeedtestProgress 65 'Verifying download hash'
        $actualSha256 = (Get-FileHash -LiteralPath $zipPath -Algorithm SHA256).Hash.ToUpperInvariant()
        if ($actualSha256 -ne $expectedSha256) { throw "Speedtest CLI download hash mismatch: $actualSha256" }
        Add-Type -AssemblyName System.IO.Compression.FileSystem
        New-Item -ItemType Directory -Force -Path $extractRoot | Out-Null
        try {
            Write-SpeedtestProgress 75 'Extracting verified Ookla CLI package'
            [System.IO.Compression.ZipFile]::ExtractToDirectory($zipPath, $extractRoot)
            $extractedExe = Join-Path $extractRoot 'speedtest.exe'
            if (-not (Test-Path -LiteralPath $extractedExe -PathType Leaf)) { throw "Speedtest CLI zip did not contain speedtest.exe" }
            Copy-Item -LiteralPath $extractedExe -Destination $installExe -Force
            $license = Join-Path $extractRoot 'speedtest.md'
            if (Test-Path -LiteralPath $license -PathType Leaf) { Copy-Item -LiteralPath $license -Destination (Join-Path $installRoot 'speedtest.md') -Force }
        } finally {
            Remove-Item -LiteralPath $extractRoot -Recurse -Force -ErrorAction SilentlyContinue
        }
        Write-SpeedtestProgress 85 'Verifying installed CLI'
        if (-not (Test-SpeedtestCliExecutable -Path $installExe)) { throw "Installed Speedtest CLI is not executable: $installExe" }
        $userPath = [Environment]::GetEnvironmentVariable('Path','User')
        $pathParts = @($userPath -split ';' | Where-Object { $_ })
        if ($pathParts -notcontains $installRoot) {
            [Environment]::SetEnvironmentVariable('Path', (($pathParts + $installRoot) -join ';'), 'User')
        }
        $envParts = @($env:Path -split ';' | Where-Object { $_ })
        if ($envParts -notcontains $installRoot) { $env:Path = (($envParts + $installRoot) -join ';') }
        return $installExe
    }

    $cli = $null
    if (Test-SpeedtestCliExecutable -Path $installExe) { $cli = $installExe }
    if (-not $cli) {
        Write-SpeedtestProgress 25 'Checking other Speedtest CLI installations'
        $commands = @(Get-Command speedtest.exe -CommandType Application -ErrorAction SilentlyContinue)
        foreach ($cmd in $commands) {
            if ($cmd -and $cmd.Source -and $cmd.Source -ne $installExe -and (Test-SpeedtestCliExecutable -Path $cmd.Source)) {
                $cli = $cmd.Source
                break
            }
        }
    }
    if (-not $cli) {
        Write-SpeedtestProgress 40 'No usable CLI found; preparing verified installation'
        $cli = Install-SpeedtestCliExecutable
    }

    Write-SpeedtestProgress 95 'Starting Speedtest CLI'
    if ($ArgumentList -and $ArgumentList.Count -gt 0) {
        & $cli @ArgumentList
        return
    }

    & $cli --version
    & $cli --accept-license --accept-gdpr
    } finally {
        Write-Progress -Id 768 -Activity 'Speedtest CLI' -Completed
    }
}

if ($MyInvocation.InvocationName -ne '.') {
    & 'speed' @args
}
