# Generated by 2sc from function 'Start-DKillFastBackendHeadless' (2026-08-13 00:47:24).
# Self-bootstrap: load the profile environment when this script runs
# outside a profile session so it behaves exactly like the function it
# was copied from. The module is also force-re-imported when the copy
# loaded in this process is stale (psm1 changed on disk) so a long-
# running session never runs an outdated dispatcher.
$__2scProfileModule = 'C:\Users\micha\Documents\WindowsPowerShell\Modules\CodexProfileFunctions\CodexProfileFunctions.psd1'
$__2scNeedBootstrap = -not (Get-Command -Name 'Initialize-CodexProfileFunctions' -CommandType Function -ErrorAction SilentlyContinue)
if (-not $__2scNeedBootstrap) {
    $__2scLoadedModule = Get-Module -Name 'CodexProfileFunctions' -ErrorAction SilentlyContinue | Select-Object -First 1
    if ($__2scLoadedModule) {
        $__2scLoadedFingerprint = $__2scLoadedModule.SessionState.PSVariable.GetValue('ProfileModuleFingerprint')
        $__2scModuleFile = Join-Path $__2scLoadedModule.ModuleBase 'CodexProfileFunctions.psm1'
        if ([System.IO.File]::Exists($__2scModuleFile)) {
            $__2scDiskInfo = Get-Item -LiteralPath $__2scModuleFile -ErrorAction SilentlyContinue
            if ($__2scDiskInfo) {
                $__2scDiskFingerprint = '{0}|{1}' -f $__2scDiskInfo.Length, $__2scDiskInfo.LastWriteTimeUtc.Ticks
                if ([string]$__2scLoadedFingerprint -and $__2scDiskFingerprint -ne [string]$__2scLoadedFingerprint) { $__2scNeedBootstrap = $true }
            }
        }
    }
}
if ($__2scNeedBootstrap) {
    if (-not (Test-Path -LiteralPath $__2scProfileModule -PathType Leaf)) {
        throw "2sc-generated script requires the Codex profile module: $__2scProfileModule"
    }
    Import-Module -Name $__2scProfileModule -Force -DisableNameChecking -ErrorAction Stop
    Initialize-CodexProfileFunctions
}
function Start-DKillFastBackendHeadless {
    [CmdletBinding()]
    param([string]$DockerExe)
    $backendExe=Join-Path ${env:ProgramFiles} 'Docker\Docker\resources\com.docker.backend.exe'
    if(-not(Test-Path -LiteralPath $backendExe)){Write-DKillFastLine ("DKILL_BACKEND_START_FAIL backend not found: {0}" -f $backendExe) Red;return $false}
    Write-Progress -Activity 'Docker launch' -Status 'Starting Docker backend headlessly' -PercentComplete 65
    $failures=@()
    if($script:DKillFastIsAdmin){foreach($serviceName in @('vmms','vmcompute','hns','com.docker.service')){try{Set-Service -Name $serviceName -StartupType Automatic -ErrorAction Stop;Invoke-DKillFastSc -Action start -ServiceName $serviceName -Milliseconds 140}catch{$failures+=$_.Exception.Message;Write-DKillFastLine ("DKILL_BACKEND_START_WARN service={0}: {1}" -f $serviceName,$_.Exception.Message) Yellow}}}
    try{New-Item -ItemType Directory -Force -Path 'C:\ProgramData\DockerDesktop\vm-data' -ErrorAction Stop|Out-Null}catch{$failures+=$_.Exception.Message;Write-DKillFastLine ("DKILL_BACKEND_START_WARN vm-data directory: {0}" -f $_.Exception.Message) Yellow}
    $started=Start-DKillFastHiddenProcess -FilePath $backendExe -ArgumentList @('-unattended','-with-frontend=false','-accept-license','-engine','HyperV');Write-Progress -Activity 'Docker launch' -Completed;if($started){Write-DKillFastLine ("DKILL_BACKEND_START_OK warnings={0}" -f $failures.Count) Green;return $true};return $false
}

if ($MyInvocation.InvocationName -ne '.') {
    & 'Start-DKillFastBackendHeadless' @args
}
