# Generated by 2sc from function 'Start-AfitgirlMinuteMonitor' (2026-08-13 00:38:50).
# Self-bootstrap: load the profile environment when this script runs
# outside a profile session so it behaves exactly like the function it
# was copied from. The module is also force-re-imported when the copy
# loaded in this process is stale (psm1 changed on disk) so a long-
# running session never runs an outdated dispatcher.
$__2scProfileModule = 'C:\Users\micha\Documents\WindowsPowerShell\Modules\CodexProfileFunctions\CodexProfileFunctions.psd1'
$__2scNeedBootstrap = -not (Get-Command -Name 'Initialize-CodexProfileFunctions' -CommandType Function -ErrorAction SilentlyContinue)
if (-not $__2scNeedBootstrap) {
    $__2scLoadedModule = Get-Module -Name 'CodexProfileFunctions' -ErrorAction SilentlyContinue | Select-Object -First 1
    if ($__2scLoadedModule) {
        $__2scLoadedFingerprint = $__2scLoadedModule.SessionState.PSVariable.GetValue('ProfileModuleFingerprint')
        $__2scModuleFile = Join-Path $__2scLoadedModule.ModuleBase 'CodexProfileFunctions.psm1'
        if ([System.IO.File]::Exists($__2scModuleFile)) {
            $__2scDiskInfo = Get-Item -LiteralPath $__2scModuleFile -ErrorAction SilentlyContinue
            if ($__2scDiskInfo) {
                $__2scDiskFingerprint = '{0}|{1}' -f $__2scDiskInfo.Length, $__2scDiskInfo.LastWriteTimeUtc.Ticks
                if ([string]$__2scLoadedFingerprint -and $__2scDiskFingerprint -ne [string]$__2scLoadedFingerprint) { $__2scNeedBootstrap = $true }
            }
        }
    }
}
if ($__2scNeedBootstrap) {
    if (-not (Test-Path -LiteralPath $__2scProfileModule -PathType Leaf)) {
        throw "2sc-generated script requires the Codex profile module: $__2scProfileModule"
    }
    Import-Module -Name $__2scProfileModule -Force -DisableNameChecking -ErrorAction Stop
    Initialize-CodexProfileFunctions
}
function Start-AfitgirlMinuteMonitor {
    [CmdletBinding()]
    param(
        [ValidateRange(0, 100000)][int] $MinimumActive = 16,
        [ValidateRange(0, 100000)][int] $MinimumTotalSpeedMBps = 40
    )

    $ps5 = Join-Path $env:SystemRoot 'System32\WindowsPowerShell\v1.0\powershell.exe'
    $profilePath = 'C:\Users\micha\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1'
    $logDir = 'F:\Downloads\.fitgirl_tmp'
    if (-not (Test-Path -LiteralPath $logDir -PathType Container)) { New-Item -ItemType Directory -Force -Path $logDir | Out-Null }
    $logPath = Join-Path $logDir 'afitgirl-minute-speed-monitor.log'
    if (-not (Test-Path -LiteralPath $ps5 -PathType Leaf)) { throw "Windows PowerShell 5 missing: $ps5" }
    Get-CimInstance Win32_Process -ErrorAction SilentlyContinue |
        Where-Object {
            $_.Name -match 'powershell' -and $_.ProcessId -ne $PID -and
            ('' + $_.CommandLine) -match 'AfitgirlMinuteSpeedMonitorV4|afitgirl-minute-speed-monitor'
        } |
        ForEach-Object {
            try {
                Write-Host ("AFIT_MINUTE_MONITOR_PROGRESS stage=stopping-prior-monitor pid={0}" -f $_.ProcessId) -ForegroundColor Cyan
                Stop-Process -Id $_.ProcessId -Force -ErrorAction Stop
            } catch {
                Write-Warning ("AFIT_MINUTE_MONITOR_WARN prior_pid={0} error={1}" -f $_.ProcessId, $_.Exception.Message)
            }
        }

    $code = @"
`$ErrorActionPreference = 'Continue'
`$marker = 'afitgirl-minute-speed-monitor'
`$mutex = New-Object System.Threading.Mutex(`$false, 'Global\AfitgirlMinuteSpeedMonitorV4')
if (-not `$mutex.WaitOne(0)) { return }
try {
    . '$profilePath'
    Add-Content -LiteralPath '$logPath' -Value ((Get-Date -Format s) + ' monitor v4 started; target-active=$MinimumActive target-speed-mbps=$MinimumTotalSpeedMBps') -Encoding UTF8
    `$lastBridge = [datetime]::MinValue
    `$lastLog = [datetime]::MinValue
    while (`$true) {
        try {
            `$now = Get-Date
            `$s = Invoke-AfitgirlDownloadPolicy -MinimumActive $MinimumActive -MinimumTotalSpeedMBps $MinimumTotalSpeedMBps -Quiet
            `$perTitle = @()
            try {
                foreach(`$item in @((Invoke-AfitgirlAria2Rpc -Method 'aria2.tellActive' -Params @() -TimeoutSec 8).result)){
                    `$name = ''
                    try { if(`$item.bittorrent -and `$item.bittorrent.info -and `$item.bittorrent.info.name){ `$name = '' + `$item.bittorrent.info.name } } catch {}
                    if([string]::IsNullOrWhiteSpace(`$name)){
                        try { foreach(`$f in @(`$item.files)){ if(`$f.path){ `$name = Split-Path -Leaf (Split-Path -Parent ('' + `$f.path)); break } } } catch {}
                    }
                    if([string]::IsNullOrWhiteSpace(`$name)){ `$name = '' + `$item.gid }
                    `$spd = 0L; try { `$spd = [int64]`$item.downloadSpeed } catch {}
                    `$done = 0L; `$total = 0L; try { `$done = [int64]`$item.completedLength; `$total = [int64]`$item.totalLength } catch {}
                    `$pct = if(`$total -gt 0){ [math]::Round((100.0 * `$done / `$total), 2) } else { 0 }
                    `$perTitle += (('{0}={1}MB/s {2}%' -f `$name,[math]::Round((`$spd/1MB),2),`$pct))
                }
            } catch { `$perTitle += ('per-title-speed-warning=' + `$_.Exception.Message) }
            try { Invoke-AfitgirlVisibleDownloadsRepair -Reason 'live monitor refresh' | Out-Null } catch { Add-Content -LiteralPath '$logPath' -Value ((Get-Date -Format s) + ' visible refresh warning: ' + `$_.Exception.Message) -Encoding UTF8 }
            if (((`$now - `$lastLog).TotalSeconds -ge 10)) {
                Add-Content -LiteralPath '$logPath' -Value ((Get-Date -Format s) + (' active={0} waiting={1} stopped={2} total_speed={3}MB/s target={4}MB/s status={5}; titles: {6}' -f `$s.Active,`$s.Waiting,`$s.Stopped,`$s.SpeedMBps,`$s.TargetMBps,`$s.Status,(`$perTitle -join ' | '))) -Encoding UTF8
                `$lastLog = `$now
            }
        } catch {
            Add-Content -LiteralPath '$logPath' -Value ((Get-Date -Format s) + ' monitor warning: ' + `$_.Exception.Message) -Encoding UTF8
        }
        Start-Sleep -Seconds 10
    }
} finally {
    try { `$mutex.ReleaseMutex() } catch {}
    try { `$mutex.Dispose() } catch {}
}
"@
    $childPath = Join-Path $logDir 'AfitgirlMinuteSpeedMonitorV4.ps1'
    [IO.File]::WriteAllText($childPath, $code, [Text.Encoding]::UTF8)
    $process = Start-Process -FilePath $ps5 -ArgumentList @('-NoProfile','-ExecutionPolicy','Bypass','-WindowStyle','Hidden','-File',$childPath) -WindowStyle Hidden -PassThru -ErrorAction Stop
    Write-Host ("AFIT_MINUTE_MONITOR_OK pid={0} log={1} script={2}" -f $process.Id, $logPath, $childPath) -ForegroundColor Green
    return [pscustomobject]@{ ProcessId = $process.Id; LogPath = $logPath; ScriptPath = $childPath }
}

if ($MyInvocation.InvocationName -ne '.') {
    & 'Start-AfitgirlMinuteMonitor' @args
}
