# Generated by 2sc from function 'Start-DKillFastDockerHeadless' (2026-08-13 00:43:22).
# Self-bootstrap: load the profile environment when this script runs
# outside a profile session so it behaves exactly like the function it
# was copied from. The module is also force-re-imported when the copy
# loaded in this process is stale (psm1 changed on disk) so a long-
# running session never runs an outdated dispatcher.
$__2scProfileModule = 'C:\Users\micha\Documents\WindowsPowerShell\Modules\CodexProfileFunctions\CodexProfileFunctions.psd1'
$__2scNeedBootstrap = -not (Get-Command -Name 'Initialize-CodexProfileFunctions' -CommandType Function -ErrorAction SilentlyContinue)
if (-not $__2scNeedBootstrap) {
    $__2scLoadedModule = Get-Module -Name 'CodexProfileFunctions' -ErrorAction SilentlyContinue | Select-Object -First 1
    if ($__2scLoadedModule) {
        $__2scLoadedFingerprint = $__2scLoadedModule.SessionState.PSVariable.GetValue('ProfileModuleFingerprint')
        $__2scModuleFile = Join-Path $__2scLoadedModule.ModuleBase 'CodexProfileFunctions.psm1'
        if ([System.IO.File]::Exists($__2scModuleFile)) {
            $__2scDiskInfo = Get-Item -LiteralPath $__2scModuleFile -ErrorAction SilentlyContinue
            if ($__2scDiskInfo) {
                $__2scDiskFingerprint = '{0}|{1}' -f $__2scDiskInfo.Length, $__2scDiskInfo.LastWriteTimeUtc.Ticks
                if ([string]$__2scLoadedFingerprint -and $__2scDiskFingerprint -ne [string]$__2scLoadedFingerprint) { $__2scNeedBootstrap = $true }
            }
        }
    }
}
if ($__2scNeedBootstrap) {
    if (-not (Test-Path -LiteralPath $__2scProfileModule -PathType Leaf)) {
        throw "2sc-generated script requires the Codex profile module: $__2scProfileModule"
    }
    Import-Module -Name $__2scProfileModule -Force -DisableNameChecking -ErrorAction Stop
    Initialize-CodexProfileFunctions
}
function Start-DKillFastDockerHeadless {
    [CmdletBinding()]
    param([Parameter(Mandatory)][string]$DockerExe,[string]$Reason = 'headless restart')
    if($NoLaunch -or $WhatIfPreference -or $script:DKillFastEarlyLaunchStarted) { Write-DKillFastLine 'DKILL_HEADLESS_START_SKIP launch disabled or already started' DarkGray; return $false }
    $failures=@()
    Write-Progress -Activity 'Docker launch' -Status 'Preparing headless Docker services' -PercentComplete 20
    if($script:DKillFastIsAdmin){foreach($serviceName in @('vmms','vmcompute','hns','com.docker.service')){try{Set-Service -Name $serviceName -StartupType Automatic -ErrorAction Stop;Invoke-DKillFastSc -Action start -ServiceName $serviceName -Milliseconds 250}catch{$failures+=$_.Exception.Message;Write-DKillFastLine ("DKILL_HEADLESS_START_WARN service={0}: {1}" -f $serviceName,$_.Exception.Message) Yellow}}}
    $serviceOnlyReady=$false
    try{$serviceDeadline=(Get-Date).AddMilliseconds([Math]::Max(80,[Math]::Min(250,(Get-DKillFastRemainingMilliseconds)-900)));while((Get-Date)-lt$serviceDeadline){if(Test-DKillFastDockerReady -DockerExe $DockerExe){$serviceOnlyReady=$true;break};Start-Sleep -Milliseconds 120}}catch{$failures+=$_.Exception.Message;Write-DKillFastLine ("DKILL_HEADLESS_START_WARN readiness probe: {0}" -f $_.Exception.Message) Yellow}
    if($serviceOnlyReady){$script:DKillFastEarlyLaunchStarted=$true;Write-Progress -Activity 'Docker launch' -Completed;Write-DKillFastLine ("DKILL_HEADLESS_START_OK service-only reason={0} warnings={1}" -f $Reason,$failures.Count) Green;return $true}
    Write-Progress -Activity 'Docker launch' -Status 'Trying Docker Desktop CLI launch' -PercentComplete 60
    if(Start-DKillFastDockerDesktopCli -DockerExe $DockerExe){$script:DKillFastEarlyLaunchStarted=$true;Write-Progress -Activity 'Docker launch' -Completed;Write-DKillFastLine ("DKILL_HEADLESS_START_OK cli reason={0} warnings={1}" -f $Reason,$failures.Count) Green;return $true}
    Write-Progress -Activity 'Docker launch' -Status 'Trying Docker backend launch' -PercentComplete 80
    if(Start-DKillFastBackendHeadless -DockerExe $DockerExe){$script:DKillFastEarlyLaunchStarted=$true;Write-Progress -Activity 'Docker launch' -Completed;Write-DKillFastLine ("DKILL_HEADLESS_START_OK backend reason={0} warnings={1}" -f $Reason,$failures.Count) Green;return $true}
    Write-Progress -Activity 'Docker launch' -Completed;Write-DKillFastLine ("DKILL_HEADLESS_START_FAIL reason={0} warnings={1}" -f $Reason,$failures.Count) Red;return $false
}

if ($MyInvocation.InvocationName -ne '.') {
    & 'Start-DKillFastDockerHeadless' @args
}
