# Generated by 2sc from function 'terminaladmin' (2026-08-13 00:39:17).
# Self-bootstrap: load the profile environment when this script runs
# outside a profile session so it behaves exactly like the function it
# was copied from. The module is also force-re-imported when the copy
# loaded in this process is stale (psm1 changed on disk) so a long-
# running session never runs an outdated dispatcher.
$__2scProfileModule = 'C:\Users\micha\Documents\WindowsPowerShell\Modules\CodexProfileFunctions\CodexProfileFunctions.psd1'
$__2scNeedBootstrap = -not (Get-Command -Name 'Initialize-CodexProfileFunctions' -CommandType Function -ErrorAction SilentlyContinue)
if (-not $__2scNeedBootstrap) {
    $__2scLoadedModule = Get-Module -Name 'CodexProfileFunctions' -ErrorAction SilentlyContinue | Select-Object -First 1
    if ($__2scLoadedModule) {
        $__2scLoadedFingerprint = $__2scLoadedModule.SessionState.PSVariable.GetValue('ProfileModuleFingerprint')
        $__2scModuleFile = Join-Path $__2scLoadedModule.ModuleBase 'CodexProfileFunctions.psm1'
        if ([System.IO.File]::Exists($__2scModuleFile)) {
            $__2scDiskInfo = Get-Item -LiteralPath $__2scModuleFile -ErrorAction SilentlyContinue
            if ($__2scDiskInfo) {
                $__2scDiskFingerprint = '{0}|{1}' -f $__2scDiskInfo.Length, $__2scDiskInfo.LastWriteTimeUtc.Ticks
                if ([string]$__2scLoadedFingerprint -and $__2scDiskFingerprint -ne [string]$__2scLoadedFingerprint) { $__2scNeedBootstrap = $true }
            }
        }
    }
}
if ($__2scNeedBootstrap) {
    if (-not (Test-Path -LiteralPath $__2scProfileModule -PathType Leaf)) {
        throw "2sc-generated script requires the Codex profile module: $__2scProfileModule"
    }
    Import-Module -Name $__2scProfileModule -Force -DisableNameChecking -ErrorAction Stop
    Initialize-CodexProfileFunctions
}
function terminaladmin {
    [CmdletBinding()]
    param(
        [switch]$NoLaunch
    )

    $toolDirectory = 'C:\Users\micha\.codex\tools\terminal'
    $repairScript = Join-Path $toolDirectory 'Repair-AdminWindowsTerminal.ps1'
    $launchScript = Join-Path $toolDirectory 'Launch-AdminWindowsTerminal.ps1'
    $windowsPowerShell = Join-Path $env:SystemRoot 'System32\WindowsPowerShell\v1.0\powershell.exe'
    $packagedSettingsPath = Join-Path $env:LOCALAPPDATA 'Packages\Microsoft.WindowsTerminal_8wekyb3d8bbwe\LocalState\settings.json'

    foreach ($requiredPath in @($repairScript, $launchScript, $windowsPowerShell, $packagedSettingsPath)) {
        if (-not (Test-Path -LiteralPath $requiredPath -PathType Leaf)) {
            throw "terminaladmin dependency is missing: $requiredPath"
        }
    }

    & $windowsPowerShell -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Bypass -File $repairScript 0
    if ($LASTEXITCODE -ne 0) {
        throw "Windows Terminal administrator repair failed with exit code $LASTEXITCODE."
    }

    Get-Process -Name 'elevate-shim' -ErrorAction SilentlyContinue |
        Stop-Process -Force -ErrorAction SilentlyContinue

    $packagedSettings = Get-Content -LiteralPath $packagedSettingsPath -Raw | ConvertFrom-Json
    if ($packagedSettings.profiles.defaults.elevate -ne $false) {
        throw 'The packaged Windows Terminal elevation shim is still enabled.'
    }

    if ($NoLaunch) {
        return [pscustomobject]@{
            Enforcement = 'Enabled'
            PackagedElevation = $false
            Launched = $false
        }
    }

    $launchResult = & $launchScript -StartingDirectory $PWD.Path
    if (-not $launchResult -or $launchResult.Elevated -ne $true) {
        throw 'The administrator Terminal task did not acknowledge an elevated launch.'
    }

    [pscustomobject]@{
        Enforcement = 'Enabled'
        PackagedElevation = $false
        Launched = $true
        Elevated = $true
        Terminal = $launchResult.Terminal
        ProcessId = $launchResult.ProcessId
        RequestId = $launchResult.RequestId
    }
}

if ($MyInvocation.InvocationName -ne '.') {
    & 'terminaladmin' @args
}
