# Generated by 2sc from function 'Test-SpeedtestCliExecutable' (2026-08-13 00:41:28).
# Self-bootstrap: load the profile environment when this script runs
# outside a profile session so it behaves exactly like the function it
# was copied from. The module is also force-re-imported when the copy
# loaded in this process is stale (psm1 changed on disk) so a long-
# running session never runs an outdated dispatcher.
$__2scProfileModule = 'C:\Users\micha\Documents\WindowsPowerShell\Modules\CodexProfileFunctions\CodexProfileFunctions.psd1'
$__2scNeedBootstrap = -not (Get-Command -Name 'Initialize-CodexProfileFunctions' -CommandType Function -ErrorAction SilentlyContinue)
if (-not $__2scNeedBootstrap) {
    $__2scLoadedModule = Get-Module -Name 'CodexProfileFunctions' -ErrorAction SilentlyContinue | Select-Object -First 1
    if ($__2scLoadedModule) {
        $__2scLoadedFingerprint = $__2scLoadedModule.SessionState.PSVariable.GetValue('ProfileModuleFingerprint')
        $__2scModuleFile = Join-Path $__2scLoadedModule.ModuleBase 'CodexProfileFunctions.psm1'
        if ([System.IO.File]::Exists($__2scModuleFile)) {
            $__2scDiskInfo = Get-Item -LiteralPath $__2scModuleFile -ErrorAction SilentlyContinue
            if ($__2scDiskInfo) {
                $__2scDiskFingerprint = '{0}|{1}' -f $__2scDiskInfo.Length, $__2scDiskInfo.LastWriteTimeUtc.Ticks
                if ([string]$__2scLoadedFingerprint -and $__2scDiskFingerprint -ne [string]$__2scLoadedFingerprint) { $__2scNeedBootstrap = $true }
            }
        }
    }
}
if ($__2scNeedBootstrap) {
    if (-not (Test-Path -LiteralPath $__2scProfileModule -PathType Leaf)) {
        throw "2sc-generated script requires the Codex profile module: $__2scProfileModule"
    }
    Import-Module -Name $__2scProfileModule -Force -DisableNameChecking -ErrorAction Stop
    Initialize-CodexProfileFunctions
}
function Test-SpeedtestCliExecutable {
        param([Parameter(Mandatory = $true)][string] $Path)
        try {
            if (-not (Test-Path -LiteralPath $Path -PathType Leaf)) { return $false }
            $item = Get-Item -LiteralPath $Path -Force -ErrorAction Stop
            if ($item.Length -lt 1024) { return $false }
            $fs = [System.IO.File]::Open($item.FullName, [System.IO.FileMode]::Open, [System.IO.FileAccess]::Read, [System.IO.FileShare]::ReadWrite)
            try {
                if ($fs.Length -lt 2) { return $false }
                $b1 = $fs.ReadByte(); $b2 = $fs.ReadByte()
                if ($b1 -ne 77 -or $b2 -ne 90) { return $false }
            } finally { $fs.Close() }
            $stdout = Join-Path $env:TEMP ('speedtest-probe-' + [Guid]::NewGuid().ToString('N') + '.out')
            $stderr = Join-Path $env:TEMP ('speedtest-probe-' + [Guid]::NewGuid().ToString('N') + '.err')
            try {
                $p = Start-Process -FilePath $item.FullName -ArgumentList '--version' -WorkingDirectory $env:TEMP -NoNewWindow -Wait -PassThru -RedirectStandardOutput $stdout -RedirectStandardError $stderr -ErrorAction Stop
                if ($p.ExitCode -ne 0) { return $false }
                return $true
            } finally {
                Remove-Item -LiteralPath $stdout,$stderr -Force -ErrorAction SilentlyContinue
            }
        } catch {
            return $false
        }
    }

if ($MyInvocation.InvocationName -ne '.') {
    & 'Test-SpeedtestCliExecutable' @args
}
