# Generated by 2sc from function 'Test-ReassTreeEqual' (2026-08-13 00:39:19).
# Self-bootstrap: load the profile environment when this script runs
# outside a profile session so it behaves exactly like the function it
# was copied from. The module is also force-re-imported when the copy
# loaded in this process is stale (psm1 changed on disk) so a long-
# running session never runs an outdated dispatcher.
$__2scProfileModule = 'C:\Users\micha\Documents\WindowsPowerShell\Modules\CodexProfileFunctions\CodexProfileFunctions.psd1'
$__2scNeedBootstrap = -not (Get-Command -Name 'Initialize-CodexProfileFunctions' -CommandType Function -ErrorAction SilentlyContinue)
if (-not $__2scNeedBootstrap) {
    $__2scLoadedModule = Get-Module -Name 'CodexProfileFunctions' -ErrorAction SilentlyContinue | Select-Object -First 1
    if ($__2scLoadedModule) {
        $__2scLoadedFingerprint = $__2scLoadedModule.SessionState.PSVariable.GetValue('ProfileModuleFingerprint')
        $__2scModuleFile = Join-Path $__2scLoadedModule.ModuleBase 'CodexProfileFunctions.psm1'
        if ([System.IO.File]::Exists($__2scModuleFile)) {
            $__2scDiskInfo = Get-Item -LiteralPath $__2scModuleFile -ErrorAction SilentlyContinue
            if ($__2scDiskInfo) {
                $__2scDiskFingerprint = '{0}|{1}' -f $__2scDiskInfo.Length, $__2scDiskInfo.LastWriteTimeUtc.Ticks
                if ([string]$__2scLoadedFingerprint -and $__2scDiskFingerprint -ne [string]$__2scLoadedFingerprint) { $__2scNeedBootstrap = $true }
            }
        }
    }
}
if ($__2scNeedBootstrap) {
    if (-not (Test-Path -LiteralPath $__2scProfileModule -PathType Leaf)) {
        throw "2sc-generated script requires the Codex profile module: $__2scProfileModule"
    }
    Import-Module -Name $__2scProfileModule -Force -DisableNameChecking -ErrorAction Stop
    Initialize-CodexProfileFunctions
}
function Test-ReassTreeEqual {
    param(
        [Parameter(Mandatory)]
        [string]$Expected,

        [Parameter(Mandatory)]
        [string]$Actual,

        [Parameter(Mandatory)]
        [string]$Stage,

        [Parameter(Mandatory)]
        [int]$ProgressStart,

        [Parameter(Mandatory)]
        [int]$ProgressEnd
    )

    $expectedRoot = [IO.Path]::GetFullPath($Expected).TrimEnd('\')
    $actualRoot = [IO.Path]::GetFullPath($Actual).TrimEnd('\')
    $expectedFiles = Get-ReassFiles -Path $expectedRoot
    $actualFiles = Get-ReassFiles -Path $actualRoot
    if ($expectedFiles.Count -ne $actualFiles.Count) {
        throw ("reass: verification failed at {0}; file count expected={1} actual={2}" -f $Stage, $expectedFiles.Count, $actualFiles.Count)
    }

    $actualMap = @{}
    foreach ($file in $actualFiles) {
        $actualMap[$file.FullName.Substring($actualRoot.Length).TrimStart('\')] = $file
    }

    for ($index = 0; $index -lt $expectedFiles.Count; $index++) {
        $expectedFile = $expectedFiles[$index]
        $relative = $expectedFile.FullName.Substring($expectedRoot.Length).TrimStart('\')
        if (-not $actualMap.ContainsKey($relative)) {
            throw ("reass: verification failed at {0}; missing file {1}" -f $Stage, $relative)
        }

        $actualFile = $actualMap[$relative]
        if ($expectedFile.Length -ne $actualFile.Length) {
            throw ("reass: verification failed at {0}; byte mismatch for {1}" -f $Stage, $relative)
        }

        $expectedHash = (Get-FileHash -LiteralPath $expectedFile.FullName -Algorithm SHA256 -ErrorAction Stop).Hash
        $actualHash = (Get-FileHash -LiteralPath $actualFile.FullName -Algorithm SHA256 -ErrorAction Stop).Hash
        if ($expectedHash -ne $actualHash) {
            throw ("reass: verification failed at {0}; hash mismatch for {1}" -f $Stage, $relative)
        }

        $percent = $ProgressStart + [Math]::Floor(($ProgressEnd - $ProgressStart) * (($index + 1) / [double][Math]::Max(1, $expectedFiles.Count)))
        Write-Progress -Id 776 -Activity 'Restoring High On Life 2 save data' -Status ("{0}: {1}" -f $Stage, $relative) -PercentComplete $percent
    }
}

if ($MyInvocation.InvocationName -ne '.') {
    & 'Test-ReassTreeEqual' @args
}
