# Generated by 2sc from function 'Test-DKillFastDockerReady' (2026-08-13 00:08:11).
# Self-bootstrap: load the profile environment when this script runs
# outside a profile session so it behaves exactly like the function it
# was copied from. The module is also force-re-imported when the copy
# loaded in this process is stale (psm1 changed on disk) so a long-
# running session never runs an outdated dispatcher.
$__2scProfileModule = 'C:\Users\micha\Documents\WindowsPowerShell\Modules\CodexProfileFunctions\CodexProfileFunctions.psd1'
$__2scNeedBootstrap = -not (Get-Command -Name 'Initialize-CodexProfileFunctions' -CommandType Function -ErrorAction SilentlyContinue)
if (-not $__2scNeedBootstrap) {
    $__2scLoadedModule = Get-Module -Name 'CodexProfileFunctions' -ErrorAction SilentlyContinue | Select-Object -First 1
    if ($__2scLoadedModule) {
        $__2scLoadedFingerprint = $__2scLoadedModule.SessionState.PSVariable.GetValue('ProfileModuleFingerprint')
        $__2scModuleFile = Join-Path $__2scLoadedModule.ModuleBase 'CodexProfileFunctions.psm1'
        if ([System.IO.File]::Exists($__2scModuleFile)) {
            $__2scDiskInfo = Get-Item -LiteralPath $__2scModuleFile -ErrorAction SilentlyContinue
            if ($__2scDiskInfo) {
                $__2scDiskFingerprint = '{0}|{1}' -f $__2scDiskInfo.Length, $__2scDiskInfo.LastWriteTimeUtc.Ticks
                if ([string]$__2scLoadedFingerprint -and $__2scDiskFingerprint -ne [string]$__2scLoadedFingerprint) { $__2scNeedBootstrap = $true }
            }
        }
    }
}
if ($__2scNeedBootstrap) {
    if (-not (Test-Path -LiteralPath $__2scProfileModule -PathType Leaf)) {
        throw "2sc-generated script requires the Codex profile module: $__2scProfileModule"
    }
    Import-Module -Name $__2scProfileModule -Force -DisableNameChecking -ErrorAction Stop
    Initialize-CodexProfileFunctions
}
function Test-DKillFastDockerReady {
    [CmdletBinding()]
    param([Parameter(Mandatory)][string]$DockerExe,[switch]$FinalProbe)

    if([string]::IsNullOrWhiteSpace($DockerExe) -or -not (Test-Path -LiteralPath $DockerExe)) { Write-DKillFastLine ("DKILL_READY_FAIL executable not found: {0}" -f $DockerExe) Red; return $false }
    $process = $null
    try {
        $remaining = Get-DKillFastRemainingMilliseconds
        if(-not $FinalProbe -and $remaining -lt 300) { Write-DKillFastLine 'DKILL_READY_SKIP insufficient remaining time' Yellow; return $false }
        $waitMs = if($FinalProbe){2500}else{[Math]::Max(350,[Math]::Min(1400,$remaining - 150))}
        Write-Progress -Activity 'Docker readiness' -Status ("Probing Docker server for up to {0}ms" -f $waitMs) -PercentComplete 40
        $psi = New-Object Diagnostics.ProcessStartInfo
        $psi.FileName = $DockerExe; $psi.Arguments = 'version --format "{{.Server.Version}}"'; $psi.UseShellExecute = $false; $psi.CreateNoWindow = $true; $psi.RedirectStandardOutput = $true; $psi.RedirectStandardError = $true
        $process = New-Object Diagnostics.Process; $process.StartInfo = $psi
        if(-not $process.Start()) { throw 'process start returned false' }
        if(-not $process.WaitForExit($waitMs)) { try { $process.Kill() } catch { Write-DKillFastLine ("DKILL_READY_WARN timeout kill failed: {0}" -f $_.Exception.Message) Yellow }; Write-DKillFastLine ("DKILL_READY_FAIL timeout after {0}ms" -f $waitMs) Red; return $false }
        $stdout = $process.StandardOutput.ReadToEnd().Trim(); $stderr = $process.StandardError.ReadToEnd().Trim()
        if($process.ExitCode -ne 0 -or [string]::IsNullOrWhiteSpace($stdout) -or $stderr -match '(?i)failed to connect|daemon is not running|cannot find|error during connect') { Write-DKillFastLine ("DKILL_READY_FAIL exit={0} stdout={1} stderr={2}" -f $process.ExitCode,$stdout,$stderr) Red; return $false }
        Write-DKillFastLine ("DKILL_READY_OK server_version={0}" -f $stdout) Green
        return $true
    } catch { Write-DKillFastLine ("DKILL_READY_FAIL exception: {0}" -f $_.Exception.Message) Red; return $false }
    finally { Write-Progress -Activity 'Docker readiness' -Completed; if($process){ try { $process.Dispose() } catch { Write-DKillFastLine ("DKILL_READY_WARN dispose failed: {0}" -f $_.Exception.Message) Yellow } } }
}

if ($MyInvocation.InvocationName -ne '.') {
    & 'Test-DKillFastDockerReady' @args
}
