# Generated by 2sc from function 'Update-FullProfileDefinitionCache' (2026-08-13 00:38:56).
# Self-bootstrap: load the profile environment when this script runs
# outside a profile session so it behaves exactly like the function it
# was copied from. The module is also force-re-imported when the copy
# loaded in this process is stale (psm1 changed on disk) so a long-
# running session never runs an outdated dispatcher.
$__2scProfileModule = 'C:\Users\micha\Documents\WindowsPowerShell\Modules\CodexProfileFunctions\CodexProfileFunctions.psd1'
$__2scNeedBootstrap = -not (Get-Command -Name 'Initialize-CodexProfileFunctions' -CommandType Function -ErrorAction SilentlyContinue)
if (-not $__2scNeedBootstrap) {
    $__2scLoadedModule = Get-Module -Name 'CodexProfileFunctions' -ErrorAction SilentlyContinue | Select-Object -First 1
    if ($__2scLoadedModule) {
        $__2scLoadedFingerprint = $__2scLoadedModule.SessionState.PSVariable.GetValue('ProfileModuleFingerprint')
        $__2scModuleFile = Join-Path $__2scLoadedModule.ModuleBase 'CodexProfileFunctions.psm1'
        if ([System.IO.File]::Exists($__2scModuleFile)) {
            $__2scDiskInfo = Get-Item -LiteralPath $__2scModuleFile -ErrorAction SilentlyContinue
            if ($__2scDiskInfo) {
                $__2scDiskFingerprint = '{0}|{1}' -f $__2scDiskInfo.Length, $__2scDiskInfo.LastWriteTimeUtc.Ticks
                if ([string]$__2scLoadedFingerprint -and $__2scDiskFingerprint -ne [string]$__2scLoadedFingerprint) { $__2scNeedBootstrap = $true }
            }
        }
    }
}
if ($__2scNeedBootstrap) {
    if (-not (Test-Path -LiteralPath $__2scProfileModule -PathType Leaf)) {
        throw "2sc-generated script requires the Codex profile module: $__2scProfileModule"
    }
    Import-Module -Name $__2scProfileModule -Force -DisableNameChecking -ErrorAction Stop
    Initialize-CodexProfileFunctions
}
function Update-FullProfileDefinitionCache {
    param(
        [Parameter(Mandatory = $true)][string]$SourcePath,
        [Parameter(Mandatory = $true)][string]$CachePath
    )

    if (-not (Test-Path -LiteralPath $SourcePath -PathType Leaf)) {
        throw "Full PowerShell profile library not found: $SourcePath"
    }

    $sourceItem = Get-Item -LiteralPath $SourcePath
    $cacheFormat = '# FullProfileDefinitionCacheFormat: 2'
    if (Test-Path -LiteralPath $CachePath -PathType Leaf) {
        $cacheItem = Get-Item -LiteralPath $CachePath
        $cacheHeader = Get-Content -LiteralPath $CachePath -TotalCount 3 -ErrorAction SilentlyContinue
        if ($cacheItem.LastWriteTimeUtc -ge $sourceItem.LastWriteTimeUtc -and $cacheHeader -contains $cacheFormat) { return }
    }

    $parseErrors = $null
    $tokens = $null
    $ast = [System.Management.Automation.Language.Parser]::ParseFile($SourcePath, [ref]$tokens, [ref]$parseErrors)
    if ($parseErrors -and $parseErrors.Count -gt 0) {
        throw "Cannot parse full PowerShell profile library '$SourcePath': $($parseErrors[0].Message)"
    }

    $lastFunctionLines = New-Object 'System.Collections.Hashtable' ([System.StringComparer]::OrdinalIgnoreCase)
    foreach ($functionAst in $ast.FindAll({ param($node) $node -is [System.Management.Automation.Language.FunctionDefinitionAst] }, $true)) {
        $functionName = $functionAst.Name -replace '^(?i:global:)', ''
        $lastFunctionLines[$functionName] = $functionAst.Extent.StartLineNumber
    }

    $parts = New-Object 'System.Collections.Generic.List[string]'
    $parts.Add($cacheFormat) | Out-Null
    $parts.Add("# Generated from $SourcePath. Contains final function definitions and safe assignments only.") | Out-Null
    $parts.Add("# Regenerate by calling fullprofile after editing the full profile source.") | Out-Null

    foreach ($statement in $ast.EndBlock.Statements) {
        if ($statement -is [System.Management.Automation.Language.FunctionDefinitionAst]) {
            $functionName = $statement.Name -replace '^(?i:global:)', ''
            if ($lastFunctionLines[$functionName] -eq $statement.Extent.StartLineNumber) {
                $parts.Add($statement.Extent.Text.TrimEnd()) | Out-Null
            }
            continue
        }

        if ($statement -is [System.Management.Automation.Language.AssignmentStatementAst]) {
            $commands = @($statement.FindAll({ param($node) $node -is [System.Management.Automation.Language.CommandAst] }, $true))
            if ($commands.Count -eq 0) {
                $parts.Add($statement.Extent.Text.TrimEnd()) | Out-Null
            }
            continue
        }

        if ($statement -is [System.Management.Automation.Language.PipelineAst]) {
            $commands = @($statement.FindAll({ param($node) $node -is [System.Management.Automation.Language.CommandAst] }, $true))
            if ($commands.Count -gt 0 -and @($commands | Where-Object { $_.GetCommandName() -ne 'Set-Alias' }).Count -eq 0) {
                $parts.Add($statement.Extent.Text.TrimEnd()) | Out-Null
            }
        }
    }

    $cacheDir = Split-Path -Parent $CachePath
    if (-not (Test-Path -LiteralPath $cacheDir -PathType Container)) {
        New-Item -ItemType Directory -Path $cacheDir -Force | Out-Null
    }

    $tempPath = "$CachePath.tmp"
    [System.IO.File]::WriteAllText($tempPath, ($parts -join [Environment]::NewLine + [Environment]::NewLine), [System.Text.UTF8Encoding]::new($false))
    Move-Item -LiteralPath $tempPath -Destination $CachePath -Force
}

if ($MyInvocation.InvocationName -ne '.') {
    & 'Update-FullProfileDefinitionCache' @args
}
