# Generated by 2sc from function 'Wait-RedockerSafeDockerReady' (2026-08-13 00:43:59).
# Self-bootstrap: load the profile environment when this script runs
# outside a profile session so it behaves exactly like the function it
# was copied from. The module is also force-re-imported when the copy
# loaded in this process is stale (psm1 changed on disk) so a long-
# running session never runs an outdated dispatcher.
$__2scProfileModule = 'C:\Users\micha\Documents\WindowsPowerShell\Modules\CodexProfileFunctions\CodexProfileFunctions.psd1'
$__2scNeedBootstrap = -not (Get-Command -Name 'Initialize-CodexProfileFunctions' -CommandType Function -ErrorAction SilentlyContinue)
if (-not $__2scNeedBootstrap) {
    $__2scLoadedModule = Get-Module -Name 'CodexProfileFunctions' -ErrorAction SilentlyContinue | Select-Object -First 1
    if ($__2scLoadedModule) {
        $__2scLoadedFingerprint = $__2scLoadedModule.SessionState.PSVariable.GetValue('ProfileModuleFingerprint')
        $__2scModuleFile = Join-Path $__2scLoadedModule.ModuleBase 'CodexProfileFunctions.psm1'
        if ([System.IO.File]::Exists($__2scModuleFile)) {
            $__2scDiskInfo = Get-Item -LiteralPath $__2scModuleFile -ErrorAction SilentlyContinue
            if ($__2scDiskInfo) {
                $__2scDiskFingerprint = '{0}|{1}' -f $__2scDiskInfo.Length, $__2scDiskInfo.LastWriteTimeUtc.Ticks
                if ([string]$__2scLoadedFingerprint -and $__2scDiskFingerprint -ne [string]$__2scLoadedFingerprint) { $__2scNeedBootstrap = $true }
            }
        }
    }
}
if ($__2scNeedBootstrap) {
    if (-not (Test-Path -LiteralPath $__2scProfileModule -PathType Leaf)) {
        throw "2sc-generated script requires the Codex profile module: $__2scProfileModule"
    }
    Import-Module -Name $__2scProfileModule -Force -DisableNameChecking -ErrorAction Stop
    Initialize-CodexProfileFunctions
}
function Wait-RedockerSafeDockerReady {
        param([string]$DockerExe,[int]$TimeoutSeconds = 180)
        $deadline = (Get-Date).AddSeconds([Math]::Max(5,$TimeoutSeconds))
        $last = -1
        do {
            if(Test-RedockerSafeDockerReady -DockerExe $DockerExe){ return $true }
            $elapsed = [int]([Math]::Max(0,((Get-Date).AddSeconds($TimeoutSeconds) - $deadline).TotalSeconds))
            $pct = [Math]::Min(99,[int](($elapsed / [Math]::Max(1,$TimeoutSeconds)) * 100))
            if($pct -ne $last){
                Write-RedockerSafeLine ("waiting for Docker daemon readiness {0}%" -f $pct) DarkCyan
                $last = $pct
            }
            Start-Sleep -Milliseconds 750
        } while((Get-Date) -lt $deadline)
        return (Test-RedockerSafeDockerReady -DockerExe $DockerExe -Milliseconds 2500)
    }

if ($MyInvocation.InvocationName -ne '.') {
    & 'Wait-RedockerSafeDockerReady' @args
}
