# Generated by 2sc from function 'webterm' (2026-08-12 23:59:25).
# Self-bootstrap: load the profile environment when this script runs
# outside a profile session so it behaves exactly like the function it
# was copied from. The module is also force-re-imported when the copy
# loaded in this process is stale (psm1 changed on disk) so a long-
# running session never runs an outdated dispatcher.
$__2scProfileModule = 'C:\Users\micha\Documents\WindowsPowerShell\Modules\CodexProfileFunctions\CodexProfileFunctions.psd1'
$__2scNeedBootstrap = -not (Get-Command -Name 'Initialize-CodexProfileFunctions' -CommandType Function -ErrorAction SilentlyContinue)
if (-not $__2scNeedBootstrap) {
    $__2scLoadedModule = Get-Module -Name 'CodexProfileFunctions' -ErrorAction SilentlyContinue | Select-Object -First 1
    if ($__2scLoadedModule) {
        $__2scLoadedFingerprint = $__2scLoadedModule.SessionState.PSVariable.GetValue('ProfileModuleFingerprint')
        $__2scModuleFile = Join-Path $__2scLoadedModule.ModuleBase 'CodexProfileFunctions.psm1'
        if ([System.IO.File]::Exists($__2scModuleFile)) {
            $__2scDiskInfo = Get-Item -LiteralPath $__2scModuleFile -ErrorAction SilentlyContinue
            if ($__2scDiskInfo) {
                $__2scDiskFingerprint = '{0}|{1}' -f $__2scDiskInfo.Length, $__2scDiskInfo.LastWriteTimeUtc.Ticks
                if ([string]$__2scLoadedFingerprint -and $__2scDiskFingerprint -ne [string]$__2scLoadedFingerprint) { $__2scNeedBootstrap = $true }
            }
        }
    }
}
if ($__2scNeedBootstrap) {
    if (-not (Test-Path -LiteralPath $__2scProfileModule -PathType Leaf)) {
        throw "2sc-generated script requires the Codex profile module: $__2scProfileModule"
    }
    Import-Module -Name $__2scProfileModule -Force -DisableNameChecking -ErrorAction Stop
    Initialize-CodexProfileFunctions
}
function webterm {
    [CmdletBinding()]
    param([string]$WorkingDirectory = (Get-Location).Path)

    if (-not (Test-Path -LiteralPath $WorkingDirectory -PathType Container)) {
        throw "WEBTERM: working directory does not exist: $WorkingDirectory"
    }
    $systemRoot = [Environment]::GetEnvironmentVariable('SystemRoot', 'Process')
    if ([string]::IsNullOrWhiteSpace($systemRoot)) { $systemRoot = 'C:\Windows' }
    $powershell = Join-Path $systemRoot 'System32\WindowsPowerShell\v1.0\powershell.exe'
    if (-not (Test-Path -LiteralPath $powershell -PathType Leaf)) {
        throw "WEBTERM: Windows PowerShell 5 executable is missing: $powershell"
    }
    $statePath = Get-ProfileManagedWebTermStatePath
    $existingState = $null
    if (Test-Path -LiteralPath $statePath -PathType Leaf) {
        try { $existingState = Get-Content -LiteralPath $statePath -Raw | ConvertFrom-Json } catch { $existingState = $null }
    }
    $existingProcess = Get-ProfileManagedWebTermProcess -State $existingState
    if ($existingProcess) {
        Write-Output ("WEBTERM_OK action=already-running pid={0}" -f $existingProcess.Id)
        return
    }
    if ($existingState) {
        Remove-Item -LiteralPath $statePath -Force -ErrorAction SilentlyContinue
    }
    Write-Output ("WEBTERM_PROGRESS stage=starting working_directory=""{0}""" -f $WorkingDirectory)
    $process = Start-Process -FilePath $powershell -ArgumentList @('-NoExit', '-Command', 'Set-Location -LiteralPath $args[0]', '--', $WorkingDirectory) -WorkingDirectory $WorkingDirectory -PassThru
    $stateDirectory = Split-Path -Parent $statePath
    New-Item -ItemType Directory -Path $stateDirectory -Force | Out-Null
    [System.IO.File]::WriteAllText($statePath, (([pscustomobject]@{
        ProcessId = $process.Id
        ProcessStartedUtc = $process.StartTime.ToUniversalTime().ToString('o')
        WorkingDirectory = $WorkingDirectory
        StartedUtc = [DateTime]::UtcNow.ToString('o')
    }) | ConvertTo-Json -Depth 2), (New-Object System.Text.UTF8Encoding($false)))
    Write-Output ("WEBTERM_OK pid={0}" -f $process.Id)
}

if ($MyInvocation.InvocationName -ne '.') {
    & 'webterm' @args
}
