# Generated by 2sc from function 'Write-MmmenuRealProgressLine' (2026-08-12 23:59:08).
# Self-bootstrap: load the profile environment when this script runs
# outside a profile session so it behaves exactly like the function it
# was copied from. The module is also force-re-imported when the copy
# loaded in this process is stale (psm1 changed on disk) so a long-
# running session never runs an outdated dispatcher.
$__2scProfileModule = 'C:\Users\micha\Documents\WindowsPowerShell\Modules\CodexProfileFunctions\CodexProfileFunctions.psd1'
$__2scNeedBootstrap = -not (Get-Command -Name 'Initialize-CodexProfileFunctions' -CommandType Function -ErrorAction SilentlyContinue)
if (-not $__2scNeedBootstrap) {
    $__2scLoadedModule = Get-Module -Name 'CodexProfileFunctions' -ErrorAction SilentlyContinue | Select-Object -First 1
    if ($__2scLoadedModule) {
        $__2scLoadedFingerprint = $__2scLoadedModule.SessionState.PSVariable.GetValue('ProfileModuleFingerprint')
        $__2scModuleFile = Join-Path $__2scLoadedModule.ModuleBase 'CodexProfileFunctions.psm1'
        if ([System.IO.File]::Exists($__2scModuleFile)) {
            $__2scDiskInfo = Get-Item -LiteralPath $__2scModuleFile -ErrorAction SilentlyContinue
            if ($__2scDiskInfo) {
                $__2scDiskFingerprint = '{0}|{1}' -f $__2scDiskInfo.Length, $__2scDiskInfo.LastWriteTimeUtc.Ticks
                if ([string]$__2scLoadedFingerprint -and $__2scDiskFingerprint -ne [string]$__2scLoadedFingerprint) { $__2scNeedBootstrap = $true }
            }
        }
    }
}
if ($__2scNeedBootstrap) {
    if (-not (Test-Path -LiteralPath $__2scProfileModule -PathType Leaf)) {
        throw "2sc-generated script requires the Codex profile module: $__2scProfileModule"
    }
    Import-Module -Name $__2scProfileModule -Force -DisableNameChecking -ErrorAction Stop
    Initialize-CodexProfileFunctions
}
function Write-MmmenuRealProgressLine {
        param([string]$Label,[int]$Elapsed,[int]$ProcessId,[int]$Tick)
        $parts=@()
        $nativeAge=[int][Math]::Floor(((Get-Date)-$script:MmmenuLastNativeProgressUtc).TotalSeconds)
        $showByteProgress = ($Label -eq 'tar-import')
        if($showByteProgress -and $script:MmmenuContextTotalBytes -gt 0){
            if($script:MmmenuContextDoneBytes -ge $script:MmmenuContextTotalBytes){
                $parts += ('context-stream-complete={0}/{1}; docker-import-finalizing-no-native-percent' -f (Format-MmmenuMB $script:MmmenuContextDoneBytes),(Format-MmmenuMB $script:MmmenuContextTotalBytes))
            } else {
                $pct=[Math]::Min([double]99.99,[Math]::Round(100.0*[double]$script:MmmenuContextDoneBytes/[Math]::Max([double]1,[double]$script:MmmenuContextTotalBytes),2))
                $parts += ('context={0}/{1} {2}%' -f (Format-MmmenuMB $script:MmmenuContextDoneBytes),(Format-MmmenuMB $script:MmmenuContextTotalBytes),$pct)
            }
        }
        if($showByteProgress -and $script:MmmenuBuildCurrentBytes -gt 0){
            if($script:MmmenuContextTotalBytes -gt 0){
                if($script:MmmenuBuildCurrentBytes -ge $script:MmmenuContextTotalBytes){
                    $parts += ('build-transfer-complete={0}/{1}; waiting-for-docker-finalize' -f (Format-MmmenuMB $script:MmmenuBuildCurrentBytes),(Format-MmmenuMB $script:MmmenuContextTotalBytes))
                } else {
                    $pct=[Math]::Min([double]99.99,[Math]::Round(100.0*[double]$script:MmmenuBuildCurrentBytes/[Math]::Max([double]1,[double]$script:MmmenuContextTotalBytes),2))
                    $parts += ('build-transfer={0}/{1} {2}%' -f (Format-MmmenuMB $script:MmmenuBuildCurrentBytes),(Format-MmmenuMB $script:MmmenuContextTotalBytes),$pct)
                }
            } else {
                $parts += ('build-transfer={0}' -f (Format-MmmenuMB $script:MmmenuBuildCurrentBytes))
            }
        }
        if($showByteProgress -and $script:MmmenuPushLayers.Count -gt 0){
            $cur=[int64]0; $tot=[int64]0
            foreach($v in $script:MmmenuPushLayers.Values){ $cur += [int64]$v[0]; $tot += [int64]$v[1] }
            if($tot -gt 0 -and $cur -ge $tot){
                $parts += ('push-layers-complete={0}/{1}; waiting-for-registry-confirm' -f (Format-MmmenuMB $cur),(Format-MmmenuMB $tot))
            } else {
                $pct=[Math]::Min([double]99.99,[Math]::Round(100.0*[double]$cur/[Math]::Max([double]1,[double]$tot),2))
                $parts += ('push={0}/{1} {2}%' -f (Format-MmmenuMB $cur),(Format-MmmenuMB $tot),$pct)
            }
        }
        if($parts.Count -eq 0){ $parts += 'stage-running-no-byte-total' }
        $parts += ('last-real-byte-update={0}s-ago' -f $nativeAge)
        Write-Host ("[mmmenu][docker:{0}] progress elapsed={1}s pid={2} {3}" -f $Label,$Elapsed,$ProcessId,($parts -join ' ')) -ForegroundColor DarkCyan
    }

if ($MyInvocation.InvocationName -ne '.') {
    & 'Write-MmmenuRealProgressLine' @args
}
