# Generated by 2sc from function 'Write-CcSpaceFastProgress' (2026-08-13 00:44:40).
# Self-bootstrap: load the profile environment when this script runs
# outside a profile session so it behaves exactly like the function it
# was copied from. The module is also force-re-imported when the copy
# loaded in this process is stale (psm1 changed on disk) so a long-
# running session never runs an outdated dispatcher.
$__2scProfileModule = 'C:\Users\micha\Documents\WindowsPowerShell\Modules\CodexProfileFunctions\CodexProfileFunctions.psd1'
$__2scNeedBootstrap = -not (Get-Command -Name 'Initialize-CodexProfileFunctions' -CommandType Function -ErrorAction SilentlyContinue)
if (-not $__2scNeedBootstrap) {
    $__2scLoadedModule = Get-Module -Name 'CodexProfileFunctions' -ErrorAction SilentlyContinue | Select-Object -First 1
    if ($__2scLoadedModule) {
        $__2scLoadedFingerprint = $__2scLoadedModule.SessionState.PSVariable.GetValue('ProfileModuleFingerprint')
        $__2scModuleFile = Join-Path $__2scLoadedModule.ModuleBase 'CodexProfileFunctions.psm1'
        if ([System.IO.File]::Exists($__2scModuleFile)) {
            $__2scDiskInfo = Get-Item -LiteralPath $__2scModuleFile -ErrorAction SilentlyContinue
            if ($__2scDiskInfo) {
                $__2scDiskFingerprint = '{0}|{1}' -f $__2scDiskInfo.Length, $__2scDiskInfo.LastWriteTimeUtc.Ticks
                if ([string]$__2scLoadedFingerprint -and $__2scDiskFingerprint -ne [string]$__2scLoadedFingerprint) { $__2scNeedBootstrap = $true }
            }
        }
    }
}
if ($__2scNeedBootstrap) {
    if (-not (Test-Path -LiteralPath $__2scProfileModule -PathType Leaf)) {
        throw "2sc-generated script requires the Codex profile module: $__2scProfileModule"
    }
    Import-Module -Name $__2scProfileModule -Force -DisableNameChecking -ErrorAction Stop
    Initialize-CodexProfileFunctions
}
function Write-CcSpaceFastProgress {
    param(
        [Parameter(Mandatory = $true)][string]$Stage,
        [string]$Target = '',
        [string]$Detail = ''
    )

    $elapsed = [int][Math]::Floor(((Get-Date) - $started).TotalSeconds)
    $targetText = if ([string]::IsNullOrWhiteSpace($Target)) { '-' } else { $Target }
    $detailText = if ([string]::IsNullOrWhiteSpace($Detail)) { '-' } else { $Detail }
    Write-Output ("CCSPACEFAST_PROGRESS stage={0} target=""{1}"" processed={2} deleted={3} skipped={4} failed={5} elapsed_s={6} detail=""{7}""" -f $Stage, $targetText, $script:ccSpaceFastProcessed, $script:ccSpaceFastDeleted, $script:ccSpaceFastSkipped, $script:ccSpaceFastFailed, $elapsed, $detailText)
    Write-Progress -Id $progressId -Activity 'ccspacefast: clearing safe temporary caches' -Status ("{0}: {1}" -f $Stage, $targetText) -PercentComplete 0
    $script:ccSpaceFastLastReport = Get-Date
}

if ($MyInvocation.InvocationName -ne '.') {
    & 'Write-CcSpaceFastProgress' @args
}
