# Generated by 2sc from function 'cccc' (2026-08-05 14:37:13).
function cccc {
    $ErrorActionPreference = 'Continue'
    $ccccSteps = @('mgr','siz','dkill','siz','allstart2','dddesk','ccc3','ccc4','ccc5','ram','adw','qaccess','pplans','upup','fixvc','gnet','netboost','cleanf','ram','beforere','fixfixfix','beforere','ccsizes','cleanc','rmvol','fixvss2','scanfast','cle1','bin','cleanc','fixvss2','rmdump','ffrmall','beforere','ram','siz')
    $cleanCcccOutput = {
        param([string]$StepName, [string]$Text)
        if ([string]::IsNullOrWhiteSpace($Text)) { return }
        $clean = $Text
        $knownNoise = @(
            '(?ms)^Register-ScheduledTask\s*:\s*The parameter is incorrect\..*?FullyQualifiedErrorId\s*:\s*HRESULT 0x80070057,Register-ScheduledTask\s*',
            '(?ms)^The system cannot find the path specified\. \(Exception from HRESULT: 0x80070003\).*?FullyQualifiedErrorId\s*:\s*System\.IO\.DirectoryNotFoundException\s*',
            '(?ms)^npm\.cmd\s*:\s*npm notice.*?FullyQualifiedErrorId\s*:\s*NativeCommandError\s*'
        )
        foreach ($pattern in $knownNoise) { $clean = [regex]::Replace($clean, $pattern, '') }
        if ($clean -ne $Text) {
            Write-Host ("[cccc] suppressed known nonfatal noisy PowerShell error formatting from {0}; full raw output is intentionally not re-thrown." -f $StepName)
        }
        if (-not [string]::IsNullOrWhiteSpace($clean)) { Write-Host ($clean.TrimEnd()) }
    }
    foreach ($ccccStep in $ccccSteps) {
        if (-not (Get-Command $ccccStep -ErrorAction SilentlyContinue)) {
            Write-Warning ("[cccc] step not found, skipped: {0}" -f $ccccStep)
            continue
        }
        try {
            $captured = (& $ccccStep 2>&1 | Out-String)
            & $cleanCcccOutput $ccccStep $captured
        } catch {
            $failureText = ($_ | Out-String)
            & $cleanCcccOutput $ccccStep $failureText
            Write-Warning ("[cccc] step failed but cccc continued: {0}" -f $ccccStep)
        }
    }
    $global:LASTEXITCODE = 0
}

if ($MyInvocation.InvocationName -ne '.') {
    & 'cccc' @args
}
